<?php

if (!defined('IN_WACKO'))
{
	exit;
}

$wacko_translation = [

	// language
	'lang_scheme'	=> [
		'name'		=> 'Englisch',
		'code'		=> 'de',
		'dir'		=> 'ltr',
		'locale'	=> 'de_DE.UTF-8',
	],

	// common
	'AddButton'					=> 'Neu',
	'ArchiveButton'				=> 'Archivieren',
	'CancelButton'				=> 'Abbrechen',
	'ContinueButton'			=> 'Weiter',
	'ConvertButton'				=> 'Konvertieren',
	'CreateButton'				=> 'Anlegen',
	'DeleteButton'				=> 'Löschen',
	'RemoveButton'				=> 'Entfernen',
	'RenameButton'				=> 'Umbenennen',
	'ResetButton'				=> 'Reset',
	'RestoreButton'				=> 'Wiederherstellen',
	'SaveButton'				=> 'Speichern',
	'SearchButton'				=> 'Suchen',
	'SendButton'				=> 'Senden',
	'SetButton'					=> 'Setzen',
	'SubmitButton'				=> 'Absenden',
	'UpdateButton'				=> 'Aktualisieren',

	'FormInvalid'				=> 'Das abgeschickte Formular war ungültig. Versuchen Sie es erneut.',
	'UnitPixel'					=> 'px',
	'Number'					=> 'Nummer',

	// logged in panel
	'AccountText'				=> 'Konto',
	'AccountTip'				=> 'Kontoeinstellungen',
	'AdminText'					=> 'Admin',
	'AdminTip'					=> 'Administrationsbereich',
	'LogoutLink'				=> 'Abmelden',
	'LogoutButton'				=> 'Abmelden',
	'LogoutAreYouSure'			=> 'Wollen Sie sich wirklich abmelden?',

	// registration panel
	'RegistrationWelcome'		=> 'Neue Benutzerregistrierung:',
	'RegistrationButton'		=> 'Registrieren',
	'UserNameOwned'				=> 'Dieser Benutzername ist bereits registriert. Bitte wählen Sie einen anderen.',
	'SiteRegistered'			=> 'Sie haben sich erfolgreich auf der Seite %1 registriert.',
	'RegistrationEmailInfo'		=> 'Eine gültige E-Mail-Adresse. Alle E-Mails des Systems werden an diese Adresse gesendet. Die E-Mail-Adresse wird nicht veröffentlicht und wird nur verwendet, wenn Sie ein neues Passwort erhalten möchten oder bestimmte Nachrichten oder Benachrichtigungen per E-Mail erhalten möchten.',
	'EmailConfirmHint'			=> 'Bitte bestätigen Sie Ihre E-Mail-Adresse, indem Sie in den Anweisungen auf den Link klicken. <br>Wenn Sie Ihre E-Mail-Adresse nicht verifizieren, können Sie kein mögliches verlorenes Passwort abrufen. <br>Des Weiteren werden Sie nicht über aktuelle Änderungen und Kommentare informiert.',
	'EmailConfirmRequired'		=> 'Ohne eine bestätigte E-Mail-Adresse dürfen Sie sich nicht einloggen.',
	'NameTooShort'				=> 'Der Benutzername ist zu kurz, mindestens %2 Zeichen sind erforderlich.',
	'NameTooLong'				=> 'Der Benutzername ist zu lang, maximal %2 Zeichen sind erlaubt.',
	'NameAlphanumOnly'			=> 'Benutzername muss zwischen %1 und %2 Zeichen lang sein und nur alphanumerische Zeichen verwenden. Großbuchstaben sind in Ordnung.',
	'NameCamelCaseOnly'			=> 'Benutzername muss zwischen %1 und %2 Zeichen lang und WikiName formatiert sein.',
	'NewUserAccount'			=> 'neues Benutzerkonto',

	'NewAccountSubject'			=> 'Kontoregistrierung',
	'NewAccountAdminCreated'	=> 'Der Benutzer %1 hat ein Benutzerkonto mit dem Benutzernamen "%2" für Sie erstellt. Um Ihre Registrierung abzuschließen, besuchen Sie die folgende URL (stellen Sie sicher, dass sie als einzelne Zeile eingegeben wurde) und legen Sie Ihr eigenes Zugangspasswort fest:',
	'NewAccountUsername'		=> 'Benutzername:',
	'AccountLanguage'			=> 'Sprache:',
	'NewAccountEmail'			=> 'Email:',
	'NewAccountIP'				=> 'Remote-IP-Adresse:',
	'NewAccountSignupInfo'		=> 'Folgendes Konto wurde erstellt:',

	'UserWaitingApproval'		=> 'Eine E-Mail wurde an den Seitenadministrator gesendet. Der Administrator prüft die übermittelten Informationen und genehmigt oder lehnt Ihre Anfrage ab.',
	'UserRequiresApproval'		=> 'Um diesen Benutzer den Zugriff auf %1 zu genehmigen oder zu verweigern, gehen Sie in das Admin-Panel.',
	'UserApprovalInfo'			=> 'Nach der Registrierung wird Ihre Anfrage an den Website-Administrator zur Genehmigung geschickt. Sie erhalten dann eine E-Mail mit weiteren Anweisungen.',
	'UserApprovalHint'			=> 'Die erfolgreiche Aktivierung Ihres Kontos wird in einer bestimmten E-Mail bekannt gegeben. Bis dahin ist ein Login nicht möglich.',

	'UserApprovalPending'		=> 'Ihr Konto ist noch nicht genehmigt.',
	'UserApprovalDenied'		=> 'Ihrem Konto wurde der Zugriff auf diese Seite verweigert.',

	'RegistrationApproved'		=> 'Registrierung genehmigt',
	'RegistrationDenied'		=> 'Registrierung verweigert',
	'PendingApproval'			=> 'Ausstehende Genehmigung',

	'UserApprovedInfo'			=> 'Sie wurden für den Zugriff auf %1 freigeschaltet.',
	'UserDeniedInfo'			=> 'Ihnen wurde der Zugriff auf %1 verweigert.',

	'RegistrationThreshold'		=> 'Die Zeit für das Ausfüllen des Formulars sollte nicht weniger als %1 Sekunden betragen.',
	'Language'					=> 'Sprache',

	// login panel
	'LoginWelcome'				=> 'Anmelden',
	'CreateAccount'				=> 'Neues Konto erstellen',
	'RegistrationLink'			=> 'Anmeldung',
	'LoginName'					=> 'Benutzername',
	'Password'					=> 'Passwort',
	'LoginButton'				=> 'Anmelden',
	'LoginLink'					=> 'Anmelden',
	'PersistentCookie'			=> 'Eingeloggt bleiben',
	'Session'					=> 'Sitzung',
	'SessionTip'				=> 'Parameter der aktuellen Sitzung',
	'SessionDuration'			=> 'Sitzungsdauer',
	'SessionDurationSession'	=> 'browser Sitzung',
	'SessionDurationDay'		=> '1 Tag',
	'SessionDurationWeek'		=> '1 Woche',
	'SessionDurationMonth'		=> '1 Monat',
	'LoggedInAs'				=> 'Sie sind eingeloggt als',

	'ClearCookies'				=> 'Alle Cookies löschen',
	'BindSessionIp'				=> 'Sitzung an die IP-Adresse binden',
	'BindSessionIpOn'			=> 'aktiviert (aktuelle IP %1)',
	'TrafficProtection'			=> 'Verkehrsschutz',
	'SessionEnds'				=> 'Die aktuelle Sitzung endet',
	'LastVisit'					=> 'Letzter Besuch wurde registriert',

	'LoginIncorrect'			=> 'Der Benutzername oder das Passwort, das Sie eingegeben haben, ist ungültig.',
	'WelcomeBack'				=> 'Willkommen zurück, %1',
	'LoginAttemptsExceeded'		=> 'Sie haben die maximal zulässige Anzahl an Anmeldeversuchen überschritten.<br>Zusätzlich zu deinem Benutzernamen und Passwort musst du jetzt auch das CAPTCHA unten lösen.',

	// session notice
	'IPAddressChanged'			=> 'IP-Adresse geändert auf %1 (war %2)',

	'SessionReplay'				=> 'Sitzung wurde wegen Wiederholung beendet.',
	'SessionObsolete'			=> 'Sitzung ist veraltet.',
	'SessionExpired'			=> 'Sitzung ist abgelaufen.',
	'SessionTimeout'			=> 'Sitzung wurde wegen Timeout beendet.',
	'SessionInactivity'			=> 'Sitzung wegen Inaktivität beendet.',
	'SessionUaChange'			=> 'Sitzung wurde wegen Änderung des User-Agents beendet.',
	'SessionTLSChange'			=> 'Sitzung wurde wegen TLS-Änderung beendet.',
	'SessionIPChange'			=> 'Sitzung wurde wegen IP-Änderung beendet.',

	// other
	'Guest'						=> 'Gast',
	'Everybody'					=> 'Alle',
	'Help'						=> 'Hilfe',
	'TopicSearchText'			=> 'Nur in Titeln suchen',
	'WordprocessorVersion'		=> 'Word-Prozessor-Version',

	// notifications
	'EmailHello'				=> 'Hallo ',
	'EmailModerator'			=> 'Moderator',
	'WatchedPageChanged'		=> 'Seite geändert ',
	'SomeoneChangedThisPage'	=> ' hat eine Seite geändert, die Sie beobachten: ',
	'NewPageCreatedSubj'		=> 'Eine neue Seite',
	'NewPageCreatedBody'		=> 'Benutzer %1 hat eine neue Seite erstellt: ',
	'FileUploadedSubj'			=> 'Eine neue Datei',
	'FileUploadedBody'			=> 'Benutzer %1 hat eine neue Datei hochgeladen: ',
	'FileReplacedBody'			=> 'Benutzer %1 hat die Datei ersetzt: ',

	'ActionDenied'				=> 'Aktion wird hier abgelehnt.',
	'TocTitle'					=> 'Inhalt ',
	'OuterLink2'				=> 'Ausgehender Link',
	'FileLink'					=> '',
	'PDFLink'					=> 'PDF-Dokument',
	'RDFLink'					=> 'RDF Dokument',
	'EmailLink'					=> 'E-Mail schreiben (Start des E-Mail-Clients)',
	'JabberLink'				=> 'Chat via XMPP (Jabber-Client)',
	'PermaLink'					=> 'Permalink',
	'PermaLinkTip'				=> 'Permanenter Link zu dieser Revision der Seite',
	'PermaLink0Tip'				=> 'Permanenter Link zu dieser Seite',

	'ShowTip'					=> 'Zurück im Ansichtsmodus',
	'ShowText'					=> 'Ansicht',
	'WikieditAutocomplete'		=> 'Schließe wikilinks durch Strg+Leerzeichen ab',
	'WikiEditInactiveJs'		=> 'Um WikiEdit nutzen zu können, aktivieren Sie bitte JavaScript in Ihrem Browser.',
	'NumerateLinks'				=> 'Links in der Druckansicht nummerieren',
	'Comment'					=> 'Kommentar',
	'Comments0'					=> 'Kommentar hinzufügen',
	'Comments1'					=> 'Kommentar lesen (1 Kommentar)',
	'CommentsN'					=> 'Kommentare lesen (%1 Kommentare)',
	'Comments'					=> 'Kommentare',
	'CommentHint'				=> '<a href="%1">Anmelden</a> oder <a href="%2">erstellen Sie ein Konto</a> , um einen Kommentar zu schreiben.',
	'CommentEdited'				=> 'bearbeitet',
	'Links'						=> 'Links',
	'Version'					=> 'Version',

	// details formatter
	'ShowHideDetails'			=> 'Details',

	'PrivacyPolicy'				=> 'Datenschutzerklärung',
	'TermsOfUse'				=> 'Nutzungsbedingungen',
	'AcceptTermsOfUse'			=> 'Ich habe die Nutzungsbedingungen der Website gelesen, verstanden und erkläre mich damit einverstanden.',

	'ShowComments'				=> 'Kommentare / Formular anzeigen',
	'HideComments'				=> 'Kommentare ausblenden / Formular',
	'AddComment'				=> 'Kommentar zu dieser Seite hinzufügen:',
	'AddCommentTitle'			=> 'Titel des Kommentars:',
	'CommentTitleRe'			=> 'Re:',
	'AddCommentButton'			=> 'Kommentar hinzufügen',
	'HereLink'					=> 'hier',
	'PageHandlerMoreTip'		=> 'mehr',

	'ThemeCorrupt'				=> 'Theme ist beschädigt',
	'InvalidNamespace'			=> 'Ungültiger Namensraum angegeben.',
	'DoesNotExists'				=> 'Diese Seite existiert nicht.',
	'PromptCreate'				=> 'Vielleicht möchtest du <strong><a href="%1"></a></strong> erstellen?',
	'RevisionHint'				=> 'Dies ist eine alte Revision von <a href="%1">%2</a> von %3 bearbeitet von %4.',
	'ReadAccessDenied'			=> 'Sie sind nicht berechtigt, diese Seite zu lesen.',
	'ReadAccessDeniedHintGuest'	=> 'Zum Lesen dieser Seite sollten Sie sich anmelden.',
	'PageDeletedInfo'			=> 'Diese Seite wurde gelöscht.',
	'RevisionDeletedInfo'		=> 'Diese Revision wurde gelöscht.',
	'CommentDeletedInfo'		=> 'Dieser Kommentar wurde gelöscht.',

	'LastEditedBy'				=> 'Zuletzt bearbeitet von',
	'YouAreOwner'				=> 'Sie sind der Besitzer dieser Seite.',
	'Owner'						=> 'Besitzer:',
	'Nobody'					=> 'Niemand',
	'TakeOwnership'				=> 'Besitz übernehmen',
	'FilesTip'					=> 'Angehängte Dateien verwalten',
	'FilesText'					=> 'Anhänge',
	'DeleteTip'					=> 'Seite, ihre Dateien und Kommentare löschen',
	'DeleteCommentTip'			=> 'Kommentar löschen',
	'DeleteText'				=> 'Löschen',
	'AclText'					=> 'Berechtigungen',
	'AclTip'					=> 'Berechtigungen bearbeiten',

	'PropertiesText'			=> 'Eigenschaften',
	'PropertiesTip'				=> 'Seiteneigenschaften bearbeiten',
	'EditTip'					=> 'Diese Seite bearbeiten.',
	'EditText'					=> 'Bearbeiten',
	'EditSection'				=> 'Abschnitt %1 bearbeiten',
	'EditSectionHint'			=> 'Abschnitt %1 von %2',
	'SectionHeadline'			=> 'Abschnitt',
	'EditCommentTip'			=> 'Kommentar bearbeiten',
	'EditComment'				=> 'Kommentar bearbeiten',
	'ReplyComment'				=> 'Antwort',
	'ReplyCommentTip'			=> 'Diesen Kommentar beantworten',
	'RevisionTip'				=> 'Seitenversionen anzeigen',
	'RevisionText'				=> 'Versionen',
	'ReferrersTip'				=> 'Eine Liste von URLs anzeigen, die auf diese Seite verweisen',
	'ReferrersText'				=> 'Verweise',
	'ModerateTip'				=> 'Moderation von Themen und Forenbeiträgen',
	'ModerateText'				=> 'Mäßig',
	'SearchText'				=> 'Suche: ',

	'AclUpdated'				=> 'Zugriffskontrolllisten aktualisiert',
	'AclGaveOwnership'			=> ' und gab Eigentum an %1.',
	'AclNoNewOwner'				=> 'Seiteneigentum wird nicht übertragen, da der Benutzer %1 nicht gefunden wurde.',
	'NewPageOwnership'			=> 'Übertragener Seitenbesitz',
	'YouAreNewOwner'			=> 'früherer Besitzer %1 übertragen ' . "\n" . 'der folgenden Seite für Sie',
	'PageOwnershipInfo'			=> '',
	'AclRead'					=> 'Lesen:',
	'AclWrite'					=> 'Schreiben:',
	'AclComment'				=> 'Kommentare:',
	'AclCreate'					=> 'Erstellen:',
	'AclUpload'					=> 'Hochladen:',
	'AclFor'					=> 'Zugriffskontrolllisten für %1',
	'SetOwner'					=> 'Besitzer:',
	'OwnerDontChange'			=> 'Nicht ändern',
	'AclAccessDenied'			=> 'Sie sind nicht der Besitzer dieser Seite.',
	'AclSyntaxError'			=> 'Fehler bei der Syntax der Zugriffsliste',
	'AclHelp'					=> '<code>*</code> - jeder ist erlaubt<br>' .
									'<code>$</code> - nur registrierte Benutzer<br>' .
									'<code>!</code> - Ein vorhergehendes Ausrufezeichen verweigert das entsprechende Recht<br>' .
									'<code>[UserName]</code> - Namen der erlaubten Benutzer<br>' .
									'<code>[GroupName]</code> - Namen der erlaubten Benutzergruppe (Alias)<br>' .
									'<code>(eine leere Liste)</code> - nur der Seitenbesitzer hat Zugriff',

	'AccessMode'				=> 'Sichtbarkeit',
	'AccessDenied'				=> 'verweigert',
	'AccessPublic'				=> 'öffentlich',
	'AccessRegistered'			=> 'registriert',
	'AccessPrivate'				=> 'privat',
	'AccessCustom'				=> 'benutzerdefiniert',

	// purge handler
	'PurgePage'					=> 'Purge page',
	'NotOwnerAndCantPurge'		=> 'Sie sind nicht der Besitzer der Seite und können sie nicht bereinigen.',
	'ReallyPurge'				=> 'ACHTUNG: Das Löschen der Seite ist unumkehrbar!',
	'SelectPurgeOptions'		=> 'Wählen Sie die notwendigen Löschoptionen aus:',
	'PurgeComments'				=> 'Alle Kommentare der Seite löschen',
	'CommentsPurged'			=> 'Alle Kommentare wurden gelöscht.',
	'PurgeFiles'				=> 'Alle beigefügten Dateien entfernen',
	'FilesPurged'				=> 'Alle angehängten Dateien wurden entfernt.',
	'PurgeRevisions'			=> 'Alle Revisionen der Seite löschen',
	'RevisionsPurged'			=> 'Revisionen wurden gelöscht.',
	'PurgeButton'				=> 'Purge',

	// categories handler
	'Categories'				=> 'Kategorien',
	'CategoriesAssign'			=> 'zuweisen',
	'CategoriesEdit'			=> 'bearbeiten',
	'Category'					=> 'Kategorie',
	'CategoriesFor'				=> 'Kategorien für',
	'CategoriesTip'				=> 'Kategorien bearbeiten',
	'CategoriesText'			=> 'Kategorien',
	'CategoriesUpdated'			=> 'Kategorien aktualisiert',
	'CategoriesAlreadyExists'	=> 'Kategorie %1 existiert bereits.',
	'CategoriesAdded'			=> 'Kategorie %1 erfolgreich hinzugefügt.',
	'CategoriesRenamed'			=> 'Kategorie erfolgreich umbenannt.',
	'CategoriesUngrouped'		=> 'Kategorie erfolgreich entschlüsselt.',
	'CategoriesGrouped'			=> 'Die Kategorie, die in der neuen Gruppe eingegeben wurde.',
	'NoMultilevelGrouping'		=> 'Mehrstufige Gruppierungskategorien sind nicht möglich.',
	'CategoriesDeleted'			=> 'Die Kategorie wurde aus der Datenbank und allen Seiten gelöscht.',
	'CategoriesAdd'				=> 'Neue Kategorie hinzufügen',
	'CategoryDescription'		=> 'Beschreibung',
	'CategoriesAddGrouped'		=> 'Gruppiert mit der Kategorie',
	'CategoriesAddGroupedNo'	=> 'Keine Gruppe.',
	'CategoriesRename'			=> 'Umbenennen der Kategorie %1 in',
	'CategoriesRenameInfo'		=> '* Hinweis: Änderungen wirken sich auf alle Seiten aus, die dieser Kategorie zugeordnet sind.',
	'CategoriesGroup'			=> 'Gruppenkategorien %1 mit',
	'CategoriesGroupInfo'		=> '* Wählen Sie [keine Gruppe] aus, um die Kategorie zu debundeln.',
	'CategoriesNoGroup'			=> '[keine Gruppe]',
	'CategoriesDelete'			=> 'Sind Sie sicher, dass Sie die Kategorie %1 entfernen möchten?',
	'CategoriesDeleteInfo'		=> '* Hinweis: Änderungen wirken sich auf alle Seiten aus, die dieser Kategorie zugeordnet sind. Wenn das Wort eine Unterkategorie hat, werden sie nicht gelöscht, sondern nur entlarvt.',
	'CategoriesStoreInfo'		=> 'Um Kategorien einer Seite zuzuordnen, wählen Sie die Kontrollkästchen.',
	'CategoriesStoreButton'		=> 'Kategorien speichern',
	'CategoriesGroupButton'		=> 'Gruppe',
	'CategoriesEditInfo'		=> 'Um die Kategorieliste zu bearbeiten, wählen Sie die Optionsschaltfläche.',
	'NoCategoriesForThisLang'	=> 'Kategorien für diese Sprache sind nicht spezifiziert.',
	'PagesCategory'				=> 'Seitenkategorie',
	'CategoryNotExists'			=> 'Kategorie existiert nicht.',
	'CategoryEmpty'				=> 'Kategorie leer.',
	'NoCategorySelected'		=> 'Keine Kategorie ausgewählt.',
	'NoCategoriesAssigned'		=> 'Keine Kategorien für diese Sprache zugewiesen.',
	'TagCloud'					=> 'Tag-Cloud',
	'PagesTaggedWith'			=> '%1 Seiten mit %2 getaggt',
	'CategoriesOfCluster'		=> 'von Cluster',
	'TaggedWithTip'				=> 'zeige Seiten mit Schlagwort %1',

	// source handler
	'SourceText'				=> 'Quelle',
	'SourceTip'					=> 'Wiki-Quelle anzeigen',
	'SourceCopyToClipboard'		=> 'in die Zwischenablage kopieren',
	'SourceFor'					=> 'Quelle für %1 anzeigen',

	// Groups action
	'GroupsSearch'				=> 'Gruppen finden',
	'GroupsNoMatching'			=> 'Passende Gruppen nicht gefunden. Versuchen Sie weniger strenge Suchkriterien.',
	'GroupsOpenProfile'			=> 'Profil anzeigen',
	'GroupsName'				=> 'Gruppe',
	'GroupsMembers'				=> 'Mitglieder',
	'GroupsDescription'			=> 'Beschreibung',
	'GroupsCreated'				=> 'Erstellt',
	'GroupsNotFound'			=> 'Gruppe %2 nicht gefunden. Klicken Sie <a href="%1">hier</a>, um zur Hauptliste zu gelangen.',
	'GroupsProfile'				=> 'Profil',
	'GroupsList'				=> 'Gesamte Liste der Gruppen anzeigen',
	'GroupSpace'				=> 'Gruppenraum',

	'MetaUpdated'				=> 'Meta-Daten aktualisiert',

	'PreviewButton'				=> 'Vorschau',
	'Preview'					=> 'Vorschau',
	'Chars'						=> 'zeichen',
	'PageBody'					=> 'Seitenkörper',
	'EditNote'					=> 'Zusammenfassung bearbeiten',
	'EditNoteMissing'			=> 'Zusammenfassung bearbeiten fehlt',
	'EditMinor'					=> 'Kleinere Bearbeitung',
	'MinorEditHide'				=> 'Kleine Bearbeitung ausblenden',
	'MinorEditShow'				=> 'Kleine Bearbeitung anzeigen',
	'PostAnonymously'			=> 'Poste anonym ohne deinen Namen anzugeben',
	'NotifyMe'					=> 'Benachrichtigen Sie mich über neue Kommentare und Änderungen der Seite',
	'OverwriteAlert'			=> 'ÜBERTRAG: Diese Seite wurde während der Bearbeitung von jemand anderem geändert.<br>Bitte kopieren Sie Ihre Änderungen und bearbeiten Sie diese Seite erneut.',
	'TextDbOversize'			=> 'Warnung: Ihr Text überschreitet die Länge um %1 Zeichen. Bitte kürzen Sie Ihren Text auf eine zulässige Anzahl von Zeichen. Tipp: Sie können den verbleibenden Text auf einer separaten Seite platzieren.',
	'EditingRevisionWarning'	=> 'Sie bearbeiten eine alte Revision dieser Seite. Wenn Sie diese veröffentlichen, werden alle Änderungen, die seitdem vorgenommen wurden, entfernt. <br>Sie können stattdessen die aktuelle Revision bearbeiten.',
	'WriteAccessDenied'			=> 'Sie haben keinen Schreibzugriff auf diese Seite.',
	'EmptyPage'					=> 'Seitentext war leer - nicht gespeichert!',
	'EmptyComment'				=> 'Kommentar-Text war leer - nicht gespeichert!',
	'CommentAccessDenied'		=> 'Du hast keine Berechtigung Kommentare auf dieser Seite zu posten.',
	'CommentFlooded'			=> 'Das Intervall zwischen der Veröffentlichung der Beiträge darf nicht weniger als %1 Sekunden betragen.',
	'CommentAdded'				=> 'Kommentar hinzugefügt.',
	'YouAreNowTheOwner'			=> 'Sie sind jetzt der Besitzer dieser Seite.',
	'PageSaved'					=> 'Seitenversion %1 gespeichert.',
	'CommentSaved'				=> 'Kommentar gespeichert.',

	'RevisionsFor'				=> 'Revisionen für %1',
	'DefaultDiffMode'			=> 'Standard-Diff-Modus',
	'DiffMode'		=> [
		'0'		=> 'Voller Diff',
		'1'		=> 'Einfacher Diff',
		'2'		=> 'Quelle',
		'3'		=> 'Seite an Seite',
		'4'		=> 'Inline',
		'5'		=> 'Zusammengeführt',
		'6'		=> 'Einheitlich',
		'7'		=> 'Kontext',
	],

	'PreviousEdit'				=> 'Vorherige Änderung',
	'NextEdit'					=> 'Nächste Bearbeitung',

	'Diff'						=> 'Diff',
	'PreviousVersion'			=> 'Vorherige Revision',
	'LatestVersion'				=> 'Letzte Revision',
	'NextVersion'				=> 'Nächste Revision',

	'ShowDifferencesButton'		=> 'Unterschiede anzeigen',
	'CancelReturnButton'		=> 'Abbrechen und zur Seite zurückkehren',
	'Comparison'				=> 'Unterschied zwischen Revisionen für %1',
	'RevisionAsOf'				=> 'Revision %1 ab',
	'SimpleDiffAdditions'		=> 'Zusätze:',
	'SimpleDiffDeletions'		=> 'Löschen:',
	'NoDifferences'				=> 'Keine Unterschiede.',
	'ReEditOldRevision'			=> 'Diese alte Revision erneut bearbeiten',

	'ExternalPages'				=> 'Externe Seiten, die auf %1 verlinken (%2) (<a href="%3">siehe Liste der Domains</a>):',
	'ExternalPagesGlobal'		=> 'Sites, die auf dieses WackoWiki verlinken (%2) (<a href="%1">siehe Liste der Domains</a>):',
	'Last24Hours'				=> 'letzte 24 Stunden',
	'LastDays'					=> 'letzte %1 Tage',
	'DomainsSitesPages'			=> 'Domains/Sites-Seiten, die mit  %1 (%2) verlinkt (<a href="%3">siehe Liste der verschiedenen URLs</a>):',
	'DomainsSitesPagesGlobal'	=> 'Domains/Sites, die mit diesem WackoWiki verlinkt (<a href="%1">siehe Liste der verschiedenen URLs</a>):',
	'ViewReferrersPage'			=> 'zu Seite',
	'ViewReferrersPerPage'		=> 'pro Seite',
	'ViewReferrersByTime'		=> 'nach Zeit',
	'ViewReferrersGlobal'		=> 'global',
	'NoneReferrers'				=> 'Keine',
	'NotOwnerCantDelete'		=> 'Sie sind nicht Eigentümer dieser Seite und können sie nicht löschen',

	// remove
	'RemovePage'				=> 'Seite entfernen',
	'RemoveRevision'			=> 'Revision entfernen',
	'RemoveComment'				=> 'Kommentar löschen',
	'RemoveCluster'				=> 'Alle Seiten des Clusters entfernen',
	'RemoveDontKeep'			=> 'Keine Kopie einer gelöschten Seite und Kommentare speichern',
	'RemoveDontKeepRevision'	=> 'Keine Kopie der gelöschten Revision speichern',
	'RemoveDontKeepComment'		=> 'Keine Kopie des gelöschten Kommentars speichern',
	'RemoveDontKeepFile'		=> 'Keine Kopie der gelöschten Datei speichern',
	'ReferrersRemoved'			=> 'Verweise entfernt.',
	'LinksRemoved'				=> 'Links entfernt.',
	'CategoriesRemoved'			=> 'Seitenkategorien gelöscht.',
	'AclsRemoved'				=> 'Seitenakls entfernt.',
	'BookmarksRemoved'			=> 'Lesezeichen entfernt.',
	'WatchesRemoved'			=> 'Uhren entfernt.',
	'CommentsRemoved'			=> 'Kommentare von Seite entfernt.',
	'FilesRemoved'				=> 'Dateien von der Seite entfernt.',
	'PageRemoved'				=> 'Seite entfernt.',
	'PageCachePurged'			=> 'Cache gelöscht.',
	'ClusterRemoved'			=> 'Alle Seiten des Clusters entfernt.',
	'RevisionRemoved'			=> 'Revision %1 entfernt.',
	'RevisionsRemoved'			=> 'Revisionen entfernt.',
	'ActionHaveNoUndo'			=> 'Diese Aktion kann nicht rückgängig gemacht werden.',

	// restore
	'PageRestored'				=> 'Seite wiederhergestellt.',
	'RevisionRestored'			=> 'Revision wiederhergestellt.',
	'LocalFilesRestored'		=> 'Lokale Dateien wiederhergestellt.',

	'PrintVersion'				=> 'Version drucken',
	'PrintText'					=> 'Drucken',
	'LinkedPages'				=> 'Verknüpfte Seiten:',
	'NoLinkedPages'				=> 'Es gibt keine verlinkten Seiten',
	'ReferringPages'			=> 'Verweisende Seiten:',
	'NoReferringPages'			=> 'Es gibt keine verweisenden Seiten',
	'Footnotes'					=> 'Fußnoten:',
	'Footnote'					=> 'Fußnote',
	'MostPopularPages'			=> 'Beliebteste Seiten',
	'MostCommentedPages'		=> 'Meiste kommentierte Seiten',
	'NoAccessToSourcePage'		=> 'Sie sind nicht berechtigt, die Aktionsquellseite zu lesen.',
	'SourcePageDoesntExist'		=> 'Aktionsquellseite existiert noch nicht',
	'NotLoggedInThusEdited'		=> 'Sie sind nicht eingeloggt, daher konnten wir die von Ihnen bearbeiteten Seiten nicht identifizieren.',
	'DidntEditAnyPage'			=> 'Sie haben noch keine Seiten bearbeitet.',
	'NoPagesFound'				=> 'Keine Seiten gefunden.',
	'MyChangesTitle1'			=> 'Dies ist die Liste der Seiten, die Sie bearbeitet haben, sortiert nach dem Zeitpunkt Ihrer letzten Änderung',
	'MyChangesTitle2'			=> 'Dies ist die Liste der Seiten, die Sie bearbeitet haben, zusammen mit der Zeit Ihrer letzten Änderung',
	'OrderABC'					=> 'alphabetisch',
	'OrderCreation'				=> 'nach Erstellung',
	'OrderChange'				=> 'nach Änderung',
	'ListOwnedPages'			=> 'Dies ist die Liste der Seiten, die Sie besitzen (alphabetisch sortiert)',
	'ListOwnedPages2'			=> 'Dies ist die Liste der Seiten, die Sie besitzen (nach Datum sortiert)',
	'ListOwnedPages3'			=> 'Dies ist die Liste der Seiten, die Sie besitzen (nach Änderungen sortiert)',
	'NotLoggedInThusOwned'		=> 'Sie sind nicht eingeloggt, daher konnten wir Ihre Seiten nicht abrufen.',
	'NoOrphaned'				=> 'Keine verwaisten Seiten. Gut.',
	'NoRecentComments'			=> 'Keine aktuellen Kommentare.',
	'LatestCommentBy'			=> 'letzter Kommentar von',
	'NoRecentlyCommented'		=> 'Keine kürzlich kommentierte Seite.',
	'NoDeletedPages'			=> 'Keine gelöschten Seiten gefunden.',
	'NoDeletedRevisions'		=> 'Keine gelöschten Revisionen gefunden.',
	'NoDeletedFiles'			=> 'Keine gelöschten Dateien gefunden.',
	'CommentsDisabled'			=> 'Kommentare sind nicht verfügbar.',

	'SearchResults'				=> 'Suchergebnisse für ',
	'NotFound'					=> 'nicht gefunden',
	'NoResultsFor'				=> 'Keine Ergebnisse für ',
	'SearchFor'					=> 'Suche nach:',
	'TopicSearchResults'		=> 'Suchergebnisse für Themen ',
	'NotFoundInTopics'			=> 'nicht in Themen gefunden',
	'FilterLangNotAvailable'	=> 'Die ausgewählte Sprache ist nicht verfügbar!',

	'PostedBy'					=> 'gepostet von',
	'ThisIsCommentOn'			=> 'Dies ist ein Kommentar zu',
	'At'						=> 'am',
	'To'						=> 'zu',
	'By'						=> 'von',
	'From'						=> 'von',
	'For'						=> 'für',
	'ReturnToCommented'			=> 'Zurück zur kommentierten Seite',
	'AbandonedComment'			=> 'Die Seite, zu der dieser Kommentar gehört, existiert nicht mehr!',

	'PagesLinkingTo'			=> 'Seiten verlinken zu',
	'NoPageLinkingTo'			=> 'Keine Seite verlinkt zu',
	'NoWantedPages'				=> 'Keine gewünschten Seiten. Gut.',
	'RemoveWatch'				=> 'Uhr für diese Seite entfernen',
	'SetWatch'					=> 'Diese Seite ansehen',
	'WatchText'					=> 'Beobachten',
	'UnwatchText'				=> 'Nicht folgen',
	'UserSettingsStored'		=> 'Benutzereinstellungen gespeichert.',
	'LoggedOut'					=> 'Sie sind nun ausgeloggt.',
	'LoggedOutAuto'				=> 'Aus Sicherheitsgründen ist Ihre Sitzung beendet. Bitte melden Sie sich erneut an.',

	// user settings
	'EmailConfirmResent'		=> 'Bestätigungscode per E-Mail an Ihre Adresse gesendet.',
	'EmailConfirmNotSent'		=> 'Der Bestätigungscode konnte nicht gesendet werden: E-Mail wurde nicht angegeben!',
	'Hello'						=> 'Hallo',
	'UserName'					=> 'Benutzername',
	'EmailAddress'				=> 'E-Mail-Adresse',
	'RealName'					=> 'Echter Name',
	'MenuItemsShown'			=> 'Menüpunkte angezeigt',
	'RecordsPerPage'			=> 'Datensätze pro Seite',
	'DoShowComments'			=> 'Kommentare standardmäßig anzeigen',
	'DoubleclickEditing'		=> 'Doppelklick-Bearbeitung',
	'UpdateSettingsButton'		=> 'Update-Einstellungen',

	'AccountDisabled'			=> 'Ihr Konto kann deaktiviert oder gesperrt werden.',
	'WrongPassword'				=> 'Falsches Passwort!',
	'ConfirmPassword'			=> 'Passwort bestätigen',
	'Email'						=> 'E-Mail-Adresse',
	'MustBeWikiName'			=> 'Benutzername muss <a href="https://wackowiki.org/doc/Doc/English/WikiName" target="_blank">WikiName</a> formatiert sein!',
	'SpecifyEmail'				=> 'Sie müssen eine E-Mail-Adresse angeben.',
	'NotAEmail'					=> 'Das sieht nicht wie eine gültige E-Mail-Adresse aus.',
	'EmailTaken'				=> 'Die eingegebene E-Mail-Adresse wird bereits verwendet.',
	'EmailDomainNotAllowed'		=> 'Die eingegebene E-Mail-Adresse %1 ist nicht in der zulässigen Domänenliste.',
	'PasswordsDidntMatch'		=> 'Passwörter stimmen nicht überein.',
	'SpacesArentAllowed'		=> 'Leerzeichen sind in Passwörtern nicht erlaubt.',
	'ListMyPages'				=> 'Ihre Seiten auflisten',
	'ListMyChanges'				=> 'Ihre Änderungen auflisten',
	'ListMyWatches'				=> 'Liste der beobachteten Seiten',
	'ListMyChangesWatches'		=> 'Änderungen unter beobachteten Seiten',
	'SeeListOfPages'			=> 'Sehen Sie eine Liste von Seiten, die Sie besitzen (MyPages) und Seiten, die Sie bearbeitet haben (MyChanges).',
	'AddBookmark'				=> 'Aktuelle Seite zu Lesezeichen hinzufügen',
	'RemoveBookmark'			=> 'Aus Lesezeichen entfernen',

	'YourLanguage'				=> 'Sprache auswählen',
	'ShowSpaces'				=> 'Leerzeichen in WikiNames anzeigen',
	'WrongPage4Redirect'		=> 'Umleitung aufgrund falscher Umleitungsparameter nicht möglich',
	'RedirectsToItself'			=> 'Die Seite leitet zu sich selbst weiter.',
	'ReallyDeletePage'			=> 'Möchten Sie diese Seite wirklich LÖSCHEN?<br>Für diese Aktion gibt es keine Rückgängig!<br><br>WARNUNG: Beim Löschen dieser Seite werden alle Seitenversionen, Kommentare, Anhänge, ACLs und Referrer gelöscht.',
	'CommentForWatchedPage'		=> 'Neuer Kommentar für Seite ',
	'SomeoneCommented'			=> ' kommentierte diese Seite, die Sie beobachten: ',
	'AlertReferringPages'		=> 'Diese Seite wird von diesen Seiten verwiesen',

	'AccountDelete'				=> 'Konto löschen',
	'AccountDeleteConfirm'		=> 'Sind Sie sicher, dass Sie das Konto löschen möchten?',
	'AccountDeleted'			=> 'Konto erfolgreich gelöscht',
	'AccountDeleteHeader'		=> 'Konto %1 löschen',
	'AccountDeleteInfo'			=> 'Of the data you created (e.g. email, preferences, attachments, wiki entries) as much as possible will be deleted. Note, however, that data like attachments and wiki entries cannot be deleted without impeding the work of the other users. Such data is hence reassigned to an account called %1. As the data of every deleted account is reassigned to this account it will not be possible to distinguish the data you created from the data of another deleted account.',
	'AccountDeleteWarning'		=> 'Das Löschen des Benutzerkontos ist eine unumkehrbare Aktion.',
	'AccountDeleteHint'			=> 'Ihr Konto wird aus dem System gelöscht. Sie können sich daher nicht mehr mit Ihren aktuellen Zugangsdaten anmelden. Wenn Sie sich dafür entscheiden, wieder ein Benutzer dieser Anwendung zu werden, können Sie dies mit den Mitteln tun, die diese Anwendung gewährt.',
	'AccountDeleteVerify'		=> 'Geben Sie Ihre Anmeldung %1 ein, um die Löschung zu bestätigen. Einmal abgeschickt, werden Sie aufgefordert, Ihr Passwort zu bestätigen.',

	'MarkRead'					=> 'Alle als gelesen markieren',
	'CurrentTime'				=> 'Zurzeit ist es',
	'Created'					=> 'erstellt',
	'Modified'					=> 'geändert',

	'EditIcon'					=> 'bearbeiten',
	'TreeClusterTitle'			=> 'Baum des Clusters %1',
	'TreeSiteTitle'				=> 'Seitenbaum',
	'TreeEmpty'					=> '%1 hat keine Unterseiten',
	'TreeEmptyLevels'			=> '%1 hat keine Unterseiten für bestimmte Tiefenstufen. Erhöhe den Wert für die Tiefe.',
	'TreeTooBig'				=> 'zu viele Unterseiten',

	// clone handler
	'ClonePage'					=> 'Seite klonen',
	'CloneText'					=> 'Klonen',
	'CloneName'					=> 'Neuen Namen für einen Klon dieser Seite eingeben',
	'CloneButton'				=> 'Klonen',
	'PageCloned'				=> 'Seite %1 geklont.',
	'ClonedFrom'				=> 'Von %1 geklont .',
	'MassClone'					=> 'Gesamten Cluster klonen',
	'MassCloning'				=> 'Klone Cluster.',
	'CloneCannotRead'			=> 'Unlesbare Seite %1.',
	'CloneCannotCreate'			=> 'Nicht erstellbare Seite %1.',

	'SortComment'				=> 'Kommentare sortieren nach',
	'SortCommentAsc'			=> 'Zuletzt unten',
	'SortCommentDesc'			=> 'Zuletzt oben',

	'RenamePage'				=> 'Seite umbenennen',
	'RenameText'				=> 'Umbenennen',
	'RenameTip'					=> 'Seite umbenennen',
	'NewName'					=> 'Neuen Namen für diese Seite eingeben',
	'AlreadyExists'				=> 'Seite %1 existiert bereits.',
	'AlreadyNamed'				=> 'Diese Seite wurde bereits %1 genannt.',
	'PageRenamed'				=> 'Seite umbenannt.',
	'NewNameOfPage'				=> 'Neuer Name dieser Seite: ',
	'NotOwnerCantRename'		=> 'Sie sind nicht Eigentümer dieser Seite und können sie daher nicht umbenennen',
	'NeedRedirect'				=> 'Weiterleitung zur neuen Seite auf der alten Seite erstellen',
	'RedirectCreated'			=> 'Auf der Seite von %1 wurde die Weiterleitung zum neuen erstellt',

	'UserSettings'				=> 'Benutzereinstellungen',
	'UserSettingsGeneral'		=> 'Allgemein',
	'UserSettingsNotifications'	=> 'Benachrichtigungen',

	'NotifyMinorEdit'			=> 'Auch kleinere Änderungen benachrichtigen',
	'NotifyPageEdit'			=> 'Bearbeiten',
	'NotifyComment'				=> 'Kommentar',
	'NotifyOff'					=> 'Aus',
	'NotifyAlways'				=> 'Immer',
	'NotifyPending'				=> 'Ausstehend',
	'NotifyDigest'				=> 'Digest',
	'NotifyPendingPageTip'		=> 'Es wird nur eine Benachrichtigung für die erste Änderung einer Seite gesendet, die Sie beobachten.',
	'NotifyPendingCommentTip'	=> 'Für den ersten Kommentar wird nur eine Benachrichtigung an eine Seite gesendet.',
	'NotifyPendingTip'			=> 'Die Benachrichtigung wird automatisch wieder aktiviert, wenn Sie die aktuelle Version der Seite besuchen.',

	'FurtherPending'			=> 'Bei weiteren Änderungen wird es keine weiteren Benachrichtigungen geben, es sei denn, Sie besuchen diese Seite.',

	'UserSettingsEmailMe'		=> 'E-Mail wenn ...',

	'UserSettingsExtended'		=> 'Erweitert',
	'UserSettingsOther'			=> 'Andere Einstellungen',
	'UserSpace'					=> 'Benutzerbereich',
	'ChooseTheme'				=> 'Theme auswählen',

	'CreatePage'				=> 'Diese Seite erstellen',
	'CreateNewPage'				=> 'Neue Seite erstellen',
	'CreateNewPageText'			=> 'Anlegen',
	'CreateNewPageTip'			=> 'Neue Seite erstellen',

	'CreateRandomPage'			=> 'Erstelle eine zufällige Seite:',
	'CreateSubPage'				=> 'Erstelle eine Unterseite im Cluster:',
	'CreatePageParentCluster'	=> 'Erstelle eine Seite im übergeordneten Cluster:',
	'CreatePageDenied'			=> 'Sie haben nicht die notwendigen Zugriffsrechte.',
	'CreatePageDeniedAddress'	=> 'Sie haben nicht das Recht, die Seite unter dieser Adresse zu erstellen.',
	'PageAlreadyExists'			=> 'Nach der Adresse ist die Seite %1 bereits vorhanden.',
	'PageAlreadyExistsEdit'		=> 'Willst du %1?',
	'PageAlreadyExistsEdit2'	=> 'bearbeiten',
	'PageAlreadyExistsEditDenied'	=> 'Du kannst es nicht bearbeiten.',

	'SimilarPagesExists'		=> 'Ähnliche Seiten wie %1 existieren bereits:',
	'SimilarPagesHint'			=> 'Es gibt ähnliche Seiten wie %1:',

	'PageReservedWord'			=> 'Sie können %1 nicht als Teil der Adresse verwenden, da es sich um ein reserviertes Wort handelt.',
	'UserReservedWord'			=> 'Benutzernamen dürfen nicht %1 enthalten, da es sich um ein reserviertes Wort handelt.',

	'DontRedirect'				=> 'Automatische Weiterleitung durch Aktion Umleitung nicht erlauben.',
	'SendWatchEmail'			=> 'Senden Sie eine Benachrichtigung per E-Mail, wenn jemand (außer Ihnen) eine Seite ändert, die Sie beobachten',
	'AllowIntercom'				=> 'Erlaube persönliche Nachrichten von Benutzern des Systems',
	'AllowMassemail'			=> 'Administratoren können mir Informationen per E-Mail senden',
	'HideLastSession'			=> 'Letzte Sitzung ausblenden',
	'ValidateIP'				=> 'Sitzung wird an IP gebunden',
	'AnonymousPub'				=> 'Vorzugsweise anonym veröffentlicht (um den Namen zu verbergen)',
	'PageMoved'					=> 'Diese Seite verschoben. Sie finden sie unter',
	'RedirectedFrom'			=> 'Umgeleitet von %1',
	'RedirectedTo'				=> 'Umgeleitet zu',
	'CurrentPassword'			=> 'Aktuelles Passwort',
	'NewPassword'				=> 'Neues Passwort',
	'YouWantChangePassword'		=> 'Passwort ändern',
	'ChangePasswordButton'		=> 'Passwort ändern',
	'PasswordChanged'			=> 'Passwort geändert',
	'EmailWelcome'				=> 'Sie haben sich registriert am ',
	'EmailRegistered'			=> 'Sie haben sich erfolgreich bei %1 registriert.' . "\n" . 'Ihr Benutzername: %2' . "\n\n",
	'EmailVerify'				=> 'Wenn Sie Benachrichtigungen erhalten möchten, müssen Sie Ihre E-Mail-Adresse bestätigen. Bitte klicken Sie auf oder kopieren Sie den folgenden Link in einen Webbrowser: ' . "\n" . '%1',
	'EmailRegisteredLogin'		=> 'Bitte kehren Sie zum Wiki zurück und melden Sie sich mit Ihrem neuen Benutzernamen und Passwort an.',
	'EmailRegisteredIgnore'		=> 'Wenn Sie diese Registrierung nicht angefordert haben, ignorieren Sie diese Nachricht und nichts wird passieren.',
	'EmailDoNotReply'			=> 'Antworten Sie nicht auf diese Nachricht.',
	'EmailReverify'				=> 'Jemand (vielleicht du) hat Ihre E-Mail als Benachrichtigungsadresse bei %1 eingereicht.' . "\n" . 'Ihr Benutzername: %2'."\n\n" . 'Wenn Sie Benachrichtigungen erhalten möchten, müssen Sie Ihre E-Mail bestätigen. Bitte folgen Sie dem Link, um dies zu tun.' . "\n" . '%3' . "\n\n",
	'EmailConfirm'				=> 'Bitte bestätigen Sie Ihre E-Mail',
	'EmailConfirmed'			=> 'E-Mail erfolgreich bestätigt.',
	'EmailNotConfirmed'			=> 'E-Mail kann nicht bestätigt werden. Dies kann durch einen falschen Bestätigungscode oder die E-Mail-Adresse bereits bestätigt werden. Sie können überprüfen, ob die E-Mail-Adresse bereits bestätigt ist, indem Sie sich auf Ihrer %1 Seite anmelden und ihren Status ansehen.',
	'EmailNotVerified'			=> 'E-Mail nicht überprüft!',
	'EmailNotVerifiedDesc'		=> 'Sie erhalten keine Benachrichtigung über Änderungen oder Kommentare von beobachteten Seiten, ' .
									'or messages from other users. Also, you <strong>will not be able to recover a forgotten password</strong>, ' .
									'bis Ihre E-Mail-Adresse bestätigt ist, indem Sie auf den Link in der E-Mail klicken. ' .
									'Wenn Sie innerhalb weniger Tage nach der Registrierung keine E-Mail erhalten, fragen Sie es erneut durch Klicken auf ',

	'ForgotPasswordHint'		=> 'Geben Sie Ihre Login- und E-Mail-Adresse ein' . "\n" . 'dann wird Ihnen eine E-Mail mit Anweisungen geschickt.',
	'ForgotPassword'			=> 'Passwort vergessen?',
	'UserNotFound'				=> 'Benutzer mit diesem Namen oder dieser E-Mail-Adresse wurde nicht gefunden.',
	'NotConfirmedEmail'			=> 'Ihre E-Mail-Adresse wurde nicht bestätigt.<br>E-Mail kann nicht an eine nicht bestätigte Adresse gesendet werden.',
	'EmailForgotSubject'		=> 'Passwort erneuern für ',
	'EmailForgotMessage'		=> 'Jemand (vielleicht du) hat Ihr Passwort für %1 vergessen.' . "\n" . 'Ihr Login: %2'."\n\n" . 'Klicken Sie auf den Link oder kopieren Sie ihn in die Adresszeile des Browsers, um Ihr Passwort zu ändern.' . "\n" . '%3'."\n\n",
	'CodeWasSent'				=> 'Die Anleitung zur Passwortwiederherstellung wurde Ihnen per E-Mail zugeschickt.',
	'WrongCode'					=> 'Falscher Code',
	'ChangePasswordForUser'		=> 'Passwortänderung von %1',

	'Watchers'					=> 'Liste der Beobachter für %1',
	'WatchersFor'				=> 'Beobachter für',
	'NoWatchers'				=> 'Es gibt keine Beobachter für %1',
	'NotOwnerToViewWatchers'	=> 'Sie sind nicht der Besitzer dieser Seite und Sie können keine Liste der Beobachter dafür sehen.',

	// thumbnail
	'TbnError'					=> 'Fehler beim Erstellen des Thumbnails: %1',
	'TbnImageAreaTooBig'		=> 'Datei mit Größen größer als %1',
	'TbnImageMissing'			=> 'Datei scheint fehlt: %1',

	// admin_recovery action
	'GenerateRecoveryHash'		=> 'Generieren Sie den Passwort-Hash für Ihr <code>recovery_password</code>',

	// import action
	'ImportTo'					=> 'In Cluster importieren:',
	'ImportWhat'				=> 'XML-Datei zum Importieren:',
	'ImportButton'				=> 'Importieren',
	'ImportSuccess'				=> 'Erfolgreich importiert.',
	'ImportFailed'				=> 'WICHTIG.',
	'ImportHint'				=> 'Bitte gib einen Cluster an, in den du importieren möchtest, keine relative Adresse.',
	'ImportAttention'			=> 'Achtung: Überschreibt die gleichen Seiten im Cluster.',
	'ImportNote'				=> 'Importierte Seite',

	// mywatches action
	'WatchedPages'				=> 'Liste aller Seiten, denen Sie folgen für Änderungen ',
	'UnwatchedPages'			=> 'Liste aller Seiten, die Sie nicht beobachten',
	'NoWatchedPages'			=> 'Sie haben keine beobachteten Seiten.',
	'NoUnwatchedPages'			=> 'Sie beobachten Änderungen auf allen Seiten.',
	'ViewWatchedPages'			=> 'Gesehene Seiten anzeigen',
	'ViewUnwatchedPages'		=> 'Ungesehene Seite anzeigen',
	'NotLoggedInWatches'		=> 'Sie sind nicht eingeloggt, daher konnten wir Ihre Liste der Uhren nicht identifizieren.',

	// mychangeswatches action
	'MyChangesWatches'			=> 'Liste aller Seiten, die Sie gesehen haben, die von anderen seit Ihrer letzten Bearbeitung bearbeitet wurden',
	'ResetChangesWatches'		=> 'die Liste der Änderungen zurücksetzen',
	'NoChangesWatches'			=> 'Unter Ihren beobachteten Seiten sind keine Änderungen...',

	// whatsnew action
	'NewCommentAdded'			=> 'Neuer Kommentar hinzugefügt',
	'NewFileAdded'				=> 'Neue Datei hinzugefügt',
	'NewPageCreated'			=> 'Neue Seite erstellt',
	'NewRevisionAdded'			=> 'Seite geändert',
	'Cluster'					=> 'Cluster',
	'PageDeleted'				=> 'Seite gelöscht',
	'CommentDeleted'			=> 'Kommentar gelöscht',
	'FileDeleted'				=> 'Datei gelöscht',

	// users action
	'UsersSearch'				=> 'Benutzer finden',
	'UsersOpenProfile'			=> 'Profil anzeigen',
	'UsersNoMatching'			=> 'Passende Benutzer nicht gefunden. Versuchen Sie weniger strenge Suchkriterien.',
	'UsersName'					=> 'Name',
	'UsersPages'				=> 'Seiten',
	'UsersChanges'				=> 'Änderungen',
	'UsersSubscription'			=> 'Abonnement',
	'UsersWatches'				=> 'Uhren',
	'UsersComments'				=> 'Kommentare',
	'UsersUploads'				=> 'Uploads',
	'UploadQuota'				=> 'Verwendeter Speicherplatz',
	'UploadQuotaTip'			=> 'Raumkontingent hochladen',
	'UsersLogins'				=> 'Anmeldungen',
	'UsersRevisions'			=> 'Versionen',
	'UsersSignup'				=> 'Anmelden',
	'UsersLastSession'			=> 'Letzte Sitzung',
	'UsersNotFound'				=> 'Benutzer %2 nicht gefunden. Klicken Sie <a href="%1">hier</a>, um zur Hauptliste zu gelangen.',
	'UsersProfile'				=> 'Profil',
	'UsersContact'				=> 'Kontakt',
	'UsersList'					=> 'Gesamte Liste der Benutzer anzeigen',
	'UsersNA'					=> '[nicht gesetzt]',
	'UsersNA2'					=> '[No]',
	'UsersSignupDate'			=> 'Anmeldedatum',
	'UsersGroupMembership'		=> 'Gruppenmitgliedschaft',
	'UsersPersonalInfo'			=> 'Persönliche Info',
	'UsersOwnedPages'			=> 'Eigene Seiten:',
	'UsersCommentsPosted'		=> 'Kommentare gepostet:',
	'UsersFilesUploaded'		=> 'Dateien hochgeladen:',
	'UsersRevisionsMade'		=> 'Revisionen gemacht:',
	'UsersDocsSortName'			=> '[Nach Namen sortieren]',
	'UsersDocsSortCreation'		=> '[Nach Erstellungsdatum sortieren]',
	'UsersChangesSortAsc'		=> 'Aufsteigend sortieren]',
	'UsersChangesSortDesc'		=> '[Absteigend sortieren]',
	'UsersSessionNA'			=> '[nicht aufgezeichnet]',
	'UsersSessionHidden'		=> '[hidden]',
	'IntercomSubject'			=> 'Betreff:',
	'IntercomMessage'			=> 'Nachricht:',
	'IntercomCopy'				=> 'Senden Sie mir eine Kopie',
	'IntercomSubjectN'			=> '[ein neues Thema starten]',
	'IntercomDisabled'			=> 'Entschuldigung, Sie wollen oder können keine persönlichen Nachrichten empfangen.',
	'IntercomHint'				=> 'Bitte melden Sie sich zuerst an und folgen Sie dem Link, wenn Sie die persönliche Nachricht beantworten möchten, die Sie erhalten haben.',
	'IntercomDesc'				=> 'Hinweis: Senden von persönlichen Nachrichten an den E-Mail-Empfänger ohne Angabe Ihrer Adresse. Der Empfänger kann Ihnen mit einem ähnlichen Formular auf Ihrer Profilseite antworten. ',
	'PMOversized'				=> 'Die Länge der Nachricht überschreitet die maximal zulässige Größe um %1. Bitte kürzen Sie Ihre Nachricht und senden Sie sie erneut ab.',
	'PMFlooded'					=> 'Das Intervall zwischen dem Senden persönlicher Nachrichten sollte nicht weniger als %1 Sekunden betragen.',
	'PMSent'					=> 'Persönliche Nachricht wurde erfolgreich an den Benutzer gesendet.',
	'PMBody'					=> 'Diese Nachricht wurde Ihnen vom Benutzer %1 zugeschickt.',
	'PMBodyCopy'				=> 'Sie haben die folgende Nachricht an den Benutzer %1 gesendet.',
	'PMReply'					=> 'Um diese E-Mail zu beantworten, klicken Sie auf den folgenden Link (verwenden Sie nicht den Antwort-Button / Antworten im Mailer):',
	'PMNotLoggedIn'				=> 'Sie sind nicht im System registriert und können keine persönlichen Nachrichten an Benutzer senden.',

	// admin_replace action
	'ReplaceText'				=> 'Text ersetzen',
	'TextOriginal'				=> 'Originaltext:',
	'TextReplacement'			=> 'Ersetzungstext',
	'ReplaceTextRegex'			=> 'Reguläre Ausdrücke verwenden',
	'Namespace'					=> 'Namensraum:',
	'ReplaceTextCluster'		=> 'Nur innerhalb dieses Clusters suchen und ersetzen:',
	'ReplaceTextEditPages'		=> 'Text in Seiteninhalt ersetzen',
	'ReplaceTextEditComments'	=> 'Text in Kommentaren ersetzen',
	'ReplaceTextEditTitles'		=> 'Text in Seitentitel ersetzen',
	'ReplaceTextGiveTarget'		=> 'Sie müssen die Zeichenkette angeben, die ersetzt werden soll.',
	'ReplaceTextNoNamespace'	=> 'Sie müssen mindestens einen Namensraum auswählen.',
	'ReplaceTextNoDifference'	=> 'Es gibt keinen Unterschied zwischen Ersetzungstext und Zieltext.',
	'ReplaceTextNoOption'		=> 'Sie müssen mindestens eine der Ersatzoptionen auswählen.',
	'ReplaceTextPagesEdit'		=> 'Ersetzen Sie %1 durch %2 im Text der folgenden %3 Seiten:',
	'ReplaceTextTitlesEdit'		=> 'Ersetzen Sie %1 durch %2 in den Titeln der folgenden %3 Seiten:',
	'ReplaceTextReplace'		=> 'Ersetzen',
	'ReplaceTextSuccess'		=> '%1 wurde auf %3 Seiten durch %2 ersetzt.',
	'ReplaceTextNoMatch'		=> 'Es wurden keine Seiten gefunden, die den String %1 enthalten.',
	'ReplaceTextNoTitleMatch'	=> 'Es wurden keine Seiten gefunden, deren Titel %1 enthält.',
	'ReplaceTextEditFailed'		=> 'Ersetzen des Textes fehlgeschlagen',
	'ReplaceTextTitleTooBig'	=> 'Original- oder Ersatztext ist zu groß für den Titel.',
	'ReplaceTextReturn'			=> 'Zurück zum Formular',
	'ReplaceTextWarning'		=> 'Warnung: Es gibt %1 Seiten, die bereits den Ersetzungsstring enthalten, %2. Wenn Sie diesen Ersatz vornehmen, werden Sie nicht in der Lage sein, Ihre Ersetzungen von diesen Strings zu trennen.',
	'ReplaceTextBlankWarning'	=> 'Warnung: Da der Ersetzungsstring leer ist, ist diese Operation nicht umkehrbar.',
	'ReplaceTextEditSummary'	=> 'Textersetzung: %1 → %2',
	'InvertSelection'			=> 'Auswahl umkehren',

	// Properties
	'PropertiesFor'				=> 'Seiteneigenschaften für %1',
	'MetaTag'					=> 'Markierung',
	'MetaTitle'					=> 'Titel',
	'MetaKeywords'				=> 'Stichwörter',
	'MetaDescription'			=> 'Beschreibung',
	'On'						=> 'An',
	'Off'						=> 'Aus',
	'Registered'				=> 'Registriert',
	'MetaComments'				=> 'Kommentare anzeigen',
	'MetaFiles'					=> 'Datei-Panel anzeigen',
	'MetaToc'					=> 'Inhaltsverzeichnis anzeigen',
	'MetaIndex'					=> 'Cluster-Bereich anzeigen',
	'MetaIndexMode'				=> 'Ebenenmodus anzeigen',
	'MetaIndexFull'				=> 'Baum',
	'MetaIndexUpper'			=> 'Oben',
	'MetaIndexLower'			=> 'Unterer',
	'MetaHtml'					=> 'HTML-Unterstützung für Seite',
	'MetaSafeHtml'				=> 'Filtern von unsicherem HTML',
	'MetaTypografica'			=> 'Typografischer Korrekturleser',
	'MetaNoIndex'				=> 'Suchmaschinen blockieren',
	'SettingsID'				=> 'Seiten-ID',
	'SettingsSize'				=> 'Größe',
	'SettingsSizeTip'			=> 'quelle / kompiliert',
	'SettingsCreated'			=> 'Erstellt',
	'SettingsCurrent'			=> 'Geändert',
	'SettingsTotalRevs'			=> 'Versionen',
	'SettingsTotalComs'			=> 'Kommentare',
	'SettingsWatchers'			=> 'Beobachter',
	'SettingsHits'				=> 'Aufrufe',
	'SettingsText'				=> 'Einstellungen',
	'SettingsEdit'				=> 'Bearbeiten',
	'SettingsRevisions'			=> 'Versionen',
	'SettingsClone'				=> 'Klonen',
	'SettingsRename'			=> 'Umbenennen',
	'MassRename'				=> 'für den ganzen Cluster',
	'SettingsRemove'			=> 'Entfernen',
	'SettingsPurge'				=> 'Purge',
	'SettingsModerate'			=> 'Mäßig',
	'SettingsPermissions'		=> 'Berechtigungen',
	'AclForEntireCluster'		=> 'für den ganzen Cluster',
	'SettingsAttachments'		=> 'Anhänge',
	'SettingsUpload'			=> 'Hochladen',
	'SettingsCategories'		=> 'Kategorien',
	'SettingsLanguages'			=> 'Sprachen',
	'SettingsReferrers'			=> 'Verweise',
	'SettingsWatch'				=> 'Beobachten',
	'SettingsLatex'				=> 'LaTeX-Version',
	'SettingsXML'				=> 'Als XML exportieren',
	'NeedToChangeLang'			=> 'Nicht unterstützte Seitensprache %1 muss geändert werden.',
	'SetLang'					=> 'Sprache dieser Seite',
	'SetMenuLabel'				=> 'Menübezeichnung',
	'SetShowMenuLabel'			=> 'In Navigation anzeigen',

	// upload
	'UploadFiles'				=> 'Dateien hochladen',
	'UploadFor'					=> 'Datei-Upload:',
	'UploadButton'				=> 'Hochladen',
	'UploadGlobalText'			=> 'für öffentlichen Zugang',
	'UploadGlobal'				=> 'global',
	'UploadLocalText'			=> 'nur für Benutzer, die die aktuelle Seite ansehen dürfen',
	'UploadAsName'				=> 'Name:',
	'UploadOverwrite'			=> 'Bestehende Dateien überschreiben',
	'FileDesc'					=> 'Beschreibung:',
	'UploadForbidden'			=> 'Sie sind hier nicht berechtigt, Dateien hochzuladen.',
	'UploadOverwriteDenied'		=> 'Nur der Besitzer oder Administrator kann die %1 Datei überschreiben.',
	'UploadNoFile'				=> 'Es gab aus irgendeinem Grund keine Datei in Form.',
	'UploadMaxSizeReached'		=> 'Dateigröße ist über dem zulässigen Limit!',
	'UploadDirNotWritable'		=> 'Dateiverzeichnis ist nicht beschreibbar!',
	'UploadNotAPicture'			=> 'Das Hochladen von Bildern ist nur erlaubt. Was versuchst du hochladen?',
	'UploadEmptyExtension'		=> 'Der Dateiname und die Endung dürfen nicht leer sein.',
	'FilenameTooLong'			=> 'Dateinamen dürfen nicht länger als 240 Bytes sein.',
	'BannedFiletype'			=> '%1 ist kein erlaubter Dateityp.',
	'PermittedFiletype'			=> 'Erlaubte Dateitypen:',
	'UploadMimeMismatch'		=> 'Die Dateiendung %1 stimmt nicht mit dem erkannten MIME-Typ der Datei überein (%2).',
	'UploadBadMime'				=> 'Dateien des MIME-Typs %1 dürfen nicht hochgeladen werden.',
	'FileIsDuplicate'			=> 'Der Upload ist ein exaktes Duplikat der aktuellen Version.',
	'FileHasDuplicate'			=> 'Diese Datei ist ein Duplikat der folgenden Dateien:',

	'UploadMaxFileQuota'		=> 'Sie haben Ihr Upload-Limit erreicht. Diese Datei kann nicht hochgeladen werden',
	'UploadDone'				=> 'Dateiupload erfolgreich',
	'UploadFileForbidden'		=> 'Dateizugriff verboten',
	'UploadTitle'				=> 'Von dieser Seite zugängliche Dateien',
	'UploadTitleGlobal'			=> 'Dateien von überall aus erreichbar',

	'UploadFile'				=> 'Hochladen',
	'UploadMax'					=> 'Nicht mehr als ',
	'UploadUsedStorage'			=> 'Verwendeter Speicher ',

	// attachments
	'Attachments'				=> 'Anhänge',
	'Attachment'				=> 'Anhang',
	'AttachmentsToPage'			=> 'zu Seite',
	'AttachmentsToCluster'		=> 'Cluster',
	'AttachmentsByTime'			=> 'nach Zeit',
	'AttachmentsGlobal'			=> 'global',
	'AttachmentsAll'			=> 'alle',
	'AttachmentsLinked'			=> 'verwendet',

	'FileViewProperties'		=> 'Ansicht',
	'FileViewPropertiesTip'		=> 'Metadaten dieser Datei anzeigen',
	'FileEditProperties'		=> 'Bearbeiten',
	'FileEditPropertiesTip'		=> 'Metadaten dieser Datei bearbeiten',
	'FileEditedMeta'			=> 'Metadaten dieser Datei aktualisiert',
	'FileEditDenied'			=> 'Sie sind nicht berechtigt, diese Datei zu bearbeiten',
	'FileLabel'					=> 'Label',
	'FileLabelTip'				=> 'Diese Datei benennen',
	'FileRemove'				=> 'Entfernen',
	'FileRemovedFromDB'			=> 'Datei aus der Datenbank entfernt',
	'FileRemovedFromFS'			=> 'Datei vom physischen Hosting gelöscht',
	'FileRemovedFromFSError'	=> 'Es scheint unmöglich zu sein, die Datei zu löschen!',
	'FileRemoveConfirm'			=> 'Sicher, diese Datei zu entfernen?',
	'FileRemoveDenied'			=> 'Sie sind nicht berechtigt, diese Datei zu entfernen',
	'FileNotFound'				=> 'Datei nicht gefunden.',

	'FileSearch'				=> 'Datei suchen',
	'UploadBy'					=> 'Hochgeladen von:',
	'FileAdded'					=> 'Hinzugefügt:',
	'FileModified'				=> 'Geändert:',
	'FileSize'					=> 'Größe:',
	'FileDimension'				=> 'Dimension:',
	'MimeType'					=> 'Mimetyp:',
	'FileName'					=> 'Name:',
	'FileCaption'				=> 'Überschrift:',
	'FileAuthor'				=> 'Autor:',
	'FileSource'				=> 'Quelle:',
	'FileSourceUrl'				=> 'URL:',
	'FileAttachedTo'			=> 'Angehängt an:',
	'FileSyntax'				=> 'Syntax:',
	'FileAbsolutePath'			=> 'absoluter Pfad',
	'FileRelativePath'			=> 'relativer Pfad',
	'FileUsage'					=> 'Datei-Nutzung:',
	'FileUsageText'				=> 'Die folgenden Seiten Link zu dieser Datei:',
	'NoFileUsage'				=> 'Kein Link zu dieser Datei.',

	'FileSortExt'				=> 'ausbau',
	'FileSortName'				=> 'name',
	'FileSortSize'				=> 'grösse',
	'FileSortTime'				=> 'erstellt',

	'SortBy'					=> 'Sortieren nach',
	'Ascending'					=> 'aufsteigend',
	'Decending'					=> 'absteigend',

	'Files0'					=> 'Dateien anhängen',
	'Files1'					=> 'Dateien anzeigen (1 Datei)',
	'FilesN'					=> 'Dateien anzeigen (%1 Dateien)',
	'Files'						=> 'Dateien',
	'File'						=> 'Datei',
	'ShowFiles'					=> 'Dateien / Formular anzeigen',
	'HideFiles'					=> 'Dateien ausblenden / Formular',
	'DoShowFiles'				=> 'Dateilisten standardmäßig anzeigen',
	'NoAttachments'				=> 'Es gibt keine angehängten Dateien zum Anzeigen.',

	'RegistrationLang'			=> 'Ihre Sprache',
	'InvalidWikiName'			=> 'Ausgewählter Name ist ungültig',
	'InvalidUserName'			=> 'Ausgewählter Benutzername ist ungültig',
	'Bookmarks'					=> 'Lesezeichen',
	'ReallyDeleteComment'		=> 'Möchten Sie diesen Kommentar wirklich LÖSCHEN?<br>Für diese Aktion gibt es keine Rückgängig!',
	'ReallyDeleteRevision'		=> 'Möchtest du diese Revision wirklich LÖSCHEN?<br>Für diese Aktion gibt es keine Rückgängigkeit!',

	'RegistrationClosed'		=> 'Registrierung ist hier nicht verfügbar. Versuchen Sie, den Administrator der Website zu kontaktieren.',
	'AclAreYouSure'				=> 'Sie werden ACLs dieser Seite und all ihre Unterseiten ändern. Fortfahren?',

	'BookmarkDeleteSelected'	=> 'Ausgewählte löschen',
	'BookmarkMark'				=> 'Markierung',
	'BookmarkNumber'			=> 'Nein.',
	'BookmarkNone'				=> 'Sie haben keine Lesezeichen.',
	'BookmarkTitle'				=> 'Lesezeichen-Titel',
	'BookmarkPage'				=> 'Seite',
	'BookmarkSaveChanges'		=> 'Änderungen speichern',
	'BookmarksAddPage'			=> 'Lesezeichen für die folgende Seite festlegen',
	'BookmarkAlreadyExists'		=> 'Das Lesezeichen existiert bereits.',

	'PoweredBy'					=> 'Unterstützt von',

	'MassRenaming'				=> 'Gesamten Cluster umbenennen',
	'MassNewName'				=> 'Neuen Namen für diesen Cluster eingeben',
	'MassNeedRedirect'			=> 'Weiterleitung zu den neuen Seiten auf den alten Seiten erstellen',

	// pagination
	'ToOverview'				=> 'Zurück zur Übersicht',
	'Overview'					=> 'Übersicht',
	'ToThePage'					=> 'Zur Seite:',
	'Next'						=> 'Nächste',
	'Prev'						=> 'Vorher',
	'NextAcr'					=> 'Nächste',
	'PrevAcr'					=> 'Vorher',
	'Back'						=> 'Zurück',

	// filter
	'Filter'					=> 'Filtern',
	'OptionalFilters'			=> 'Optionale Filter:',
	'Any'						=> 'Alle',

	// My Groups
	'UserGroups'				=> 'Benutzergruppen',
	'MyGroups'					=> 'Gruppenzuordnungen',
	'Group'						=> 'gruppe',
	'Groups'					=> 'gruppen',

	// license action
	'DistributedUnder'			=> 'Material ist verteilt unter',
	'AuthorsDisplayHint'		=> 'Die Liste der Autoren wird beim Speichern der Seite angezeigt.',
	'AnonymousUsers'			=> 'Anonyme Benutzer',
	'License'					=> 'Lizenz',
	'LicenseArray'				=> [
		'1'		=> 'Namensnennung-NoDerivate',
		'2'		=> 'Namensnennung-Nichtkommerziell-ShareAlike',
		'3'		=> 'Namensnennung-Nichtkommerzial-NoDerivate',
		'4'		=> 'Namensnennung-Alike',
		'5'		=> 'Namensnennung-Nicht-Kommerzielles',
		'6'		=> 'Zuordnung',
		'7'		=> 'CC0 1.0 Universal',
		'8'		=> 'GNU Free Documentation Lizenz',
		'9'		=> 'Öffentliche Domäne / Freie Nutzung',
		'10'	=> 'Alle Rechte vorbehalten',
	],
	'LicenseMeta'				=> [
		'1'		=> 'Öffentliche Domain',
		'2'		=> 'Einige Rechte vorbehalten',
		'3'		=> 'Alle Rechte vorbehalten',
	],

	// Cache
	'ClearCache'				=> 'Cache leeren',
	'CacheCleared'				=> 'Cache geleert.',
	'ConfigCache'				=> 'Cache konfigurieren',
	'FeedCache'					=> 'Feed-Cache',
	'PageCache'					=> 'Seitencache',
	'SQLCache'					=> 'SQL-Cache',
	'TemplateCache'				=> 'Vorlagencache',
	'ThumbCache'				=> 'Thumbnail cache',

	// Embed
	'EmbedNoURL'				=> 'Bitte geben Sie eine Adresse der Ressource mit der Parameter-URL an. (z.B. {{embed url="https://example.com/embed/video.mp4"}} )',

	// Feed
	'FeedTitle'					=> 'Feed-Titel',
	'FeedMulti'					=> 'Multi-Feed',
	'FeedNoURL'					=> 'Bitte geben Sie einen Feed mit der Parameter-URL an. (z.B. {{feed url="https://example.com/feed.xml"}} )',
	'FeedError'					=> 'Feed konnte nicht geladen oder analysiert werden',
	'FeedSource'				=> 'Quelle:',
	'FeedXMLTip'				=> '',

	// XML / RSS autodiscovery
	'ChangesXMLTitle'			=> ' - Letzte Änderungen',
	'ChangesXML'				=> 'Letzte Änderungen am ',
	'CommentsXMLTitle'			=> ' - Letzte Kommentare',
	'CommentsXML'				=> 'Kürzliche Kommentare zu den ',
	'NewsXMLTitle'				=> ' - Neueste Nachrichten',
	'NewsXML'					=> 'Neueste Nachrichten an die ',
	'RevisionXMLTip'			=> 'Klicken Sie hier, um die letzten Seitenversionen im XML-Format anzuzeigen.',
	'CommentsXMLTip'			=> 'Klicken Sie hier, um die letzten Kommentare im XML-Format anzuzeigen.',
	'ChangesXMLTip'				=> 'Klicken Sie hier, um die letzten Änderungen im XML-Format anzuzeigen.',
	'NewsXMLTip'				=> 'Klicken Sie hier, um aktuelle Nachrichten im XML-Format anzuzeigen.',
	'RevisionsXML'				=> 'Versionen von ',
	'ExportClusterXML'			=> 'Export des gesamten Clusters von ',
	'AccessDeniedXML'			=> 'Sie sind nicht berechtigt, auf diese Informationen zuzugreifen.',

	'ChangesFeed'				=> 'Änderungen',
	'CommentsFeed'				=> 'Kommentare',
	'NewsFeed'					=> 'Nachrichten',
	'RevisionsFeed'				=> 'Versionen von ',

	'LastModification'			=> 'Letzte Änderung',

	// Captcha
	'Captcha'					=> 'Bitte geben Sie das Wort ein, das Sie im Bild lesen',
	'CaptchaFailed'				=> 'Sie haben das Captcha-Wort falsch eingegeben. Bitte versuchen Sie es erneut.',
	'CaptchaReload'				=> 'Neues Captcha',
	'CaptchaReloadWarning'		=> 'Das Captcha-Bild kann leider nicht neu geladen werden. Du musst die Seite neu laden um dies zu tun',

	// news
	'News'						=> 'Nachrichten',
	'NewsName'					=> 'Titel:',
	'NewsNoName'				=> 'Du hast vergessen, die Schlagzeile hinzuzufügen.',
	'NewsNotAvailable'			=> 'Keine Nachrichten verfügbar.',
	'NewsNoClusterDefined'		=> 'Kein News-Cluster definiert.',
	'NewsDiscuss'				=> 'Diskutieren Sie diesen Artikel...',

	// blog
	'BlogNewTopic'				=> 'Neuen Beitrag erstellen',
	'NoPostAvailable'			=> 'Noch kein Beitrag verfügbar.',

	// Review
	'Reviewer'					=> 'Prüfer',
	'Reviewed'					=> 'überprüft',
	'Review'					=> 'bewerten',
	'ReviewedBy'				=> 'überprüft von',
	'RemoveReview'				=> 'Bewertung für diese Seite entfernen',
	'SetReview'					=> 'Diese Seite überprüft',
	'SetAsReviewed'				=> 'Seite als überprüft festlegen',
	'SetAsUnreviewed'			=> 'Seite als ungeprüft festlegen',

	// word filter
	'PotentialSpam'				=> 'Identifizierter potenzieller Spam',

	// moderation handler
	'Moderation'				=> 'Moderation',
	'Topics'					=> 'themen',
	'ModerateSection'			=> 'abschnitt / Seite ',

	'NotModerator'				=> 'Sie haben keine Befugnis, diese Seite / Kapitel zu moderieren',
	'ModerateDeleteTopic'		=> 'Thema / Seite löschen',
	'ModerateDeletePosts'		=> 'Kommentare löschen',
	'ModerateMove'				=> 'Bewegen',
	'ModerateSplit'				=> 'Kommentare teilen / verschieben',
	'ModerateMerge'				=> 'Zusammenführen',
	'ModerateLock'				=> 'Sperren',
	'ModerateUnlock'			=> 'Entsperren',
	'ModerateAccept'			=> 'Akzeptieren',
	'ModerateDeleteConfirm'		=> 'Are you sure you want to <strong>remove</strong> the following topics?',
	'ModerateRenameConfirm'		=> 'Neuen Titel für die ausgewählte Seite eingeben',
	'ModerateRenameExists'		=> 'Seite mit gleichem Namen existiert bereits! Wählen Sie einen anderen Namen.',
	'ModerateRename1Only'		=> 'Hinweis: Nur die erste Seite, die Sie ausgewählt haben, wird umbenannt!',
	'ModerateMovesConfirm'		=> 'Wählen Sie die Ziel-Partition, um das Forum zu verschieben',
	'ModerateMoveConfirm'		=> 'Wählen Sie das Forum oder geben Sie den Cluster an, um diese Themen zu verschieben. Um eine Seite in das Stammverzeichnis der Site zu verschieben, geben Sie &quot;/&quot; ein',
	'ModeratePgMoveConfirm'		=> 'Geben Sie den Namen des Clusters an, in dem die Seite platziert werden soll. Um eine Seite in das Stammverzeichnis der Site zu verschieben, tippen Sie &quot;/&quot;',
	'ModerateMoveExists'		=> 'Vorgang abgebrochen: In diesem Abschnitt gibt es bereits Themen mit dem gleichen Namen %1. Wenn Sie die oben genannten Themen noch übertragen müssen, benennen Sie sie bitte zuerst um.',
	'ModerateMoveNotExists'		=> 'Die Seite / der Cluster existiert nicht. Bitte überprüfen Sie den Namen und versuchen Sie es erneut.',
	'ModerateMergeConfirm'		=> 'Wählen Sie ein Thema, das den Rest kombinieren soll',
	'ModerateMerge2Min'			=> 'Um beizutreten müssen Sie mindestens zwei Themen wählen!',
	'ModerateComDelConfirm'		=> 'Bist du sicher, dass du <strong></strong> %1 %2 entfernen möchtest?',
	'ModerateComment'			=> 'Kommentar',
	'ModerateComments'			=> 'Kommentare',
	'ModerateSplitNewName'		=> 'Geben Sie einen Namen für ein separates Thema ein und wählen Sie ein Trennschema',
	'ModerateSplitPageName'		=> 'Geben Sie den Namen der Seite / des Themas ein, wo trennbare Kommentare verschoben werden sollen, und wählen Sie ein Trennungsschema',
	'ModerateSplitAllAfter'		=> 'Trenne alle Kommentare nach dem ersten ausgewählt (und einschließlich)',
	'ModerateSplitSelected'		=> 'Nur ausgewählte Kommentare getrennt (Gesamt %1)',
	'ModerateUserProfile'		=> 'profil',
	'ModerateNoItemChosen'		=> 'Bitte wählen Sie mindestens ein Element über die Schaltfläche Set aus.',

	'ModerateSection2'			=> 'moderiere Abschnitt',
	'ModerateTopicsDeleted'		=> 'Ausgewählte Themen erfolgreich gelöscht.',
	'ModerateTopicsRelocated'	=> 'Ausgewählte Themen erfolgreich neu lokalisiert.',
	'ModerateTopicsRenamed'		=> 'Thema erfolgreich umbenannt.',
	'ModerateTopicsMerged'		=> 'Ausgewählte Themen erfolgreich zusammengeführt.',
	'ModerateTopicsBlocked'		=> 'Ausgewählte Themen erfolgreich gesperrt',
	'ModerateTopicsUnlocked'	=> 'Ausgewählte Themen erfolgreich entsperrt.',
	'ModerateTopicDeleted'		=> 'Thema wurde erfolgreich entfernt.',
	'ModeratePageMoved'			=> 'Seite erfolgreich verschoben.',
	'ModerateTopicRenamed'		=> 'Thema erfolgreich umbenannt.',
	'ModerateTopicBlocked'		=> 'Thema erfolgreich gesperrt',
	'ModerateTopicUnlocked'		=> 'Thema erfolgreich entsperrt.',
	'ModerateCommentsDeleted'	=> 'Ausgewählte Kommentare erfolgreich entfernt.',
	'ModerateCommentsSplit'		=> 'Ausgewählte Kommentare erfolgreich in einem neuen Thema getrennt.',
	'ModerateCommentsSplitFailed'	=> 'Hinweis: Aus irgendeinem Grund ist die Trennung der ausgewählten Kommentare zu einem neuen Thema fehlgeschlagen.<br>Dies sollte in der Regel nicht passieren. Bitte benachrichtigen Sie den Administrator.<br>Das Problem wurde vorsorglich in seiner ursprünglichen Form bewahrt.',
	'ModerateCommentsMoved'		=> 'Ausgewählte Kommentare erfolgreich auf die angegebene Seite migriert.',

	// forum
	'ForumSubforums'			=> 'Forum',
	'ForumTopic'				=> 'Thema',
	'ForumTopics'				=> 'Themen',
	'ForumPosts'				=> 'Beiträge',
	'ForumReplies'				=> 'Antworten',
	'ForumAuthor'				=> 'Autor',
	'ForumViews'				=> 'Aufrufe',
	'ForumCreated'				=> 'Erstellt',
	'ForumComments'				=> 'Kommentare',
	'ForumLastComment'			=> 'Letzter Kommentar',
	'ForumNoComments'			=> 'Keine Kommentare',
	'ForumNoTopics'				=> 'Es gibt keine Themen oder Beiträge in diesem Forum.',
	'ForumNewTopic'				=> 'Eine neue Diskussion starten',
	'ForumTopicName'			=> 'Themen-Name:',
	'ForumTopicSubmit'			=> 'Thema absenden',
	'ForumNoTopicName'			=> 'Geben Sie einen Namen für die neue Seite an.',
	'ForumNewPosts'				=> 'neuer Beitrag',
	'ForumLocked'				=> 'sektion gesperrt',
	'ForumUpdated'				=> 'aktualisiert',
	'ForumNoClusterDefined'		=> 'Kein Forum Cluster definiert.',
	'ForumOutsideCluster'		=> 'Stelle sicher, dass sich die %1 Aktion im Forum Cluster befindet.',

	// password complexity
	'PwdCplxShort'				=> 'Passwort ist zu kurz.',
	'PwdCplxEquals'				=> 'Passwort enthält den Benutzernamen.',
	'PwdCplxWeak'				=> 'Das Passwort erfüllt nicht die komplexen Anforderungen.',
	'PwdCplxDesc1'				=> 'Anforderungen für das Passwort: ',
	'PwdCplxDesc2'				=> 'das Passwort darf nicht weniger als %1 Zeichen sein',
	'PwdCplxDesc3'				=> 'darf deinen Benutzernamen nicht enthalten',
	'PwdCplxDesc4'				=> 'sollte bestehen aus ',
	'PwdCplxDesc41'				=> 'Buchstaben und Zahlen',
	'PwdCplxDesc42'				=> 'Groß- und Kleinbuchstaben und Zahlen',
	'PwdCplxDesc43'				=> 'Groß- und Kleinbuchstaben, Ziffern und nicht-alphanumerische Zeichen',
	'PwdCplxDesc5'				=> 'Sie können Buchstaben, Zahlen und Sonderzeichen außer Leerzeichen verwenden.',

	'PasswordTooShort'			=> 'Passwort zu kurz.',
	'PasswordTooCommon'			=> 'Dieses Passwort ist zu häufig.',
	'PasswordSameAsUsername'	=> 'Ihr Passwort ist das gleiche wie Ihr Benutzername.',
	'PasswordSameAsEmail'		=> 'Ihr Passwort ist das gleiche wie Ihre E-Mail.',

	'Timezone'					=> 'Timezone',

	'LanguageArray'	=> [
		'bg' => 'Bulgarisch',
		'da' => 'Dänisch',
		'de' => 'Deutsch',
		'el' => 'Griechisch',
		'en' => 'Englisch',
		'es' => 'Spanisch',
		'et' => 'Estnisch',
		'fa' => 'Persisch',
		'fr' => 'Französisch',
		'hi' => 'Hannah',
		'hu' => 'Ungarisch',
		'it' => 'Italienisch',
		'ja' => 'Japanisch',
		'ko' => 'Koreanisch',
		'nl' => 'Niederländisch',
		'pl' => 'Polnisch',
		'pt' => 'Portugiesisch',
		'ru' => 'Russisch',
		'ta' => 'Tamil',
		'zh' => 'Chinesisch',
		'zh-tw' => 'Chinesisch',
	],

	'AccountStatus'				=> 'Kontostatus',
	'AccountStatusArray' => [
		'0' => 'aktiv',
		'1' => 'ausstehend',
		'2' => 'blockiert',
		'3' => 'inaktiv',
	],

	'JustNow'		=> 'gerade jetzt',
	'MinuteAgo'		=> 'vor einer Minute',
	'MinutesAgo'	=> '%1 minutes ago',
	'HourAgo'		=> 'vor einer Stunde',
	'HoursAgo'		=> '%1 hours ago',
	'DayAgo'		=> 'gestern',
	'DaysAgo'		=> '%1 days ago',
	'WeekAgo'		=> 'vor einer Woche',
	'WeeksAgo'		=> '%1 weeks ago',
	'MonthAgo'		=> 'vor einem Monat',
	'MonthsAgo'		=> '%1 months ago',
	'YearAgo'		=> 'vor einem Jahr',
	'YearsAgo'		=> '%1 years ago',

	'InAMoment'		=> 'in einem Moment',
	'InAMinute'		=> 'in einer Minute',
	'InMinutes'		=> 'in %1 Minuten',
	'InAnHour'		=> 'in einer Stunde',
	'InHours'		=> 'in %1 Stunden',
	'Tomorrow'		=> 'morgen',
	'InDays'		=> 'in %1 Tagen',
	'InAWeek'		=> 'in einer Woche',
	'InWeeks'		=> 'in %1 Wochen',
	'InAMonth'		=> 'in einem Monat',
	'InMonths'		=> 'in %1 Monaten',
	'InAYear'		=> 'in einem Jahr',
	'InYears'		=> 'in %1 Jahren',

	// norm multiples
	'ByteDecimalShort'			=> ['B', 'kB', 'MN', 'SF', 'TB', 'PB', 'TB', 'ZB', 'JB'],
	'ByteDecimalLong'			=> ['Byte', 'Kilobyte', 'Megabyte', 'Gigabyte', 'Terabyte', 'Petabyte', 'Exabyte', 'Zettabyte', 'Yottabyte'],
	'ByteBinaryShort'			=> ['B', 'KiB', 'MiB', 'GiB', 'TiB', 'PiB', 'Kevin', 'ZiB', 'YiB'],
	'ByteBinaryLong'			=> ['Byte', 'Kibibyte', 'Mebibyte', 'Gibibyte', 'Tebibyte', 'Pebibyte', 'Exbibyte', 'Zebibyte', 'Yobibyte'],
	'PixelDecimalShort'			=> ['px', 'KP', 'MP', 'GP', 'PN', 'PP', 'EP', 'ZP', 'JP'],
	'PixelDecimalLong'			=> ['pixel', 'Kpx', 'Mpx', 'Gpx', 'Tpx', 'Ppx', 'Epx', 'Zpx', 'Ypx'],

	// loading error
	'UnknownAction'				=> 'Unbekannte Aktion',
	'UnknownMethod'				=> 'Unbekannte Methode',
	'FormatterNotFound'			=> 'Formatierung %1 nicht gefunden',

	// log
	'LogAdminLoginSuccess'		=> 'Erfolgreiche Anmeldung im Administrationsbereich',
	'LogAdminLogout'			=> 'Abmelden des administrativen Panels',
	'LogAdminLoginFailed'		=> '!!Fehler beim autorisieren des Zugriffs auf das Administrationsbereich!!',
	'LogAdminLoginLocked'		=> 'Login im Administrationsbereich gesperrt',
	'LogUserCookieForged'		=> '!!**Ein Versuch, sich auf einem gefälschten Cookie mit Login ##%1##**!!',
	'LogInvalidFormToken'		=> 'Mögliche CSRF-Attacke im Gange: %1',
	'LogRemovedPage'			=> '!!Seite ##%1## (Benutzer %2)!!',
	'LogRemovedCluster'			=> '!!**Cluster** ##%1## (Benutzer %2)!!',
	'LogRemovedRevision'		=> '!!Entfernte Revision ##%3## der Seite [[/%1]] (Benutzer %2)!!',
	'LogRemovedComment'			=> '!!Kommentar von %3 auf Seite [[/%1]] (Benutzer %2)!!',
	'LogRemovedFile'			=> '!!Datei ##%2## von Seite [[/%1]]!!',
	'LogRemovedAllComments'		=> '!!Alle Kommentare der Seite [[/%1]]!!',
	'LogRemovedAllRevisions'	=> '!!Alle Revisionen der Seite [[/%1] ] entfernt!!',
	'LogRemovedAllFiles'		=> '!!Alle an [[/%1] ]angehängten Dateien entfernt!!',
	'LogTopicLocked'			=> 'Forenthema ist gesperrt [[/%1]]',
	'LogTopicUnlocked'			=> 'Forenthema entsperrt [[/%1]]',
	'LogAclUpdated'				=> 'Aktualisierte ACL-Seite [[/%1]]',
	'LogOwnershipChanged'		=> 'Besitz der Seite [[/%1]] an den Benutzer ##%2 ## übertragen',
	'LogUserLoginFailed'		=> '!!Erfolgreiche Anmeldeversuche mit ##~%1##!!',
	'LogClonedPage'				=> 'Seite ##%1## geklont an [[/%2]]',
	'LogRenamedPage'			=> 'Seite ##%1## umbenannt in [[/%2]]',
	'LogRenamedPage2'			=> '. Die alte Seite als Link auf die neue Seite gesetzt',
	'LogSplittedPage'			=> 'Kommentare auf der Seite [[/%1]] auf Seite [[/%2] ] aufgeteilt',
	'LogMergedPages'			=> 'Seiten %1 fusioniert mit Seite [[/%2]]',
	'LogUserPasswordReminded'	=> 'Benutzer ##%1## hat nach der Passwortwiederherstellung gefragt ##%2##',
	'LogUserPasswordRecovered'	=> 'Benutzer ##%1## erfolgreich das vergessene Passwort wiederhergestellt',
	'LogUserPasswordChanged'	=> 'Benutzer ##%1## erfolgreich aktualisiert (geändert) das Passwort',
	'LogUserPasswordMismatch'	=> '!!Benutzer ##%1## konnte das Passwort nicht ändern: aktuelles Passwort stimmt nicht überein!!',
	'LogUserIPSwitched'			=> 'Änderung der IP-Adresse des Benutzers %1 von %2 auf %3',
	'LogPageImported'			=> 'Importierte Seite [[/%1]]',
	'LogSaveNoRights'			=> 'Keine angemessenen Rechte zum Speichern der Seite [[/%1]]',
	'LogPageCreated'			=> 'Neue Seite [[/%1] ] erstellt',
	'LogPagePropertiesUpdated'	=> 'Aktualisierte Seiteneigenschaften [[/%1]]',
	'LogPageOwnershipClaimed'	=> 'Der Benutzer hat das Eigentum an der Seite [[/%1]]',
	'LogFileUploadedLocal'		=> 'Neue Datei ##%2## hochgeladen auf die Seite [[/%1]] (Größe %3)',
	'LogFileUploadedGlobal'		=> 'Neue Datei ##%2## in den globalen Ordner hochgeladen (Größe %3)',
	'LogPMSent'					=> 'Persönliche Nachricht ##%1## -> ##%2## erfolgreich gesendet',
	'LogUserSimilarName'		=> 'Es gab Versuche, sich unter dem gleichen Benutzernamen zu registrieren: ##%1##',
	'LogUserEmailNotAllowed'	=> 'E-Mail ##%1## nicht in der erlaubten Domänenliste',
	'LogRegisterTiming'			=> 'Registrierung fehlgeschlagen, der Schwellenwert für die Formularzeit beträgt ##%1## Sekunden (war ##%2##)',
	'LogUserRegistered'			=> 'Neuer Benutzer ##%1## (##%2 ##) erfolgreich registriert',
	'LogUserEmailActivated'		=> 'E-Mail ##%1## des Benutzers ##%2 ## erfolgreich aktiviert',
	'LogCommentPosted'			=> '[[/%1 new comment(s)]] auf Seite [[/%2] ] hinzugefügt',
	'LogUserLoginOK'			=> 'Benutzer ##%1## erfolgreich angemeldet',
	'LogUserLoggedOut'			=> 'Benutzer ##%1## erfolgreich abgemeldet',
	'LogUserSessionContinued'	=> 'Benutzer ##%1## setzte die abgebrochene Sitzung fort',
	'LogUserSettingsUpdate'		=> 'Benutzer ##%1## persönliche Einstellungen aktualisiert',
	'LogPageEdited'				=> 'Bearbeitete Seite [[/%1]]',
	'LogCommentEdited'			=> 'Bearbeiteter Kommentar [[/%1]]',
	'LogUpdatedFileMeta'		=> 'Aktualisierte Datei-Metadaten für ##%2## von Seite [[/%1]]',
	'LogUpdatedFileCategories'	=> 'Dateikategorien für ##%2## von Seite [[/%1] aktualisiert',

	'LogXmlSitemapGenerated'	=> 'XML-Sitemap generiert',
	'LogReferrersPurged'		=> 'Wartung: Referrer gelöscht',
	'LogRevisionsPurged'		=> 'Wartung: veraltete Seiten-Revisionen gelöscht',
	'LogDeletedPagesPurged'		=> 'Wartung: gelöschte Seiten gelöscht',
	'LogSystemLogPurged'		=> 'Wartung: Systemprotokoll gelöscht',
	'LogCachedPagesPurged'		=> 'Wartung: Cache-Seiten gelöscht',
	'LogSqlCachePurged'			=> 'Wartung: Cached sql Ergebnisse gelöscht',
	'LogExpiredTokensPurged'	=> 'Wartung: Abgelaufene Cookie_Token gelöscht',
	'LogErrorSplitComments'		=> 'Fehler beim Trennen der Kommentare vom Thema [[/%1]] ein neues Thema ##%2##: Seite wurde nicht erstellt',
	'LogCategoriesUpdated'		=> 'Aktualisierte Seitenkategorien [[/%1]]',
	'LogCategoryCreated'		=> 'Neue Kategorie erstellt //%1//',
	'LogCategoryRenamed'		=> 'Kategorie ##%1## umbenannt in ##%2 ## #',
	'LogCategoryDebundled'		=> 'Kategorie ##%1## entschlüsselt',
	'LogCategoryGrouped'		=> 'Kategorie ##%1## mit dem Wort ##%2 ## gruppiert',
	'LogCategoryRemoved'		=> 'Kategorie ##%1## aus der Datenbank entfernt',
	'LogThumbnailGeneration'	=> 'Thumbnail Erzeugung %1 Sekunden.',

	'ErrorMinPHPVersion'		=> 'Die PHP-Version muss größer als <strong> sein' . PHP_MIN_VERSION . '</strong>,' .
									' dein Server scheint <strong> auszuführen' . PHP_VERSION . '</strong>.' .
									'  Sie sollten auf eine neuere PHP-Version aktualisieren, damit WackoWiki korrekt funktioniert.',

];
