<?php

if (!defined('IN_WACKO'))
{
	exit;
}

$wacko_translation = [

	// language
	'lang_scheme'	=> [
		'name'		=> 'Angielski',
		'code'		=> 'pl',
		'dir'		=> 'ltr',
		'locale'	=> 'pl_PL.UTF-8',
	],

	// common
	'AddButton'					=> 'Dodaj',
	'ArchiveButton'				=> 'Archiwum',
	'CancelButton'				=> 'Anuluj',
	'ContinueButton'			=> 'Kontynuuj',
	'ConvertButton'				=> 'Konwertuj',
	'CreateButton'				=> 'Utwórz',
	'DeleteButton'				=> 'Usuń',
	'RemoveButton'				=> 'Usuń',
	'RenameButton'				=> 'Zmień nazwę',
	'ResetButton'				=> 'Reset',
	'RestoreButton'				=> 'Przywróć',
	'SaveButton'				=> 'Zapisz',
	'SearchButton'				=> 'Szukaj',
	'SendButton'				=> 'Wyślij',
	'SetButton'					=> 'Ustaw',
	'SubmitButton'				=> 'Prześlij',
	'UpdateButton'				=> 'Aktualizuj',

	'FormInvalid'				=> 'Wysłany formularz jest nieprawidłowy. Spróbuj ponownie przesłać.',
	'UnitPixel'					=> 'px',
	'Number'					=> 'Numer',

	// logged in panel
	'AccountText'				=> 'Konto',
	'AccountTip'				=> 'Ustawienia konta',
	'AdminText'					=> 'Administrator',
	'AdminTip'					=> 'Panel administracyjny',
	'LogoutLink'				=> 'Wyloguj się',
	'LogoutButton'				=> 'Wyloguj się',
	'LogoutAreYouSure'			=> 'Czy na pewno chcesz się wylogować?',

	// registration panel
	'RegistrationWelcome'		=> 'Rejestracja nowego użytkownika:',
	'RegistrationButton'		=> 'Zarejestruj',
	'UserNameOwned'				=> 'Ta nazwa użytkownika jest już zarejestrowana. Proszę wybrać inną.',
	'SiteRegistered'			=> 'Pomyślnie zarejestrowałeś się na stronie %1.',
	'RegistrationEmailInfo'		=> 'Prawidłowy adres e-mail. Wszystkie e-maile z systemu zostaną wysłane na ten adres. Adres e-mail nie jest upubliczniony i będzie używany tylko wtedy, gdy chcesz otrzymać nowe hasło lub chcesz otrzymywać określone wiadomości lub powiadomienia e-mailem.',
	'EmailConfirmHint'			=> 'Potwierdź swój adres e-mail, klikając na link w instrukcjach wysłanych do Ciebie. <br>Jeśli nie zweryfikujesz swojego adresu e-mail, nie będziesz w stanie odzyskać możliwego utraconego hasła. <br>Ponadto nie zostaniesz powiadomiony o ostatnich zmianach i komentarzach.',
	'EmailConfirmRequired'		=> 'Bez potwierdzonego adresu e-mail nie będziesz mógł się zalogować.',
	'NameTooShort'				=> 'Nazwa użytkownika jest zbyt krótka, wymagane jest minimum %2 znaków.',
	'NameTooLong'				=> 'Nazwa użytkownika jest zbyt długa, maksymalnie %2 znaków jest dozwolona.',
	'NameAlphanumOnly'			=> 'Nazwa użytkownika musi zawierać się między %1 i %2 znakami i używać tylko znaków alfanumerycznych. Duże litery są w porządku.',
	'NameCamelCaseOnly'			=> 'Nazwa użytkownika musi być pomiędzy %1 i %2 znakami i sformatowana WikiName',
	'NewUserAccount'			=> 'nowe konto użytkownika',

	'NewAccountSubject'			=> 'Rejestracja konta',
	'NewAccountAdminCreated'	=> 'Użytkownik %1 utworzył dla Ciebie konto z nazwą użytkownika "%2". Aby zakończyć rejestrację, odwiedź następujący adres URL (upewnij się, że został wprowadzony jako pojedynczy wiersz) i ustaw własne hasło dostępu:',
	'NewAccountUsername'		=> 'Nazwa użytkownika:',
	'AccountLanguage'			=> 'Język:',
	'NewAccountEmail'			=> 'Email:',
	'NewAccountIP'				=> 'zdalny adres IP:',
	'NewAccountSignupInfo'		=> 'Następujące konto zostało utworzone:',

	'UserWaitingApproval'		=> 'E-mail został wysłany do administratora witryny. Administrator przejrzy informacje, które zostały przesłane i zatwierdzi lub odrzuci Twoje żądanie.',
	'UserRequiresApproval'		=> 'Aby zatwierdzić lub odmówić temu użytkownikowi dostępu do %1 przejdź do panelu administratora.',
	'UserApprovalInfo'			=> 'Po zarejestrowaniu się Twój wniosek zostanie wysłany do administratora witryny w celu zatwierdzenia. Następnie otrzymasz wiadomość e-mail z dalszymi instrukcjami.',
	'UserApprovalHint'			=> 'Pomyślna aktywacja Twojego konta zostanie ogłoszona w określonym adresie e-mail. Do tego czasu login nie jest możliwy.',

	'UserApprovalPending'		=> 'Twoje konto nadal oczekuje na zatwierdzenie.',
	'UserApprovalDenied'		=> 'Twoje konto zostało pozbawione dostępu do tej witryny.',

	'RegistrationApproved'		=> 'Rejestracja zatwierdzona',
	'RegistrationDenied'		=> 'Rejestracja odrzucona',
	'PendingApproval'			=> 'Oczekujące na zatwierdzenie',

	'UserApprovedInfo'			=> 'You have been approved to access %1.',
	'UserDeniedInfo'			=> 'Odmowa dostępu do %1.',

	'RegistrationThreshold'		=> 'Czas wypełnienia formularza nie powinien być krótszy niż %1 sekund.',
	'Language'					=> 'Język',

	// login panel
	'LoginWelcome'				=> 'Logowanie',
	'CreateAccount'				=> 'Utwórz nowe konto',
	'RegistrationLink'			=> 'Rejestracja',
	'LoginName'					=> 'Nazwa użytkownika',
	'Password'					=> 'Hasło',
	'LoginButton'				=> 'Logowanie',
	'LoginLink'					=> 'Logowanie',
	'PersistentCookie'			=> 'Zostań zalogowany',
	'Session'					=> 'Sesja',
	'SessionTip'				=> 'parametry bieżącej sesji',
	'SessionDuration'			=> 'Czas trwania sesji',
	'SessionDurationSession'	=> 'sesja przeglądarki',
	'SessionDurationDay'		=> '1 dzień',
	'SessionDurationWeek'		=> '1 tydzień',
	'SessionDurationMonth'		=> '1 miesiąc',
	'LoggedInAs'				=> 'Jesteś zalogowany jako',

	'ClearCookies'				=> 'Usuń wszystkie ciasteczka',
	'BindSessionIp'				=> 'Powiąż sesję z adresem IP',
	'BindSessionIpOn'			=> 'włączone (aktualny adres IP %1)',
	'TrafficProtection'			=> 'Ochrona ruchu',
	'SessionEnds'				=> 'Bieżąca sesja kończy się',
	'LastVisit'					=> 'Ostatnia wizyta została zarejestrowana',

	'LoginIncorrect'			=> 'Wprowadzona nazwa użytkownika lub hasło jest nieprawidłowe.',
	'WelcomeBack'				=> 'Witamy ponownie, %1',
	'LoginAttemptsExceeded'		=> 'Przekroczono maksymalną dozwoloną liczbę prób logowania.<br>Oprócz nazwy użytkownika i hasła musisz teraz rozwiązać CAPTCHA poniżej.',

	// session notice
	'IPAddressChanged'			=> 'Adres IP zmieniony na %1 (był %2)',

	'SessionReplay'				=> 'Sesja zakończona z powodu repliki.',
	'SessionObsolete'			=> 'Sesja jest nieaktualna.',
	'SessionExpired'			=> 'Sesja wygasła.',
	'SessionTimeout'			=> 'Sesja zakończona z powodu przekroczenia limitu czasu.',
	'SessionInactivity'			=> 'Sesja zakończona z powodu braku aktywności.',
	'SessionUaChange'			=> 'Sesja zakończona z powodu zmiany agenta użytkownika.',
	'SessionTLSChange'			=> 'Sesja zakończona z powodu zmiany TLS.',
	'SessionIPChange'			=> 'Sesja zakończona z powodu zmiany IP.',

	// other
	'Guest'						=> 'Gość',
	'Everybody'					=> 'Wszyscy',
	'Help'						=> 'Pomoc',
	'TopicSearchText'			=> 'Szukaj tylko w tytułach',
	'WordprocessorVersion'		=> 'Wersja procesora słów',

	// notifications
	'EmailHello'				=> 'Witaj ',
	'EmailModerator'			=> 'Moderator',
	'WatchedPageChanged'		=> 'Strona zmieniona ',
	'SomeoneChangedThisPage'	=> ' zmieniła stronę, którą oglądasz: ',
	'NewPageCreatedSubj'		=> 'Nowa strona',
	'NewPageCreatedBody'		=> 'Użytkownik %1 utworzył nową stronę: ',
	'FileUploadedSubj'			=> 'Nowy plik',
	'FileUploadedBody'			=> 'Użytkownik %1 przesłał nowy plik: ',
	'FileReplacedBody'			=> 'Użytkownik %1 zastąpił plik: ',

	'ActionDenied'				=> 'Odrzuca się tutaj akcji.',
	'TocTitle'					=> 'Treść ',
	'OuterLink2'				=> 'Link wychodzący',
	'FileLink'					=> '',
	'PDFLink'					=> 'Dokument PDF',
	'RDFLink'					=> 'Dokument RDF',
	'EmailLink'					=> 'Napisz e-mail (uruchomienie klienta pocztowego)',
	'JabberLink'				=> 'Czat przez XMPP (uruchamianie klienta Jabber)',
	'PermaLink'					=> 'Link bezpośredni',
	'PermaLinkTip'				=> 'Stały link do tej wersji strony',
	'PermaLink0Tip'				=> 'Stały link do tej strony',

	'ShowTip'					=> 'Powrót w trybie widoku',
	'ShowText'					=> 'Widok',
	'WikieditAutocomplete'		=> 'Kompletne zabijanie przez Ctrl + Space',
	'WikiEditInactiveJs'		=> 'Aby móc korzystać z WikiEdit, włącz JavaScript w przeglądarce.',
	'NumerateLinks'				=> 'Numeruj linki w widoku wydruku',
	'Comment'					=> 'Komentarz',
	'Comments0'					=> 'Dodaj swój komentarz',
	'Comments1'					=> 'Przeczytaj komentarz (1 komentarz)',
	'CommentsN'					=> 'Przeczytaj komentarze (%1 komentarzy)',
	'Comments'					=> 'Komentarze',
	'CommentHint'				=> '<a href="%1">Zaloguj się</a> lub <a href="%2">utwórz konto</a> , aby opublikować komentarz.',
	'CommentEdited'				=> 'edytowano',
	'Links'						=> 'Linki',
	'Version'					=> 'Wersja',

	// details formatter
	'ShowHideDetails'			=> 'Szczegóły',

	'PrivacyPolicy'				=> 'Polityka prywatności',
	'TermsOfUse'				=> 'Warunki użytkowania',
	'AcceptTermsOfUse'			=> 'Przeczytałem, zrozumiałem i akceptuję warunki korzystania z serwisu.',

	'ShowComments'				=> 'Wyświetl komentarze / formularz',
	'HideComments'				=> 'Ukryj komentarze / formularz',
	'AddComment'				=> 'Dołącz komentarz do tej strony:',
	'AddCommentTitle'			=> 'Nazwa komentarza:',
	'CommentTitleRe'			=> 'Odp:',
	'AddCommentButton'			=> 'Dołącz komentarz',
	'HereLink'					=> 'tutaj',
	'PageHandlerMoreTip'		=> 'więcej',

	'ThemeCorrupt'				=> 'Motyw jest uszkodzony',
	'InvalidNamespace'			=> 'Podano nieprawidłową przestrzeń nazw.',
	'DoesNotExists'				=> 'Ta strona nie istnieje.',
	'PromptCreate'				=> 'Maybe you want to <strong><a href="%1">create</a></strong> it?',
	'RevisionHint'				=> 'To jest stara wersja <a href="%1">%2</a> z %3 edytowana przez %4.',
	'ReadAccessDenied'			=> 'Nie masz uprawnień do odczytu tej strony.',
	'ReadAccessDeniedHintGuest'	=> 'Aby przeczytać tę stronę, musisz się zalogować.',
	'PageDeletedInfo'			=> 'Ta strona została usunięta.',
	'RevisionDeletedInfo'		=> 'Ta wersja została usunięta.',
	'CommentDeletedInfo'		=> 'Ten komentarz został usunięty.',

	'LastEditedBy'				=> 'Ostatnio edytowane przez',
	'YouAreOwner'				=> 'Jesteś właścicielem tej strony.',
	'Owner'						=> 'Właściciel:',
	'Nobody'					=> 'Nikt',
	'TakeOwnership'				=> 'Przejmij własność',
	'FilesTip'					=> 'Zarządzaj załączonymi plikami',
	'FilesText'					=> 'Załączniki',
	'DeleteTip'					=> 'Usuń stronę, jej pliki i komentarze',
	'DeleteCommentTip'			=> 'Usuń komentarz',
	'DeleteText'				=> 'Usuń',
	'AclText'					=> 'Uprawnienia',
	'AclTip'					=> 'Edytuj uprawnienia',

	'PropertiesText'			=> 'Właściwości',
	'PropertiesTip'				=> 'Edytuj właściwości strony',
	'EditTip'					=> 'Edytuj tę stronę.',
	'EditText'					=> 'Edytuj',
	'EditSection'				=> 'Edytuj sekcję %1',
	'EditSectionHint'			=> 'Sekcja %1 %2',
	'SectionHeadline'			=> 'Sekcja',
	'EditCommentTip'			=> 'Edytuj komentarz',
	'EditComment'				=> 'Edytuj ten komentarz',
	'ReplyComment'				=> 'Odpowiedz',
	'ReplyCommentTip'			=> 'Odpowiedz na ten komentarz',
	'RevisionTip'				=> 'Zobacz zmiany strony',
	'RevisionText'				=> 'Wersje',
	'ReferrersTip'				=> 'Zobacz listę adresów URL odnoszących się do tej strony',
	'ReferrersText'				=> 'Odsyłacze',
	'ModerateTip'				=> 'Moderacja tematów i postów na forum',
	'ModerateText'				=> 'Umiarkowane',
	'SearchText'				=> 'Szukaj: ',

	'AclUpdated'				=> 'Listy kontroli dostępu zaktualizowane',
	'AclGaveOwnership'			=> ' i dał prawo własności %1.',
	'AclNoNewOwner'				=> 'Własność strony nie została przeniesiona, ponieważ użytkownik %1 nie został znaleziony.',
	'NewPageOwnership'			=> 'Przeniesiona własność strony',
	'YouAreNewOwner'			=> 'poprzedni właściciel %1 przeniósł własność ' . "\n" . 'z śledzonej strony dla Ciebie',
	'PageOwnershipInfo'			=> '',
	'AclRead'					=> 'Odczyt:',
	'AclWrite'					=> 'Napisz:',
	'AclComment'				=> 'Komentarze:',
	'AclCreate'					=> 'Utwórz:',
	'AclUpload'					=> 'Załaduj:',
	'AclFor'					=> 'Listy kontroli dostępu dla %1',
	'SetOwner'					=> 'Ustaw właściciela:',
	'OwnerDontChange'			=> 'Nie zmieniaj',
	'AclAccessDenied'			=> 'Nie jesteś właścicielem tej strony.',
	'AclSyntaxError'			=> 'Błąd składni listy kontroli dostępu',
	'AclHelp'					=> '<code>*</code> - każdy jest dozwolony<br>' .
									'<code>$</code> - tylko zarejestrowani użytkownicy<br>' .
									'<code>!</code> - poprzedni wykrzyknik odrzuca odpowiednie prawo<br>' .
									'<code>[UserName]</code> - nazwy dozwolonych użytkowników<br>' .
									'<code>[GroupName]</code> - nazwy dozwolonej grupy użytkowników (alias)<br>' .
									'<code>(pusta lista)</code> - tylko właściciel strony ma dostęp',

	'AccessMode'				=> 'Widoczność',
	'AccessDenied'				=> 'odmowa',
	'AccessPublic'				=> 'publiczna',
	'AccessRegistered'			=> 'zarejestrowany',
	'AccessPrivate'				=> 'prywatny',
	'AccessCustom'				=> 'niestandardowy',

	// purge handler
	'PurgePage'					=> 'Purge page',
	'NotOwnerAndCantPurge'		=> 'Nie jesteś właścicielem strony i nie możesz go usunąć.',
	'ReallyPurge'				=> 'UWAGA: Pingowanie strony jest nieodwracalne!',
	'SelectPurgeOptions'		=> 'Wybierz niezbędne opcje czyszczenia:',
	'PurgeComments'				=> 'Wyczyść wszystkie komentarze strony',
	'CommentsPurged'			=> 'Wszystkie komentarze zostały usunięte.',
	'PurgeFiles'				=> 'Usuń wszystkie załączone pliki',
	'FilesPurged'				=> 'Wszystkie załączone pliki zostały usunięte.',
	'PurgeRevisions'			=> 'Wyczyść wszystkie wersje strony',
	'RevisionsPurged'			=> 'Rewizje zostały oczyszczone.',
	'PurgeButton'				=> 'Purge',

	// categories handler
	'Categories'				=> 'Kategorie',
	'CategoriesAssign'			=> 'przypisz',
	'CategoriesEdit'			=> 'edytuj',
	'Category'					=> 'Kategoria',
	'CategoriesFor'				=> 'Kategorie dla',
	'CategoriesTip'				=> 'Edytuj kategorie',
	'CategoriesText'			=> 'Kategorie',
	'CategoriesUpdated'			=> 'Kategorie zaktualizowane',
	'CategoriesAlreadyExists'	=> 'Kategoria %1 już istnieje.',
	'CategoriesAdded'			=> 'Kategoria %1 została dodana.',
	'CategoriesRenamed'			=> 'Zmieniono nazwę kategorii.',
	'CategoriesUngrouped'		=> 'Kategoria została obciążona pomyślnie.',
	'CategoriesGrouped'			=> 'Kategoria wpisana do nowej grupy.',
	'NoMultilevelGrouping'		=> 'Wielopoziomowe kategorie grupowania nie są możliwe.',
	'CategoriesDeleted'			=> 'Kategoria została usunięta z bazy danych i wszystkich stron.',
	'CategoriesAdd'				=> 'Dodaj nową kategorię',
	'CategoryDescription'		=> 'Opis',
	'CategoriesAddGrouped'		=> 'Pogrupowane według kategorii',
	'CategoriesAddGroupedNo'	=> 'Brak grupy.',
	'CategoriesRename'			=> 'Zmień nazwę kategorii %1 na',
	'CategoriesRenameInfo'		=> '* Uwaga: Zmiana wpłynie na wszystkie strony, które są przypisane do tej kategorii.',
	'CategoriesGroup'			=> 'Grupa kategorii %1 z',
	'CategoriesGroupInfo'		=> '* Wybierz [brak grupy], aby obciążyć kategorię.',
	'CategoriesNoGroup'			=> '[brak grupy]',
	'CategoriesDelete'			=> 'Czy na pewno chcesz usunąć kategorię %1?',
	'CategoriesDeleteInfo'		=> '* Uwaga: Zmiana wpłynie na wszystkie strony, które są przypisane do tej kategorii. Jeśli słowo ma podkategorię, nie zostanie usunięte, ale tylko obciążone.',
	'CategoriesStoreInfo'		=> 'Aby przypisać kategorie do strony, wybierz pola wyboru.',
	'CategoriesStoreButton'		=> 'Zapisz kategorie',
	'CategoriesGroupButton'		=> 'Grupa',
	'CategoriesEditInfo'		=> 'Aby edytować listę kategorii, wybierz przycisk radiowy.',
	'NoCategoriesForThisLang'	=> 'Kategorie dla tego języka nie są określone.',
	'PagesCategory'				=> 'Kategoria stron',
	'CategoryNotExists'			=> 'Kategoria nie istnieje.',
	'CategoryEmpty'				=> 'Kategoria pusta.',
	'NoCategorySelected'		=> 'Nie wybrano kategorii.',
	'NoCategoriesAssigned'		=> 'Brak przypisanych kategorii dla tego języka.',
	'TagCloud'					=> 'Chmura tagów',
	'PagesTaggedWith'			=> '%1 stron oznaczonych %2',
	'CategoriesOfCluster'		=> 'klastra',
	'TaggedWithTip'				=> 'pokaż strony oznaczone %1',

	// source handler
	'SourceText'				=> 'Źródło',
	'SourceTip'					=> 'Zobacz źródło wiki',
	'SourceCopyToClipboard'		=> 'skopiuj do schowka',
	'SourceFor'					=> 'Zobacz źródło dla %1',

	// Groups action
	'GroupsSearch'				=> 'Znajdź grupy',
	'GroupsNoMatching'			=> 'Nie znaleziono pasujących grup. Spróbuj mniej rygorystycznych kryteriów wyszukiwania.',
	'GroupsOpenProfile'			=> 'Zobacz profil',
	'GroupsName'				=> 'Grupa',
	'GroupsMembers'				=> 'Członkowie',
	'GroupsDescription'			=> 'Opis',
	'GroupsCreated'				=> 'Utworzono',
	'GroupsNotFound'			=> 'Grupa %2 nie została znaleziona. Kliknij <a href="%1">tutaj</a>, aby przejść do głównej listy.',
	'GroupsProfile'				=> 'Profil',
	'GroupsList'				=> 'Zobacz całą listę grup',
	'GroupSpace'				=> 'Przestrzeń grupy',

	'MetaUpdated'				=> 'Dane meta zaktualizowane',

	'PreviewButton'				=> 'Podgląd',
	'Preview'					=> 'Podgląd',
	'Chars'						=> 'znaki',
	'PageBody'					=> 'Treść strony',
	'EditNote'					=> 'Edytuj podsumowanie',
	'EditNoteMissing'			=> 'Edytuj brakujące podsumowanie',
	'EditMinor'					=> 'Drobna edycja',
	'MinorEditHide'				=> 'Ukryj drobną edycję',
	'MinorEditShow'				=> 'Pokaż drobną edycję',
	'PostAnonymously'			=> 'Publikuj anonimowo, nie podając swojego imienia',
	'NotifyMe'					=> 'Powiadom mnie o nowych komentarzach i zmianach strony',
	'OverwriteAlert'			=> 'OVERWRITE ALERT: This page was modified by someone else while you were editing it.<br>Please copy your changes and re-edit this page.',
	'TextDbOversize'			=> 'Ostrzeżenie: Twój tekst przekracza limit długości o %1 znaków. Proszę skrócić tekst do dopuszczalnej liczby znaków. Wskazówka: Możesz umieścić pozostały tekst na osobnej stronie.',
	'EditingRevisionWarning'	=> 'Edytujesz starą wersję tej strony. Jeśli ją opublikujesz, wszelkie zmiany wprowadzone od tego czasu zostaną usunięte. <br>Zamiast tego możesz edytować bieżącą wersję.',
	'WriteAccessDenied'			=> 'Nie masz dostępu do zapisu na tej stronie.',
	'EmptyPage'					=> 'Treść strony była pusta - nie zapisana!',
	'EmptyComment'				=> 'Treść komentarza była pusta - nie zapisana!',
	'CommentAccessDenied'		=> 'Przepraszamy, nie możesz dodawać komentarzy na tej stronie.',
	'CommentFlooded'			=> 'Odstęp pomiędzy publikacją postów nie może być krótszy niż %1 sekund.',
	'CommentAdded'				=> 'Komentarz dodany.',
	'YouAreNowTheOwner'			=> 'Jesteś teraz właścicielem tej strony.',
	'PageSaved'					=> 'Zapisano wersję strony %1.',
	'CommentSaved'				=> 'Komentarz zapisany.',

	'RevisionsFor'				=> 'Wersje dla %1',
	'DefaultDiffMode'			=> 'Domyślny tryb różnicowy',
	'DiffMode'		=> [
		'0'		=> 'Pełna różnica',
		'1'		=> 'Prosty diff',
		'2'		=> 'Źródło',
		'3'		=> 'Obok siebie',
		'4'		=> 'Wbudowany',
		'5'		=> 'Scalony',
		'6'		=> 'Zunifikowany',
		'7'		=> 'Kontekst',
	],

	'PreviousEdit'				=> 'Poprzednia edycja',
	'NextEdit'					=> 'Następna edycja',

	'Diff'						=> 'Różnica',
	'PreviousVersion'			=> 'Poprzednia wersja',
	'LatestVersion'				=> 'Najnowsza wersja',
	'NextVersion'				=> 'Następna wersja',

	'ShowDifferencesButton'		=> 'Pokaż różnice',
	'CancelReturnButton'		=> 'Anuluj i wróć do strony',
	'Comparison'				=> 'Różnica pomiędzy wersjami dla %1',
	'RevisionAsOf'				=> 'Wersja %1 od',
	'SimpleDiffAdditions'		=> 'Dodatki:',
	'SimpleDiffDeletions'		=> 'Usunięcia:',
	'NoDifferences'				=> 'Brak różnic.',
	'ReEditOldRevision'			=> 'Ponownie edytuj stare wersje',

	'ExternalPages'				=> 'Zewnętrzne strony łączące z %1 (%2) (<a href="%3">zobacz listę domen</a>):',
	'ExternalPagesGlobal'		=> 'Witryny łączące się z tym WackoWiki (%2) (<a href="%1">zobacz listę domen</a>):',
	'Last24Hours'				=> 'ostatnie 24 godziny',
	'LastDays'					=> 'last %1 days',
	'DomainsSitesPages'			=> 'Domeny/strony internetowe łączące z  %1 (%2) (<a href="%3">zobacz listę różnych adresów URL</a>):',
	'DomainsSitesPagesGlobal'	=> 'Domeny/strony łączące się z tym WackoWiki (<a href="%1">zobacz listę różnych adresów URL</a>):',
	'ViewReferrersPage'			=> 'na stronę',
	'ViewReferrersPerPage'		=> 'na stronie',
	'ViewReferrersByTime'		=> 'wg czasu',
	'ViewReferrersGlobal'		=> 'globalny',
	'NoneReferrers'				=> 'Brak',
	'NotOwnerCantDelete'		=> 'Nie jesteś właścicielem tej strony i nie możesz jej usunąć',

	// remove
	'RemovePage'				=> 'Usuń stronę',
	'RemoveRevision'			=> 'Usuń wersję',
	'RemoveComment'				=> 'Usuń komentarz',
	'RemoveCluster'				=> 'Usuń wszystkie strony klastra',
	'RemoveDontKeep'			=> 'Nie zapisuj kopii usuniętej strony i komentarzy',
	'RemoveDontKeepRevision'	=> 'Nie zapisuj kopii usuniętej wersji',
	'RemoveDontKeepComment'		=> 'Nie zapisuj kopii usuniętego komentarza',
	'RemoveDontKeepFile'		=> 'Nie zapisuj kopii usuniętego pliku',
	'ReferrersRemoved'			=> 'Usunięto odsyłaczy.',
	'LinksRemoved'				=> 'Linki usunięte.',
	'CategoriesRemoved'			=> 'Usunięto kategorie stron.',
	'AclsRemoved'				=> 'Usunięto akty strony.',
	'BookmarksRemoved'			=> 'Zakładki usunięte.',
	'WatchesRemoved'			=> 'Obserwacje usunięte.',
	'CommentsRemoved'			=> 'Usunięto komentarze ze strony.',
	'FilesRemoved'				=> 'Pliki ze strony usunięte.',
	'PageRemoved'				=> 'Strona usunięta.',
	'PageCachePurged'			=> 'Pamięć podręczna oczyszczona.',
	'ClusterRemoved'			=> 'Usunięto wszystkie strony klastru.',
	'RevisionRemoved'			=> 'Wersja %1 usunięta.',
	'RevisionsRemoved'			=> 'Wersje usunięte.',
	'ActionHaveNoUndo'			=> 'Tej czynności nie można cofnąć.',

	// restore
	'PageRestored'				=> 'Strona przywrócona.',
	'RevisionRestored'			=> 'Rewizja przywrócona.',
	'LocalFilesRestored'		=> 'Przywrócono pliki lokalne.',

	'PrintVersion'				=> 'Drukuj wersję',
	'PrintText'					=> 'Drukuj',
	'LinkedPages'				=> 'Powiązane strony:',
	'NoLinkedPages'				=> 'Brak powiązanych stron',
	'ReferringPages'			=> 'Strony odsyłające:',
	'NoReferringPages'			=> 'Brak stron polecających',
	'Footnotes'					=> 'Przypisy:',
	'Footnote'					=> 'Przypis',
	'MostPopularPages'			=> 'Najpopularniejsze strony',
	'MostCommentedPages'		=> 'Najczęściej komentowane strony',
	'NoAccessToSourcePage'		=> 'Nie możesz odczytać strony źródłowej akcji.',
	'SourcePageDoesntExist'		=> 'Strona źródłowa akcji jeszcze nie istnieje',
	'NotLoggedInThusEdited'		=> 'Nie jesteś zalogowany, dlatego nie mogliśmy zidentyfikować stron, które edytowałeś.',
	'DidntEditAnyPage'			=> 'Nie edytowałeś jeszcze żadnych stron.',
	'NoPagesFound'				=> 'Nie znaleziono stron.',
	'MyChangesTitle1'			=> 'To jest lista stron, które edytowałeś, uporządkowana według czasu ostatniej zmiany',
	'MyChangesTitle2'			=> 'To jest lista stron, które edytowałeś, wraz z czasem ostatniej zmiany',
	'OrderABC'					=> 'alfabetycznie',
	'OrderCreation'				=> 'przez tworzenie',
	'OrderChange'				=> 'wg zmiany',
	'ListOwnedPages'			=> 'To jest lista stron, które posiadasz (uporządkowane alfabetycznie)',
	'ListOwnedPages2'			=> 'To jest lista stron, które posiadasz (uporządkowane według daty)',
	'ListOwnedPages3'			=> 'To jest lista stron, które posiadasz (uporządkowane po zmianach)',
	'NotLoggedInThusOwned'		=> 'Nie jesteś zalogowany, dlatego nie mogliśmy pobrać twoich stron.',
	'NoOrphaned'				=> 'Brak osieroconych stron. Dobrze.',
	'NoRecentComments'			=> 'Brak ostatnich komentarzy.',
	'LatestCommentBy'			=> 'najnowszy komentarz przez',
	'NoRecentlyCommented'		=> 'Brak ostatnio skomentowanej strony.',
	'NoDeletedPages'			=> 'Nie znaleziono usuniętych stron.',
	'NoDeletedRevisions'		=> 'Nie znaleziono usuniętych wersji.',
	'NoDeletedFiles'			=> 'Nie znaleziono usuniętych plików.',
	'CommentsDisabled'			=> 'Komentarze nie są dostępne.',

	'SearchResults'				=> 'Wyniki wyszukiwania dla ',
	'NotFound'					=> 'nie znaleziono',
	'NoResultsFor'				=> 'Brak wyników dla ',
	'SearchFor'					=> 'Szukaj:',
	'TopicSearchResults'		=> 'Wyniki wyszukiwania tematów dla ',
	'NotFoundInTopics'			=> 'nie znaleziono w wątkach',
	'FilterLangNotAvailable'	=> 'Wybrany język jest niedostępny!',

	'PostedBy'					=> 'opublikowane przez',
	'ThisIsCommentOn'			=> 'To jest komentarz na',
	'At'						=> 'w',
	'To'						=> 'do',
	'By'						=> 'przez',
	'From'						=> 'od',
	'For'						=> 'dla',
	'ReturnToCommented'			=> 'Powrót do skomentowanej strony',
	'AbandonedComment'			=> 'Strona, do której ten komentarz już nie istnieje!',

	'PagesLinkingTo'			=> 'Strony linkujące do',
	'NoPageLinkingTo'			=> 'Żadna strona nie jest połączona z',
	'NoWantedPages'				=> 'Brak chcianych stron. Dobrze.',
	'RemoveWatch'				=> 'Usuń zegarek dla tej strony',
	'SetWatch'					=> 'Obejrzyj stronę',
	'WatchText'					=> 'Obejrzyj',
	'UnwatchText'				=> 'Nie obserwuj',
	'UserSettingsStored'		=> 'Zapisano ustawienia użytkownika.',
	'LoggedOut'					=> 'Zostałeś wylogowany.',
	'LoggedOutAuto'				=> 'Ze względów bezpieczeństwa sesja zakończyła się. Zaloguj się ponownie.',

	// user settings
	'EmailConfirmResent'		=> 'Kod potwierdzający e-mail wysłany ponownie na twój adres.',
	'EmailConfirmNotSent'		=> 'Nie można wysłać kodu potwierdzającego: nie określono adresu e-mail!',
	'Hello'						=> 'Witaj',
	'UserName'					=> 'Nazwa użytkownika',
	'EmailAddress'				=> 'Adres e-mail',
	'RealName'					=> 'Prawdziwe imię',
	'MenuItemsShown'			=> 'Wyświetlone pozycje menu',
	'RecordsPerPage'			=> 'Rekordy na stronę',
	'DoShowComments'			=> 'Pokaż komentarze domyślnie',
	'DoubleclickEditing'		=> 'Edycja dwukrotnego kliknięcia',
	'UpdateSettingsButton'		=> 'Aktualizuj ustawienia',

	'AccountDisabled'			=> 'Twoje konto może być wyłączone lub zablokowane.',
	'WrongPassword'				=> 'Błędne hasło!',
	'ConfirmPassword'			=> 'Potwierdź hasło',
	'Email'						=> 'Adres e-mail',
	'MustBeWikiName'			=> 'Nazwa użytkownika musi być <a href="https://wackowiki.org/doc/Doc/English/WikiName" target="_blank">WikiName</a> sformatowana!',
	'SpecifyEmail'				=> 'Musisz podać adres e-mail.',
	'NotAEmail'					=> 'To nie wygląda jak poprawny adres e-mail.',
	'EmailTaken'				=> 'Wprowadzony adres e-mail jest już w użyciu.',
	'EmailDomainNotAllowed'		=> 'Wprowadzony adres e-mail %1 nie jest na liście dozwolonych domen.',
	'PasswordsDidntMatch'		=> 'Hasła nie są identyczne.',
	'SpacesArentAllowed'		=> 'Spacje nie są dozwolone w hasłach.',
	'ListMyPages'				=> 'Pokaż swoje strony',
	'ListMyChanges'				=> 'Lista zmian',
	'ListMyWatches'				=> 'Lista obejrzanych stron',
	'ListMyChangesWatches'		=> 'Zmiany pomiędzy obejrzanymi stronami',
	'SeeListOfPages'			=> 'Zobacz listę stron, które posiadasz (MyPages) i stron, które edytowałeś (MyChanges).',
	'AddBookmark'				=> 'Dodaj bieżącą stronę do zakładek',
	'RemoveBookmark'			=> 'Usuń z zakładek',

	'YourLanguage'				=> 'Wybierz język',
	'ShowSpaces'				=> 'Pokaż spacje w WikiNames',
	'WrongPage4Redirect'		=> 'Nie można przekierować z powodu złego parametru przekierowania',
	'RedirectsToItself'			=> 'Strona przekierowuje do siebie.',
	'ReallyDeletePage'			=> 'Czy na pewno chcesz zrezygnować z tej strony?<br>Nie ma cofnięcia dla tej akcji!<br><br>OSTRZEŻENIE: Usunięcie tej strony spowoduje usunięcie wszystkich wersji stron, komentarzy, załączników, ACL i polecających.',
	'CommentForWatchedPage'		=> 'Nowy komentarz do strony ',
	'SomeoneCommented'			=> ' skomentowałaś tę stronę, którą oglądasz: ',
	'AlertReferringPages'		=> 'Ta strona jest przywoływana przez te strony',

	'AccountDelete'				=> 'Usuń konto',
	'AccountDeleteConfirm'		=> 'Czy na pewno chcesz usunąć konto?',
	'AccountDeleted'			=> 'Konto pomyślnie usunięte',
	'AccountDeleteHeader'		=> 'Usuń konto %1',
	'AccountDeleteInfo'			=> 'Z danych które utworzyłeś (np. e-mail, preferencje, załączniki, wpisy wiki) zostaną usunięte. Należy jednak zauważyć, że dane takie jak załączniki i wpisy wiki nie mogą zostać usunięte bez utrudniania pracy innych użytkowników. Takie dane są zatem ponownie przypisane do konta o nazwie %1. Ponieważ dane każdego usuniętego konta są ponownie przypisane do tego konta, nie będzie możliwe odróżnienie danych utworzonych od danych innego usuniętego konta.',
	'AccountDeleteWarning'		=> 'Usunięcie konta użytkownika jest akcją nieodwracalną.',
	'AccountDeleteHint'			=> 'Twoje konto zostanie usunięte z systemu. W związku z tym nie będziesz mógł zalogować się przy użyciu aktualnych danych logowania. Jeśli zdecydujesz się ponownie zostać użytkownikiem tej aplikacji, możesz to zrobić, korzystając ze środków przyznawanych przez tę aplikację.',
	'AccountDeleteVerify'		=> 'Wprowadź swój login %1 , aby zweryfikować usunięcie. Po przesłaniu zostaniesz poproszony o potwierdzenie hasła.',

	'MarkRead'					=> 'Oznacz wszystkie jako przeczytane',
	'CurrentTime'				=> 'Obecnie jest',
	'Created'					=> 'utworzono',
	'Modified'					=> 'Zmodyfikowano',

	'EditIcon'					=> 'edytuj',
	'TreeClusterTitle'			=> 'Drzewo klastra %1',
	'TreeSiteTitle'				=> 'Drzewo witryny',
	'TreeEmpty'					=> '%1 nie ma podstron',
	'TreeEmptyLevels'			=> '%1 nie ma podstron dla podanego poziomu głębokości. Zwiększa wartość głębokości.',
	'TreeTooBig'				=> 'zbyt wiele podstron',

	// clone handler
	'ClonePage'					=> 'Skopiuj stronę',
	'CloneText'					=> 'Klonuj',
	'CloneName'					=> 'Wprowadź nową nazwę dla klonu tej strony',
	'CloneButton'				=> 'Klonuj',
	'PageCloned'				=> 'Strona %1 sklonowana.',
	'ClonedFrom'				=> 'Klonowany z %1.',
	'MassClone'					=> 'Klonuj cały klaster',
	'MassCloning'				=> 'Klonowanie klastrów.',
	'CloneCannotRead'			=> 'Nieczytelna strona %1.',
	'CloneCannotCreate'			=> 'Nietworzalna strona %1.',

	'SortComment'				=> 'Sortuj komentarze według',
	'SortCommentAsc'			=> 'Najnowsze na dole',
	'SortCommentDesc'			=> 'Najnowsze z góry',

	'RenamePage'				=> 'Zmień nazwę strony',
	'RenameText'				=> 'Zmień nazwę',
	'RenameTip'					=> 'Zmień nazwę strony',
	'NewName'					=> 'Wprowadź nową nazwę dla tej strony',
	'AlreadyExists'				=> 'Strona %1 już istnieje.',
	'AlreadyNamed'				=> 'Ta strona o nazwie %1.',
	'PageRenamed'				=> 'Zmieniono nazwę strony.',
	'NewNameOfPage'				=> 'Nowa nazwa tej strony: ',
	'NotOwnerCantRename'		=> 'Nie jesteś właścicielem tej strony i dlatego nie możesz jej zmienić nazwy',
	'NeedRedirect'				=> 'Utwórz przekierowanie do nowej strony na starej stronie',
	'RedirectCreated'			=> 'Na stronie %1 utworzono przekierowanie do nowego',

	'UserSettings'				=> 'Ustawienia użytkownika',
	'UserSettingsGeneral'		=> 'Ogólny',
	'UserSettingsNotifications'	=> 'Powiadomienia',

	'NotifyMinorEdit'			=> 'Powiadom również drobną edycję',
	'NotifyPageEdit'			=> 'Edytuj',
	'NotifyComment'				=> 'Komentarz',
	'NotifyOff'					=> 'Wyłączony',
	'NotifyAlways'				=> 'Zawsze',
	'NotifyPending'				=> 'Oczekujące',
	'NotifyDigest'				=> 'Podsumowanie',
	'NotifyPendingPageTip'		=> 'Tylko jedno powiadomienie jest wysyłane dla pierwszej zmiany strony którą oglądasz.',
	'NotifyPendingCommentTip'	=> 'Tylko jedno powiadomienie jest wysyłane dla pierwszego komentarza na stronie, którą oglądasz.',
	'NotifyPendingTip'			=> 'Powiadomienie jest automatycznie włączone, gdy odwiedzasz bieżącą wersję strony.',

	'FurtherPending'			=> 'Nie będzie żadnych innych powiadomień w przypadku dalszych zmian, chyba że odwiedzisz tę stronę.',

	'UserSettingsEmailMe'		=> 'Powiadom mnie, gdy ...',

	'UserSettingsExtended'		=> 'Rozszerzone',
	'UserSettingsOther'			=> 'Inne ustawienia',
	'UserSpace'					=> 'Przestrzeń użytkownika',
	'ChooseTheme'				=> 'Wybierz motyw',

	'CreatePage'				=> 'Utwórz tę stronę',
	'CreateNewPage'				=> 'Utwórz nową stronę',
	'CreateNewPageText'			=> 'Utwórz',
	'CreateNewPageTip'			=> 'Utwórz nową stronę',

	'CreateRandomPage'			=> 'Utwórz losową stronę:',
	'CreateSubPage'				=> 'Utwórz podstronę w klastrze:',
	'CreatePageParentCluster'	=> 'Utwórz stronę w klastrze nadrzędnym:',
	'CreatePageDenied'			=> 'Nie masz niezbędnych praw dostępu.',
	'CreatePageDeniedAddress'	=> 'Nie masz prawa do tworzenia strony pod tym adresem.',
	'PageAlreadyExists'			=> 'Zgodnie z podanym adresem strona %1 już istnieje.',
	'PageAlreadyExistsEdit'		=> 'Chcesz to %1?',
	'PageAlreadyExistsEdit2'	=> 'edytuj',
	'PageAlreadyExistsEditDenied'	=> 'Nie możesz go edytować.',

	'SimilarPagesExists'		=> 'Podobne strony do %1 już istnieją:',
	'SimilarPagesHint'			=> 'Istnieją podobne strony do %1:',

	'PageReservedWord'			=> 'Nie możesz użyć %1 jako części adresu jako zastrzeżonego słowa.',
	'UserReservedWord'			=> 'Nazwy użytkowników nie mogą zawierać %1 ponieważ jest to słowo zarezerwowane.',

	'DontRedirect'				=> 'Nie zezwalaj na automatyczne przekierowanie przez akcję Przekierowanie.',
	'SendWatchEmail'			=> 'Wyślij powiadomienie e-mail, gdy ktoś (z wyjątkiem Ciebie) zmieni dowolną stronę, którą oglądasz',
	'AllowIntercom'				=> 'Zezwalaj na prywatne wiadomości od użytkowników systemu',
	'AllowMassemail'			=> 'Administratorzy mogą wysłać mi wiadomość e-mail',
	'HideLastSession'			=> 'Ukryj ostatnią sesję',
	'ValidateIP'				=> 'Łączenie sesji na IP',
	'AnonymousPub'				=> 'Najlepiej opublikować anonimowo (w celu ukrycia imienia)',
	'PageMoved'					=> 'Ta strona została przeniesiona. Możesz ją znaleźć na',
	'RedirectedFrom'			=> 'Przekierowano z %1',
	'RedirectedTo'				=> 'Przekierowano do',
	'CurrentPassword'			=> 'Aktualne hasło',
	'NewPassword'				=> 'Nowe hasło',
	'YouWantChangePassword'		=> 'Zmień hasło',
	'ChangePasswordButton'		=> 'Zmień hasło',
	'PasswordChanged'			=> 'Hasło zmienione',
	'EmailWelcome'				=> 'Zarejestrowałeś się na ',
	'EmailRegistered'			=> 'Pomyślnie zarejestrowałeś się na %1.' . "\n" . 'Twoja nazwa użytkownika: %2' . "\n\n",
	'EmailVerify'				=> 'Jeśli chcesz otrzymywać powiadomienia, musisz zweryfikować swój adres e-mail. Kliknij lub skopiuj poniższy link do przeglądarki: ' . "\n" . '%1',
	'EmailRegisteredLogin'		=> 'Wróć do Wiki i zaloguj się przy użyciu nowej nazwy użytkownika i hasła.',
	'EmailRegisteredIgnore'		=> 'Jeśli nie prosiłeś o rejestrację, zignoruj tę wiadomość i nic się nie stanie.',
	'EmailDoNotReply'			=> 'Nie odpowiadaj na tę wiadomość.',
	'EmailReverify'				=> 'Ktoś (być może Ty) przesłał Twój e-mail jako adres powiadamiający pod adresem %1.' . "\n" . 'Twoja nazwa użytkownika: %2'."\n\n" . 'Jeśli chcesz otrzymywać powiadomienia, musisz zatwierdzić swój e-mail. Kliknij link, aby to zrobić.' . "\n" . '%3' . "\n\n",
	'EmailConfirm'				=> 'Zweryfikuj swój e-mail',
	'EmailConfirmed'			=> 'E-mail został potwierdzony.',
	'EmailNotConfirmed'			=> 'Nie można potwierdzić adresu e-mail. Może to być spowodowane nieprawidłowym kodem potwierdzającym lub adresem e-mail może być już potwierdzone. Możesz sprawdzić, czy adres e-mail jest już potwierdzony poprzez logowanie i przeglądanie jego statusu na stronie %1.',
	'EmailNotVerified'			=> 'E-mail nie został zweryfikowany!',
	'EmailNotVerifiedDesc'		=> 'Nie będziesz otrzymywać powiadomień o zmianach lub komentarzach obserwowanych stron, ' .
									'lub wiadomości od innych użytkowników. Ponadto <strong>nie będzie w stanie odzyskać zapomnianego hasła</strong>, ' .
									'dopóki Twój adres e-mail nie zostanie potwierdzony za pomocą linku w wiadomości e-mail wysłanej do Ciebie. ' .
									'Jeśli w ciągu dni od rejestracji nie otrzymasz wiadomości e-mail, poproś o to ponownie klikając ',

	'ForgotPasswordHint'		=> 'Wprowadź swój login i adres e-mail,' . "\n" . 'następnie e-mail z instrukcjami zostanie wysłany do Ciebie.',
	'ForgotPassword'			=> 'Zapomniałeś hasła?',
	'UserNotFound'				=> 'Użytkownik o tej nazwie lub adresie e-mail nie został znaleziony.',
	'NotConfirmedEmail'			=> 'Your email address is not confirmed.<br>Mail can\'t be send to a non-confirmed address.',
	'EmailForgotSubject'		=> 'Odnowienie hasła dla ',
	'EmailForgotMessage'		=> 'Ktoś (być może Ty) zapomniał hasła dla %1.' . "\n" . 'Twój login: %2'."\n\n" . 'Kliknij link lub skopiuj go do linii adresu przeglądarki, aby zmienić hasło.' . "\n" . '%3'."\n\n",
	'CodeWasSent'				=> 'Instrukcja odzyskiwania hasła została wysłana do Ciebie e-mailem.',
	'WrongCode'					=> 'Błędny kod',
	'ChangePasswordForUser'		=> 'Zmiana hasła %1',

	'Watchers'					=> 'Lista obserwatorów dla %1',
	'WatchersFor'				=> 'Obserwujący',
	'NoWatchers'				=> 'Brak obserwatorów dla %1',
	'NotOwnerToViewWatchers'	=> 'Nie jesteś właścicielem tej strony i nie możesz zobaczyć listy obserwatorów.',

	// thumbnail
	'TbnError'					=> 'Błąd podczas tworzenia miniatury: %1',
	'TbnImageAreaTooBig'		=> 'Plik o wymiarach większych niż %1',
	'TbnImageMissing'			=> 'Wydaje się, że brakuje pliku: %1',

	// admin_recovery action
	'GenerateRecoveryHash'		=> 'Wygeneruj skrót hasła dla Twojego <code>recovery_password</code>',

	// import action
	'ImportTo'					=> 'Importuj w klastrze:',
	'ImportWhat'				=> 'Plik XML do zaimportowania:',
	'ImportButton'				=> 'Importuj',
	'ImportSuccess'				=> 'Zaimportowano pomyślnie.',
	'ImportFailed'				=> 'IMPORT nie powiodło się.',
	'ImportHint'				=> 'Proszę podać klaster do którego chcesz importować, bez adresu względnego.',
	'ImportAttention'			=> 'Uwaga: Nadpisuje te same strony w klastrze.',
	'ImportNote'				=> 'Zaimportowana strona',

	// mywatches action
	'WatchedPages'				=> 'Lista wszystkich stron, które obserwujesz w celu wprowadzenia zmian ',
	'UnwatchedPages'			=> 'Lista wszystkich stron, których nie obserwujesz',
	'NoWatchedPages'			=> 'Nie masz obejrzanych stron.',
	'NoUnwatchedPages'			=> 'Obserwujesz zmiany na wszystkich stronach.',
	'ViewWatchedPages'			=> 'Pokaż obejrzane strony',
	'ViewUnwatchedPages'		=> 'Pokaż nieobejrzaną stronę',
	'NotLoggedInWatches'		=> 'Nie jesteś zalogowany, dlatego nie mogliśmy zidentyfikować Twojej listy zegarków.',

	// mychangeswatches action
	'MyChangesWatches'			=> 'Lista wszystkich stron, które oglądałeś, które były edytowane przez innych od twojej ostatniej edycji',
	'ResetChangesWatches'		=> 'resetuj listę zmian',
	'NoChangesWatches'			=> 'Spośród obejrzanych stron nie ma zmian...',

	// whatsnew action
	'NewCommentAdded'			=> 'Dodano nowy komentarz',
	'NewFileAdded'				=> 'Dodano nowy plik',
	'NewPageCreated'			=> 'Utworzono nową stronę',
	'NewRevisionAdded'			=> 'Zmieniona strona',
	'Cluster'					=> 'klaster',
	'PageDeleted'				=> 'Strona usunięta',
	'CommentDeleted'			=> 'Komentarz usunięty',
	'FileDeleted'				=> 'Plik usunięty',

	// users action
	'UsersSearch'				=> 'Znajdź użytkowników',
	'UsersOpenProfile'			=> 'Zobacz profil',
	'UsersNoMatching'			=> 'Nie znaleziono pasujących użytkowników. Spróbuj mniej rygorystycznych kryteriów wyszukiwania.',
	'UsersName'					=> 'Nazwisko',
	'UsersPages'				=> 'Strony',
	'UsersChanges'				=> 'Zmiany',
	'UsersSubscription'			=> 'Subskrypcja',
	'UsersWatches'				=> 'Zegarki',
	'UsersComments'				=> 'Komentarze',
	'UsersUploads'				=> 'Wgrane',
	'UploadQuota'				=> 'Użyte miejsce',
	'UploadQuotaTip'			=> 'Prześlij spację',
	'UsersLogins'				=> 'Logowanie',
	'UsersRevisions'			=> 'Wersje',
	'UsersSignup'				=> 'Rejestracja',
	'UsersLastSession'			=> 'Ostatnia sesja',
	'UsersNotFound'				=> 'Użytkownik %2 nie znaleziony. Kliknij <a href="%1">tutaj</a>, aby przejść do głównej listy.',
	'UsersProfile'				=> 'Profil',
	'UsersContact'				=> 'Kontakt',
	'UsersList'					=> 'Zobacz całą listę użytkowników',
	'UsersNA'					=> '[nieustawione]',
	'UsersNA2'					=> '[No]',
	'UsersSignupDate'			=> 'Data rejestracji',
	'UsersGroupMembership'		=> 'Członkostwo w grupie',
	'UsersPersonalInfo'			=> 'Informacje osobiste',
	'UsersOwnedPages'			=> 'Posiadane strony:',
	'UsersCommentsPosted'		=> 'Opublikowane komentarze:',
	'UsersFilesUploaded'		=> 'Przesłane pliki:',
	'UsersRevisionsMade'		=> 'Przeprowadzone wersje:',
	'UsersDocsSortName'			=> '[Sortuj według nazwy]',
	'UsersDocsSortCreation'		=> '[Sortuj według daty utworzenia]',
	'UsersChangesSortAsc'		=> '[Sortuj rosnąco]',
	'UsersChangesSortDesc'		=> '[Sortuj malejąco]',
	'UsersSessionNA'			=> '[nie zarejestrowano]',
	'UsersSessionHidden'		=> '[hidden]',
	'IntercomSubject'			=> 'Temat:',
	'IntercomMessage'			=> 'Wiadomość:',
	'IntercomCopy'				=> 'Wyślij mi kopię',
	'IntercomSubjectN'			=> '[utwórz nowy temat]',
	'IntercomDisabled'			=> 'Przepraszamy, nie chcesz lub nie możesz otrzymywać prywatnych wiadomości.',
	'IntercomHint'				=> 'Zaloguj się najpierw i kliknij ponownie na link, jeśli chcesz odpowiedzieć na otrzymaną prywatną wiadomość.',
	'IntercomDesc'				=> 'Uwaga: Wysyłanie prywatnych wiadomości do odbiorcy wiadomości bez ujawniania adresu. Odbiorca będzie mógł odpowiedzieć na Tobie za pomocą podobnego formularza na stronie profilowej. ',
	'PMOversized'				=> 'Długość wiadomości przekracza maksymalny dozwolony rozmiar przez %1. Proszę skrócić wiadomość i przesłać ponownie.',
	'PMFlooded'					=> 'Interwał pomiędzy wysyłaniem prywatnych wiadomości nie powinien być krótszy niż %1 sekund.',
	'PMSent'					=> 'Osobista wiadomość została pomyślnie wysłana do użytkownika.',
	'PMBody'					=> 'Ta wiadomość została wysłana do Ciebie przez użytkownika %1.',
	'PMBodyCopy'				=> 'Wysłałeś następującą wiadomość do użytkownika %1.',
	'PMReply'					=> 'Aby odpowiedzieć na ten e-mail, kliknij na poniższy link (nie używaj przycisku Odpowiedz / Odpowiedz w wiadomości):',
	'PMNotLoggedIn'				=> 'Nie jesteś zarejestrowany w systemie i nie możesz wysyłać prywatnych wiadomości do użytkowników.',

	// admin_replace action
	'ReplaceText'				=> 'Zastąp tekst',
	'TextOriginal'				=> 'Oryginalny tekst:',
	'TextReplacement'			=> 'Tekst zastępczy:',
	'ReplaceTextRegex'			=> 'Użyj wyrażeń regularnych',
	'Namespace'					=> 'Przestrzeń nazw:',
	'ReplaceTextCluster'		=> 'Wyszukaj i zamień tylko w tym klastrze:',
	'ReplaceTextEditPages'		=> 'Zastąp tekst w treści strony',
	'ReplaceTextEditComments'	=> 'Zastąp tekst w komentarzach',
	'ReplaceTextEditTitles'		=> 'Zamień tekst w tytułach stron',
	'ReplaceTextGiveTarget'		=> 'Musisz określić ciąg do zastąpienia.',
	'ReplaceTextNoNamespace'	=> 'Musisz wybrać co najmniej jedną przestrzeń nazw.',
	'ReplaceTextNoDifference'	=> 'Nie ma różnicy między tekstem zastępczym a tekstem docelowym.',
	'ReplaceTextNoOption'		=> 'Musisz wybrać co najmniej jedną z opcji zamiany.',
	'ReplaceTextPagesEdit'		=> 'Zamień %1 na %2 w tekście następujących stron %3:',
	'ReplaceTextTitlesEdit'		=> 'Zamień %1 na %2 w tytułach następujących stron %3:',
	'ReplaceTextReplace'		=> 'Zamień',
	'ReplaceTextSuccess'		=> '%1 został zastąpiony %2 na stronach %3.',
	'ReplaceTextNoMatch'		=> 'Nie znaleziono stron zawierających ciąg %1.',
	'ReplaceTextNoTitleMatch'	=> 'Nie znaleziono stron, które zawierają %1.',
	'ReplaceTextEditFailed'		=> 'Zastępowanie tekstu nie powiodło się',
	'ReplaceTextTitleTooBig'	=> 'Oryginalny lub zastępczy tekst jest zbyt duży dla tytułu.',
	'ReplaceTextReturn'			=> 'Powrót do formularza',
	'ReplaceTextWarning'		=> 'Warning: There are %1 pages that already contain the replacement string, %2. If you make this replacement you will not be able to separate your replacements from these strings.',
	'ReplaceTextBlankWarning'	=> 'Uwaga: Ponieważ ciąg zastępczy jest pusty, ta operacja nie będzie odwracalna.',
	'ReplaceTextEditSummary'	=> 'Zamiana tekstu: %1 → %2',
	'InvertSelection'			=> 'Odwróć zaznaczenie',

	// Properties
	'PropertiesFor'				=> 'Właściwości strony dla %1',
	'MetaTag'					=> 'Znacznik',
	'MetaTitle'					=> 'Rozporządzenie Rady (EWG) nr 2658/87 z dnia 23 lipca 1987 r. w sprawie nomenklatury taryfowej i statystycznej oraz w sprawie Wspólnej Taryfy Celnej (Dz.U. L 256 z 7.9.1987, s. 1).',
	'MetaKeywords'				=> 'Słowa kluczowe',
	'MetaDescription'			=> 'Opis',
	'On'						=> 'Włączone',
	'Off'						=> 'Wyłączony',
	'Registered'				=> 'Zarejestrowane',
	'MetaComments'				=> 'Pokaż komentarze',
	'MetaFiles'					=> 'Pokaż panel plików',
	'MetaToc'					=> 'Pokaż spis treści',
	'MetaIndex'					=> 'Pokaż panel sekcji klastra',
	'MetaIndexMode'				=> 'Pokaż tryb poziomu',
	'MetaIndexFull'				=> 'Drzewo',
	'MetaIndexUpper'			=> 'Górny',
	'MetaIndexLower'			=> 'Niższy',
	'MetaHtml'					=> 'Wsparcie HTML dla strony',
	'MetaSafeHtml'				=> 'Filtrowanie niebezpiecznego HTML',
	'MetaTypografica'			=> 'Korektor typograficzny',
	'MetaNoIndex'				=> 'Blokuj wyszukiwarki',
	'SettingsID'				=> 'ID strony',
	'SettingsSize'				=> 'Rozmiar',
	'SettingsSizeTip'			=> 'źródło / skompilowane',
	'SettingsCreated'			=> 'Utworzono',
	'SettingsCurrent'			=> 'Zmodyfikowane',
	'SettingsTotalRevs'			=> 'Wersje',
	'SettingsTotalComs'			=> 'Komentarze',
	'SettingsWatchers'			=> 'Obserwatorzy',
	'SettingsHits'				=> 'Widoki',
	'SettingsText'				=> 'Ustawienia',
	'SettingsEdit'				=> 'Edytuj',
	'SettingsRevisions'			=> 'Wersje',
	'SettingsClone'				=> 'Klonuj',
	'SettingsRename'			=> 'Zmień nazwę',
	'MassRename'				=> 'dla całego klastra',
	'SettingsRemove'			=> 'Usuń',
	'SettingsPurge'				=> 'Purge',
	'SettingsModerate'			=> 'Umiarkowane',
	'SettingsPermissions'		=> 'Uprawnienia',
	'AclForEntireCluster'		=> 'dla całego klastra',
	'SettingsAttachments'		=> 'Załączniki',
	'SettingsUpload'			=> 'Prześlij',
	'SettingsCategories'		=> 'Kategorie',
	'SettingsLanguages'			=> 'Języki',
	'SettingsReferrers'			=> 'Odsyłacze',
	'SettingsWatch'				=> 'Obejrzyj',
	'SettingsLatex'				=> 'Wersja LaTeX',
	'SettingsXML'				=> 'Eksportuj do XML',
	'NeedToChangeLang'			=> 'Nieobsługiwany język strony %1 musi zostać zmieniony.',
	'SetLang'					=> 'Język tej strony',
	'SetMenuLabel'				=> 'Etykieta menu',
	'SetShowMenuLabel'			=> 'Pokaż w nawigacji',

	// upload
	'UploadFiles'				=> 'Prześlij pliki',
	'UploadFor'					=> 'Przesyłanie pliku:',
	'UploadButton'				=> 'Prześlij',
	'UploadGlobalText'			=> 'dla publicznego dostępu',
	'UploadGlobal'				=> 'globalny',
	'UploadLocalText'			=> 'tylko dla użytkowników uprawnionych do przeglądania bieżącej strony',
	'UploadAsName'				=> 'Nazwa:',
	'UploadOverwrite'			=> 'Nadpisz istniejące pliki',
	'FileDesc'					=> 'Opis:',
	'UploadForbidden'			=> 'Nie masz uprawnień do przesyłania plików tutaj.',
	'UploadOverwriteDenied'		=> 'Tylko właściciel pliku lub administrator może nadpisać plik %1.',
	'UploadNoFile'				=> 'Nie było pliku w formie, z jakiegoś powodu.',
	'UploadMaxSizeReached'		=> 'Rozmiar pliku przekracza dozwolony limit!',
	'UploadDirNotWritable'		=> 'Katalog plików nie jest zapisywalny!',
	'UploadNotAPicture'			=> 'Tylko przesyłanie zdjęć jest dozwolone. Co próbujesz przesłać?',
	'UploadEmptyExtension'		=> 'Nazwa pliku i rozszerzenie nie mogą być puste.',
	'FilenameTooLong'			=> 'Nazwy plików nie mogą być dłuższe niż 240 bajtów.',
	'BannedFiletype'			=> '%1 nie jest dozwolonym typem pliku.',
	'PermittedFiletype'			=> 'Dozwolone typy plików:',
	'UploadMimeMismatch'		=> 'Rozszerzenie pliku %1 nie pasuje do wykrytego typu MIME pliku (%2).',
	'UploadBadMime'				=> 'Pliki typu MIME %1 nie mogą być przesyłane.',
	'FileIsDuplicate'			=> 'Wysyłanie jest dokładnym duplikatem bieżącej wersji.',
	'FileHasDuplicate'			=> 'Ten plik jest duplikatem następujących plików:',

	'UploadMaxFileQuota'		=> 'Osiągnąłeś limit przesyłania. Ten plik nie może zostać przesłany',
	'UploadDone'				=> 'Przesyłanie pliku zakończone powodzeniem',
	'UploadFileForbidden'		=> 'Dostęp do pliku zabroniony',
	'UploadTitle'				=> 'Pliki dostępne na tej stronie',
	'UploadTitleGlobal'			=> 'Pliki dostępne z dowolnego miejsca',

	'UploadFile'				=> 'Prześlij',
	'UploadMax'					=> 'Nie więcej niż ',
	'UploadUsedStorage'			=> 'Przechowywanie w użyciu ',

	// attachments
	'Attachments'				=> 'Załączniki',
	'Attachment'				=> 'Załącznik',
	'AttachmentsToPage'			=> 'na stronę',
	'AttachmentsToCluster'		=> 'klaster',
	'AttachmentsByTime'			=> 'wg czasu',
	'AttachmentsGlobal'			=> 'globalny',
	'AttachmentsAll'			=> 'wszystkie',
	'AttachmentsLinked'			=> 'użyty',

	'FileViewProperties'		=> 'Widok',
	'FileViewPropertiesTip'		=> 'Zobacz metadane tego pliku',
	'FileEditProperties'		=> 'Edytuj',
	'FileEditPropertiesTip'		=> 'Edytuj metadane tego pliku',
	'FileEditedMeta'			=> 'Zaktualizowano metadane tego pliku',
	'FileEditDenied'			=> 'Nie masz uprawnień do edycji tego pliku',
	'FileLabel'					=> 'Etykieta',
	'FileLabelTip'				=> 'Oznacz ten plik',
	'FileRemove'				=> 'Usuń',
	'FileRemovedFromDB'			=> 'Plik usunięty z bazy danych',
	'FileRemovedFromFS'			=> 'Plik skasowany z fizycznego hostingu',
	'FileRemovedFromFSError'	=> 'Wygląda na to, że usunięcie pliku jest niemożliwe!',
	'FileRemoveConfirm'			=> 'Na pewno chcesz usunąć ten plik?',
	'FileRemoveDenied'			=> 'Nie masz uprawnień do usunięcia tego pliku',
	'FileNotFound'				=> 'Nie znaleziono pliku.',

	'FileSearch'				=> 'Znajdź plik',
	'UploadBy'					=> 'Przesłane przez:',
	'FileAdded'					=> 'Dodano:',
	'FileModified'				=> 'Zmodyfikowano:',
	'FileSize'					=> 'Rozmiar:',
	'FileDimension'				=> 'Wymiary:',
	'MimeType'					=> 'Mimetyp:',
	'FileName'					=> 'Nazwa:',
	'FileCaption'				=> 'Podpis:',
	'FileAuthor'				=> 'Autor:',
	'FileSource'				=> 'Źródło:',
	'FileSourceUrl'				=> 'URL:',
	'FileAttachedTo'			=> 'Dołączony do:',
	'FileSyntax'				=> 'Składnia:',
	'FileAbsolutePath'			=> 'ścieżka bezwzględna',
	'FileRelativePath'			=> 'ścieżka względna',
	'FileUsage'					=> 'Użycie pliku:',
	'FileUsageText'				=> 'Następujące strony linku do tego pliku:',
	'NoFileUsage'				=> 'Brak linków do tego pliku.',

	'FileSortExt'				=> 'rozszerzenie',
	'FileSortName'				=> 'Nazwa',
	'FileSortSize'				=> 'rozmiar',
	'FileSortTime'				=> 'utworzono',

	'SortBy'					=> 'Sortuj według',
	'Ascending'					=> 'rosnąco',
	'Decending'					=> 'odrzucenie',

	'Files0'					=> 'Załącz pliki',
	'Files1'					=> 'Pokaż pliki (1 plik)',
	'FilesN'					=> 'Pokaż pliki (pliki%1)',
	'Files'						=> 'Pliki',
	'File'						=> 'Plik',
	'ShowFiles'					=> 'Wyświetl pliki / formularz',
	'HideFiles'					=> 'Ukryj pliki / formularz',
	'DoShowFiles'				=> 'Pokaż domyślnie listy plików',
	'NoAttachments'				=> 'Brak załączonych plików do wyświetlenia.',

	'RegistrationLang'			=> 'Twój język',
	'InvalidWikiName'			=> 'Wybrana nazwa jest nieprawidłowa',
	'InvalidUserName'			=> 'Wybrana nazwa użytkownika jest nieprawidłowa',
	'Bookmarks'					=> 'Zakładki',
	'ReallyDeleteComment'		=> 'Czy na pewno chcesz zrezygnować z tego komentarza?<br>Nie ma cofnięcia dla tej akcji!',
	'ReallyDeleteRevision'		=> 'Czy na pewno chcesz zrezygnować z tej wersji?<br>Nie ma cofnięcia dla tej akcji!',

	'RegistrationClosed'		=> 'Rejestracja jest tutaj niedostępna. Spróbuj skontaktować się z administratorem witryny.',
	'AclAreYouSure'				=> 'Zamierzasz zmienić ACL tej strony i jej wszystkie podstrony. Kontynuować?',

	'BookmarkDeleteSelected'	=> 'Usuń zaznaczone',
	'BookmarkMark'				=> 'Oznacz',
	'BookmarkNumber'			=> 'Nie.',
	'BookmarkNone'				=> 'Nie masz zakładek.',
	'BookmarkTitle'				=> 'Tytuł zakładki',
	'BookmarkPage'				=> 'Strona',
	'BookmarkSaveChanges'		=> 'Zapisz zmiany',
	'BookmarksAddPage'			=> 'Ustaw zakładkę dla następującej strony',
	'BookmarkAlreadyExists'		=> 'Zakładka już istnieje.',

	'PoweredBy'					=> 'Wspierane przez',

	'MassRenaming'				=> 'Zmień nazwę całego klastra',
	'MassNewName'				=> 'Wprowadź nową nazwę dla tego klastra',
	'MassNeedRedirect'			=> 'Utwórz przekierowanie do nowych stron na starych stronach',

	// pagination
	'ToOverview'				=> 'Powrót do przeglądu',
	'Overview'					=> 'Przegląd',
	'ToThePage'					=> 'Do strony:',
	'Next'						=> 'Następny',
	'Prev'						=> 'Poprzedni',
	'NextAcr'					=> 'Następny',
	'PrevAcr'					=> 'Poprzedni',
	'Back'						=> 'Powrót',

	// filter
	'Filter'					=> 'Filtr',
	'OptionalFilters'			=> 'Filtry opcjonalne:',
	'Any'						=> 'Dowolny',

	// My Groups
	'UserGroups'				=> 'Grupy użytkowników',
	'MyGroups'					=> 'Skojarzenia grupy',
	'Group'						=> 'grupa',
	'Groups'					=> 'grupy',

	// license action
	'DistributedUnder'			=> 'Materiał rozprowadzany jest pod',
	'AuthorsDisplayHint'		=> 'Lista autorów będzie wyświetlana podczas zapisywania strony.',
	'AnonymousUsers'			=> 'Anonimowi użytkownicy',
	'License'					=> 'Licencja',
	'LicenseArray'				=> [
		'1'		=> 'Atrybuty niebędące instrumentami pochodnymi',
		'2'		=> 'Atrybucja-NieCommercial-ShareAlike',
		'3'		=> 'Atrybucja-niekomercyjne instrumenty pochodne',
		'4'		=> 'Atrybucja-ShareAlike',
		'5'		=> 'Atrybucja-niehandlowa',
		'6'		=> 'Atrybuty',
		'7'		=> 'CC0 1.0 Universal',
		'8'		=> 'Licencja bezpłatnej dokumentacji GNU',
		'9'		=> 'Domena publiczna / darmowe korzystanie',
		'10'	=> 'Wszystkie prawa zastrzeżone',
	],
	'LicenseMeta'				=> [
		'1'		=> 'Domena publiczna',
		'2'		=> 'Niektóre prawa zastrzeżone',
		'3'		=> 'Wszystkie prawa zastrzeżone',
	],

	// Cache
	'ClearCache'				=> 'Usuń pamięć podręczną',
	'CacheCleared'				=> 'Pamięć podręczna wyczyszczona.',
	'ConfigCache'				=> 'Pamięć podręczna konfiguracji',
	'FeedCache'					=> 'Pamięć podręczna',
	'PageCache'					=> 'Skrzynka strony',
	'SQLCache'					=> 'Skrzynka SQL',
	'TemplateCache'				=> 'Skrzynka szablonu',
	'ThumbCache'				=> 'Thumbnail cache',

	// Embed
	'EmbedNoURL'				=> 'Proszę podać adres zasobu z adresem URL parametru (np. {{embed url="https://example.com/embed/video.mp4"}} )',

	// Feed
	'FeedTitle'					=> 'Tytuł kanału',
	'FeedMulti'					=> 'Multi-Feed',
	'FeedNoURL'					=> 'Proszę podać kanał z adresem URL parametru (np. {{feed url="https://example.com/feed.xml"}} )',
	'FeedError'					=> 'Nie można załadować ani analizować kanału',
	'FeedSource'				=> 'Źródło:',
	'FeedXMLTip'				=> '',

	// XML / RSS autodiscovery
	'ChangesXMLTitle'			=> ' - Ostatnie zmiany',
	'ChangesXML'				=> 'Ostatnie zmiany ',
	'CommentsXMLTitle'			=> ' - Ostatnie komentarze',
	'CommentsXML'				=> 'Ostatnie komentarze do ',
	'NewsXMLTitle'				=> ' - Najnowsze wiadomości',
	'NewsXML'					=> 'Najnowsze wiadomości ',
	'RevisionXMLTip'			=> 'Kliknij, aby wyświetlić ostatnie zmiany strony w formacie XML.',
	'CommentsXMLTip'			=> 'Kliknij, aby zobaczyć ostatnie komentarze w formacie XML.',
	'ChangesXMLTip'				=> 'Kliknij, aby wyświetlić ostatnie zmiany w formacie XML.',
	'NewsXMLTip'				=> 'Kliknij, aby zobaczyć najnowsze wiadomości w formacie XML.',
	'RevisionsXML'				=> 'Rewizje ',
	'ExportClusterXML'			=> 'Eksport całego klastra ',
	'AccessDeniedXML'			=> 'Nie masz uprawnień do dostępu do tych informacji.',

	'ChangesFeed'				=> 'Zmiany',
	'CommentsFeed'				=> 'Komentarze',
	'NewsFeed'					=> 'Wiadomości',
	'RevisionsFeed'				=> 'Rewizje ',

	'LastModification'			=> 'Ostatnia modyfikacja',

	// Captcha
	'Captcha'					=> 'Wpisz słowo, które przeczytałeś na obrazku',
	'CaptchaFailed'				=> 'Wpisałeś słowo captcha nieprawidłowo. Spróbuj ponownie.',
	'CaptchaReload'				=> 'Nowy Captcha',
	'CaptchaReloadWarning'		=> 'Przepraszamy, nie można odświeżyć obrazka captcha, musisz odświeżyć stronę, aby to zrobić',

	// news
	'News'						=> 'Wiadomości',
	'NewsName'					=> 'Tytuł:',
	'NewsNoName'				=> 'Zapomniałeś dodać nagłówek wiadomości.',
	'NewsNotAvailable'			=> 'Brak dostępnych wiadomości.',
	'NewsNoClusterDefined'		=> 'Nie zdefiniowano klastra wiadomości.',
	'NewsDiscuss'				=> 'Omówienie tego artykułu...',

	// blog
	'BlogNewTopic'				=> 'Utwórz nowy post',
	'NoPostAvailable'			=> 'Brak dostępnych postów.',

	// Review
	'Reviewer'					=> 'Recenzent',
	'Reviewed'					=> 'zweryfikowane',
	'Review'					=> 'recenzja',
	'ReviewedBy'				=> 'zweryfikowane przez',
	'RemoveReview'				=> 'Usuń recenzję dla tej strony',
	'SetReview'					=> 'Przeglądano tę stronę',
	'SetAsReviewed'				=> 'Ustaw stronę jako przejrzaną',
	'SetAsUnreviewed'			=> 'Ustaw stronę jako niesprawdzoną',

	// word filter
	'PotentialSpam'				=> 'Zidentyfikowany potencjalny spam',

	// moderation handler
	'Moderation'				=> 'Moderacja',
	'Topics'					=> 'tematy',
	'ModerateSection'			=> 'sekcja / strona ',

	'NotModerator'				=> 'Nie masz uprawnień do moderowania tej strony / rozdziału',
	'ModerateDeleteTopic'		=> 'Usuń temat / stronę',
	'ModerateDeletePosts'		=> 'Usuń komentarze',
	'ModerateMove'				=> 'Przenieś',
	'ModerateSplit'				=> 'Podziel / Przenieś komentarze',
	'ModerateMerge'				=> 'Połącz',
	'ModerateLock'				=> 'Blokada',
	'ModerateUnlock'			=> 'Odblokuj',
	'ModerateAccept'			=> 'Zaakceptuj',
	'ModerateDeleteConfirm'		=> 'Are you sure you want to <strong>remove</strong> the following topics?',
	'ModerateRenameConfirm'		=> 'Wprowadź nowy tytuł dla wybranej strony',
	'ModerateRenameExists'		=> 'Strona o tej samej nazwie już istnieje! Wybierz inną nazwę.',
	'ModerateRename1Only'		=> 'Uwaga: tylko pierwsza wybrana strona zostanie zmieniona na nową!',
	'ModerateMovesConfirm'		=> 'Wybierz docelową partycję, aby przenieść forum do',
	'ModerateMoveConfirm'		=> 'Wybierz forum lub wybierz klastr, aby przenieść te tematy. Aby przenieść stronę do katalogu głównego witryny, wpisz &quot;/&quot;',
	'ModeratePgMoveConfirm'		=> 'Określ nazwę klastra, w którym należy umieścić stronę. Aby przenieść stronę do katalogu głównego witryny, wpisz &quot;/&quot;',
	'ModerateMoveExists'		=> 'Operacja przerwana: W tej sekcji już istnieją tematy o tej samej nazwie %1. Jeśli nadal musisz przenieść wyżej wymienione tematy, zmień ich nazwę na początku.',
	'ModerateMoveNotExists'		=> 'Strona / klaster nie istnieje. Sprawdź nazwę i spróbuj ponownie.',
	'ModerateMergeConfirm'		=> 'Wybierz temat, który powinien łączyć pozostałe',
	'ModerateMerge2Min'			=> 'Aby dołączyć musisz wybrać co najmniej dwa wątki!',
	'ModerateComDelConfirm'		=> 'Czy na pewno chcesz <strong>usunąć</strong> %1 %2?',
	'ModerateComment'			=> 'Komentarz',
	'ModerateComments'			=> 'Komentarze',
	'ModerateSplitNewName'		=> 'Określ nazwę dla oddzielnego tematu i wybierz schemat separacji',
	'ModerateSplitPageName'		=> 'Wprowadź nazwę strony / tematu, gdzie przenieść odłączalne komentarze i wybierz schemat separacji',
	'ModerateSplitAllAfter'		=> 'Odłącz wszystkie komentarze po pierwszym wybraniu (i włącznie)',
	'ModerateSplitSelected'		=> 'Oddzielne tylko wybrane komentarze (suma %1)',
	'ModerateUserProfile'		=> 'profil',
	'ModerateNoItemChosen'		=> 'Proszę wybrać co najmniej jeden element za pomocą przycisku Zestaw.',

	'ModerateSection2'			=> 'umiarkowany odcinek',
	'ModerateTopicsDeleted'		=> 'Wybrane tematy zostały pomyślnie usunięte.',
	'ModerateTopicsRelocated'	=> 'Wybrane tematy zostały pomyślnie przeniesione.',
	'ModerateTopicsRenamed'		=> 'Zmieniono nazwę tematu.',
	'ModerateTopicsMerged'		=> 'Wybrane tematy pomyślnie scalone.',
	'ModerateTopicsBlocked'		=> 'Wybrane tematy zostały pomyślnie zablokowane',
	'ModerateTopicsUnlocked'	=> 'Wybrane tematy pomyślnie odblokowane.',
	'ModerateTopicDeleted'		=> 'Temat został pomyślnie usunięty.',
	'ModeratePageMoved'			=> 'Strona przeniesiona pomyślnie.',
	'ModerateTopicRenamed'		=> 'Zmieniono nazwę tematu.',
	'ModerateTopicBlocked'		=> 'Temat został pomyślnie zablokowany',
	'ModerateTopicUnlocked'		=> 'Wątek odblokowany.',
	'ModerateCommentsDeleted'	=> 'Wybrane komentarze zostały pomyślnie usunięte.',
	'ModerateCommentsSplit'		=> 'Wybrane komentarze zostały pomyślnie oddzielone w nowym wątku.',
	'ModerateCommentsSplitFailed'	=> 'Uwaga: Z jakiegoś powodu oddzielenie zaznaczonych komentarzy od nowego tematu nie powiodło się.<br>Zazwyczaj tak się nie stanie, więc poinformuj administratora witryny.<br>W ramach środków ostrożności problem został zachowany w oryginalnej formie.',
	'ModerateCommentsMoved'		=> 'Wybrane komentarze zostały pomyślnie przeniesione na daną stronę.',

	// forum
	'ForumSubforums'			=> 'Forum',
	'ForumTopic'				=> 'Temat',
	'ForumTopics'				=> 'Tematy',
	'ForumPosts'				=> 'Posty',
	'ForumReplies'				=> 'Odpowiedzi',
	'ForumAuthor'				=> 'Autor',
	'ForumViews'				=> 'Widoki',
	'ForumCreated'				=> 'Utworzono',
	'ForumComments'				=> 'Komentarze',
	'ForumLastComment'			=> 'Ostatni komentarz',
	'ForumNoComments'			=> 'Brak komentarzy',
	'ForumNoTopics'				=> 'Brak wątków lub postów na tym forum.',
	'ForumNewTopic'				=> 'Rozpocznij nową dyskusję',
	'ForumTopicName'			=> 'Nazwa wątku:',
	'ForumTopicSubmit'			=> 'Prześlij temat',
	'ForumNoTopicName'			=> 'Określ nazwę dla nowej strony.',
	'ForumNewPosts'				=> 'nowy post',
	'ForumLocked'				=> 'sekcja zablokowana',
	'ForumUpdated'				=> 'zaktualizowano',
	'ForumNoClusterDefined'		=> 'Nie zdefiniowano klastra forum.',
	'ForumOutsideCluster'		=> 'Upewnij się, że akcja %1 znajduje się wewnątrz klastra forum.',

	// password complexity
	'PwdCplxShort'				=> 'Hasło jest zbyt krótkie.',
	'PwdCplxEquals'				=> 'Hasło zawiera nazwę użytkownika.',
	'PwdCplxWeak'				=> 'Hasło nie spełnia wymogów złożoności.',
	'PwdCplxDesc1'				=> 'Wymagania dotyczące hasła: ',
	'PwdCplxDesc2'				=> 'hasło nie powinno być mniejsze niż %1 znaków',
	'PwdCplxDesc3'				=> 'nie może zawierać nazwy użytkownika',
	'PwdCplxDesc4'				=> 'powinien składać się z ',
	'PwdCplxDesc41'				=> 'litery i cyfry',
	'PwdCplxDesc42'				=> 'wielkie i małe litery i cyfry',
	'PwdCplxDesc43'				=> 'wielkie i małe litery, cyfry i znaki niealfanumeryczne',
	'PwdCplxDesc5'				=> 'Możesz użyć dowolnych liter, cyfr i znaków specjalnych, z wyjątkiem spacji.',

	'PasswordTooShort'			=> 'Hasło jest zbyt krótkie.',
	'PasswordTooCommon'			=> 'To hasło jest zbyt powszechne.',
	'PasswordSameAsUsername'	=> 'Twoje hasło jest takie samo jak nazwa użytkownika.',
	'PasswordSameAsEmail'		=> 'Twoje hasło jest takie samo jak Twój e-mail.',

	'Timezone'					=> 'Timezone',

	'LanguageArray'	=> [
		'bg' => 'bułgarski',
		'da' => 'duński',
		'de' => 'niemiecki',
		'el' => 'grecki',
		'en' => 'Angielski',
		'es' => 'hiszpański',
		'et' => 'estoński',
		'fa' => 'perski',
		'fr' => 'Francuski',
		'hi' => 'Hindi',
		'hu' => 'węgierski',
		'it' => 'włoski',
		'ja' => 'japoński',
		'ko' => 'koreański',
		'nl' => 'Holenderski',
		'pl' => 'polski',
		'pt' => 'Portugalski',
		'ru' => 'rosyjski',
		'ta' => 'Tamil',
		'zh' => 'Chiński',
		'zh-tw' => 'Chiński',
	],

	'AccountStatus'				=> 'Status konta',
	'AccountStatusArray' => [
		'0' => 'aktywna',
		'1' => 'oczekujące',
		'2' => 'zablokowane',
		'3' => 'nieaktywny',
	],

	'JustNow'		=> 'właśnie teraz',
	'MinuteAgo'		=> 'minutę temu',
	'MinutesAgo'	=> '%1 minutes ago',
	'HourAgo'		=> 'godzinę temu',
	'HoursAgo'		=> '%1 hours ago',
	'DayAgo'		=> 'wczoraj',
	'DaysAgo'		=> '%1 days ago',
	'WeekAgo'		=> 'tydzień temu',
	'WeeksAgo'		=> '%1 tygodni temu',
	'MonthAgo'		=> 'miesiąc temu',
	'MonthsAgo'		=> '%1 months ago',
	'YearAgo'		=> 'rok temu',
	'YearsAgo'		=> '%1 years ago',

	'InAMoment'		=> 'za chwilę',
	'InAMinute'		=> 'za minutę',
	'InMinutes'		=> 'in %1 minutes',
	'InAnHour'		=> 'za godzinę',
	'InHours'		=> 'in %1 hours',
	'Tomorrow'		=> 'jutro',
	'InDays'		=> 'in %1 days',
	'InAWeek'		=> 'za tydzień',
	'InWeeks'		=> 'w %1 tygodni',
	'InAMonth'		=> 'za miesiąc',
	'InMonths'		=> 'w %1 miesięcy',
	'InAYear'		=> 'za rok',
	'InYears'		=> 'in %1 years',

	// norm multiples
	'ByteDecimalShort'			=> ['B', 'kB', 'MB', 'GB', 'TB', 'PB', 'EB', 'ZB', 'JM'],
	'ByteDecimalLong'			=> ['bajt', 'Kilobyte', 'Megabyte', 'Gigabyte', 'Terabyte', 'Petabyte', 'Exabyte', 'Zettabyte', 'Yottabyte'],
	'ByteBinaryShort'			=> ['B', 'KiB', 'MB', 'GiB', 'TiB', 'PiB', 'EiB', 'ZiB', 'YiB'],
	'ByteBinaryLong'			=> ['bajt', 'Kibibyte', 'Mebibyte', 'Gibibyte', 'Tebibyte', 'Pebibyte', 'Exbibyte', 'Zebibyte', 'Yobibyte'],
	'PixelDecimalShort'			=> ['px', 'KP', 'PP', 'GP', 'Trójkątny', 'PP', 'PT', 'ZP', 'RP'],
	'PixelDecimalLong'			=> ['piksel', 'Kpx', 'Mpx', 'Gpx', 'Tpx', 'Ppx', 'Epx', 'Zpx', 'Ypx'],

	// loading error
	'UnknownAction'				=> 'Nieznana akcja',
	'UnknownMethod'				=> 'Nieznana metoda',
	'FormatterNotFound'			=> 'Formuła %1 nie została znaleziona',

	// log
	'LogAdminLoginSuccess'		=> 'Pomyślnie zalogowano się do panelu administracyjnego',
	'LogAdminLogout'			=> 'Wylogowanie z panelu administracyjnego',
	'LogAdminLoginFailed'		=> '!!Błąd autoryzacji dostępu do panelu administracyjnego!!',
	'LogAdminLoginLocked'		=> 'Zablokowano logowanie do panelu administracyjnego',
	'LogUserCookieForged'		=> '!!**Próba zalogowania się na wykutym ciasteczku z logowaniem ##%1##**!!',
	'LogInvalidFormToken'		=> 'Wykryto potencjalny atak CSRF w toku: %1',
	'LogRemovedPage'			=> '!!Usunięto stronę ##%1## (użytkownik %2)!!',
	'LogRemovedCluster'			=> '!!Usunięto **klaster** ##%1## (użytkownik %2)!!',
	'LogRemovedRevision'		=> '!!Usunięto wersję ##%3## strony [[/%1]] (użytkownik %2)!!',
	'LogRemovedComment'			=> '!!Usunięto komentarz z %3 na stronie [[/%1]] (użytkownik %2)!!',
	'LogRemovedFile'			=> '!!Usunięto plik ##%2## ze strony [[/%1]]!!',
	'LogRemovedAllComments'		=> '!!Usunięto wszystkie komentarze strony [[/%1]]!!',
	'LogRemovedAllRevisions'	=> '!!Usunięto wszystkie wersje strony [[/%1]]!!',
	'LogRemovedAllFiles'		=> '!!Usunięto wszystkie pliki, dołączone do [[/%1]]!!',
	'LogTopicLocked'			=> 'Temat na forum jest zablokowany [[/%1]]',
	'LogTopicUnlocked'			=> 'Odblokowany wątek na forum [[/%1]]',
	'LogAclUpdated'				=> 'Zaktualizowano stronę ACL [[/%1]]',
	'LogOwnershipChanged'		=> 'Własność strony [[/%1]] przeniesiona do użytkownika ##%2##',
	'LogUserLoginFailed'		=> '!!Nieudane próby zalogowania się z ##~%1##!!',
	'LogClonedPage'				=> 'Strona ##%1## sklonowana do [[/%2]]',
	'LogRenamedPage'			=> 'Strona ##%1## zmieniona na [[/%2]]',
	'LogRenamedPage2'			=> '. Stara strona ustawiona jako link do nowej strony',
	'LogSplittedPage'			=> 'Komentarze na stronie [[/%1]] podzielone na stronę [[/%2]]',
	'LogMergedPages'			=> 'Strony %1 scalone do strony [[/%2]]',
	'LogUserPasswordReminded'	=> 'Użytkownik ##%1## poprosił o proces odzyskiwania hasła na adres ##%2##',
	'LogUserPasswordRecovered'	=> 'Użytkownik ##%1## pomyślnie odzyskał zapomniane hasło',
	'LogUserPasswordChanged'	=> 'Użytkownik ##%1## został pomyślnie zaktualizowany (zmieniony) hasło',
	'LogUserPasswordMismatch'	=> '!!Użytkownik ##%1## nie mógł zmienić hasła: obecne hasło nie pasuje!',
	'LogUserIPSwitched'			=> 'Nieautoryzowana zmiana adresu IP użytkownika %1 z %2 na %3',
	'LogPageImported'			=> 'Zaimportowana strona [[/%1]]',
	'LogSaveNoRights'			=> 'Brak odpowiednich praw do zapisania strony [[/%1]]',
	'LogPageCreated'			=> 'Utworzono nową stronę [[/%1]]',
	'LogPagePropertiesUpdated'	=> 'Zaktualizowane właściwości strony [[/%1]]',
	'LogPageOwnershipClaimed'	=> 'Użytkownik ma prawo własności strony [[/%1]]',
	'LogFileUploadedLocal'		=> 'Nowy plik ##%2## przesłany na stronę [[/%1]] (rozmiar %3)',
	'LogFileUploadedGlobal'		=> 'Nowy plik ##%2## przesłany do folderu globalnego (rozmiar %3)',
	'LogPMSent'					=> 'Prywatna wiadomość ##%1## -> ##%2## pomyślnie wysłana',
	'LogUserSimilarName'		=> 'Próby rejestracji pod tą samą nazwą użytkownika: ##%1##',
	'LogUserEmailNotAllowed'	=> 'E-mail ##%1## niedozwolona lista domen',
	'LogRegisterTiming'			=> 'Rejestracja nie powiodła się, próg czasu formularza to ##%1## sekund (##%2##)',
	'LogUserRegistered'			=> 'Pomyślnie zarejestrowano nowego użytkownika ##%1## (##%2##)',
	'LogUserEmailActivated'		=> 'Pomyślnie aktywowano e-mail ##%1## użytkownika ##%2##',
	'LogCommentPosted'			=> 'Dodano [[/%1 nowy komentarz(y)]] do strony [[/%2]]',
	'LogUserLoginOK'			=> 'Użytkownik ##%1## pomyślnie zalogował się do systemu',
	'LogUserLoggedOut'			=> 'Użytkownik ##%1## pomyślnie wylogował się z systemu',
	'LogUserSessionContinued'	=> 'Użytkownik ##%1## kontynuował zawieszoną sesję',
	'LogUserSettingsUpdate'		=> 'Użytkownik ##%1## zaktualizował ustawienia osobiste',
	'LogPageEdited'				=> 'Edytowana strona [[/%1]]',
	'LogCommentEdited'			=> 'Edytowany komentarz [[/%1]]',
	'LogUpdatedFileMeta'		=> 'Zaktualizowano metadane pliku ##%2## ze strony [[/%1]]',
	'LogUpdatedFileCategories'	=> 'Zaktualizowano kategorie plików dla ##%2## ze strony [[/%1]]',

	'LogXmlSitemapGenerated'	=> 'Wygenerowano mapę strony XML',
	'LogReferrersPurged'		=> 'Konserwacja: oczyszczenie zleceniodawców',
	'LogRevisionsPurged'		=> 'Konserwacja: wyczyszczone przestarzałe wersje stron',
	'LogDeletedPagesPurged'		=> 'Konserwacja: usunięto strony',
	'LogSystemLogPurged'		=> 'Konserwacja: dziennik systemu wyczyszczony',
	'LogCachedPagesPurged'		=> 'Konserwacja: usunięta pamięć podręczna stron',
	'LogSqlCachePurged'			=> 'Konserwacja: wyczyszczone wyniki buforowane sql',
	'LogExpiredTokensPurged'	=> 'Konserwacja: wyczyszczono wygasłe pliki cookie_tokens',
	'LogErrorSplitComments'		=> 'Błąd podczas oddzielania komentarzy od tematu [[/%1]] nowy temat ##%2##: strona nie została utworzona',
	'LogCategoriesUpdated'		=> 'Zaktualizowano kategorie stron [[/%1]]',
	'LogCategoryCreated'		=> 'Utworzono nową kategorię //%1//',
	'LogCategoryRenamed'		=> 'Kategoria ##%1## zmiana nazwy na ##%2##',
	'LogCategoryDebundled'		=> 'Kategoria ##%1## obciążone',
	'LogCategoryGrouped'		=> 'Kategoria ##%1## pogrupowana ze słowem ##%2##',
	'LogCategoryRemoved'		=> 'Kategoria ##%1## usunięta z bazy danych',
	'LogThumbnailGeneration'	=> 'Generowanie miniatur %1 sek.',

	'ErrorMinPHPVersion'		=> 'Wersja PHP musi być większa niż <strong>' . PHP_MIN_VERSION . '</strong>,' .
									' Twój serwer wydaje się być uruchomiony <strong>' . PHP_VERSION . '</strong>.' .
									'  Powinieneś uaktualnić do najnowszej wersji PHP dla WackoWiki, aby działać poprawnie.',

];
