<?php

if (!defined('IN_WACKO'))
{
	exit;
}

$wacko_translation = [

	// language
	'lang_scheme'	=> [
		'name'		=> 'Inglese',
		'code'		=> 'it',
		'dir'		=> 'ltr',
		'locale'	=> 'it_US.UTF-8',
	],

	// common
	'AddButton'					=> 'Aggiungi',
	'ArchiveButton'				=> 'Archivio',
	'CancelButton'				=> 'Annulla',
	'ContinueButton'			=> 'Continua',
	'ConvertButton'				=> 'Converti',
	'CreateButton'				=> 'Crea',
	'DeleteButton'				=> 'Elimina',
	'RemoveButton'				=> 'Rimuovi',
	'RenameButton'				=> 'Rinomina',
	'ResetButton'				=> 'Reset',
	'RestoreButton'				=> 'Ripristina',
	'SaveButton'				=> 'Salva',
	'SearchButton'				=> 'Cerca',
	'SendButton'				=> 'Invia',
	'SetButton'					=> 'Imposta',
	'SubmitButton'				=> 'Invia',
	'UpdateButton'				=> 'Aggiorna',

	'FormInvalid'				=> 'Il modulo inviato non è valido. Riprova.',
	'UnitPixel'					=> 'px',
	'Number'					=> 'Numero',

	// logged in panel
	'AccountText'				=> 'Account',
	'AccountTip'				=> 'Impostazioni Account',
	'AdminText'					=> 'Amministratore',
	'AdminTip'					=> 'Pannello Amministrativo',
	'LogoutLink'				=> 'Esci',
	'LogoutButton'				=> 'Log out',
	'LogoutAreYouSure'			=> 'Vuoi davvero uscire?',

	// registration panel
	'RegistrationWelcome'		=> 'Nuova registrazione utente:',
	'RegistrationButton'		=> 'Registrami',
	'UserNameOwned'				=> 'Questo nome utente è già registrato. Si prega di sceglierne un altro.',
	'SiteRegistered'			=> 'Ti sei registrato con successo sul sito %1.',
	'RegistrationEmailInfo'		=> 'Un indirizzo email valido. Tutte le email del sistema verranno inviate a questo indirizzo. L\'indirizzo email non è reso pubblico e sarà utilizzato solo se si desidera ricevere una nuova password o se si desidera ricevere determinate notizie o notifiche via e-mail.',
	'EmailConfirmHint'			=> 'Si prega di confermare il proprio indirizzo e-mail cliccando sul link nelle istruzioni inviate. <br>Se non verifichi il tuo indirizzo email, non sarai in grado di recuperare una possibile password persa. <br>Inoltre non ti verrà notificato alcun cambiamento di pagina recente e commenti.',
	'EmailConfirmRequired'		=> 'Senza l\'indirizzo e-mail confermato non ti sarà permesso di effettuare il login.',
	'NameTooShort'				=> 'Il nome utente è troppo breve, è richiesto un minimo di caratteri %2.',
	'NameTooLong'				=> 'Il nome utente è troppo lungo, è consentito un massimo di caratteri %2.',
	'NameAlphanumOnly'			=> 'Il nome utente deve essere lungo tra i caratteri %1 e %2 e usare solo caratteri alfanumerici. I caratteri maiuscoli sono OK.',
	'NameCamelCaseOnly'			=> 'Il nome utente deve essere compreso tra i caratteri %1 e %2 e il formato di WikiName.',
	'NewUserAccount'			=> 'nuovo account utente',

	'NewAccountSubject'			=> 'Registrazione account',
	'NewAccountAdminCreated'	=> 'L\'utente %1 ha creato un account per te con nome utente "%2". Per completare la registrazione, visita il seguente URL (assicurati che sia inserito come singola riga) e imposta la tua password di accesso:',
	'NewAccountUsername'		=> 'Utente:',
	'AccountLanguage'			=> 'Lingua:',
	'NewAccountEmail'			=> 'Email:',
	'NewAccountIP'				=> 'Indirizzo IP remoto:',
	'NewAccountSignupInfo'		=> 'Il seguente account è stato creato:',

	'UserWaitingApproval'		=> 'Un\'email è stata inviata all\'amministratore del sito. L\'amministratore riesaminerà le informazioni che sono state presentate e approverà o negherà la richiesta.',
	'UserRequiresApproval'		=> 'Per approvare o negare l\'accesso a questo utente a %1 vai al pannello amministratore.',
	'UserApprovalInfo'			=> 'Dopo la registrazione, la tua richiesta verrà inviata all\'amministratore del sito per approvazione. Riceverai un\'email con ulteriori istruzioni.',
	'UserApprovalHint'			=> 'L\'attivazione riuscita del tuo account sarà annunciata in una specifica e-mail. Fino ad allora non è possibile effettuare il login.',

	'UserApprovalPending'		=> 'Il tuo account è ancora in attesa di approvazione.',
	'UserApprovalDenied'		=> 'Al tuo account è stato negato l\'accesso a questo sito.',

	'RegistrationApproved'		=> 'Registrazione Approvata',
	'RegistrationDenied'		=> 'Registrazione Negata',
	'PendingApproval'			=> 'Approvazione In Attesa',

	'UserApprovedInfo'			=> 'Sei stato approvato per accedere a %1.',
	'UserDeniedInfo'			=> 'Ti è stato negato l\'accesso a %1.',

	'RegistrationThreshold'		=> 'Il tempo per compilare il modulo non dovrebbe essere inferiore a %1 secondi.',
	'Language'					=> 'Lingua',

	// login panel
	'LoginWelcome'				=> 'Accedi',
	'CreateAccount'				=> 'Crea un nuovo account',
	'RegistrationLink'			=> 'Registrazione',
	'LoginName'					=> 'Username',
	'Password'					=> 'Password',
	'LoginButton'				=> 'Accedi',
	'LoginLink'					=> 'Accedi',
	'PersistentCookie'			=> 'Rimani connesso',
	'Session'					=> 'Sessione',
	'SessionTip'				=> 'parametri della sessione corrente',
	'SessionDuration'			=> 'Durata sessione',
	'SessionDurationSession'	=> 'sessione del browser',
	'SessionDurationDay'		=> '1 giorno',
	'SessionDurationWeek'		=> '1 settimana',
	'SessionDurationMonth'		=> '1 mese',
	'LoggedInAs'				=> 'Hai effettuato l\'accesso come',

	'ClearCookies'				=> 'Elimina tutti i cookie',
	'BindSessionIp'				=> 'Associa la sessione all\'indirizzo IP',
	'BindSessionIpOn'			=> 'abilitato (IP attuale %1)',
	'TrafficProtection'			=> 'Protezione Del Traffico',
	'SessionEnds'				=> 'La sessione corrente finisce',
	'LastVisit'					=> 'L\'ultima visita è stata registrata',

	'LoginIncorrect'			=> 'Il nome utente o la password che hai inserito non sono validi.',
	'WelcomeBack'				=> 'Bentornato, %1',
	'LoginAttemptsExceeded'		=> 'Hai superato il numero massimo consentito di tentativi di accesso.<br>Oltre al tuo nome utente e alla tua password devi anche risolvere il CAPTCHA qui sotto.',

	// session notice
	'IPAddressChanged'			=> 'Indirizzo IP cambiato in %1 (era %2)',

	'SessionReplay'				=> 'Sessione terminata a causa del riproduzione.',
	'SessionObsolete'			=> 'La sessione è obsoleta.',
	'SessionExpired'			=> 'La sessione è scaduta.',
	'SessionTimeout'			=> 'Sessione terminata a causa di timeout.',
	'SessionInactivity'			=> 'Sessione terminata a causa di inattività.',
	'SessionUaChange'			=> 'Sessione terminata a causa del cambiamento dell\'agente utente.',
	'SessionTLSChange'			=> 'Sessione terminata a causa del cambiamento TLS.',
	'SessionIPChange'			=> 'Sessione terminata a causa di modifiche IP.',

	// other
	'Guest'						=> 'Ospite',
	'Everybody'					=> 'Tutti',
	'Help'						=> 'Aiuto',
	'TopicSearchText'			=> 'Cerca solo nei titoli',
	'WordprocessorVersion'		=> 'Versione processore Word',

	// notifications
	'EmailHello'				=> 'Ciao ',
	'EmailModerator'			=> 'Moderatore',
	'WatchedPageChanged'		=> 'Pagina modificata ',
	'SomeoneChangedThisPage'	=> ' ha cambiato una pagina che stai guardando: ',
	'NewPageCreatedSubj'		=> 'Una nuova pagina',
	'NewPageCreatedBody'		=> 'L\'utente %1 ha creato una nuova pagina: ',
	'FileUploadedSubj'			=> 'Un nuovo file',
	'FileUploadedBody'			=> 'L\'utente %1 ha caricato un nuovo file: ',
	'FileReplacedBody'			=> 'L\'utente %1 ha sostituito il file: ',

	'ActionDenied'				=> 'L\'azione è negata qui.',
	'TocTitle'					=> 'Contenuti ',
	'OuterLink2'				=> 'Collegamento in uscita',
	'FileLink'					=> '',
	'PDFLink'					=> 'Documento PDF',
	'RDFLink'					=> 'Documento RDF',
	'EmailLink'					=> 'Scrivi un\'email (avvio del client di posta)',
	'JabberLink'				=> 'Chatta via XMPP (avvio client Jabber)',
	'PermaLink'					=> 'Permalink',
	'PermaLinkTip'				=> 'Link permanente a questa revisione della pagina',
	'PermaLink0Tip'				=> 'Link permanente a questa pagina',

	'ShowTip'					=> 'Ritorno in modalità visualizzazione',
	'ShowText'					=> 'Visualizza',
	'WikieditAutocomplete'		=> 'Completa wikilink di Ctrl+Spazio',
	'WikiEditInactiveJs'		=> 'Per poter utilizzare WikiEdit, abilita JavaScript nel tuo browser.',
	'NumerateLinks'				=> 'Numerare i collegamenti nella vista di stampa',
	'Comment'					=> 'Commento',
	'Comments0'					=> 'Aggiungi il tuo commento',
	'Comments1'					=> 'Leggi commento (1 commento)',
	'CommentsN'					=> 'Leggi i commenti (commenti%1)',
	'Comments'					=> 'Commenti',
	'CommentHint'				=> '<a href="%1">Accedi</a> o <a href="%2">crea un account</a> per pubblicare un commento.',
	'CommentEdited'				=> 'modificato',
	'Links'						=> 'Collegamenti',
	'Version'					=> 'Versione',

	// details formatter
	'ShowHideDetails'			=> 'Dettagli',

	'PrivacyPolicy'				=> 'Politica Sulla Privacy',
	'TermsOfUse'				=> 'Termini di utilizzo',
	'AcceptTermsOfUse'			=> 'Ho letto, compreso e accettato i Termini di Servizio del sito.',

	'ShowComments'				=> 'Visualizza commenti / modulo',
	'HideComments'				=> 'Nascondi commenti / modulo',
	'AddComment'				=> 'Allega un commento a questa pagina:',
	'AddCommentTitle'			=> 'Denominazione del commento:',
	'CommentTitleRe'			=> 'Re:',
	'AddCommentButton'			=> 'Allega Commento',
	'HereLink'					=> 'qui',
	'PageHandlerMoreTip'		=> 'altro',

	'ThemeCorrupt'				=> 'Tema corrotto',
	'InvalidNamespace'			=> 'Namespace fornito non valido.',
	'DoesNotExists'				=> 'Questa pagina non esiste.',
	'PromptCreate'				=> 'Forse vuoi <strong><a href="%1">creare</a></strong>?',
	'RevisionHint'				=> 'Questa è una vecchia revisione di <a href="%1">%2</a> da %3 modificata da %4.',
	'ReadAccessDenied'			=> 'Non ti è permesso leggere questa pagina.',
	'ReadAccessDeniedHintGuest'	=> 'Per leggere questa pagina, dovresti effettuare il login.',
	'PageDeletedInfo'			=> 'Questa pagina è stata cancellata.',
	'RevisionDeletedInfo'		=> 'Questa revisione è stata eliminata.',
	'CommentDeletedInfo'		=> 'Questo commento è stato eliminato.',

	'LastEditedBy'				=> 'Ultima modifica da',
	'YouAreOwner'				=> 'Sei il proprietario di questa pagina.',
	'Owner'						=> 'Proprietario:',
	'Nobody'					=> 'Nessuno',
	'TakeOwnership'				=> 'Prendi La Proprietà',
	'FilesTip'					=> 'Gestisci i file allegati',
	'FilesText'					=> 'Allegati',
	'DeleteTip'					=> 'Elimina pagina, i suoi file e commenti',
	'DeleteCommentTip'			=> 'Elimina commento',
	'DeleteText'				=> 'Elimina',
	'AclText'					=> 'Permessi',
	'AclTip'					=> 'Modifica Permessi',

	'PropertiesText'			=> 'Proprietà',
	'PropertiesTip'				=> 'Modifica Proprietà Pagina',
	'EditTip'					=> 'Modifica questa pagina.',
	'EditText'					=> 'Modifica',
	'EditSection'				=> 'Modifica sezione %1',
	'EditSectionHint'			=> 'Sezione %1 di %2',
	'SectionHeadline'			=> 'Sezione',
	'EditCommentTip'			=> 'Modifica commento',
	'EditComment'				=> 'Modifica questo commento',
	'ReplyComment'				=> 'Rispondi',
	'ReplyCommentTip'			=> 'Rispondi a questo commento',
	'RevisionTip'				=> 'Visualizza revisioni della pagina',
	'RevisionText'				=> 'Revisioni',
	'ReferrersTip'				=> 'Visualizza un elenco di URL relativi a questa pagina',
	'ReferrersText'				=> 'Referenti',
	'ModerateTip'				=> 'Moderazione di argomenti e post del forum',
	'ModerateText'				=> 'Moderato',
	'SearchText'				=> 'Cerca: ',

	'AclUpdated'				=> 'Elenco di controllo di accesso aggiornato',
	'AclGaveOwnership'			=> ' e ha dato proprietà ad %1.',
	'AclNoNewOwner'				=> 'La proprietà della pagina non è stata trasferita, perché l\'utente %1 non è stato trovato.',
	'NewPageOwnership'			=> 'Proprietà della pagina trasferita',
	'YouAreNewOwner'			=> 'ex proprietario %1 ha trasferito la proprietà ' . "\n" . 'della seguente pagina a te',
	'PageOwnershipInfo'			=> '',
	'AclRead'					=> 'Leggi:',
	'AclWrite'					=> 'Scrivi:',
	'AclComment'				=> 'Osservazioni:',
	'AclCreate'					=> 'Creazione:',
	'AclUpload'					=> 'Caricamento:',
	'AclFor'					=> 'Liste di controllo accessi per %1',
	'SetOwner'					=> 'Imposta Proprietario:',
	'OwnerDontChange'			=> 'Non cambiare',
	'AclAccessDenied'			=> 'Non sei il proprietario di questa pagina.',
	'AclSyntaxError'			=> 'Errore sintassi elenco controllo accesso',
	'AclHelp'					=> '<code>*</code> - a tutti è consentito<br>' .
									'<code>$</code> - solo gli utenti registrati<br>' .
									'<code>!</code> - un precedente punto esclamativo nega il rispettivo diritto<br>' .
									'<code>[UserName]</code> - nomi degli utenti autorizzati<br>' .
									'<code>[GroupName]</code> - nomi del gruppo di utenti autorizzato (alias)<br>' .
									'<code>(una lista vuota)</code> - solo il proprietario della pagina ha accesso',

	'AccessMode'				=> 'Visibilità',
	'AccessDenied'				=> 'negato',
	'AccessPublic'				=> 'pubblico',
	'AccessRegistered'			=> 'registrato',
	'AccessPrivate'				=> 'privato',
	'AccessCustom'				=> 'personalizzato',

	// purge handler
	'PurgePage'					=> 'Purge page',
	'NotOwnerAndCantPurge'		=> 'Non sei il proprietario della pagina e non puoi eliminarla.',
	'ReallyPurge'				=> 'ATTENZIONE: Purgare la pagina è irreversibile!',
	'SelectPurgeOptions'		=> 'Selezionare le opzioni di eliminazione necessarie:',
	'PurgeComments'				=> 'Elimina tutti i commenti della pagina',
	'CommentsPurged'			=> 'Tutti i commenti sono stati eliminati.',
	'PurgeFiles'				=> 'Rimuove tutti i file allegati',
	'FilesPurged'				=> 'Tutti i file allegati sono stati rimossi.',
	'PurgeRevisions'			=> 'Elimina tutte le revisioni della pagina',
	'RevisionsPurged'			=> 'Le revisioni sono state eliminate.',
	'PurgeButton'				=> 'Purge',

	// categories handler
	'Categories'				=> 'Categorie',
	'CategoriesAssign'			=> 'assegna',
	'CategoriesEdit'			=> 'modifica',
	'Category'					=> 'Categoria',
	'CategoriesFor'				=> 'Categorie per',
	'CategoriesTip'				=> 'Modifica categorie',
	'CategoriesText'			=> 'Categorie',
	'CategoriesUpdated'			=> 'Categorie aggiornate',
	'CategoriesAlreadyExists'	=> 'Categoria %1 esiste già.',
	'CategoriesAdded'			=> 'Categoria %1 aggiunta con successo.',
	'CategoriesRenamed'			=> 'Categoria rinominata con successo.',
	'CategoriesUngrouped'		=> 'Categoria debundled con successo.',
	'CategoriesGrouped'			=> 'La categoria inserita nel nuovo gruppo.',
	'NoMultilevelGrouping'		=> 'Le categorie di raggruppamento multilivello non sono possibili.',
	'CategoriesDeleted'			=> 'La categoria è stata eliminata dal database e da tutte le pagine.',
	'CategoriesAdd'				=> 'Aggiungi una nuova categoria',
	'CategoryDescription'		=> 'Descrizione',
	'CategoriesAddGrouped'		=> 'Raggruppato con la categoria',
	'CategoriesAddGroupedNo'	=> 'Nessun gruppo.',
	'CategoriesRename'			=> 'Rinomina la categoria %1 in',
	'CategoriesRenameInfo'		=> '* Nota: il cambiamento influenzerà tutte le pagine assegnate a quella categoria.',
	'CategoriesGroup'			=> 'Gruppo categorie %1 con',
	'CategoriesGroupInfo'		=> '* Seleziona [nessun gruppo] per debundle la categoria.',
	'CategoriesNoGroup'			=> '[nessun gruppo]',
	'CategoriesDelete'			=> 'Sei sicuro di voler rimuovere la categoria %1?',
	'CategoriesDeleteInfo'		=> '* Nota: il cambiamento influenzerà tutte le pagine assegnate a quella categoria. Se la parola ha una sottocategoria, non verranno cancellate, ma solo scollegate.',
	'CategoriesStoreInfo'		=> 'Per assegnare le categorie a una pagina, selezionare le caselle di controllo.',
	'CategoriesStoreButton'		=> 'Salva Categorie',
	'CategoriesGroupButton'		=> 'Gruppo',
	'CategoriesEditInfo'		=> 'Per modificare l\'elenco delle categorie selezionare il pulsante di scelta rapida.',
	'NoCategoriesForThisLang'	=> 'Le categorie per questa lingua non sono specificate.',
	'PagesCategory'				=> 'Categoria pagine',
	'CategoryNotExists'			=> 'La categoria non esiste.',
	'CategoryEmpty'				=> 'Categoria vuota.',
	'NoCategorySelected'		=> 'Nessuna categoria selezionata.',
	'NoCategoriesAssigned'		=> 'Nessuna categoria assegnata per questa lingua.',
	'TagCloud'					=> 'Tag Cloud',
	'PagesTaggedWith'			=> '%1 pagine taggate con %2',
	'CategoriesOfCluster'		=> 'di cluster',
	'TaggedWithTip'				=> 'mostra pagine taggate %1',

	// source handler
	'SourceText'				=> 'Fonte',
	'SourceTip'					=> 'Visualizza la sorgente wiki',
	'SourceCopyToClipboard'		=> 'copia negli appunti',
	'SourceFor'					=> 'Visualizza sorgente per %1',

	// Groups action
	'GroupsSearch'				=> 'Trova Gruppi',
	'GroupsNoMatching'			=> 'Gruppi di corrispondenza non trovati. Prova un criterio di ricerca meno severo.',
	'GroupsOpenProfile'			=> 'Visualizza Profilo',
	'GroupsName'				=> 'Gruppo',
	'GroupsMembers'				=> 'Membri',
	'GroupsDescription'			=> 'Descrizione',
	'GroupsCreated'				=> 'Creato',
	'GroupsNotFound'			=> 'Gruppo %2 non trovato. Clicca <a href="%1">qui</a>per andare alla lista principale.',
	'GroupsProfile'				=> 'Profilo',
	'GroupsList'				=> 'Visualizza l\'intero elenco dei gruppi',
	'GroupSpace'				=> 'Spazio di gruppo',

	'MetaUpdated'				=> 'Meta dati aggiornati',

	'PreviewButton'				=> 'Anteprima',
	'Preview'					=> 'Anteprima',
	'Chars'						=> 'caratteri',
	'PageBody'					=> 'Corpo della pagina',
	'EditNote'					=> 'Modifica riepilogo',
	'EditNoteMissing'			=> 'Modifica riepilogo mancante',
	'EditMinor'					=> 'Modifica minore',
	'MinorEditHide'				=> 'Nascondi modifica minore',
	'MinorEditShow'				=> 'Mostra modifica minore',
	'PostAnonymously'			=> 'Pubblica anonimamente senza dare il tuo nome',
	'NotifyMe'					=> 'Avvisami nuovi commenti e modifiche della pagina',
	'OverwriteAlert'			=> 'ALERTÀ DI SOVERWRITE: Questa pagina è stata modificata da qualcun altro durante la modifica.<br>Copiare le modifiche e ri-modificare questa pagina.',
	'TextDbOversize'			=> 'Attenzione: il tuo testo supera il limite di lunghezza di caratteri %1 . Si prega di accorciare il testo con un numero accettabile di caratteri. Suggerimento: è possibile posizionare il testo rimanente su una pagina separata.',
	'EditingRevisionWarning'	=> 'Stai modificando una vecchia revisione di questa pagina. Se la pubblichi, le modifiche apportate da allora verranno rimosse. <br>Si potrebbe voler modificare la revisione corrente.',
	'WriteAccessDenied'			=> 'Non hai accesso in scrittura a questa pagina.',
	'EmptyPage'					=> 'Il corpo della pagina era vuoto - non salvato!',
	'EmptyComment'				=> 'Il corpo del commento è vuoto - non salvato!',
	'CommentAccessDenied'		=> 'Siamo spiacenti, non hai il permesso di inviare commenti a questa pagina.',
	'CommentFlooded'			=> 'L\'intervallo tra la pubblicazione dei post non deve essere inferiore a %1 secondi.',
	'CommentAdded'				=> 'Commento aggiunto.',
	'YouAreNowTheOwner'			=> 'Ora sei il proprietario di questa pagina.',
	'PageSaved'					=> 'Versione pagina %1 salvata.',
	'CommentSaved'				=> 'Commento salvato.',

	'RevisionsFor'				=> 'Revisioni per %1',
	'DefaultDiffMode'			=> 'Modalità diff predefinita',
	'DiffMode'		=> [
		'0'		=> 'Diff completo',
		'1'		=> 'Diff semplice',
		'2'		=> 'Fonte',
		'3'		=> 'Lato a fianco',
		'4'		=> 'Incorporato',
		'5'		=> 'Fusione',
		'6'		=> 'Unificato',
		'7'		=> 'Contesto',
	],

	'PreviousEdit'				=> 'Modifica precedente',
	'NextEdit'					=> 'Prossima modifica',

	'Diff'						=> 'Diff',
	'PreviousVersion'			=> 'Revisione precedente',
	'LatestVersion'				=> 'Ultima revisione',
	'NextVersion'				=> 'Prossima revisione',

	'ShowDifferencesButton'		=> 'Mostra Differenze',
	'CancelReturnButton'		=> 'Annulla e torna alla pagina',
	'Comparison'				=> 'Differenza tra le revisioni per %1',
	'RevisionAsOf'				=> 'Revisione %1 come di',
	'SimpleDiffAdditions'		=> 'Aggiunzioni:',
	'SimpleDiffDeletions'		=> 'Eliminazioni:',
	'NoDifferences'				=> 'Nessuna differenza.',
	'ReEditOldRevision'			=> 'Ri-modifica questa vecchia revisione',

	'ExternalPages'				=> 'Pagine esterne che collegano %1 (%2) (<a href="%3">vedi elenco dei domini</a>):',
	'ExternalPagesGlobal'		=> 'Siti che collegano a questo WackoWiki (%2) (<a href="%1">vedi elenco di domini</a>):',
	'Last24Hours'				=> 'ultime 24 ore',
	'LastDays'					=> 'last %1 days',
	'DomainsSitesPages'			=> 'Pagine di dominio/siti che collegano ad  %1 (%2) (<a href="%3">vedi elenco di diversi URL</a>):',
	'DomainsSitesPagesGlobal'	=> 'Domani/siti che collegano a questo WackoWiki (<a href="%1">vedi elenco di diversi URL</a>):',
	'ViewReferrersPage'			=> 'alla pagina',
	'ViewReferrersPerPage'		=> 'per pagina',
	'ViewReferrersByTime'		=> 'per ora',
	'ViewReferrersGlobal'		=> 'globale',
	'NoneReferrers'				=> 'Nessuno',
	'NotOwnerCantDelete'		=> 'Non sei proprietario di questa pagina e non puoi eliminarla',

	// remove
	'RemovePage'				=> 'Rimuovi pagina',
	'RemoveRevision'			=> 'Rimuovi revisione',
	'RemoveComment'				=> 'Elimina commento',
	'RemoveCluster'				=> 'Rimuovi tutte le pagine del cluster',
	'RemoveDontKeep'			=> 'Non salvare una copia di una pagina e commenti rimossi',
	'RemoveDontKeepRevision'	=> 'Non salvare una copia della revisione rimossa',
	'RemoveDontKeepComment'		=> 'Non salvare una copia del commento rimosso',
	'RemoveDontKeepFile'		=> 'Non salvare una copia del file rimosso',
	'ReferrersRemoved'			=> 'Segnalatori rimossi.',
	'LinksRemoved'				=> 'Link rimossi.',
	'CategoriesRemoved'			=> 'Categorie di pagine cancellate.',
	'AclsRemoved'				=> 'Pagine acls rimosse.',
	'BookmarksRemoved'			=> 'Segnalibri rimossi.',
	'WatchesRemoved'			=> 'Orologi rimossi.',
	'CommentsRemoved'			=> 'Commenti dalla pagina rimossa.',
	'FilesRemoved'				=> 'File dalla pagina rimossa.',
	'PageRemoved'				=> 'Pagina rimossa.',
	'PageCachePurged'			=> 'Cache eliminata.',
	'ClusterRemoved'			=> 'Tutte le pagine del cluster rimosse.',
	'RevisionRemoved'			=> 'Revisione %1 rimossa.',
	'RevisionsRemoved'			=> 'Revisioni rimosse.',
	'ActionHaveNoUndo'			=> 'Questa azione non può essere annullata.',

	// restore
	'PageRestored'				=> 'Pagina ripristinata.',
	'RevisionRestored'			=> 'Revisione ripristinata.',
	'LocalFilesRestored'		=> 'File locali ripristinati.',

	'PrintVersion'				=> 'Stampa versione',
	'PrintText'					=> 'Stampa',
	'LinkedPages'				=> 'Pagine collegate:',
	'NoLinkedPages'				=> 'Non ci sono pagine collegate',
	'ReferringPages'			=> 'Pagine di riferimento:',
	'NoReferringPages'			=> 'Non ci sono pagine di riferimento',
	'Footnotes'					=> 'Note A Piè',
	'Footnote'					=> 'Nota',
	'MostPopularPages'			=> 'Pagine più popolari',
	'MostCommentedPages'		=> 'Pagine più commentate',
	'NoAccessToSourcePage'		=> 'Non è consentito leggere la pagina sorgente dell\'azione.',
	'SourcePageDoesntExist'		=> 'La pagina di origine dell\'azione non esiste ancora',
	'NotLoggedInThusEdited'		=> 'Non sei loggato, quindi non siamo riusciti a identificare le pagine che hai modificato.',
	'DidntEditAnyPage'			=> 'Non hai ancora modificato nessuna pagina.',
	'NoPagesFound'				=> 'Nessuna pagina trovata.',
	'MyChangesTitle1'			=> 'Questa è la lista delle pagine che hai modificato, ordinate al momento della tua ultima modifica',
	'MyChangesTitle2'			=> 'Questa è la lista delle pagine che hai modificato, insieme all\'ora della tua ultima modifica',
	'OrderABC'					=> 'alfabeticamente',
	'OrderCreation'				=> 'per creazione',
	'OrderChange'				=> 'per modifica',
	'ListOwnedPages'			=> 'Questa è la lista delle pagine che possiedi (ordinate alfabeticamente)',
	'ListOwnedPages2'			=> 'Questa è la lista delle pagine che possiedi (ordinate per data)',
	'ListOwnedPages3'			=> 'Questa è la lista delle pagine che possiedi (ordinate per cambiamento)',
	'NotLoggedInThusOwned'		=> 'Non hai effettuato l\'accesso, quindi non abbiamo potuto recuperare le tue pagine.',
	'NoOrphaned'				=> 'Nessuna pagina orfana. Bene.',
	'NoRecentComments'			=> 'Nessun commento recente.',
	'LatestCommentBy'			=> 'ultimo commento di',
	'NoRecentlyCommented'		=> 'Nessuna pagina commentata di recente.',
	'NoDeletedPages'			=> 'Nessuna pagina eliminata trovata.',
	'NoDeletedRevisions'		=> 'Nessuna revisione eliminata trovata.',
	'NoDeletedFiles'			=> 'Nessun file cancellato trovato.',
	'CommentsDisabled'			=> 'I commenti non sono disponibili.',

	'SearchResults'				=> 'Risultati della ricerca per ',
	'NotFound'					=> 'non trovato',
	'NoResultsFor'				=> 'Nessun risultato per ',
	'SearchFor'					=> 'Cerca per:',
	'TopicSearchResults'		=> 'Risultati ricerca argomenti per ',
	'NotFoundInTopics'			=> 'non trovato negli argomenti',
	'FilterLangNotAvailable'	=> 'La lingua selezionata non è disponibile!',

	'PostedBy'					=> 'pubblicato da',
	'ThisIsCommentOn'			=> 'Questo è un commento su',
	'At'						=> 'a',
	'To'						=> 'a',
	'By'						=> 'di',
	'From'						=> 'da',
	'For'						=> 'per',
	'ReturnToCommented'			=> 'Torna alla pagina commentata',
	'AbandonedComment'			=> 'La pagina a cui questo commento appartiene non esiste più!',

	'PagesLinkingTo'			=> 'Pagine collegate a',
	'NoPageLinkingTo'			=> 'Nessuna pagina si sta collegando a',
	'NoWantedPages'				=> 'Nessuna pagina desiderata. Bene.',
	'RemoveWatch'				=> 'Rimuovi l\'orologio per questa pagina',
	'SetWatch'					=> 'Guarda questa pagina',
	'WatchText'					=> 'Osserva',
	'UnwatchText'				=> 'Non seguire',
	'UserSettingsStored'		=> 'Impostazioni utente salvate.',
	'LoggedOut'					=> 'Ora sei disconnesso.',
	'LoggedOutAuto'				=> 'Per sicurezza, la sessione è terminata. Effettua nuovamente il login.',

	// user settings
	'EmailConfirmResent'		=> 'Codice di conferma email inviato al tuo indirizzo.',
	'EmailConfirmNotSent'		=> 'Impossibile inviare il codice di conferma: l\'email non è specificata!',
	'Hello'						=> 'Ciao',
	'UserName'					=> 'Nome utente',
	'EmailAddress'				=> 'Indirizzo email',
	'RealName'					=> 'Nome reale',
	'MenuItemsShown'			=> 'Voci di menu mostrate',
	'RecordsPerPage'			=> 'Record per pagina',
	'DoShowComments'			=> 'Mostra commenti per impostazione predefinita',
	'DoubleclickEditing'		=> 'Modifica Doubleclick',
	'UpdateSettingsButton'		=> 'Aggiorna Impostazioni',

	'AccountDisabled'			=> 'Il tuo account potrebbe essere disabilitato o bloccato.',
	'WrongPassword'				=> 'Password errata!',
	'ConfirmPassword'			=> 'Conferma password',
	'Email'						=> 'Indirizzo email',
	'MustBeWikiName'			=> 'Il nome utente deve essere formattato <a href="https://wackowiki.org/doc/Doc/English/WikiName" target="_blank">WikiName</a>!',
	'SpecifyEmail'				=> 'Devi specificare un indirizzo email.',
	'NotAEmail'					=> 'Non sembra un indirizzo email valido.',
	'EmailTaken'				=> 'L\'indirizzo email inserito è già in uso.',
	'EmailDomainNotAllowed'		=> 'L\'indirizzo email inserito %1 non è nell\'elenco dei domini consentiti.',
	'PasswordsDidntMatch'		=> 'Le password non corrispondono.',
	'SpacesArentAllowed'		=> 'Gli spazi non sono ammessi nelle password.',
	'ListMyPages'				=> 'Elenca le tue pagine',
	'ListMyChanges'				=> 'Elenca le tue modifiche',
	'ListMyWatches'				=> 'Elenco delle pagine guardate',
	'ListMyChangesWatches'		=> 'Modifiche tra le pagine guardate',
	'SeeListOfPages'			=> 'Vedi un elenco delle pagine che possiedi (MyPages) e delle pagine che hai modificato (MyChanges).',
	'AddBookmark'				=> 'Aggiungi pagina corrente ai segnalibri',
	'RemoveBookmark'			=> 'Rimuovi dai segnalibri',

	'YourLanguage'				=> 'Seleziona lingua',
	'ShowSpaces'				=> 'Mostra gli spazi in WikiNames',
	'WrongPage4Redirect'		=> 'Impossibile reindirizzare a causa di un parametro di reindirizzamento sbagliato',
	'RedirectsToItself'			=> 'La pagina reindirizza a se stessa.',
	'ReallyDeletePage'			=> 'Vuoi davvero eliminare questa pagina?<br>Non c\'è annullamento per questa azione!<br><br>ATTENZIONE: L\'eliminazione di questa pagina cancellerà tutte le versioni della pagina, i commenti, gli allegati, gli ACL e i referrer.',
	'CommentForWatchedPage'		=> 'Nuovo commento per la pagina ',
	'SomeoneCommented'			=> ' ha commentato questa pagina che stai guardando: ',
	'AlertReferringPages'		=> 'Questa pagina è richiamata da queste pagine',

	'AccountDelete'				=> 'Elimina account',
	'AccountDeleteConfirm'		=> 'Sei sicuro di voler eliminare l\'account?',
	'AccountDeleted'			=> 'Account eliminato con successo',
	'AccountDeleteHeader'		=> 'Elimina account %1',
	'AccountDeleteInfo'			=> 'Dei dati che hai creato (ad esempio email, preferenze, allegati, voci wiki) per quanto possibile verranno eliminati. Notare, tuttavia, che dati come allegati e voci wiki non possono essere eliminati senza ostacolare il lavoro degli altri utenti. Tali dati vengono quindi riassegnati a un account chiamato %1. Poiché i dati di ogni account eliminato vengono riassegnati a questo account, non sarà possibile distinguere i dati creati dai dati di un altro account eliminato.',
	'AccountDeleteWarning'		=> 'L\'eliminazione dell\'account utente è un\'azione irreversibile.',
	'AccountDeleteHint'			=> 'Il tuo account verrà eliminato dal sistema. Pertanto, non sarai più in grado di accedere con le tue credenziali correnti. Se si sceglie di diventare nuovamente un utente di questa applicazione, è possibile farlo utilizzando i mezzi che questa applicazione concede.',
	'AccountDeleteVerify'		=> 'Inserisci il tuo login %1 per verificare l\'eliminazione. Una volta inviato, ti verrà chiesto di confermare la password.',

	'MarkRead'					=> 'Segna tutti come letti',
	'CurrentTime'				=> 'Attualmente è',
	'Created'					=> 'creato',
	'Modified'					=> 'modificato',

	'EditIcon'					=> 'modifica',
	'TreeClusterTitle'			=> 'Albero dell\'ammasso %1',
	'TreeSiteTitle'				=> 'Albero del sito',
	'TreeEmpty'					=> '%1 non ha sottopagine',
	'TreeEmptyLevels'			=> '%1 non ha sottopagine per determinati livelli di profondità. Aumenta il valore per la profondità.',
	'TreeTooBig'				=> 'troppe sottopagine',

	// clone handler
	'ClonePage'					=> 'Clona pagina',
	'CloneText'					=> 'Clona',
	'CloneName'					=> 'Inserisci un nuovo nome per un clone di questa pagina',
	'CloneButton'				=> 'Clona',
	'PageCloned'				=> 'Pagina %1 clonata.',
	'ClonedFrom'				=> 'Clonato da %1.',
	'MassClone'					=> 'Clona l\'intero cluster',
	'MassCloning'				=> 'Clonazione cluster.',
	'CloneCannotRead'			=> 'Pagina illeggibile %1.',
	'CloneCannotCreate'			=> 'Pagina %1 non creabile.',

	'SortComment'				=> 'Ordina i commenti per',
	'SortCommentAsc'			=> 'Più recenti in basso',
	'SortCommentDesc'			=> 'Più recente in alto',

	'RenamePage'				=> 'Rinomina pagina',
	'RenameText'				=> 'Rinomina',
	'RenameTip'					=> 'Rinomina pagina',
	'NewName'					=> 'Inserisci un nuovo nome per questa pagina',
	'AlreadyExists'				=> 'La pagina %1 esiste già.',
	'AlreadyNamed'				=> 'Questa pagina ha già chiamato %1.',
	'PageRenamed'				=> 'Pagina rinominata.',
	'NewNameOfPage'				=> 'Nuovo nome di questa pagina: ',
	'NotOwnerCantRename'		=> 'Non sei proprietario di questa pagina e quindi non puoi rinominarla',
	'NeedRedirect'				=> 'Crea un reindirizzamento alla nuova pagina nella vecchia pagina',
	'RedirectCreated'			=> 'Nella pagina %1 creato reindirizzamento al nuovo',

	'UserSettings'				=> 'Impostazioni utente',
	'UserSettingsGeneral'		=> 'Generale',
	'UserSettingsNotifications'	=> 'Notifiche',

	'NotifyMinorEdit'			=> 'Notifica anche modifiche minori',
	'NotifyPageEdit'			=> 'Modifica',
	'NotifyComment'				=> 'Commento',
	'NotifyOff'					=> 'Off',
	'NotifyAlways'				=> 'Sempre',
	'NotifyPending'				=> 'In Attesa',
	'NotifyDigest'				=> 'Digest',
	'NotifyPendingPageTip'		=> 'Viene inviata una sola notifica per la prima modifica della pagina di una pagina che stai guardando.',
	'NotifyPendingCommentTip'	=> 'Viene inviata una sola notifica per il primo commento a una pagina che stai guardando.',
	'NotifyPendingTip'			=> 'La notifica viene riattivata automaticamente quando si visita la versione corrente della pagina.',

	'FurtherPending'			=> 'Non ci saranno altre notifiche in caso di ulteriori modifiche a meno che non si visita questa pagina.',

	'UserSettingsEmailMe'		=> 'Inviami un\'email quando...',

	'UserSettingsExtended'		=> 'Esteso',
	'UserSettingsOther'			=> 'Altre impostazioni',
	'UserSpace'					=> 'Spazio utente',
	'ChooseTheme'				=> 'Scegli tema',

	'CreatePage'				=> 'Crea questa pagina',
	'CreateNewPage'				=> 'Crea una nuova pagina',
	'CreateNewPageText'			=> 'Crea',
	'CreateNewPageTip'			=> 'Crea una nuova pagina',

	'CreateRandomPage'			=> 'Crea una pagina casuale:',
	'CreateSubPage'				=> 'Crea una sotto-pagina nel cluster:',
	'CreatePageParentCluster'	=> 'Crea una pagina nel cluster genitore:',
	'CreatePageDenied'			=> 'Lei non ha i diritti di accesso necessari.',
	'CreatePageDeniedAddress'	=> 'Non hai il diritto di creare la pagina a questo indirizzo.',
	'PageAlreadyExists'			=> 'Secondo l\'indirizzo fornito la pagina %1 esiste già.',
	'PageAlreadyExistsEdit'		=> 'Vuoi %1?',
	'PageAlreadyExistsEdit2'	=> 'modifica',
	'PageAlreadyExistsEditDenied'	=> 'Non puoi modificarlo.',

	'SimilarPagesExists'		=> 'Pagine simili a %1 esiste già:',
	'SimilarPagesHint'			=> 'Ci sono pagine simili a %1 esistenti:',

	'PageReservedWord'			=> 'Non è possibile utilizzare %1 come parte dell\'indirizzo in quanto è una parola riservata.',
	'UserReservedWord'			=> 'I nomi utente non possono contenere %1 in quanto è una parola riservata.',

	'DontRedirect'				=> 'Non consentire il reindirizzamento automatico per azione Reindirizzamento.',
	'SendWatchEmail'			=> 'Invia email di notifica quando qualcuno (tranne te) cambia qualsiasi pagina che stai guardando',
	'AllowIntercom'				=> 'Consenti messaggi personali dagli utenti del sistema',
	'AllowMassemail'			=> 'Gli amministratori possono inviarmi le informazioni',
	'HideLastSession'			=> 'Nascondi l\'ultima sessione',
	'ValidateIP'				=> 'Collegamento sessione a IP',
	'AnonymousPub'				=> 'Preferibilmente, pubblicato in forma anonima (per nascondere il nome)',
	'PageMoved'					=> 'Questa pagina si è spostata. Puoi trovarla a',
	'RedirectedFrom'			=> 'Reindirizzato da %1',
	'RedirectedTo'				=> 'Reindirizzato a',
	'CurrentPassword'			=> 'Password attuale',
	'NewPassword'				=> 'Nuova password',
	'YouWantChangePassword'		=> 'Cambia password',
	'ChangePasswordButton'		=> 'Cambia password',
	'PasswordChanged'			=> 'Password modificata',
	'EmailWelcome'				=> 'Ti sei registrato a ',
	'EmailRegistered'			=> 'Ti sei registrato con successo alla %1.' . "\n" . 'Il tuo nome utente: %2' . "\n\n",
	'EmailVerify'				=> 'Se vuoi ricevere notifiche, devi verificare il tuo indirizzo email. Clicca su o copia il seguente link a un browser web: ' . "\n" . '%1',
	'EmailRegisteredLogin'		=> 'Torna al Wiki e accedi con il tuo nuovo nome utente e password.',
	'EmailRegisteredIgnore'		=> 'Se non hai richiesto questa registrazione, ignora questo messaggio e non accadrà nulla.',
	'EmailDoNotReply'			=> 'Non rispondere a questo messaggio.',
	'EmailReverify'				=> 'Qualcuno (forse tu) ha inviato la tua email come indirizzo di notifica su %1.' . "\n" . 'Il tuo nome utente: %2'."\n\n" . 'Se vuoi ricevere notifiche, devi approvare la tua email. Per favore, segui il link per farlo.' . "\n" . '%3' . "\n\n",
	'EmailConfirm'				=> 'Verifica la tua email',
	'EmailConfirmed'			=> 'Email confermata con successo.',
	'EmailNotConfirmed'			=> 'L\'email non può essere confermata. Questo potrebbe essere dovuto a un codice di conferma errato o l\'indirizzo email potrebbe già essere confermato. Puoi controllare se l\'indirizzo email è già confermato accedendo e visualizzando il suo stato sulla tua pagina %1.',
	'EmailNotVerified'			=> 'Email non verificata!',
	'EmailNotVerifiedDesc'		=> 'Non riceverai notifica di modifiche o commenti alle pagine osservate, ' .
									'o messaggi da altri utenti. Inoltre, <strong>non sarà in grado di recuperare una password dimenticata</strong>, ' .
									'fino a quando il tuo indirizzo email sarà confermato seguendo il link nell\'email che ti è stata inviata. ' .
									'Se, entro giorni dalla registrazione, non ricevi un\'email, chiedi di nuovo cliccando ',

	'ForgotPasswordHint'		=> 'Inserisci il tuo login e indirizzo email,' . "\n" . 'poi ti verrà inviata un\'email con le istruzioni.',
	'ForgotPassword'			=> 'Password dimenticata?',
	'UserNotFound'				=> 'Non è stato trovato un utente con questo nome o indirizzo email.',
	'NotConfirmedEmail'			=> 'Il tuo indirizzo email non è confermato. Il messaggio<br>non può essere inviato a un indirizzo non confermato.',
	'EmailForgotSubject'		=> 'Rinnovo password per ',
	'EmailForgotMessage'		=> 'Qualcuno (forse tu) ha dimenticato la tua password per %1.' . "\n" . 'Il tuo login: %2'."\n\n" . 'Fare clic sul link o copiarlo nella riga dell\'indirizzo del browser per modificare la password.' . "\n" . '%3'."\n\n",
	'CodeWasSent'				=> 'L\'istruzione di recupero password è stata inviata via e-mail.',
	'WrongCode'					=> 'Codice errato',
	'ChangePasswordForUser'		=> 'Modifica password di %1',

	'Watchers'					=> 'Elenco degli osservatori per %1',
	'WatchersFor'				=> 'Osservatori per',
	'NoWatchers'				=> 'Non ci sono osservatori per %1',
	'NotOwnerToViewWatchers'	=> 'Non sei il proprietario di questa pagina e non puoi vedere la lista degli osservatori per esso.',

	// thumbnail
	'TbnError'					=> 'Errore nel creare miniature: %1',
	'TbnImageAreaTooBig'		=> 'File con dimensioni maggiori di %1',
	'TbnImageMissing'			=> 'Il file sembra mancante: %1',

	// admin_recovery action
	'GenerateRecoveryHash'		=> 'Genera l\'hash della password per la tua <code>recovery_password</code>',

	// import action
	'ImportTo'					=> 'Importa nel cluster:',
	'ImportWhat'				=> 'File XML da importare:',
	'ImportButton'				=> 'Importa',
	'ImportSuccess'				=> 'Importato con successo.',
	'ImportFailed'				=> 'IMPORTAZIONE non riuscita.',
	'ImportHint'				=> 'Fornisci un cluster a cui vuoi importare, nessun indirizzo relativo.',
	'ImportAttention'			=> 'Attenzione: sovrascrive le stesse pagine nel cluster.',
	'ImportNote'				=> 'Pagina importata',

	// mywatches action
	'WatchedPages'				=> 'Elenco di tutte le pagine che segui per le modifiche ',
	'UnwatchedPages'			=> 'Elenco di tutte le pagine che non osservi',
	'NoWatchedPages'			=> 'Non hai pagine guardate.',
	'NoUnwatchedPages'			=> 'Si osservano le modifiche in tutte le pagine.',
	'ViewWatchedPages'			=> 'Mostra pagine guardate',
	'ViewUnwatchedPages'		=> 'Mostra pagina non vista',
	'NotLoggedInWatches'		=> 'Non sei connesso, quindi non siamo riusciti a identificare la tua lista di orologi.',

	// mychangeswatches action
	'MyChangesWatches'			=> 'Elenco di tutte le pagine che hai guardato che sono state modificate da altri dalla tua ultima modifica',
	'ResetChangesWatches'		=> 'reimposta l\'elenco delle modifiche',
	'NoChangesWatches'			=> 'Tra le pagine guardate non ci sono modifiche...',

	// whatsnew action
	'NewCommentAdded'			=> 'Aggiunto nuovo commento',
	'NewFileAdded'				=> 'Aggiunto nuovo file',
	'NewPageCreated'			=> 'Creata una nuova pagina',
	'NewRevisionAdded'			=> 'Pagina modificata',
	'Cluster'					=> 'cluster',
	'PageDeleted'				=> 'Pagina eliminata',
	'CommentDeleted'			=> 'Commento eliminato',
	'FileDeleted'				=> 'File eliminato',

	// users action
	'UsersSearch'				=> 'Trova Utenti',
	'UsersOpenProfile'			=> 'Visualizza Profilo',
	'UsersNoMatching'			=> 'Corrispondenza degli utenti non trovata. Prova un criterio di ricerca meno severo.',
	'UsersName'					=> 'Nome',
	'UsersPages'				=> 'Pagine',
	'UsersChanges'				=> 'Modifiche',
	'UsersSubscription'			=> 'Abbonamento',
	'UsersWatches'				=> 'Orologi',
	'UsersComments'				=> 'Commenti',
	'UsersUploads'				=> 'Caricamenti',
	'UploadQuota'				=> 'Spazio utilizzato',
	'UploadQuotaTip'			=> 'Carica Quota Spaziale',
	'UsersLogins'				=> 'Accessi',
	'UsersRevisions'			=> 'Revisioni',
	'UsersSignup'				=> 'Registrati',
	'UsersLastSession'			=> 'Ultima sessione',
	'UsersNotFound'				=> 'Utente %2 non trovato. Clicca <a href="%1">qui</a>per andare alla lista principale.',
	'UsersProfile'				=> 'Profilo',
	'UsersContact'				=> 'Contatto',
	'UsersList'					=> 'Visualizza l\'intero elenco degli utenti',
	'UsersNA'					=> '[non impostato]',
	'UsersNA2'					=> '[No]',
	'UsersSignupDate'			=> 'Data di iscrizione',
	'UsersGroupMembership'		=> 'Adesione di gruppo',
	'UsersPersonalInfo'			=> 'Informazioni personali',
	'UsersOwnedPages'			=> 'Pagine possedute:',
	'UsersCommentsPosted'		=> 'Commenti inviati:',
	'UsersFilesUploaded'		=> 'File caricati:',
	'UsersRevisionsMade'		=> 'Revisioni effettuate:',
	'UsersDocsSortName'			=> '[Ordina per nome]',
	'UsersDocsSortCreation'		=> '[Ordina per data di creazione]',
	'UsersChangesSortAsc'		=> '[Ordinamento crescente]',
	'UsersChangesSortDesc'		=> '[Ordina in discesa]',
	'UsersSessionNA'			=> '[non registrato]',
	'UsersSessionHidden'		=> '[hidden]',
	'IntercomSubject'			=> 'Oggetto:',
	'IntercomMessage'			=> 'Messaggio:',
	'IntercomCopy'				=> 'Inviami una copia',
	'IntercomSubjectN'			=> '[avvia un nuovo argomento]',
	'IntercomDisabled'			=> 'Siamo spiacenti, non vuoi o non puoi ricevere messaggi personali.',
	'IntercomHint'				=> 'Per favore accedi prima e segui nuovamente il link, se vuoi rispondere al messaggio personale che hai ricevuto.',
	'IntercomDesc'				=> 'Nota: Invio di messaggi personali effettuati sul destinatario dell\'email senza rivelare il tuo indirizzo. Il destinatario sarà in grado di rispondere a te, utilizzando un modulo simile sulla pagina del tuo profilo. ',
	'PMOversized'				=> 'La lunghezza del messaggio supera la dimensione massima consentita di %1. Si prega di accorciare il messaggio ed inviare di nuovo.',
	'PMFlooded'					=> 'L\'intervallo tra l\'invio di messaggi personali non deve essere inferiore a %1 secondi.',
	'PMSent'					=> 'Il messaggio personale è stato inviato con successo all\'utente.',
	'PMBody'					=> 'Questo messaggio è stato inviato dall\'utente %1.',
	'PMBodyCopy'				=> 'Hai inviato il seguente messaggio all\'utente %1.',
	'PMReply'					=> 'Per rispondere a questa email, fare clic sul seguente link (non utilizzare il pulsante Rispondi / Rispondi in mailer):',
	'PMNotLoggedIn'				=> 'Non sei registrato nel sistema e non puoi inviare messaggi personali agli utenti.',

	// admin_replace action
	'ReplaceText'				=> 'Sostituire il testo',
	'TextOriginal'				=> 'Testo originale:',
	'TextReplacement'			=> 'Testo sostitutivo:',
	'ReplaceTextRegex'			=> 'Usa espressioni regolari',
	'Namespace'					=> 'Namespace:',
	'ReplaceTextCluster'		=> 'Cerca e sostituisce solo all\'interno di questo cluster:',
	'ReplaceTextEditPages'		=> 'Sostituire il testo nel contenuto della pagina',
	'ReplaceTextEditComments'	=> 'Sostituire il testo nei commenti',
	'ReplaceTextEditTitles'		=> 'Sostituire il testo nei titoli della pagina',
	'ReplaceTextGiveTarget'		=> 'È necessario specificare la stringa da sostituire.',
	'ReplaceTextNoNamespace'	=> 'Devi selezionare almeno uno spazio dei nomi.',
	'ReplaceTextNoDifference'	=> 'Non c\'è differenza tra il testo di sostituzione e il testo di destinazione.',
	'ReplaceTextNoOption'		=> 'È necessario selezionare almeno una delle opzioni di sostituzione.',
	'ReplaceTextPagesEdit'		=> 'Sostituisci %1 con %2 nel testo delle seguenti pagine %3:',
	'ReplaceTextTitlesEdit'		=> 'Sostituisci %1 con %2 nei titoli delle seguenti pagine %3:',
	'ReplaceTextReplace'		=> 'Sostituisci',
	'ReplaceTextSuccess'		=> '%1 è stato sostituito con %2 in %3 pagine.',
	'ReplaceTextNoMatch'		=> 'Non sono state trovate pagine contenenti la stringa %1.',
	'ReplaceTextNoTitleMatch'	=> 'Non sono state trovate pagine che contengono %1.',
	'ReplaceTextEditFailed'		=> 'Sostituzione del testo non riuscita',
	'ReplaceTextTitleTooBig'	=> 'Il testo originale o sostitutivo è troppo grande per il titolo.',
	'ReplaceTextReturn'			=> 'Ritorna al modulo',
	'ReplaceTextWarning'		=> 'Attenzione: Ci sono pagine %1 che contengono già la stringa di sostituzione, %2. Se si effettua questa sostituzione non si sarà in grado di separare le sostituzioni da queste stringhe.',
	'ReplaceTextBlankWarning'	=> 'Attenzione: Poiché la stringa di sostituzione è vuota, questa operazione non sarà reversibile.',
	'ReplaceTextEditSummary'	=> 'Sostituzione testo: %1 → %2',
	'InvertSelection'			=> 'Inverti selezione',

	// Properties
	'PropertiesFor'				=> 'Proprietà della pagina per %1',
	'MetaTag'					=> 'Tag',
	'MetaTitle'					=> 'Titolo',
	'MetaKeywords'				=> 'Parole Chiave',
	'MetaDescription'			=> 'Descrizione',
	'On'						=> 'Acceso',
	'Off'						=> 'Off',
	'Registered'				=> 'Registrato',
	'MetaComments'				=> 'Mostra commenti',
	'MetaFiles'					=> 'Mostra pannello file',
	'MetaToc'					=> 'Mostra la tabella dei contenuti',
	'MetaIndex'					=> 'Mostra pannello sezione cluster',
	'MetaIndexMode'				=> 'Mostra Modalità Livello',
	'MetaIndexFull'				=> 'Albero',
	'MetaIndexUpper'			=> 'Superiore',
	'MetaIndexLower'			=> 'Inferiore',
	'MetaHtml'					=> 'Supporto HTML per la pagina',
	'MetaSafeHtml'				=> 'Filtro di HTML non sicuro',
	'MetaTypografica'			=> 'Revisore Tipografico',
	'MetaNoIndex'				=> 'Blocca motori di ricerca',
	'SettingsID'				=> 'Id Pagina',
	'SettingsSize'				=> 'Dimensione',
	'SettingsSizeTip'			=> 'sorgente / compilato',
	'SettingsCreated'			=> 'Creato',
	'SettingsCurrent'			=> 'Modificato',
	'SettingsTotalRevs'			=> 'Revisioni',
	'SettingsTotalComs'			=> 'Commenti',
	'SettingsWatchers'			=> 'Osservatori',
	'SettingsHits'				=> 'Viste',
	'SettingsText'				=> 'Impostazioni',
	'SettingsEdit'				=> 'Modifica',
	'SettingsRevisions'			=> 'Revisioni',
	'SettingsClone'				=> 'Clona',
	'SettingsRename'			=> 'Rinomina',
	'MassRename'				=> 'per l\'intero cluster',
	'SettingsRemove'			=> 'Rimuovi',
	'SettingsPurge'				=> 'Purge',
	'SettingsModerate'			=> 'Moderato',
	'SettingsPermissions'		=> 'Permessi',
	'AclForEntireCluster'		=> 'per l\'intero cluster',
	'SettingsAttachments'		=> 'Allegati',
	'SettingsUpload'			=> 'Carica',
	'SettingsCategories'		=> 'Categorie',
	'SettingsLanguages'			=> 'Lingue',
	'SettingsReferrers'			=> 'Referenti',
	'SettingsWatch'				=> 'Osserva',
	'SettingsLatex'				=> 'Versione LaTeX',
	'SettingsXML'				=> 'Esporta in XML',
	'NeedToChangeLang'			=> 'La lingua di pagina %1 non supportata deve essere modificata.',
	'SetLang'					=> 'Lingua di questa pagina',
	'SetMenuLabel'				=> 'Etichetta del menu',
	'SetShowMenuLabel'			=> 'Mostra nella navigazione',

	// upload
	'UploadFiles'				=> 'Carica file',
	'UploadFor'					=> 'Caricamento file:',
	'UploadButton'				=> 'Carica',
	'UploadGlobalText'			=> 'per l\'accesso pubblico',
	'UploadGlobal'				=> 'globale',
	'UploadLocalText'			=> 'solo per gli utenti autorizzati a visualizzare la pagina corrente',
	'UploadAsName'				=> 'Nome:',
	'UploadOverwrite'			=> 'Sovrascrivi file esistenti',
	'FileDesc'					=> 'Descrizione:',
	'UploadForbidden'			=> 'Non sei autorizzato a caricare file qui.',
	'UploadOverwriteDenied'		=> 'Solo il proprietario del file o l\'amministratore possono sovrascrivere il file %1.',
	'UploadNoFile'				=> 'Non c\'era alcun file in forma, per qualche motivo.',
	'UploadMaxSizeReached'		=> 'La dimensione del file è oltre il limite consentito!',
	'UploadDirNotWritable'		=> 'La directory dei file non è scrivibile!',
	'UploadNotAPicture'			=> 'I caricamenti delle immagini sono consentiti. Cosa stai cercando di caricare?',
	'UploadEmptyExtension'		=> 'Il nome del file e l\'estensione non possono essere vuoti.',
	'FilenameTooLong'			=> 'I nomi dei file non possono essere più lunghi di 240 byte.',
	'BannedFiletype'			=> '%1 non è un tipo di file consentito.',
	'PermittedFiletype'			=> 'Tipi di file consentiti:',
	'UploadMimeMismatch'		=> 'L\'estensione di file %1 non corrisponde al tipo MIME rilevato del file (%2).',
	'UploadBadMime'				=> 'I file del tipo MIME %1 non possono essere caricati.',
	'FileIsDuplicate'			=> 'Il caricamento è un duplicato esatto della versione corrente.',
	'FileHasDuplicate'			=> 'Questo file è un duplicato dei seguenti file:',

	'UploadMaxFileQuota'		=> 'Hai raggiunto il limite di caricamento. Questo file non può essere caricato',
	'UploadDone'				=> 'Caricamento file riuscito',
	'UploadFileForbidden'		=> 'Accesso al file vietato',
	'UploadTitle'				=> 'File accessibili da questa pagina',
	'UploadTitleGlobal'			=> 'File accessibili da qualsiasi luogo',

	'UploadFile'				=> 'Carica',
	'UploadMax'					=> 'Non più di ',
	'UploadUsedStorage'			=> 'Conservazione in uso ',

	// attachments
	'Attachments'				=> 'Allegati',
	'Attachment'				=> 'Allegato',
	'AttachmentsToPage'			=> 'alla pagina',
	'AttachmentsToCluster'		=> 'cluster',
	'AttachmentsByTime'			=> 'per ora',
	'AttachmentsGlobal'			=> 'globale',
	'AttachmentsAll'			=> 'tutti',
	'AttachmentsLinked'			=> 'usato',

	'FileViewProperties'		=> 'Visualizza',
	'FileViewPropertiesTip'		=> 'Visualizza i metadati di questo file',
	'FileEditProperties'		=> 'Modifica',
	'FileEditPropertiesTip'		=> 'Modifica i metadati di questo file',
	'FileEditedMeta'			=> 'Aggiornata i metadati di questo file',
	'FileEditDenied'			=> 'Non sei autorizzato a modificare questo file',
	'FileLabel'					=> 'Etichetta',
	'FileLabelTip'				=> 'Etichetta questo file',
	'FileRemove'				=> 'Rimuovi',
	'FileRemovedFromDB'			=> 'File rimosso dal database',
	'FileRemovedFromFS'			=> 'File cancellato dall\'hosting fisico',
	'FileRemovedFromFSError'	=> 'Sembra impossibile cancellare il file!',
	'FileRemoveConfirm'			=> 'Sicuro di rimuovere questo file?',
	'FileRemoveDenied'			=> 'Non sei autorizzato a rimuovere questo file',
	'FileNotFound'				=> 'File non trovato.',

	'FileSearch'				=> 'Trova File',
	'UploadBy'					=> 'Caricato da:',
	'FileAdded'					=> 'Aggiunto:',
	'FileModified'				=> 'Modificato:',
	'FileSize'					=> 'Dimensione:',
	'FileDimension'				=> 'Dimensione:',
	'MimeType'					=> 'Mimetype:',
	'FileName'					=> 'Nome:',
	'FileCaption'				=> 'Didascalia:',
	'FileAuthor'				=> 'Autore:',
	'FileSource'				=> 'Fonte:',
	'FileSourceUrl'				=> 'URL:',
	'FileAttachedTo'			=> 'Allegato a:',
	'FileSyntax'				=> 'Sintassi:',
	'FileAbsolutePath'			=> 'percorso assoluto',
	'FileRelativePath'			=> 'percorso relativo',
	'FileUsage'					=> 'Uso del file:',
	'FileUsageText'				=> 'Le pagine seguenti collegano a questo file:',
	'NoFileUsage'				=> 'Nessuna pagina di collegamento a questo file.',

	'FileSortExt'				=> 'estensione',
	'FileSortName'				=> 'nome',
	'FileSortSize'				=> 'dimensione',
	'FileSortTime'				=> 'creato',

	'SortBy'					=> 'Ordina per',
	'Ascending'					=> 'ascendente',
	'Decending'					=> 'decendente',

	'Files0'					=> 'Allega File',
	'Files1'					=> 'Mostra file (1 file)',
	'FilesN'					=> 'Mostra file ( file%1)',
	'Files'						=> 'File',
	'File'						=> 'File',
	'ShowFiles'					=> 'Visualizza file / modulo',
	'HideFiles'					=> 'Nascondi file / modulo',
	'DoShowFiles'				=> 'Mostra elenchi di file per impostazione predefinita',
	'NoAttachments'				=> 'Non ci sono file allegati da visualizzare.',

	'RegistrationLang'			=> 'La tua lingua',
	'InvalidWikiName'			=> 'Il nome scelto non è valido',
	'InvalidUserName'			=> 'Il nome utente scelto non è valido',
	'Bookmarks'					=> 'Segnalibri',
	'ReallyDeleteComment'		=> 'Vuoi davvero eliminare questo commento?<br>Non c\'è annullamento per questa azione!',
	'ReallyDeleteRevision'		=> 'Vuoi davvero svelare questa revisione?<br>Non c\'è annullamento per questa azione!',

	'RegistrationClosed'		=> 'La registrazione non è disponibile qui. Prova a contattare l\'amministratore del sito.',
	'AclAreYouSure'				=> 'Si sta per modificare ACL di questa pagina e tutte le sue sotto-pagine. Continuare?',

	'BookmarkDeleteSelected'	=> 'Elimina selezionati',
	'BookmarkMark'				=> 'Segna',
	'BookmarkNumber'			=> 'No.',
	'BookmarkNone'				=> 'Non hai segnalibri.',
	'BookmarkTitle'				=> 'Titolo segnalibro',
	'BookmarkPage'				=> 'Pagina',
	'BookmarkSaveChanges'		=> 'Salva modifiche',
	'BookmarksAddPage'			=> 'Imposta un segnalibro per la seguente pagina',
	'BookmarkAlreadyExists'		=> 'Il segnalibro esiste già.',

	'PoweredBy'					=> 'Alimentato da',

	'MassRenaming'				=> 'Rinomina l\'intero cluster',
	'MassNewName'				=> 'Inserisci un nuovo nome per questo cluster',
	'MassNeedRedirect'			=> 'Crea un reindirizzamento alle nuove pagine nelle vecchie pagine',

	// pagination
	'ToOverview'				=> 'Torna alla panoramica',
	'Overview'					=> 'Panoramica',
	'ToThePage'					=> 'Alla pagina:',
	'Next'						=> 'Successivo',
	'Prev'						=> 'Precedente',
	'NextAcr'					=> 'Successivo',
	'PrevAcr'					=> 'Precedente',
	'Back'						=> 'Indietro',

	// filter
	'Filter'					=> 'Filtro',
	'OptionalFilters'			=> 'Filtri opzionali:',
	'Any'						=> 'Qualsiasi',

	// My Groups
	'UserGroups'				=> 'Gruppi di utenti',
	'MyGroups'					=> 'Associazioni Di Gruppo',
	'Group'						=> 'gruppo',
	'Groups'					=> 'gruppi',

	// license action
	'DistributedUnder'			=> 'Il materiale è distribuito sotto',
	'AuthorsDisplayHint'		=> 'La lista degli autori verrà visualizzata durante il salvataggio della pagina.',
	'AnonymousUsers'			=> 'Utenti anonimi',
	'License'					=> 'Licenza',
	'LicenseArray'				=> [
		'1'		=> 'Attribuzione-NoDerivati',
		'2'		=> 'Attribuzione-NonCommercial-ShareAlike',
		'3'		=> 'Attribuzione-NonCommerciale-NoDerivati',
		'4'		=> 'Attribuzione-ShareAlike',
		'5'		=> 'Attribuzione-Non Commerciale',
		'6'		=> 'Attribuzione',
		'7'		=> 'CC0 1.0 Universal',
		'8'		=> 'Licenza Di Documentazione Gratis Gnu',
		'9'		=> 'Pubblico Dominio / Uso Libero',
		'10'	=> 'Tutti I Diritti Riservati',
	],
	'LicenseMeta'				=> [
		'1'		=> 'Dominio pubblico',
		'2'		=> 'Alcuni diritti riservati',
		'3'		=> 'Tutti I Diritti Riservati',
	],

	// Cache
	'ClearCache'				=> 'Svuota cache',
	'CacheCleared'				=> 'Cache cancellata.',
	'ConfigCache'				=> 'Cache di configurazione',
	'FeedCache'					=> 'Cache dei feed',
	'PageCache'					=> 'Cache di pagina',
	'SQLCache'					=> 'Cache SQL',
	'TemplateCache'				=> 'Cache modello',
	'ThumbCache'				=> 'Thumbnail cache',

	// Embed
	'EmbedNoURL'				=> 'Specifica un indirizzo della risorsa con l\'URL dei parametri. (es. {{embed url="https://example.com/embed/video.mp4"}} )',

	// Feed
	'FeedTitle'					=> 'Titolo Feed',
	'FeedMulti'					=> 'Multi-Feed',
	'FeedNoURL'					=> 'Specifica un feed con l\'URL dei parametri. (es. {{feed url="https://example.com/feed.xml"}} )',
	'FeedError'					=> 'Impossibile caricare o analizzare il feed',
	'FeedSource'				=> 'Fonte:',
	'FeedXMLTip'				=> '',

	// XML / RSS autodiscovery
	'ChangesXMLTitle'			=> ' - Modifiche recenti',
	'ChangesXML'				=> 'Modifiche recenti alla ',
	'CommentsXMLTitle'			=> ' - Commenti recenti',
	'CommentsXML'				=> 'Commenti recenti alla ',
	'NewsXMLTitle'				=> ' - Notizie recenti',
	'NewsXML'					=> 'Notizie recenti al ',
	'RevisionXMLTip'			=> 'Fare clic per visualizzare le revisioni recenti della pagina in formato XML.',
	'CommentsXMLTip'			=> 'Fare clic per visualizzare i commenti recenti in formato XML.',
	'ChangesXMLTip'				=> 'Fare clic per visualizzare le modifiche recenti in formato XML.',
	'NewsXMLTip'				=> 'Clicca per vedere le notizie recenti in formato XML.',
	'RevisionsXML'				=> 'Revisioni di ',
	'ExportClusterXML'			=> 'Esportazione di tutto il gruppo di ',
	'AccessDeniedXML'			=> 'Non ti è permesso accedere a queste informazioni.',

	'ChangesFeed'				=> 'Modifiche',
	'CommentsFeed'				=> 'Commenti',
	'NewsFeed'					=> 'Notizie',
	'RevisionsFeed'				=> 'Revisioni di ',

	'LastModification'			=> 'Ultima Modifica',

	// Captcha
	'Captcha'					=> 'Digita la parola che hai letto nell\'immagine',
	'CaptchaFailed'				=> 'Hai inserito la parola captcha in modo errato. Riprova.',
	'CaptchaReload'				=> 'Nuova Captcha',
	'CaptchaReloadWarning'		=> 'Siamo spiacenti, non è possibile ricaricare l\'immagine captcha, è necessario ricaricare la pagina per farlo',

	// news
	'News'						=> 'Notizie',
	'NewsName'					=> 'Titolo:',
	'NewsNoName'				=> 'Hai dimenticato di aggiungere il titolo delle notizie.',
	'NewsNotAvailable'			=> 'Nessuna notizia disponibile.',
	'NewsNoClusterDefined'		=> 'Nessun cluster di notizie definito.',
	'NewsDiscuss'				=> 'Discutere questo articolo...',

	// blog
	'BlogNewTopic'				=> 'Crea un nuovo post',
	'NoPostAvailable'			=> 'Nessun post ancora disponibile.',

	// Review
	'Reviewer'					=> 'Revisore',
	'Reviewed'					=> 'recensito',
	'Review'					=> 'revisione',
	'ReviewedBy'				=> 'recensito da',
	'RemoveReview'				=> 'Rimuovi recensione per questa pagina',
	'SetReview'					=> 'Rivista questa pagina',
	'SetAsReviewed'				=> 'Imposta la pagina come recensito',
	'SetAsUnreviewed'			=> 'Imposta la pagina come non recensita',

	// word filter
	'PotentialSpam'				=> 'Spam Potenziale Identificato',

	// moderation handler
	'Moderation'				=> 'Moderazione',
	'Topics'					=> 'argomenti',
	'ModerateSection'			=> 'sezione / pagina ',

	'NotModerator'				=> 'Non hai l\'autorità di moderare questa pagina / capitolo',
	'ModerateDeleteTopic'		=> 'Elimina argomento / pagina',
	'ModerateDeletePosts'		=> 'Elimina commenti',
	'ModerateMove'				=> 'Sposta',
	'ModerateSplit'				=> 'Dividi / Sposta commenti',
	'ModerateMerge'				=> 'Unisci',
	'ModerateLock'				=> 'Blocca',
	'ModerateUnlock'			=> 'Sblocca',
	'ModerateAccept'			=> 'Accetta',
	'ModerateDeleteConfirm'		=> 'Sei sicuro di voler <strong>rimuovere</strong> i seguenti argomenti?',
	'ModerateRenameConfirm'		=> 'Inserisci un nuovo titolo per la pagina selezionata',
	'ModerateRenameExists'		=> 'La pagina con lo stesso nome esiste già! Scegli un nome diverso.',
	'ModerateRename1Only'		=> 'Nota: solo la prima pagina selezionata verrà rinominata!',
	'ModerateMovesConfirm'		=> 'Seleziona la partizione di destinazione in cui spostare il forum',
	'ModerateMoveConfirm'		=> 'Selezionare il forum o specificare il cluster per spostare questi argomenti. Per spostare una pagina nella radice del sito, digitare &quot;/&quot;',
	'ModeratePgMoveConfirm'		=> 'Specifica il nome del cluster in cui posizionare la pagina. Per spostare una pagina nella root del sito, digita &quot;/&quot;',
	'ModerateMoveExists'		=> 'Operazione interrotta: In questa sezione esiste già argomenti con lo stesso nome %1. Se hai ancora bisogno di trasferire gli argomenti sopra menzionati, rinominarli prima.',
	'ModerateMoveNotExists'		=> 'La pagina / cluster non esiste. Controlla il nome e riprova.',
	'ModerateMergeConfirm'		=> 'Scegli un argomento, che dovrebbe combinare il restante',
	'ModerateMerge2Min'			=> 'Per unirti a te devi selezionare almeno due topic!',
	'ModerateComDelConfirm'		=> 'Sei sicuro di voler <strong>rimuovere</strong> %1 %2?',
	'ModerateComment'			=> 'Commento',
	'ModerateComments'			=> 'Commenti',
	'ModerateSplitNewName'		=> 'Specifica un nome per un argomento separabile e seleziona uno schema di separazione',
	'ModerateSplitPageName'		=> 'Inserisci il nome della pagina / argomento, dove spostare i commenti staccabili e selezionare uno schema di separazione',
	'ModerateSplitAllAfter'		=> 'Stacca tutti i commenti dopo il primo selezionato (e incluso)',
	'ModerateSplitSelected'		=> 'Solo commenti selezionati separati (totale %1)',
	'ModerateUserProfile'		=> 'profilo',
	'ModerateNoItemChosen'		=> 'Si prega di selezionare almeno un elemento tramite il pulsante Imposta.',

	'ModerateSection2'			=> 'sezione moderata',
	'ModerateTopicsDeleted'		=> 'Argomenti selezionati eliminati con successo.',
	'ModerateTopicsRelocated'	=> 'Argomenti selezionati trasferiti con successo.',
	'ModerateTopicsRenamed'		=> 'Topic rinominato con successo.',
	'ModerateTopicsMerged'		=> 'Argomenti selezionati uniti con successo.',
	'ModerateTopicsBlocked'		=> 'Argomenti selezionati bloccati con successo',
	'ModerateTopicsUnlocked'	=> 'Argomenti selezionati sbloccati con successo.',
	'ModerateTopicDeleted'		=> 'Topic has been successfully removed.',
	'ModeratePageMoved'			=> 'Pagina spostata correttamente.',
	'ModerateTopicRenamed'		=> 'Topic rinominato con successo.',
	'ModerateTopicBlocked'		=> 'Argomento bloccato con successo',
	'ModerateTopicUnlocked'		=> 'Argomento sbloccato con successo.',
	'ModerateCommentsDeleted'	=> 'Commenti selezionati rimossi con successo.',
	'ModerateCommentsSplit'		=> 'Commenti selezionati separati con successo in un nuovo argomento.',
	'ModerateCommentsSplitFailed'	=> 'Nota: Per qualche motivo la separazione dei commenti selezionati in un nuovo argomento non è riuscita.<br>Di solito questo non dovrebbe accadere, quindi si prega di avvisare l\'amministratore del sito.<br>Come precauzione, il problema è stato conservato nella sua forma originale.',
	'ModerateCommentsMoved'		=> 'I commenti selezionati sono migrati con successo alla pagina data.',

	// forum
	'ForumSubforums'			=> 'Forum',
	'ForumTopic'				=> 'Argomento',
	'ForumTopics'				=> 'Argomenti',
	'ForumPosts'				=> 'Post',
	'ForumReplies'				=> 'Risposte',
	'ForumAuthor'				=> 'Autore',
	'ForumViews'				=> 'Viste',
	'ForumCreated'				=> 'Creato',
	'ForumComments'				=> 'Commenti',
	'ForumLastComment'			=> 'Ultimo commento',
	'ForumNoComments'			=> 'Nessun commento',
	'ForumNoTopics'				=> 'Non ci sono argomenti o post in questo forum.',
	'ForumNewTopic'				=> 'Inizia una nuova discussione',
	'ForumTopicName'			=> 'Nome dell\'argomento:',
	'ForumTopicSubmit'			=> 'Invia argomento',
	'ForumNoTopicName'			=> 'Specifica un nome per la nuova pagina.',
	'ForumNewPosts'				=> 'nuovo post',
	'ForumLocked'				=> 'sezione bloccata',
	'ForumUpdated'				=> 'aggiornato',
	'ForumNoClusterDefined'		=> 'Nessun cluster del Forum definito.',
	'ForumOutsideCluster'		=> 'Assicurati che l\'azione %1 si trovi all\'interno del cluster del forum.',

	// password complexity
	'PwdCplxShort'				=> 'La password è troppo corta.',
	'PwdCplxEquals'				=> 'La password contiene il nome utente.',
	'PwdCplxWeak'				=> 'La password non soddisfa i requisiti di complessità.',
	'PwdCplxDesc1'				=> 'Requisiti per la password: ',
	'PwdCplxDesc2'				=> 'la password non deve essere inferiore a caratteri %1',
	'PwdCplxDesc3'				=> 'non deve contenere il tuo username',
	'PwdCplxDesc4'				=> 'dovrebbe consistere in ',
	'PwdCplxDesc41'				=> 'lettere e numeri',
	'PwdCplxDesc42'				=> 'lettere maiuscole e minuscole e numeri',
	'PwdCplxDesc43'				=> 'lettere maiuscole e minuscole, cifre e caratteri non alfanumerici',
	'PwdCplxDesc5'				=> 'È possibile utilizzare qualsiasi lettera, numeri e caratteri speciali tranne gli spazi.',

	'PasswordTooShort'			=> 'Password troppo corta.',
	'PasswordTooCommon'			=> 'Quella password è troppo comune.',
	'PasswordSameAsUsername'	=> 'La tua password è la stessa del tuo nome utente.',
	'PasswordSameAsEmail'		=> 'La tua password è la stessa della tua email.',

	'Timezone'					=> 'Timezone',

	'LanguageArray'	=> [
		'bg' => 'Bulgaro',
		'da' => 'Danese',
		'de' => 'Tedesco',
		'el' => 'Greco',
		'en' => 'Inglese',
		'es' => 'Spagnolo',
		'et' => 'Estone',
		'fa' => 'Persiano',
		'fr' => 'Francese',
		'hi' => 'Hindi',
		'hu' => 'Ungherese',
		'it' => 'Italiano',
		'ja' => 'Giapponese',
		'ko' => 'Coreano',
		'nl' => 'Olandese',
		'pl' => 'Polacco',
		'pt' => 'Portoghese',
		'ru' => 'Russo',
		'ta' => 'Tamil',
		'zh' => 'Cinese',
		'zh-tw' => 'Cinese',
	],

	'AccountStatus'				=> 'Stato account',
	'AccountStatusArray' => [
		'0' => 'attivo',
		'1' => 'in attesa',
		'2' => 'bloccato',
		'3' => 'inattivo',
	],

	'JustNow'		=> 'proprio ora',
	'MinuteAgo'		=> 'un minuto fa',
	'MinutesAgo'	=> '%1 minuti fa',
	'HourAgo'		=> 'un\'ora fa',
	'HoursAgo'		=> '%1 ore fa',
	'DayAgo'		=> 'ieri',
	'DaysAgo'		=> '%1 giorni fa',
	'WeekAgo'		=> 'una settimana fa',
	'WeeksAgo'		=> '%1 settimane fa',
	'MonthAgo'		=> 'un mese fa',
	'MonthsAgo'		=> '%1 mesi fa',
	'YearAgo'		=> 'un anno fa',
	'YearsAgo'		=> '%1 anni fa',

	'InAMoment'		=> 'tra un attimo',
	'InAMinute'		=> 'in un minuto',
	'InMinutes'		=> 'in %1 minuti',
	'InAnHour'		=> 'in un\'ora',
	'InHours'		=> 'in %1 ore',
	'Tomorrow'		=> 'domani',
	'InDays'		=> 'in %1 giorni',
	'InAWeek'		=> 'tra una settimana',
	'InWeeks'		=> 'in %1 settimane',
	'InAMonth'		=> 'in un mese',
	'InMonths'		=> 'in %1 mesi',
	'InAYear'		=> 'in un anno',
	'InYears'		=> 'in %1 anni',

	// norm multiples
	'ByteDecimalShort'			=> ['B', 'kB', 'MB', 'GB', 'TB', 'PB', 'EB', 'ZB', 'YB'],
	'ByteDecimalLong'			=> ['Byte', 'Kilobyte', 'Megabyte', 'Gigabyte', 'Terabyte', 'Petabyte', 'Exabyte', 'Zettabyte', 'Yottabyte'],
	'ByteBinaryShort'			=> ['B', 'KiB', 'MiB', 'GiB', 'TiB', 'PiB', 'EiB', 'ZiB', 'YiB'],
	'ByteBinaryLong'			=> ['Byte', 'Kibibyte', 'Mebibyte', 'Gibibyte', 'Tebibyte', 'Pebibyte', 'Exbibyte', 'Zebibyte', 'Yobibyte'],
	'PixelDecimalShort'			=> ['px', 'KP', 'MP', 'GP', 'TP', 'PP', 'EP', 'ZP', 'YP'],
	'PixelDecimalLong'			=> ['pixel', 'Kpx', 'Mpx', 'Gpx', 'Tpx', 'Ppx', 'Epx', 'Zpx', 'Ypx'],

	// loading error
	'UnknownAction'				=> 'Azione sconosciuta',
	'UnknownMethod'				=> 'Metodo sconosciuto',
	'FormatterNotFound'			=> 'Formatter %1 non trovato',

	// log
	'LogAdminLoginSuccess'		=> 'Accesso effettuato con successo nel pannello amministrativo',
	'LogAdminLogout'			=> 'Disconnessione del gruppo di esperti amministrativi',
	'LogAdminLoginFailed'		=> '!!Impossibile autorizzare l\'accesso al panel amministrativo!!',
	'LogAdminLoginLocked'		=> 'Accesso bloccato al pannello amministrativo',
	'LogUserCookieForged'		=> '!!**Un tentativo di accedere a un cookie forgiato con login ##%1##**!!',
	'LogInvalidFormToken'		=> 'Rilevato potenziale attacco CSRF in corso: %1',
	'LogRemovedPage'			=> '!!Rimossa la pagina ##%1## (utente %2)!!',
	'LogRemovedCluster'			=> '!!Rimosso **cluster** ##%1## (utente %2)!!',
	'LogRemovedRevision'		=> '!!Rimosso la revisione ##%3## della pagina [[/%1]] (utente %2)!!',
	'LogRemovedComment'			=> '!!Rimosso commento da %3 sulla pagina [[/%1]] (utente %2)!!',
	'LogRemovedFile'			=> '!!Rimosso il file ##%2## dalla pagina [[/%1]]!!',
	'LogRemovedAllComments'		=> '!!Rimosso tutti i commenti della pagina [[/%1]]!!',
	'LogRemovedAllRevisions'	=> '!!Rimosso tutte le revisioni della pagina [[/%1]]!!',
	'LogRemovedAllFiles'		=> '!!Rimossi tutti i file, allegati a [[/%1]]!!',
	'LogTopicLocked'			=> 'L\'argomento del forum è bloccato [[/%1]]',
	'LogTopicUnlocked'			=> 'Argomento del forum sbloccato [[/%1]]',
	'LogAclUpdated'				=> 'Pagina ACL aggiornata [[/%1]]',
	'LogOwnershipChanged'		=> 'Proprietà della pagina [[/%1]] trasferita all\'utente ##%2##',
	'LogUserLoginFailed'		=> '!!Tentativi di accesso falliti con ##~%1##!!',
	'LogClonedPage'				=> 'Pagina ##%1## clonata in [[/%2]]',
	'LogRenamedPage'			=> 'Pagina ##%1## rinominata in [[/%2]]',
	'LogRenamedPage2'			=> '. La vecchia pagina impostata come collegamento a quella nuova',
	'LogSplittedPage'			=> 'Commenti sulla pagina [[/%1]] suddivisi in pagina [[/%2]]',
	'LogMergedPages'			=> 'Pagine %1 unite alla pagina [[/%2]]',
	'LogUserPasswordReminded'	=> 'L\'utente ##%1## ha chiesto il processo di ripristino della password per l\'indirizzo ##%2##',
	'LogUserPasswordRecovered'	=> 'L\'utente ##%1## ha recuperato con successo la password dimenticata',
	'LogUserPasswordChanged'	=> 'Utente ##%1## aggiornato correttamente (modificato) la password',
	'LogUserPasswordMismatch'	=> '!!Utente ##%1## non è riuscito a cambiare la password: password attuale non corrisponde!!',
	'LogUserIPSwitched'			=> 'Modifica dell\'indirizzo IP non autorizzata dell\'utente %1 da %2 a %3',
	'LogPageImported'			=> 'Pagina importata [[/%1]]',
	'LogSaveNoRights'			=> 'Nessun diritto appropriato per salvare la pagina [[/%1]]',
	'LogPageCreated'			=> 'Creata nuova pagina [[/%1]]',
	'LogPagePropertiesUpdated'	=> 'Proprietà della pagina aggiornate [[/%1]]',
	'LogPageOwnershipClaimed'	=> 'L\'utente ha ottenuto la proprietà della pagina [[/%1]]',
	'LogFileUploadedLocal'		=> 'Nuovo file ##%2## caricato sulla pagina [[/%1]] (dimensione %3)',
	'LogFileUploadedGlobal'		=> 'Nuovo file ##%2## caricato nella cartella globale (dimensione %3)',
	'LogPMSent'					=> 'Messaggio personale ##%1## -> ##%2## inviato con successo',
	'LogUserSimilarName'		=> 'Si sono verificati tentativi di registrazione con lo stesso nome utente: ##%1##',
	'LogUserEmailNotAllowed'	=> 'Email ##%1## non nell\'elenco dei domini consentiti',
	'LogRegisterTiming'			=> 'Registrazione non riuscita, la soglia di tempo del modulo è ##%1## secondi (era ##%2##)',
	'LogUserRegistered'			=> 'Registrato con successo un nuovo utente ##%1## (##%2##)',
	'LogUserEmailActivated'		=> 'Email attivata con successo ##%1## dell\'utente ##%2##',
	'LogCommentPosted'			=> 'Aggiunto [[/%1 nuovi commenti]] alla pagina [[/%2]]',
	'LogUserLoginOK'			=> 'Utente ##%1## registrato con successo nel sistema',
	'LogUserLoggedOut'			=> 'Utente ##%1## ha disconnesso con successo il sistema',
	'LogUserSessionContinued'	=> 'L\'utente ##%1## ha continuato la sessione sospesa',
	'LogUserSettingsUpdate'		=> 'Utente ##%1## impostazioni personali aggiornate',
	'LogPageEdited'				=> 'Pagina modificata [[/%1]]',
	'LogCommentEdited'			=> 'Commento modificato [[/%1]]',
	'LogUpdatedFileMeta'		=> 'Aggiornata i metadati del file per ##%2## dalla pagina [[/%1]]',
	'LogUpdatedFileCategories'	=> 'Categorie di file aggiornate per ##%2## dalla pagina [[/%1]]',

	'LogXmlSitemapGenerated'	=> 'Sitemap XML generato',
	'LogReferrersPurged'		=> 'Manutenzione: referenti purificati',
	'LogRevisionsPurged'		=> 'Manutenzione: pagine obsolete revisioni purged',
	'LogDeletedPagesPurged'		=> 'Manutenzione: pagine cancellate cancellate',
	'LogSystemLogPurged'		=> 'Manutenzione: log di sistema purificato',
	'LogCachedPagesPurged'		=> 'Manutenzione: pagine cancellate nella cache',
	'LogSqlCachePurged'			=> 'Manutenzione: cached sql risultati purged',
	'LogExpiredTokensPurged'	=> 'Manutenzione: eliminati cookie_token scaduti',
	'LogErrorSplitComments'		=> 'Errore durante la separazione dei commenti dall\'argomento [[/%1]] un nuovo argomento ##%2##: la pagina non è stata creata',
	'LogCategoriesUpdated'		=> 'Categorie di pagina aggiornate [[/%1]]',
	'LogCategoryCreated'		=> 'Creata una nuova categoria //%1//',
	'LogCategoryRenamed'		=> 'Categoria ##%1## rinominata in ##%2##',
	'LogCategoryDebundled'		=> 'Categoria ##%1## debundled',
	'LogCategoryGrouped'		=> 'Categoria ##%1## raggruppata con la parola ##%2##',
	'LogCategoryRemoved'		=> 'Categoria ##%1## rimossa dal database',
	'LogThumbnailGeneration'	=> 'Generazione miniature %1 sec.',

	'ErrorMinPHPVersion'		=> 'La versione PHP deve essere maggiore di <strong>' . PHP_MIN_VERSION . '</strong>,' .
									' il tuo server sembra essere in esecuzione <strong>' . PHP_VERSION . '</strong>.' .
									'  Si dovrebbe aggiornare a una versione PHP più recente per WackoWiki per funzionare correttamente.',

];
