<?php

if (!defined('IN_WACKO'))
{
	exit;
}

$wacko_translation = [

	// language
	'lang_scheme'	=> [
		'name'		=> 'Distr.',
		'code'		=> '中',
		'dir'		=> 'ltr',
		'locale'	=> 'zh_CN.UTF-8',
	],

	// common
	'AddButton'					=> '添加',
	'ArchiveButton'				=> '存档',
	'CancelButton'				=> '取消',
	'ContinueButton'			=> '继续',
	'ConvertButton'				=> '转换',
	'CreateButton'				=> '创建',
	'DeleteButton'				=> '删除',
	'RemoveButton'				=> '删除',
	'RenameButton'				=> '重命名：',
	'ResetButton'				=> 'Reset',
	'RestoreButton'				=> '恢复',
	'SaveButton'				=> '保存',
	'SearchButton'				=> '搜索',
	'SendButton'				=> '发送',
	'SetButton'					=> '设置',
	'SubmitButton'				=> '提交',
	'UpdateButton'				=> '更新',

	'FormInvalid'				=> '提交的表单无效。请尝试再次提交。',
	'UnitPixel'					=> 'px',
	'Number'					=> '号码',

	// logged in panel
	'AccountText'				=> '账户',
	'AccountTip'				=> '帐户设置',
	'AdminText'					=> '管理员',
	'AdminTip'					=> '管理面板',
	'LogoutLink'				=> '注销',
	'LogoutButton'				=> '注销',
	'LogoutAreYouSure'			=> '您真的想要注销吗？',

	// registration panel
	'RegistrationWelcome'		=> '新用户注册：',
	'RegistrationButton'		=> '注册我',
	'UserNameOwned'				=> '此用户名已被注册。请另选一个。',
	'SiteRegistered'			=> '您已成功注册站点 %1',
	'RegistrationEmailInfo'		=> '一个有效的电子邮件地址。来自系统的所有电子邮件将被发送到此地址。 电子邮件地址不公开，只有在您希望收到新密码或希望通过电子邮件接收某些消息或通知时才会使用。',
	'EmailConfirmHint'			=> '请点击发送给您的说明中的链接来确认您的电子邮件地址。 <br>如果您不验证您的电子邮件地址，您将无法检索可能丢失的密码。 <br>此外，您将不会收到关于最近页面更改和评论的通知。',
	'EmailConfirmRequired'		=> '没有确认的电子邮件地址，您将无法登录。',
	'NameTooShort'				=> '用户名太短，至少需要 %2 字符。',
	'NameTooLong'				=> '用户名太长，最多允许 %2 字符。',
	'NameAlphanumOnly'			=> '用户名必须介于 %1 和 %2 字符之间，并且只能使用字母数字字符。上面的字符是确定的。',
	'NameCamelCaseOnly'			=> '用户名必须介于 %1 和 %2 字符之间。',
	'NewUserAccount'			=> '新用户帐户',

	'NewAccountSubject'			=> '账户注册',
	'NewAccountAdminCreated'	=> '用户 %1 已经用用户名"%2"为您创建了一个帐户。 为了完成您的注册，请访问下面的 URL (请确保它作为单行输入)，并设置您自己的访问密码：',
	'NewAccountUsername'		=> '用户名：',
	'AccountLanguage'			=> '语言：',
	'NewAccountEmail'			=> 'Email:',
	'NewAccountIP'				=> '远程IP地址：',
	'NewAccountSignupInfo'		=> '以下帐号已创建：',

	'UserWaitingApproval'		=> '一封电子邮件已发送给站点管理员。 管理员将审查已提交的信息，并批准或拒绝您的请求。',
	'UserRequiresApproval'		=> '若要批准或拒绝此用户访问 %1 ，请前往管理面板。',
	'UserApprovalInfo'			=> '注册后，您的请求将发送给站点管理员审核。然后您将收到一封含有进一步说明的电子邮件。',
	'UserApprovalHint'			=> '您的帐户激活成功将会在特定的电子邮件中通知。直到那时，无法登录。',

	'UserApprovalPending'		=> '您的帐户仍在等待批准。',
	'UserApprovalDenied'		=> '您的帐户被拒绝访问此网站。',

	'RegistrationApproved'		=> '注册已批准',
	'RegistrationDenied'		=> '注册被拒绝',
	'PendingApproval'			=> '等待批准',

	'UserApprovedInfo'			=> '您已被批准访问 %1。',
	'UserDeniedInfo'			=> '您被拒绝访问 %1。',

	'RegistrationThreshold'		=> '填写表单的时间不应少于 %1 秒。',
	'Language'					=> '语言',

	// login panel
	'LoginWelcome'				=> '登录',
	'CreateAccount'				=> '创建新账户',
	'RegistrationLink'			=> '登记',
	'LoginName'					=> '用户名',
	'Password'					=> '密码',
	'LoginButton'				=> '登录',
	'LoginLink'					=> '登录',
	'PersistentCookie'			=> '保持登录',
	'Session'					=> '会议',
	'SessionTip'				=> '当前会话参数',
	'SessionDuration'			=> '会话持续时间',
	'SessionDurationSession'	=> '浏览器会话',
	'SessionDurationDay'		=> '1天',
	'SessionDurationWeek'		=> '1 周',
	'SessionDurationMonth'		=> '1 个月',
	'LoggedInAs'				=> '您已登录为',

	'ClearCookies'				=> '删除所有 cookie',
	'BindSessionIp'				=> '绑定会话到 IP 地址',
	'BindSessionIpOn'			=> '启用(当前IP %1)',
	'TrafficProtection'			=> '交通保护',
	'SessionEnds'				=> '当前会话结束',
	'LastVisit'					=> '上次访问已记录',

	'LoginIncorrect'			=> '您输入的用户名或密码无效。',
	'WelcomeBack'				=> '欢迎回来， %1',
	'LoginAttemptsExceeded'		=> '您超过了最大允许的登录尝试次数。<br>除了您的用户名和密码外，您现在还必须在下面解决验证码。',

	// session notice
	'IPAddressChanged'			=> 'IP地址更改为 %1 (是 %2)',

	'SessionReplay'				=> '会话因重放而终止。',
	'SessionObsolete'			=> '会话已过时。',
	'SessionExpired'			=> '会话已过期。',
	'SessionTimeout'			=> '会话因超时而终止。',
	'SessionInactivity'			=> '会话因不活动而终止。',
	'SessionUaChange'			=> '会话因用户代理更改而终止。',
	'SessionTLSChange'			=> '会话因TLS更改而终止。',
	'SessionIPChange'			=> '会话因IP更改而终止。',

	// other
	'Guest'						=> '来宾',
	'Everybody'					=> '每个人',
	'Help'						=> '帮助',
	'TopicSearchText'			=> '只搜索标题',
	'WordprocessorVersion'		=> '单词处理器版本',

	// notifications
	'EmailHello'				=> '您好 ',
	'EmailModerator'			=> '版主',
	'WatchedPageChanged'		=> '页面已更改 ',
	'SomeoneChangedThisPage'	=> ' 更改了您正在观看的页面： ',
	'NewPageCreatedSubj'		=> '新页面',
	'NewPageCreatedBody'		=> '用户 %1 创建了一个新页面： ',
	'FileUploadedSubj'			=> '一个新文件',
	'FileUploadedBody'			=> '用户 %1 上传了一个新文件： ',
	'FileReplacedBody'			=> '用户 %1 已替换文件： ',

	'ActionDenied'				=> '此处的操作被拒绝。',
	'TocTitle'					=> '目录 ',
	'OuterLink2'				=> '发送链接',
	'FileLink'					=> '',
	'PDFLink'					=> 'PDF 文档',
	'RDFLink'					=> 'RDF 文档',
	'EmailLink'					=> '写一封电子邮件 (邮件客户端启动)',
	'JabberLink'				=> '通过 XMPP 聊天 (Jabber 客户端启动)',
	'PermaLink'					=> '永久链接',
	'PermaLinkTip'				=> '永久链接到这个页面的版本',
	'PermaLink0Tip'				=> '永久链接到此页面',

	'ShowTip'					=> '返回视图模式',
	'ShowText'					=> '查看',
	'WikieditAutocomplete'		=> 'Ctrl+Space完整wiklinks',
	'WikiEditInactiveJs'		=> '为了能够使用 WikiEdit，请在浏览器中启用 JavaScript。',
	'NumerateLinks'				=> '打印视图中的链接数',
	'Comment'					=> '评论',
	'Comments0'					=> '添加您的评论',
	'Comments1'					=> '阅读评论 (1 个评论)',
	'CommentsN'					=> '阅读评论 (%1 评论)',
	'Comments'					=> '评论',
	'CommentHint'				=> '<a href="%1">登录</a> 或 <a href="%2">创建一个帐户</a> 以发表评论。',
	'CommentEdited'				=> '已编辑',
	'Links'						=> '链接',
	'Version'					=> '版本',

	// details formatter
	'ShowHideDetails'			=> '详细信息',

	'PrivacyPolicy'				=> '隐私政策',
	'TermsOfUse'				=> '使用条款',
	'AcceptTermsOfUse'			=> '我已经阅读、理解并同意网站的服务条款。',

	'ShowComments'				=> '显示评论/表单',
	'HideComments'				=> '隐藏评论/表单',
	'AddComment'				=> '将注释附加到这个页面：',
	'AddCommentTitle'			=> '评论标题：',
	'CommentTitleRe'			=> '回复：',
	'AddCommentButton'			=> '附加评论',
	'HereLink'					=> '在这里',
	'PageHandlerMoreTip'		=> '更多',

	'ThemeCorrupt'				=> '主题已损坏',
	'InvalidNamespace'			=> '给定的命名空间无效。',
	'DoesNotExists'				=> '此页面不存在。',
	'PromptCreate'				=> '也许您想要 <strong><a href="%1">创建</a></strong> 吗？',
	'RevisionHint'				=> '这是由 %4 编辑的 %3 的 <a href="%1">%2</a> 的旧版本。',
	'ReadAccessDenied'			=> '您无权读取此页面。',
	'ReadAccessDeniedHintGuest'	=> '要读取此页面，您应该登录。',
	'PageDeletedInfo'			=> '此页面已被删除。',
	'RevisionDeletedInfo'		=> '此版本已被删除。',
	'CommentDeletedInfo'		=> '此评论已被删除。',

	'LastEditedBy'				=> '最后编辑者',
	'YouAreOwner'				=> '您是此页面的所有者。',
	'Owner'						=> '所有者：',
	'Nobody'					=> '没有人',
	'TakeOwnership'				=> '取得所有权',
	'FilesTip'					=> '管理附加文件',
	'FilesText'					=> '附件',
	'DeleteTip'					=> '删除页面、文件和评论',
	'DeleteCommentTip'			=> '删除评论',
	'DeleteText'				=> '删除',
	'AclText'					=> '权限',
	'AclTip'					=> '编辑权限',

	'PropertiesText'			=> '属性',
	'PropertiesTip'				=> '编辑页面属性',
	'EditTip'					=> '编辑此页面。',
	'EditText'					=> '编辑',
	'EditSection'				=> '编辑部分 %1',
	'EditSectionHint'			=> '%1 的 %2',
	'SectionHeadline'			=> '1 P-5, 1 P-4, 1 P-3,',
	'EditCommentTip'			=> '编辑评论',
	'EditComment'				=> '编辑此评论',
	'ReplyComment'				=> '答复',
	'ReplyCommentTip'			=> '回复此评论',
	'RevisionTip'				=> '查看页面修订',
	'RevisionText'				=> '修订版',
	'ReferrersTip'				=> '查看引用此页面的 URL 列表',
	'ReferrersText'				=> '推荐人',
	'ModerateTip'				=> '主题和论坛帖子的管理',
	'ModerateText'				=> '中度',
	'SearchText'				=> '搜索： ',

	'AclUpdated'				=> '访问控制列表已更新',
	'AclGaveOwnership'			=> ' 并授予 %1 所有权。',
	'AclNoNewOwner'				=> '页面所有权未被转移，因为找不到用户 %1。',
	'NewPageOwnership'			=> '已传输的页面所有权',
	'YouAreNewOwner'			=> '原所有者 %1 转移了所有权 ' . "\n" . '跟随您的页面',
	'PageOwnershipInfo'			=> '',
	'AclRead'					=> '读取：',
	'AclWrite'					=> '写入：',
	'AclComment'				=> '评论：',
	'AclCreate'					=> '创建：',
	'AclUpload'					=> '上传：',
	'AclFor'					=> '%1 的访问控制列表',
	'SetOwner'					=> '设置所有者：',
	'OwnerDontChange'			=> '不要更改',
	'AclAccessDenied'			=> '您不是此页面的所有者。',
	'AclSyntaxError'			=> '访问控制列表语法错误',
	'AclHelp'					=> '<code>*</code> - 每个人都被允许<br>' .
									'<code>$</code> - 只有注册用户<br>' .
									'<code>！</code> - 先前的装饰标记拒绝了相应的<br>' .
									'<code>[UserName]</code> - names of allowed users<br>' .
									'<code>[GroupName]</code> - 允许用户组 (别名)<br>' .
									'<code>(空列表)</code> - 只有页面所有者可以访问',

	'AccessMode'				=> '可见性',
	'AccessDenied'				=> '已拒绝',
	'AccessPublic'				=> '公开的',
	'AccessRegistered'			=> '已注册',
	'AccessPrivate'				=> '私人的',
	'AccessCustom'				=> '自定义',

	// purge handler
	'PurgePage'					=> 'Purge page',
	'NotOwnerAndCantPurge'		=> '你不是页面的所有者，你不能清理它。',
	'ReallyPurge'				=> '注意：清除页面是不可逆的 ！',
	'SelectPurgeOptions'		=> '选择必要的清除选项：',
	'PurgeComments'				=> '清除页面的所有评论',
	'CommentsPurged'			=> '所有评论都已删除。',
	'PurgeFiles'				=> '删除所有附加文件',
	'FilesPurged'				=> '所有附加文件都已删除。',
	'PurgeRevisions'			=> '清除页面的所有版本',
	'RevisionsPurged'			=> '对修订案进行了清理。',
	'PurgeButton'				=> 'Purge',

	// categories handler
	'Categories'				=> '类别管理',
	'CategoriesAssign'			=> '分配',
	'CategoriesEdit'			=> '编辑',
	'Category'					=> '类别',
	'CategoriesFor'				=> '类别',
	'CategoriesTip'				=> '编辑类别',
	'CategoriesText'			=> '类别管理',
	'CategoriesUpdated'			=> '类别已更新',
	'CategoriesAlreadyExists'	=> '类别 %1 已经存在。',
	'CategoriesAdded'			=> '分类 %1 添加成功。',
	'CategoriesRenamed'			=> '类别已成功重命名。',
	'CategoriesUngrouped'		=> '分类拆解成功。',
	'CategoriesGrouped'			=> '该类别已输入到新组中。',
	'NoMultilevelGrouping'		=> '不可能有多级分组类别。',
	'CategoriesDeleted'			=> '该类别已从数据库和所有页面删除。',
	'CategoriesAdd'				=> '添加新类别',
	'CategoryDescription'		=> '描述',
	'CategoriesAddGrouped'		=> '按类别分组',
	'CategoriesAddGroupedNo'	=> '没有组。',
	'CategoriesRename'			=> '将 %1 类别重命名为',
	'CategoriesRenameInfo'		=> '* 注意：更改将影响分配给该类别的所有页面。',
	'CategoriesGroup'			=> '%1 分组类别',
	'CategoriesGroupInfo'		=> '* 选择 [无组别] 来拆分类别。',
	'CategoriesNoGroup'			=> '[无组别]',
	'CategoriesDelete'			=> '您确定要删除 %1类别？',
	'CategoriesDeleteInfo'		=> '* 注意：更改将影响分配给该类别的所有页面。 如果该词有子类别，它们将不会被删除，只会被删除掉。',
	'CategoriesStoreInfo'		=> '要将类别分配到一个页面，请选择复选框。',
	'CategoriesStoreButton'		=> '保存类别',
	'CategoriesGroupButton'		=> '组别',
	'CategoriesEditInfo'		=> '要编辑分类列表请选择无线电按钮。',
	'NoCategoriesForThisLang'	=> '未指定此语言的类别。',
	'PagesCategory'				=> '页面类别',
	'CategoryNotExists'			=> '类别不存在。',
	'CategoryEmpty'				=> '类别为空。',
	'NoCategorySelected'		=> '没有选择类别。',
	'NoCategoriesAssigned'		=> '此语言没有分配的类别。',
	'TagCloud'					=> '标签云',
	'PagesTaggedWith'			=> '%1 页面标记为 %2',
	'CategoriesOfCluster'		=> '群组中',
	'TaggedWithTip'				=> '显示标记为 %1 的页面',

	// source handler
	'SourceText'				=> '来源',
	'SourceTip'					=> '查看wiki源',
	'SourceCopyToClipboard'		=> '复制到剪贴板',
	'SourceFor'					=> '查看 %1 的源',

	// Groups action
	'GroupsSearch'				=> '查找组',
	'GroupsNoMatching'			=> '找不到匹配的组。请尝试较不严格的搜索条件。',
	'GroupsOpenProfile'			=> '查看个人资料',
	'GroupsName'				=> '组别',
	'GroupsMembers'				=> '成员',
	'GroupsDescription'			=> '描述',
	'GroupsCreated'				=> '已创建',
	'GroupsNotFound'			=> '%2 组未找到。点击 <a href="%1"></a>前往主列表。',
	'GroupsProfile'				=> '个人信息',
	'GroupsList'				=> '查看整个组列表',
	'GroupSpace'				=> '群组空间',

	'MetaUpdated'				=> '元数据已更新',

	'PreviewButton'				=> '预览',
	'Preview'					=> '预览',
	'Chars'						=> '字符数',
	'PageBody'					=> '页面内容',
	'EditNote'					=> '编辑摘要',
	'EditNoteMissing'			=> '编辑摘要丢失',
	'EditMinor'					=> '次要编辑',
	'MinorEditHide'				=> '隐藏次要编辑',
	'MinorEditShow'				=> '显示次要编辑',
	'PostAnonymously'			=> '匿名发布而不给你的名字',
	'NotifyMe'					=> '通知我新的评论和页面更改',
	'OverwriteAlert'			=> 'OVERWRITE ALERT: This page was modified by someone else while you were editing it.<br>Please copy your changes and re-edit this page.',
	'TextDbOversize'			=> '警告：您的文本超过 %1 个字符。 请将您的文本缩短到可接受的字符数。提示：您可以将其余文本放在单独的页面上。',
	'EditingRevisionWarning'	=> '您正在编辑此页面的旧版本。如果您发布，此后所作的任何更改都将被删除。 <br>您可能希望编辑当前的版本。',
	'WriteAccessDenied'			=> '您没有对此页面的写权限。',
	'EmptyPage'					=> '页面正文为空 - 未保存！',
	'EmptyComment'				=> '评论正文为空 - 未保存！',
	'CommentAccessDenied'		=> '抱歉，您無法發送留言到這個頁面。',
	'CommentFlooded'			=> '发布帖子之间的间隔不应小于 %1 秒。',
	'CommentAdded'				=> '评论已添加。',
	'YouAreNowTheOwner'			=> '您现在是此页面的所有者。',
	'PageSaved'					=> '页面版本 %1 已保存。',
	'CommentSaved'				=> '评论已保存。',

	'RevisionsFor'				=> '%1 版本',
	'DefaultDiffMode'			=> '默认差异模式',
	'DiffMode'		=> [
		'0'		=> '完全差异',
		'1'		=> '简单的差异',
		'2'		=> '来源',
		'3'		=> '并侧的',
		'4'		=> '内联',
		'5'		=> '已合并',
		'6'		=> '统一的',
		'7'		=> '二. 背景',
	],

	'PreviousEdit'				=> '上次编辑',
	'NextEdit'					=> '下次编辑',

	'Diff'						=> '差异',
	'PreviousVersion'			=> '上次修订版',
	'LatestVersion'				=> '最新修订版',
	'NextVersion'				=> '下一次修订版',

	'ShowDifferencesButton'		=> '显示差异',
	'CancelReturnButton'		=> '取消并返回页面',
	'Comparison'				=> '%1 修订版之间的差异',
	'RevisionAsOf'				=> '%1 修订为',
	'SimpleDiffAdditions'		=> '增添：',
	'SimpleDiffDeletions'		=> '删除：',
	'NoDifferences'				=> '没有差异。',
	'ReEditOldRevision'			=> '重新编辑旧版本',

	'ExternalPages'				=> '连接到 %1 (%2)的外部页面(<a href="%3">见域列表</a>):',
	'ExternalPagesGlobal'		=> '链接到此 WackoWiki (%2)的站点(<a href="%1">查看域列表</a>)：',
	'Last24Hours'				=> '过去 24 小时',
	'LastDays'					=> '最近的 %1 天',
	'DomainsSitesPages'			=> '连接到  %1 (%2) 的域/站点页面(<a href="%3">查看不同的 URL</a>)：',
	'DomainsSitesPagesGlobal'	=> '链接到此 WackoWiki 的域/站点(<a href="%1">见不同的 URL</a> 列表)：',
	'ViewReferrersPage'			=> '到页面',
	'ViewReferrersPerPage'		=> '每页',
	'ViewReferrersByTime'		=> '按时间',
	'ViewReferrersGlobal'		=> '全局设置',
	'NoneReferrers'				=> '无',
	'NotOwnerCantDelete'		=> '您不是此页面的所有者，不能删除它',

	// remove
	'RemovePage'				=> '删除页面',
	'RemoveRevision'			=> '删除修订版',
	'RemoveComment'				=> '删除评论',
	'RemoveCluster'				=> '移除集群的所有页面',
	'RemoveDontKeep'			=> '不要保存已删除页面和评论的副本',
	'RemoveDontKeepRevision'	=> '不要保存已删除版本的副本',
	'RemoveDontKeepComment'		=> '不要保存已删除评论的副本',
	'RemoveDontKeepFile'		=> '不要保存已删除文件的副本',
	'ReferrersRemoved'			=> '来源已删除。',
	'LinksRemoved'				=> '链接已删除。',
	'CategoriesRemoved'			=> '页面分类已删除。',
	'AclsRemoved'				=> '页面动作已移除。',
	'BookmarksRemoved'			=> '书签已删除。',
	'WatchesRemoved'			=> '监视已移除。',
	'CommentsRemoved'			=> '从页面删除评论。',
	'FilesRemoved'				=> '从页面删除文件。',
	'PageRemoved'				=> '页面已删除。',
	'PageCachePurged'			=> '缓存已清除。',
	'ClusterRemoved'			=> '群集的所有页面已删除。',
	'RevisionRemoved'			=> '版本 %1 已删除。',
	'RevisionsRemoved'			=> '修改已删除。',
	'ActionHaveNoUndo'			=> '此操作不能撤消。',

	// restore
	'PageRestored'				=> '页面已恢复。',
	'RevisionRestored'			=> '修订已恢复。',
	'LocalFilesRestored'		=> '本地文件已恢复。',

	'PrintVersion'				=> '打印版本',
	'PrintText'					=> '打印',
	'LinkedPages'				=> '链接的页面：',
	'NoLinkedPages'				=> '没有链接的页面',
	'ReferringPages'			=> '参考页面：',
	'NoReferringPages'			=> '没有引用页面',
	'Footnotes'					=> '脚注：',
	'Footnote'					=> '脚注1',
	'MostPopularPages'			=> '最受欢迎的页面',
	'MostCommentedPages'		=> '评论最多的页面',
	'NoAccessToSourcePage'		=> '您无权读取操作源页面。',
	'SourcePageDoesntExist'		=> '操作源页面尚不存在',
	'NotLoggedInThusEdited'		=> '您尚未登录，因此我们无法识别您编辑过的页面。',
	'DidntEditAnyPage'			=> '您还没有编辑任何页面。',
	'NoPagesFound'				=> '未找到页面。',
	'MyChangesTitle1'			=> '这是您编辑过的页面的列表，按您上次更改时间排序',
	'MyChangesTitle2'			=> '这是您编辑的页面列表以及您上次修改的时间',
	'OrderABC'					=> '按字母排序',
	'OrderCreation'				=> '通过创建',
	'OrderChange'				=> '通过更改',
	'ListOwnedPages'			=> '这是您自己的页面列表(按字母顺序排列)',
	'ListOwnedPages2'			=> '这是您自己的页面列表(按日期排序)',
	'ListOwnedPages3'			=> '这是您自己的页面列表 (通过更改排序)',
	'NotLoggedInThusOwned'		=> '您没有登录，因此我们无法检索您的页面。',
	'NoOrphaned'				=> '没有孤立的页面。很好。',
	'NoRecentComments'			=> '最近没有评论。',
	'LatestCommentBy'			=> '最新评论',
	'NoRecentlyCommented'		=> '没有最近评论的页面。',
	'NoDeletedPages'			=> '未找到删除的页面。',
	'NoDeletedRevisions'		=> '未找到删除的版本。',
	'NoDeletedFiles'			=> '未找到删除的文件。',
	'CommentsDisabled'			=> '评论不可用。',

	'SearchResults'				=> '搜索结果 ',
	'NotFound'					=> '找不到',
	'NoResultsFor'				=> '没有结果 ',
	'SearchFor'					=> '搜索：',
	'TopicSearchResults'		=> '主题搜索结果 ',
	'NotFoundInTopics'			=> '在主题中未找到',
	'FilterLangNotAvailable'	=> '所选语言不可用！',

	'PostedBy'					=> '发表者：',
	'ThisIsCommentOn'			=> '这是评论于',
	'At'						=> '在',
	'To'						=> '到',
	'By'						=> '由',
	'From'						=> '来自',
	'For'						=> '为',
	'ReturnToCommented'			=> '返回评论页面',
	'AbandonedComment'			=> '此评论所属的页面不再存在！',

	'PagesLinkingTo'			=> '链接到',
	'NoPageLinkingTo'			=> '没有页面链接到',
	'NoWantedPages'				=> '没有想要的页面。很好。',
	'RemoveWatch'				=> '删除此页面的观察',
	'SetWatch'					=> '观看此页',
	'WatchText'					=> '观察',
	'UnwatchText'				=> '未关注',
	'UserSettingsStored'		=> '用户设置已保存。',
	'LoggedOut'					=> '您现在已登出。',
	'LoggedOutAuto'				=> '为了安全起见，您的会话已经结束。请重新登录。',

	// user settings
	'EmailConfirmResent'		=> '电子邮件确认码已重新发送到您的地址。',
	'EmailConfirmNotSent'		=> '无法发送确认码：未指定电子邮件！',
	'Hello'						=> '您好',
	'UserName'					=> '用户名',
	'EmailAddress'				=> '电子邮件地址',
	'RealName'					=> '真实姓名',
	'MenuItemsShown'			=> '显示菜单项',
	'RecordsPerPage'			=> '每页记录数',
	'DoShowComments'			=> '默认情况下显示评论',
	'DoubleclickEditing'		=> '双击编辑',
	'UpdateSettingsButton'		=> '更新设置',

	'AccountDisabled'			=> '您的帐户可能被禁用或封禁。',
	'WrongPassword'				=> '密码错误！',
	'ConfirmPassword'			=> '确认密码',
	'Email'						=> '电子邮件地址',
	'MustBeWikiName'			=> '用户名必须是 <a href="https://wackowiki.org/doc/Doc/English/WikiName" target="_blank">Wikiname</a> 格式化！',
	'SpecifyEmail'				=> '您必须指定一个电子邮件地址。',
	'NotAEmail'					=> '这看起来不是一个有效的电子邮件地址。',
	'EmailTaken'				=> '输入的电子邮件地址已被使用。',
	'EmailDomainNotAllowed'		=> '输入的电子邮件地址 %1 不在允许的域名列表中。',
	'PasswordsDidntMatch'		=> '密码不匹配。',
	'SpacesArentAllowed'		=> '密码中不允许有空格。',
	'ListMyPages'				=> '列出您的页面',
	'ListMyChanges'				=> '列出您的更改',
	'ListMyWatches'				=> '已观看页面列表',
	'ListMyChangesWatches'		=> '已观看页面之间的变化',
	'SeeListOfPages'			=> '查看您自己的页面列表 (MyPages) 和您已编辑的页面(MyChanges)。',
	'AddBookmark'				=> '将当前页面添加到书签',
	'RemoveBookmark'			=> '从书签删除',

	'YourLanguage'				=> '选择语言',
	'ShowSpaces'				=> '在维基名称中显示空格',
	'WrongPage4Redirect'		=> '无法重定向，因为重定向参数错误',
	'RedirectsToItself'			=> '页面重定向到自己。',
	'ReallyDeletePage'			=> '您真的想要删除此页面吗？<br>此操作没有撤销！<br><br>警告：删除此页面将删除所有页面版本、注释、附件、ACL和推荐人。',
	'CommentForWatchedPage'		=> '新建页面评论 ',
	'SomeoneCommented'			=> ' 评论您正在观看的这个页面： ',
	'AlertReferringPages'		=> '这个页面被这些页面引用',

	'AccountDelete'				=> '删除帐户',
	'AccountDeleteConfirm'		=> '您确定要删除该帐户吗？',
	'AccountDeleted'			=> '帐户删除成功',
	'AccountDeleteHeader'		=> '删除帐户 %1',
	'AccountDeleteInfo'			=> '您创建的数据(例如电子邮件、首选项、附件、维基条目)将被尽可能地删除。 但请注意，像附件和维基条目这样的数据不能在不妨碍其他用户工作的情况下被删除。 因此这种数据被重新分配到一个叫做 %1的帐户。 由于每个已删除的帐户的数据都已重新分配到该帐户，所以无法区分您创建的数据和另一个已删除帐户的数据。',
	'AccountDeleteWarning'		=> '删除用户帐户是一个不可逆的操作。',
	'AccountDeleteHint'			=> '您的帐户将从系统中删除。因此，您将无法使用您当前的凭据登录。 如果您选择再次成为此应用程序的用户，您可以通过使用此应用程序授予的方式来做到这一点。',
	'AccountDeleteVerify'		=> '输入您的登录 %1 以验证删除。提交后，您将被要求确认您的密码。',

	'MarkRead'					=> '全部标记为已读',
	'CurrentTime'				=> '目前是',
	'Created'					=> '已创建',
	'Modified'					=> '已修改',

	'EditIcon'					=> '编辑',
	'TreeClusterTitle'			=> 'Tree of cluster %1',
	'TreeSiteTitle'				=> '站点树',
	'TreeEmpty'					=> '%1 没有子页面',
	'TreeEmptyLevels'			=> '%1 没有给定深度水平的子页面。增加深度值。',
	'TreeTooBig'				=> '太多子页面',

	// clone handler
	'ClonePage'					=> '复制页面',
	'CloneText'					=> '克隆...',
	'CloneName'					=> '输入此页面克隆的新名称',
	'CloneButton'				=> '克隆...',
	'PageCloned'				=> '页面 %1 已被克隆。',
	'ClonedFrom'				=> '从 %1 克隆。',
	'MassClone'					=> '克隆整个数据组',
	'MassCloning'				=> '克隆集群。',
	'CloneCannotRead'			=> '不可读页面 %1。',
	'CloneCannotCreate'			=> '不可创建页面 %1。',

	'SortComment'				=> '评论排序方式',
	'SortCommentAsc'			=> '最近在底部',
	'SortCommentDesc'			=> '最近在顶部',

	'RenamePage'				=> '重命名页面',
	'RenameText'				=> '重命名：',
	'RenameTip'					=> '重命名页面',
	'NewName'					=> '输入此页面的新名称',
	'AlreadyExists'				=> '页面 %1 已经存在。',
	'AlreadyNamed'				=> '此页面已命名为 %1',
	'PageRenamed'				=> '页面已重命名。',
	'NewNameOfPage'				=> '此页面的新名称： ',
	'NotOwnerCantRename'		=> '您不是此页面的所有者，因此无法重命名它',
	'NeedRedirect'				=> '创建重定向到旧页面的新页面',
	'RedirectCreated'			=> 'In the page %1 created redirect to the new one',

	'UserSettings'				=> '用户设置',
	'UserSettingsGeneral'		=> 'A. 概况',
	'UserSettingsNotifications'	=> '通知',

	'NotifyMinorEdit'			=> '同时通知次要编辑',
	'NotifyPageEdit'			=> '编辑',
	'NotifyComment'				=> '评论',
	'NotifyOff'					=> '关闭',
	'NotifyAlways'				=> '总是显示',
	'NotifyPending'				=> '待定',
	'NotifyDigest'				=> '摘要',
	'NotifyPendingPageTip'		=> '对于您正在观看的页面的第一页更改，只发送了一个通知。',
	'NotifyPendingCommentTip'	=> '只有一个通知被发送给您正在观看的一个页面。',
	'NotifyPendingTip'			=> '当您访问当前版本的页面时，通知将自动重新启用。',

	'FurtherPending'			=> '除非您访问此页面否则没有其他通知。',

	'UserSettingsEmailMe'		=> '给我发电子邮件...',

	'UserSettingsExtended'		=> '扩展',
	'UserSettingsOther'			=> '其他设置',
	'UserSpace'					=> '用户空间',
	'ChooseTheme'				=> '选择主题',

	'CreatePage'				=> '创建此页面',
	'CreateNewPage'				=> '创建一个新页面',
	'CreateNewPageText'			=> '创建',
	'CreateNewPageTip'			=> '创建一个新页面',

	'CreateRandomPage'			=> '创建一个随机页面：',
	'CreateSubPage'				=> '在集群中创建子页面：',
	'CreatePageParentCluster'	=> '在父集群中创建页面：',
	'CreatePageDenied'			=> '您没有必要的访问权限。',
	'CreatePageDeniedAddress'	=> '您无权在此地址创建页面。',
	'PageAlreadyExists'			=> '根据提供的地址，页面 %1 已经存在。',
	'PageAlreadyExistsEdit'		=> '您想要 %1 吗？',
	'PageAlreadyExistsEdit2'	=> '编辑',
	'PageAlreadyExistsEditDenied'	=> '您不能编辑它。',

	'SimilarPagesExists'		=> '与 %1 相似的页面已经存在：',
	'SimilarPagesHint'			=> '%1 存在类似的页面：',

	'PageReservedWord'			=> '您不能使用 %1 作为地址的一部分，因为这是一个保留词。',
	'UserReservedWord'			=> '用户名不能包含 %1 作为一个保留词。',

	'DontRedirect'				=> '不允许动作重定向自动重定向。',
	'SendWatchEmail'			=> '当有人(不包括您)更改您关注的任何页面时，发送通知邮件',
	'AllowIntercom'				=> '允许来自系统用户的个人消息',
	'AllowMassemail'			=> '管理员可以发送电子邮件给我信息',
	'HideLastSession'			=> '隐藏上次会话',
	'ValidateIP'				=> '连接到IP的会话',
	'AnonymousPub'				=> '最好匿名发布(隐藏名称)',
	'PageMoved'					=> '此页面被移动。您可以在',
	'RedirectedFrom'			=> '重定向从 %1',
	'RedirectedTo'				=> '重定向到',
	'CurrentPassword'			=> '当前密码',
	'NewPassword'				=> '新密码',
	'YouWantChangePassword'		=> '更改密码',
	'ChangePasswordButton'		=> '更改密码',
	'PasswordChanged'			=> '密码已更改',
	'EmailWelcome'				=> '您已注册于 ',
	'EmailRegistered'			=> '您已成功注册到 %1。' . "\n" . '您的用户名： %2' . "\n\n",
	'EmailVerify'				=> '如果您想要接收通知，您必须验证您的电子邮件地址。请点击或复制以下链接到网页浏览器： ' . "\n" . '%1',
	'EmailRegisteredLogin'		=> '请返回Wiki并使用您的新用户名和密码登录。',
	'EmailRegisteredIgnore'		=> '如果您没有请求此注册，忽略此消息，不会发生任何事情。',
	'EmailDoNotReply'			=> '不回复此消息。',
	'EmailReverify'				=> '有人(可能是你)在 %1 上提交了您的电子邮件通知地址。' . "\n" . '您的用户名： %2'."\n\n" . '如果您想要接收通知，您需要批准您的电子邮件。请点击链接进行此操作。' . "\n" . '%3' . "\n\n",
	'EmailConfirm'				=> '请验证您的电子邮件',
	'EmailConfirmed'			=> '电子邮件已成功确认。',
	'EmailNotConfirmed'			=> '无法确认电子邮件。这可能是由于验证码不正确或电子邮件地址可能已被确认。 您可以在您的 %1 页面登录和查看其状态是否已经确认电子邮件地址。',
	'EmailNotVerified'			=> '电子邮件未验证！',
	'EmailNotVerifiedDesc'		=> '您将不会收到更改通知或已查看页面的评论， ' .
									'或者来自其他用户的消息。另外，您 <strong>将无法恢复忘记的密码</strong> ' .
									'直到您的电子邮件地址通过关注发送给您的电子邮件中的链接得到确认。 ' .
									'如果在注册后几天内您没有收到一封电子邮件，点击后再次询问它 ',

	'ForgotPasswordHint'		=> '输入您的登录和电子邮件地址。' . "\n" . '然后会向您发送一封包含说明的电子邮件。',
	'ForgotPassword'			=> '忘记密码？',
	'UserNotFound'				=> '找不到具有此名称或电子邮件地址的用户。',
	'NotConfirmedEmail'			=> '您的电子邮件地址未被确认。<br>邮件不能发送到一个未确认的地址。',
	'EmailForgotSubject'		=> '密码更新为 ',
	'EmailForgotMessage'		=> '有人(可能是你)忘记了您的 %1 密码。' . "\n" . '您的登录名: %2'."\n\n" . '点击链接或将其复制到浏览器地址行以更改您的密码。' . "\n" . '%3'."\n\n",
	'CodeWasSent'				=> '密码恢复指示已通过电子邮件发送给您。',
	'WrongCode'					=> '错误的代码',
	'ChangePasswordForUser'		=> '%1的密码更改',

	'Watchers'					=> '%1的关注者列表',
	'WatchersFor'				=> '关注者',
	'NoWatchers'				=> '%1 没有关注者',
	'NotOwnerToViewWatchers'	=> '您不是这个页面的所有者，不能看到这个页面的关注者列表。',

	// thumbnail
	'TbnError'					=> '创建缩略图时出错： %1',
	'TbnImageAreaTooBig'		=> '尺寸大于 %1 的文件',
	'TbnImageMissing'			=> '文件似乎丢失： %1',

	// admin_recovery action
	'GenerateRecoveryHash'		=> 'Generate the password hash for your <code>recovery_password</code>',

	// import action
	'ImportTo'					=> '导入集群：',
	'ImportWhat'				=> '要导入的 XML 文件：',
	'ImportButton'				=> '导入',
	'ImportSuccess'				=> '导入成功。',
	'ImportFailed'				=> 'IMPORT 失败。',
	'ImportHint'				=> '请提供您想要导入到没有相对地址的集群。',
	'ImportAttention'			=> '注意：覆盖集群中相同的页面。',
	'ImportNote'				=> '导入页面',

	// mywatches action
	'WatchedPages'				=> '更改所关注的所有页面列表 ',
	'UnwatchedPages'			=> '您不观看的所有页面列表',
	'NoWatchedPages'			=> '您没有关注过的页面。',
	'NoUnwatchedPages'			=> '您正在关注所有页面中的更改。',
	'ViewWatchedPages'			=> '显示已观看页面',
	'ViewUnwatchedPages'		=> '显示未观看的页面',
	'NotLoggedInWatches'		=> '您没有登录，因此我们无法识别您的观察列表。',

	// mychangeswatches action
	'MyChangesWatches'			=> '自您上次编辑以来被他人编辑的所有页面列表',
	'ResetChangesWatches'		=> '重置更改列表',
	'NoChangesWatches'			=> '您所关注的页面中没有变化...',

	// whatsnew action
	'NewCommentAdded'			=> '添加新评论',
	'NewFileAdded'				=> '添加新文件',
	'NewPageCreated'			=> '创建了一个新页面',
	'NewRevisionAdded'			=> '更改页面',
	'Cluster'					=> '群組',
	'PageDeleted'				=> '页面已删除',
	'CommentDeleted'			=> '评论已删除',
	'FileDeleted'				=> '文件已删除',

	// users action
	'UsersSearch'				=> '查找用户',
	'UsersOpenProfile'			=> '查看个人资料',
	'UsersNoMatching'			=> '找不到匹配的用户。请尝试较不严格的搜索条件。',
	'UsersName'					=> '名称',
	'UsersPages'				=> '页 次',
	'UsersChanges'				=> '更改',
	'UsersSubscription'			=> '订阅',
	'UsersWatches'				=> '观察',
	'UsersComments'				=> '评论',
	'UsersUploads'				=> '上传',
	'UploadQuota'				=> '已用空间',
	'UploadQuotaTip'			=> '上传空格数',
	'UsersLogins'				=> '登录',
	'UsersRevisions'			=> '修订版',
	'UsersSignup'				=> '注册',
	'UsersLastSession'			=> '上届会议',
	'UsersNotFound'				=> '找不到用户 %2 。点击 <a href="%1">这里</a>去到主列表。',
	'UsersProfile'				=> '个人信息',
	'UsersContact'				=> '聯繫人',
	'UsersList'					=> '查看整个用户列表',
	'UsersNA'					=> '[未设置]',
	'UsersNA2'					=> '[No]',
	'UsersSignupDate'			=> '注册日期',
	'UsersGroupMembership'		=> '群组成员',
	'UsersPersonalInfo'			=> '个人信息',
	'UsersOwnedPages'			=> '拥有页面：',
	'UsersCommentsPosted'		=> '已发布的评论：',
	'UsersFilesUploaded'		=> '文件已上传：',
	'UsersRevisionsMade'		=> '已修改：',
	'UsersDocsSortName'			=> '[按名称排序]',
	'UsersDocsSortCreation'		=> '[按创建日期排序]',
	'UsersChangesSortAsc'		=> '[排序升序]',
	'UsersChangesSortDesc'		=> '[排序降序]',
	'UsersSessionNA'			=> '[未记录]',
	'UsersSessionHidden'		=> '[hidden]',
	'IntercomSubject'			=> '主题：',
	'IntercomMessage'			=> '消息：',
	'IntercomCopy'				=> '给我发送一份副本',
	'IntercomSubjectN'			=> '[开始一个新主题]',
	'IntercomDisabled'			=> '抱歉，您不想要或无法接收个人消息。',
	'IntercomHint'				=> '如果您想要回答您收到的个人信息，请先登录并再次点击链接。',
	'IntercomDesc'				=> '注意：发送邮件收件人上传的个人信息时不披露您的地址。 收件人将能够在您的个人资料页面上使用类似的表单回复您。 ',
	'PMOversized'				=> '消息长度超过 %1的最大允许大小。请缩短您的消息并再次提交。',
	'PMFlooded'					=> '发送个人消息之间的间隔不应小于 %1 秒。',
	'PMSent'					=> '个人信息已成功发送给用户。',
	'PMBody'					=> '此消息已由用户 %1 发送给您。',
	'PMBodyCopy'				=> '您向用户 %1 发送了以下消息。',
	'PMReply'					=> '要回答此电子邮件，请点击以下链接 (不在邮件中使用回复按钮 / 回复)：',
	'PMNotLoggedIn'				=> '您没有在系统中注册，无法向用户发送个人消息。',

	// admin_replace action
	'ReplaceText'				=> '替换文本',
	'TextOriginal'				=> '原文：',
	'TextReplacement'			=> '替换文本：',
	'ReplaceTextRegex'			=> '使用正则表达式',
	'Namespace'					=> '命名空间：',
	'ReplaceTextCluster'		=> '仅在此集群中搜索并替换：',
	'ReplaceTextEditPages'		=> '替换页面内容中的文本',
	'ReplaceTextEditComments'	=> '替换评论中的文本',
	'ReplaceTextEditTitles'		=> '替换页面标题中的文本',
	'ReplaceTextGiveTarget'		=> '您必须指定要替换的字符串。',
	'ReplaceTextNoNamespace'	=> '您必须选择至少一个命名。',
	'ReplaceTextNoDifference'	=> '替换文本和目标文本之间没有区别。',
	'ReplaceTextNoOption'		=> '您必须选择至少一个替换选项。',
	'ReplaceTextPagesEdit'		=> 'Replace %1 with %2 in the text of the following %3 pages:',
	'ReplaceTextTitlesEdit'		=> 'Replace %1 with %2 in the titles of the following %3 pages:',
	'ReplaceTextReplace'		=> '替换',
	'ReplaceTextSuccess'		=> '%1 已被 %2 在 %3 页面替代。',
	'ReplaceTextNoMatch'		=> '没有找到包含字符串 %1 的页面。',
	'ReplaceTextNoTitleMatch'	=> '找不到标题包含 %1 的页面。',
	'ReplaceTextEditFailed'		=> '替换文本失败',
	'ReplaceTextTitleTooBig'	=> '原始文本或替换文本对标题太大。',
	'ReplaceTextReturn'			=> '返回表单',
	'ReplaceTextWarning'		=> '警告： %1 页面已经包含替换字符串， %2。 如果你做了这个替换，你将无法将你的替换与这些字符串分开。',
	'ReplaceTextBlankWarning'	=> '警告：由于替换字符串为空，此操作将不可逆。',
	'ReplaceTextEditSummary'	=> '文本替换： %1 -> %2',
	'InvertSelection'			=> '反转选择',

	// Properties
	'PropertiesFor'				=> '%1 的页面属性',
	'MetaTag'					=> '标签',
	'MetaTitle'					=> '标题',
	'MetaKeywords'				=> '关键字',
	'MetaDescription'			=> '描述',
	'On'						=> '开启',
	'Off'						=> '关闭',
	'Registered'				=> '已注册',
	'MetaComments'				=> '显示评论',
	'MetaFiles'					=> '显示文件面板',
	'MetaToc'					=> '显示目录',
	'MetaIndex'					=> '显示群集部分面板',
	'MetaIndexMode'				=> '显示级别模式',
	'MetaIndexFull'				=> '树',
	'MetaIndexUpper'			=> '上方',
	'MetaIndexLower'			=> '较低',
	'MetaHtml'					=> 'HTML支持页面',
	'MetaSafeHtml'				=> '过滤不安全的 HTML',
	'MetaTypografica'			=> '图形校验器',
	'MetaNoIndex'				=> '屏蔽搜索引擎',
	'SettingsID'				=> '页面 ID',
	'SettingsSize'				=> '大小',
	'SettingsSizeTip'			=> '源 / 已编译',
	'SettingsCreated'			=> '已创建',
	'SettingsCurrent'			=> '已修改',
	'SettingsTotalRevs'			=> '修订版',
	'SettingsTotalComs'			=> '评论',
	'SettingsWatchers'			=> '观看者',
	'SettingsHits'				=> '视图',
	'SettingsText'				=> '设置',
	'SettingsEdit'				=> '编辑',
	'SettingsRevisions'			=> '修订版',
	'SettingsClone'				=> '克隆...',
	'SettingsRename'			=> '重命名：',
	'MassRename'				=> '适用于整个组',
	'SettingsRemove'			=> '删除',
	'SettingsPurge'				=> 'Purge',
	'SettingsModerate'			=> '中度',
	'SettingsPermissions'		=> '权限',
	'AclForEntireCluster'		=> '适用于整个组',
	'SettingsAttachments'		=> '附件',
	'SettingsUpload'			=> '上传',
	'SettingsCategories'		=> '类别管理',
	'SettingsLanguages'			=> '语文',
	'SettingsReferrers'			=> '推荐人',
	'SettingsWatch'				=> '观察',
	'SettingsLatex'				=> 'LaTeX 版本',
	'SettingsXML'				=> '导出为 XML',
	'NeedToChangeLang'			=> '不支持的页面语言 %1 需要更改。',
	'SetLang'					=> '此页面的语言',
	'SetMenuLabel'				=> '菜单标签',
	'SetShowMenuLabel'			=> '在导航中显示',

	// upload
	'UploadFiles'				=> '上传文件',
	'UploadFor'					=> '文件上传：',
	'UploadButton'				=> '上传',
	'UploadGlobalText'			=> '公共访问',
	'UploadGlobal'				=> '全局设置',
	'UploadLocalText'			=> '只允许用户查看当前页面',
	'UploadAsName'				=> '姓名：',
	'UploadOverwrite'			=> '覆盖现有文件',
	'FileDesc'					=> '描述：',
	'UploadForbidden'			=> '您无权在此上传文件。',
	'UploadOverwriteDenied'		=> '只有文件所有者或管理员可以覆盖 %1 文件。',
	'UploadNoFile'				=> '由于某种原因，没有任何形式的文件。',
	'UploadMaxSizeReached'		=> '文件大小超过允许的限制！',
	'UploadDirNotWritable'		=> '文件目录不可写入！',
	'UploadNotAPicture'			=> '只允许上传图片。您正在尝试上传什么？',
	'UploadEmptyExtension'		=> '文件名和扩展名不能为空。',
	'FilenameTooLong'			=> '文件名不能超过 240 字节。',
	'BannedFiletype'			=> '%1 不是允许的文件类型。',
	'PermittedFiletype'			=> '允许的文件类型：',
	'UploadMimeMismatch'		=> '文件扩展名 %1 与检测到的 MIME 类型不匹配(%2)。',
	'UploadBadMime'				=> '不允许上传 MIME 类型的 %1 文件。',
	'FileIsDuplicate'			=> '上传是当前版本的确切重复。',
	'FileHasDuplicate'			=> '此文件是以下文件的副本：',

	'UploadMaxFileQuota'		=> '您已达到上传限制。无法上传此文件',
	'UploadDone'				=> '文件上传成功',
	'UploadFileForbidden'		=> '禁止文件访问',
	'UploadTitle'				=> '从此页面可以访问的文件',
	'UploadTitleGlobal'			=> '文件可从任何地方访问',

	'UploadFile'				=> '上传',
	'UploadMax'					=> '不超过 ',
	'UploadUsedStorage'			=> '正在使用的存储 ',

	// attachments
	'Attachments'				=> '附件',
	'Attachment'				=> '附文',
	'AttachmentsToPage'			=> '到页面',
	'AttachmentsToCluster'		=> '群組',
	'AttachmentsByTime'			=> '按时间',
	'AttachmentsGlobal'			=> '全局设置',
	'AttachmentsAll'			=> '所有的',
	'AttachmentsLinked'			=> '已使用',

	'FileViewProperties'		=> '查看',
	'FileViewPropertiesTip'		=> '查看此文件的元数据',
	'FileEditProperties'		=> '编辑',
	'FileEditPropertiesTip'		=> '编辑此文件的元数据',
	'FileEditedMeta'			=> '更新此文件的元数据',
	'FileEditDenied'			=> '您无权编辑此文件',
	'FileLabel'					=> '标签',
	'FileLabelTip'				=> '标记此文件',
	'FileRemove'				=> '删除',
	'FileRemovedFromDB'			=> '从数据库中删除文件',
	'FileRemovedFromFS'			=> '从物理主机擦除文件',
	'FileRemovedFromFSError'	=> '似乎无法擦除文件！',
	'FileRemoveConfirm'			=> '确定要删除此文件吗？',
	'FileRemoveDenied'			=> '您无权删除此文件',
	'FileNotFound'				=> '找不到文件。',

	'FileSearch'				=> '查找文件',
	'UploadBy'					=> '上传者：',
	'FileAdded'					=> '添加：',
	'FileModified'				=> '已修改：',
	'FileSize'					=> '大小：',
	'FileDimension'				=> '尺寸：',
	'MimeType'					=> 'Mimetype：',
	'FileName'					=> '姓名：',
	'FileCaption'				=> '标题：',
	'FileAuthor'				=> '作者：',
	'FileSource'				=> '资料来源：',
	'FileSourceUrl'				=> 'URL：',
	'FileAttachedTo'			=> '附加到：',
	'FileSyntax'				=> '语法：',
	'FileAbsolutePath'			=> '绝对路径',
	'FileRelativePath'			=> '相对路径',
	'FileUsage'					=> '文件用法：',
	'FileUsageText'				=> '以下页面链接到此文件：',
	'NoFileUsage'				=> '没有页面链接到此文件。',

	'FileSortExt'				=> '扩展',
	'FileSortName'				=> '名称',
	'FileSortSize'				=> '大小',
	'FileSortTime'				=> '已创建',

	'SortBy'					=> '排序方式',
	'Ascending'					=> '升序排序',
	'Decending'					=> '十月',

	'Files0'					=> '附加文件',
	'Files1'					=> '显示文件 (1 个文件)',
	'FilesN'					=> '显示文件 (%1 文件)',
	'Files'						=> '文件',
	'File'						=> '文件',
	'ShowFiles'					=> '显示文件/表单',
	'HideFiles'					=> '隐藏文件/表单',
	'DoShowFiles'				=> '默认显示文件列表',
	'NoAttachments'				=> '没有要显示的附加文件。',

	'RegistrationLang'			=> '您的语言',
	'InvalidWikiName'			=> '所选名称无效',
	'InvalidUserName'			=> '所选用户名无效',
	'Bookmarks'					=> '书签',
	'ReallyDeleteComment'		=> '您真的想要删除此评论吗？<br>此操作没有撤销！',
	'ReallyDeleteRevision'		=> '您真的想要删除此修订吗？<br>此操作没有撤销！',

	'RegistrationClosed'		=> '注册不可用。请尝试联系站点管理员。',
	'AclAreYouSure'				=> '您将更改此页面及其所有子页面的 ACL。是否继续？',

	'BookmarkDeleteSelected'	=> '删除选中的',
	'BookmarkMark'				=> '标记',
	'BookmarkNumber'			=> '否。',
	'BookmarkNone'				=> '您没有书签。',
	'BookmarkTitle'				=> '书签标题',
	'BookmarkPage'				=> '页',
	'BookmarkSaveChanges'		=> '保存更改',
	'BookmarksAddPage'			=> '为以下页面设置书签',
	'BookmarkAlreadyExists'		=> '书签已经存在。',

	'PoweredBy'					=> '支持者：',

	'MassRenaming'				=> '重命名整个分组',
	'MassNewName'				=> '为此集群输入新名称',
	'MassNeedRedirect'			=> '创建重定向到旧页面上的新页面',

	// pagination
	'ToOverview'				=> '返回概览',
	'Overview'					=> '概览',
	'ToThePage'					=> '到页：',
	'Next'						=> '下一个',
	'Prev'						=> '上一个',
	'NextAcr'					=> '下一个',
	'PrevAcr'					=> '上一个',
	'Back'						=> '后退',

	// filter
	'Filter'					=> '筛选器',
	'OptionalFilters'			=> '可选过滤器：',
	'Any'						=> '任何',

	// My Groups
	'UserGroups'				=> '用户组',
	'MyGroups'					=> '群组关联',
	'Group'						=> '群組',
	'Groups'					=> '组',

	// license action
	'DistributedUnder'			=> '材料分布在',
	'AuthorsDisplayHint'		=> '保存页面时将显示作者列表。',
	'AnonymousUsers'			=> '匿名用户',
	'License'					=> '许可协议',
	'LicenseArray'				=> [
		'1'		=> '署名-禁止演示符',
		'2'		=> '署名-非商业性分享-相同方式共享',
		'3'		=> '署名-非商业性-禁止演示符',
		'4'		=> '署名-相同方式共享',
		'5'		=> '署名-非商业化',
		'6'		=> '属性',
		'7'		=> 'CC0 1.0 Universal',
		'8'		=> 'GNU 免费文档许可证',
		'9'		=> '公共域名/免费使用',
		'10'	=> '版权所有',
	],
	'LicenseMeta'				=> [
		'1'		=> '公共域',
		'2'		=> '保留某些权利',
		'3'		=> '版权所有',
	],

	// Cache
	'ClearCache'				=> '清除缓存',
	'CacheCleared'				=> '缓存已清除。',
	'ConfigCache'				=> '配置缓存',
	'FeedCache'					=> '新闻源缓存',
	'PageCache'					=> '页面缓存',
	'SQLCache'					=> 'SQL 缓存',
	'TemplateCache'				=> '模板缓存',
	'ThumbCache'				=> 'Thumbnail cache',

	// Embed
	'EmbedNoURL'				=> '请指定一个带参数URL的资源地址(例如，{{embed url="https://example.com/embed/video.mp4"}} )',

	// Feed
	'FeedTitle'					=> '新闻源标题',
	'FeedMulti'					=> '多种源',
	'FeedNoURL'					=> '请指定一个带参数URL的主页(例如{{feed url="https://example.com/feed.xml"}} )',
	'FeedError'					=> '无法加载或解析feed',
	'FeedSource'				=> '资料来源：',
	'FeedXMLTip'				=> '',

	// XML / RSS autodiscovery
	'ChangesXMLTitle'			=> ' - 最近的变化',
	'ChangesXML'				=> '最近更改到 ',
	'CommentsXMLTitle'			=> ' - 最近评论',
	'CommentsXML'				=> '最近发表的评论 ',
	'NewsXMLTitle'				=> ' - 最近的新闻',
	'NewsXML'					=> '最近发布的消息 ',
	'RevisionXMLTip'			=> '单击以XML格式查看最近的页面修订。',
	'CommentsXMLTip'			=> '单击以XML格式查看最近的评论。',
	'ChangesXMLTip'				=> '点击查看XML格式的最近更改。',
	'NewsXMLTip'				=> '单击以XML格式查看最新消息。',
	'RevisionsXML'				=> '修订版本 ',
	'ExportClusterXML'			=> '导出整个群集 ',
	'AccessDeniedXML'			=> '您无权访问此信息。',

	'ChangesFeed'				=> '更改',
	'CommentsFeed'				=> '评论',
	'NewsFeed'					=> '新闻',
	'RevisionsFeed'				=> '修订版本 ',

	'LastModification'			=> '最后修改',

	// Captcha
	'Captcha'					=> '请在图像中输入您所读的单词',
	'CaptchaFailed'				=> '您输入的验证码不正确。请再试一次。',
	'CaptchaReload'				=> '新建验证码',
	'CaptchaReloadWarning'		=> '抱歉，无法重新加载验证码图像，您将需要重新加载页面才能做到这一点。',

	// news
	'News'						=> '新闻',
	'NewsName'					=> '标题：',
	'NewsNoName'				=> '你忘了添加新闻标题。',
	'NewsNotAvailable'			=> '没有可用的新闻。',
	'NewsNoClusterDefined'		=> '未定义新闻组。',
	'NewsDiscuss'				=> '讨论这篇文章...',

	// blog
	'BlogNewTopic'				=> '创建一个新帖子',
	'NoPostAvailable'			=> '还没有可用的文章。',

	// Review
	'Reviewer'					=> '审核者',
	'Reviewed'					=> '已审核',
	'Review'					=> '审查',
	'ReviewedBy'				=> '审核者',
	'RemoveReview'				=> '删除此页面的评论',
	'SetReview'					=> '已审核此页面',
	'SetAsReviewed'				=> '将页面设置为已审核',
	'SetAsUnreviewed'			=> '将页面设置为未审核页面',

	// word filter
	'PotentialSpam'				=> '已识别的潜在垃圾信息',

	// moderation handler
	'Moderation'				=> '审核',
	'Topics'					=> '主题',
	'ModerateSection'			=> '部分 / 页面 ',

	'NotModerator'				=> '您无权管理此页面/章节',
	'ModerateDeleteTopic'		=> '删除主题 / 页面',
	'ModerateDeletePosts'		=> '删除评论',
	'ModerateMove'				=> '移动',
	'ModerateSplit'				=> '拆分/移动评论',
	'ModerateMerge'				=> '合并',
	'ModerateLock'				=> '锁定',
	'ModerateUnlock'			=> '解锁',
	'ModerateAccept'			=> '接受',
	'ModerateDeleteConfirm'		=> 'Are you sure you want to <strong>remove</strong> the following topics?',
	'ModerateRenameConfirm'		=> '输入所选页面的新标题',
	'ModerateRenameExists'		=> '已存在具有相同名称的页面！选择不同的名称。',
	'ModerateRename1Only'		=> '注意：您选择的第一个页面将被重命名！',
	'ModerateMovesConfirm'		=> '选择目标分区移动到论坛',
	'ModerateMoveConfirm'		=> '选择论坛或指定要移动这些主题的集群。要移动一个页面到站点根目录，请输入 &quot;/&quot;',
	'ModeratePgMoveConfirm'		=> '指定要放置页面的集群名称。 要移动页面到站点根目录，请输入 &quot;/&quot;',
	'ModerateMoveExists'		=> '操作中止：在本节中已经存在具有相同名称 %1的主题。 如果您仍然需要转移上述主题，请先重命名它们。',
	'ModerateMoveNotExists'		=> '页面/集群不存在。请检查名称并重试。',
	'ModerateMergeConfirm'		=> '选择一个主题，将余下的主题合并',
	'ModerateMerge2Min'			=> '要加入，您必须选择至少两个主题！',
	'ModerateComDelConfirm'		=> 'Are you sure you want to <strong>remove</strong> %1 %2?',
	'ModerateComment'			=> '评论',
	'ModerateComments'			=> '评论',
	'ModerateSplitNewName'		=> '指定一个可分离主题的名称并选择一个分离模式',
	'ModerateSplitPageName'		=> '输入页面/主题的名称，移动不可更改的评论，并选择分离模式',
	'ModerateSplitAllAfter'		=> '在首次选择(和包括)后拆除所有评论',
	'ModerateSplitSelected'		=> '只分离选中的评论 (总计 %1)',
	'ModerateUserProfile'		=> '个人信息',
	'ModerateNoItemChosen'		=> '请通过设置按钮选择至少一个项目。',

	'ModerateSection2'			=> '管理部分',
	'ModerateTopicsDeleted'		=> '已成功删除选定的主题。',
	'ModerateTopicsRelocated'	=> '选定的主题已成功迁移。',
	'ModerateTopicsRenamed'		=> '主题已成功重命名。',
	'ModerateTopicsMerged'		=> '选定的主题已成功合并。',
	'ModerateTopicsBlocked'		=> '已成功阻止选定的主题',
	'ModerateTopicsUnlocked'	=> '所选主题解锁成功。',
	'ModerateTopicDeleted'		=> '主题已成功删除。',
	'ModeratePageMoved'			=> '页面成功移动。',
	'ModerateTopicRenamed'		=> '主题已成功重命名。',
	'ModerateTopicBlocked'		=> '主题已成功阻止',
	'ModerateTopicUnlocked'		=> '主题解锁成功。',
	'ModerateCommentsDeleted'	=> '已成功删除选定的评论。',
	'ModerateCommentsSplit'		=> '在一个新主题中成功地分隔了选定的评论。',
	'ModerateCommentsSplitFailed'	=> 'Note: For some reason separating the selected comments to a new topic failed.<br>Usually this should not happen, so please notify the site administrator.<br>As a precaution, the issue has been preserved in its original form.',
	'ModerateCommentsMoved'		=> '选中的评论成功迁移到给定的页面。',

	// forum
	'ForumSubforums'			=> '论坛',
	'ForumTopic'				=> '主题',
	'ForumTopics'				=> '主题',
	'ForumPosts'				=> '员额',
	'ForumReplies'				=> '回复',
	'ForumAuthor'				=> '作者',
	'ForumViews'				=> '视图',
	'ForumCreated'				=> '已创建',
	'ForumComments'				=> '评论',
	'ForumLastComment'			=> '上次评论',
	'ForumNoComments'			=> '没有评论',
	'ForumNoTopics'				=> '在这个论坛中没有任何主题或帖子。',
	'ForumNewTopic'				=> '开始新的讨论',
	'ForumTopicName'			=> '主题名称：',
	'ForumTopicSubmit'			=> '提交主题',
	'ForumNoTopicName'			=> '指定新页面的名称。',
	'ForumNewPosts'				=> '新帖子',
	'ForumLocked'				=> '节已锁定',
	'ForumUpdated'				=> '已更新',
	'ForumNoClusterDefined'		=> '未定义论坛集群。',
	'ForumOutsideCluster'		=> '确认 %1 操作位于论坛集群中。',

	// password complexity
	'PwdCplxShort'				=> '密码太短。',
	'PwdCplxEquals'				=> '密码包含用户名。',
	'PwdCplxWeak'				=> '密码不符合复杂性要求。',
	'PwdCplxDesc1'				=> '密码所需： ',
	'PwdCplxDesc2'				=> '密码不能小于 %1 个字符',
	'PwdCplxDesc3'				=> '不能包含您的用户名',
	'PwdCplxDesc4'				=> '应该包含 ',
	'PwdCplxDesc41'				=> '字母和数字',
	'PwdCplxDesc42'				=> '大写字母和小写字母及数字',
	'PwdCplxDesc43'				=> '大写字母和小写字母，数字和非字母数字字符',
	'PwdCplxDesc5'				=> '除空格外，您可以使用任何字母、数字和特殊字符。',

	'PasswordTooShort'			=> '密码太短.',
	'PasswordTooCommon'			=> '这个密码太常见。',
	'PasswordSameAsUsername'	=> '您的密码与您的用户名相同。',
	'PasswordSameAsEmail'		=> '您的密码与您的电子邮件相同。',

	'Timezone'					=> 'Timezone',

	'LanguageArray'	=> [
		'bg' => '保加利亚文',
		'da' => '丹麦语',
		'de' => '德文',
		'el' => '希腊语',
		'en' => 'Distr.',
		'es' => '西班牙语',
		'et' => '爱沙尼亚语',
		'fa' => '波斯文',
		'fr' => '法文',
		'hi' => '印地文',
		'hu' => '匈牙利',
		'it' => '意大利语',
		'ja' => '日语',
		'ko' => '韩语',
		'nl' => '荷兰语',
		'pl' => '波兰语',
		'pt' => '葡萄牙文',
		'ru' => '俄文',
		'ta' => 'Tamil',
		'zh' => '中文',
		'zh-tw' => '中文',
	],

	'AccountStatus'				=> '帐户状态',
	'AccountStatusArray' => [
		'0' => '已激活',
		'1' => '待定',
		'2' => '已阻止',
		'3' => '未激活',
	],

	'JustNow'		=> '就在这里',
	'MinuteAgo'		=> '1分钟前',
	'MinutesAgo'	=> '%1 分钟前',
	'HourAgo'		=> '1小时前',
	'HoursAgo'		=> '%1 小时前',
	'DayAgo'		=> '昨天：',
	'DaysAgo'		=> '%1 天前',
	'WeekAgo'		=> '一周前',
	'WeeksAgo'		=> '%1 周前',
	'MonthAgo'		=> '一个月前',
	'MonthsAgo'		=> '%1 个月前',
	'YearAgo'		=> '一年前',
	'YearsAgo'		=> '%1 年前',

	'InAMoment'		=> '在一定时间内',
	'InAMinute'		=> '一分钟内',
	'InMinutes'		=> '在 %1 分钟内',
	'InAnHour'		=> '一小时内',
	'InHours'		=> '在 %1 小时内',
	'Tomorrow'		=> '明天',
	'InDays'		=> '在 %1 天内',
	'InAWeek'		=> '一周内',
	'InWeeks'		=> '在 %1 周',
	'InAMonth'		=> '一个月内',
	'InMonths'		=> '在 %1 个月',
	'InAYear'		=> '一年内',
	'InYears'		=> '在 %1 年',

	// norm multiples
	'ByteDecimalShort'			=> ['B', '千B', 'MB', 'GB', 'TB', 'PB', 'EB', 'ZB', 'YB'],
	'ByteDecimalLong'			=> ['字节', 'Kilobyte', 'Megabyte', 'Gigabyte', 'Terabyte', 'Petabyte', 'Exabyte', 'Zettabyte', 'Yottabyte'],
	'ByteBinaryShort'			=> ['B', 'KiB', 'MiB', 'GiB', 'TiB', 'PiB', 'EiB', 'ZiB', 'YiB'],
	'ByteBinaryLong'			=> ['字节', 'Kibibyte', 'Mebibyte', 'Gibibyte', 'Tebibyte', 'Pebibyte', 'Exbibyte', 'Zebibyte', 'Yobibyte'],
	'PixelDecimalShort'			=> ['px', 'KP', 'MP', 'GP', '私信', 'PP', '经度', 'ZP', 'YP'],
	'PixelDecimalLong'			=> ['像素', 'Kpx', 'Mpx', 'Gpx', '公差数', 'Ppx', '剧集', 'Zpx', 'Ypx'],

	// loading error
	'UnknownAction'				=> '未知动作',
	'UnknownMethod'				=> '未知方法',
	'FormatterNotFound'			=> '找不到 %1 格式文件',

	// log
	'LogAdminLoginSuccess'		=> '成功登录到管理面板',
	'LogAdminLogout'			=> '退出管理面板',
	'LogAdminLoginFailed'		=> '!!未能授权访问管理面板!!',
	'LogAdminLoginLocked'		=> '锁定登录到管理面板',
	'LogUserCookieForged'		=> '!!**尝试登录一个伪造的 cookie ##%1##**!',
	'LogInvalidFormToken'		=> '检测到潜在的 CSRF 攻击正在进行中： %1',
	'LogRemovedPage'			=> '!!已删除页面 ##%1## (用户 %2)!!',
	'LogRemovedCluster'			=> '!!已删除 **群集** ##%1## (用户 %2)!!',
	'LogRemovedRevision'		=> '!!已删除版本 ##%3## 页 [[/%1](用户 %2)!!',
	'LogRemovedComment'			=> '!!在页面 [[/%1]] (用户 %2 ) 上删除了 %3 中的评论!!',
	'LogRemovedFile'			=> '!!已从页面 #%2## 移除文件 [[/%1]]!!',
	'LogRemovedAllComments'		=> '!!移除页面的所有评论 [[/%1]]!!',
	'LogRemovedAllRevisions'	=> '!!已删除页面的所有版本 [[/%1]]!!',
	'LogRemovedAllFiles'		=> '!!已移除所有文件，连接到 [[/%1]]!!',
	'LogTopicLocked'			=> '论坛主题已锁定 [[/%1]]',
	'LogTopicUnlocked'			=> '解锁讨论主题 [[/%1]]',
	'LogAclUpdated'				=> '已更新 ACL 页面 [[/%1]]',
	'LogOwnershipChanged'		=> '页面[[/%1]]的所有权已转移到用户 ##%2##',
	'LogUserLoginFailed'		=> '!!无法成功地尝试使用 ##~%1##！',
	'LogClonedPage'				=> '第##%1## 克隆到 [[/%2] 页',
	'LogRenamedPage'			=> 'Page ##%1## renamed to [[/%2]]',
	'LogRenamedPage2'			=> '。旧页面设置为与新页面的链接',
	'LogSplittedPage'			=> '页面[[/%1]] 上的注释拆分到页面 [[/%2]]',
	'LogMergedPages'			=> '第 %1 页已合并到第[[/%2] 页',
	'LogUserPasswordReminded'	=> '用户 ##%1## 请求密码恢复过程地址 ##%2##',
	'LogUserPasswordRecovered'	=> '用户 ##%1## 成功恢复了忘记的密码',
	'LogUserPasswordChanged'	=> '用户 ##%1## 更新成功(更改了) 密码',
	'LogUserPasswordMismatch'	=> '!!User ##%1## 更改密码失败：当前密码不匹配！',
	'LogUserIPSwitched'			=> '未授权的 IP 地址更改用户 %1 从 %2 到 %3',
	'LogPageImported'			=> '导入页面 [[/%1]]',
	'LogSaveNoRights'			=> '没有保存页面 [[/%1] ] 的适当权限',
	'LogPageCreated'			=> '创建新页面 [[/%1]]',
	'LogPagePropertiesUpdated'	=> '更新页面属性 [[/%1]]',
	'LogPageOwnershipClaimed'	=> '用户获得页面 [[/%1] ] 的所有权',
	'LogFileUploadedLocal'		=> '新文件 ##%2## 上传到页面 [[/%1]] (大小 %3)',
	'LogFileUploadedGlobal'		=> '新文件 ##%2## 上传到全局文件夹 (大小 %3)',
	'LogPMSent'					=> '个人消息 ##%1## -> ##%2## 成功发送',
	'LogUserSimilarName'		=> '尝试以相同的用户名注册：##%1##',
	'LogUserEmailNotAllowed'	=> '电子邮件##%1## 不在允许的域名列表',
	'LogRegisterTiming'			=> '注册失败，表单时间阈值是 ##%1## 秒(是 ##%2##)',
	'LogUserRegistered'			=> '成功注册了一个新用户 ##%1## (##%2##)',
	'LogUserEmailActivated'		=> '成功激活电子邮件 ##%1## 用户##%2##',
	'LogCommentPosted'			=> '添加[[/%1 new comment(s)]]到页面 [[/%2]',
	'LogUserLoginOK'			=> '用户 ##%1## 成功登录到系统',
	'LogUserLoggedOut'			=> '用户 ##%1## 成功注销系统',
	'LogUserSessionContinued'	=> '用户 ##%1## 继续暂停会话',
	'LogUserSettingsUpdate'		=> '用户 ##%1## 更新了个人设置',
	'LogPageEdited'				=> '编辑页面 [[/%1]]',
	'LogCommentEdited'			=> '已编辑评论 [[/%1]]',
	'LogUpdatedFileMeta'		=> '从第[[/%1] 页更新第#%2##号文件元数据',
	'LogUpdatedFileCategories'	=> '从第[[/%1] 页更新第#%2## 的文件类别',

	'LogXmlSitemapGenerated'	=> '生成XML站点地图',
	'LogReferrersPurged'		=> '维护：被清除的',
	'LogRevisionsPurged'		=> '维护：删除了过时的页面修订',
	'LogDeletedPagesPurged'		=> '维护：删除页面',
	'LogSystemLogPurged'		=> '维护：系统日志已清除',
	'LogCachedPagesPurged'		=> '维护：已清除缓存页面',
	'LogSqlCachePurged'			=> '维护：已净化缓存的 sql 结果',
	'LogExpiredTokensPurged'	=> '维护：已清除过期的 cookie_tokens',
	'LogErrorSplitComments'		=> '将评论与主题 [[/%1]] 分开时出错：一个新主题 ##%2##：页面未创建',
	'LogCategoriesUpdated'		=> '更新页面类别 [[/%1]]',
	'LogCategoryCreated'		=> 'Created a new category //%1//',
	'LogCategoryRenamed'		=> '类别 ##%1## 重命名为 ##%2##',
	'LogCategoryDebundled'		=> '类别 ##%1## 已拆分',
	'LogCategoryGrouped'		=> '分类 ##%1## 按单词##%2 ## 分组',
	'LogCategoryRemoved'		=> '类别##%1## 已从数据库中删除',
	'LogThumbnailGeneration'	=> '缩略图生成 %1 秒。',

	'ErrorMinPHPVersion'		=> 'PHP 版本必须大于 <strong>' . PHP_MIN_VERSION . '</strong>，' .
									' 您的服务器似乎正在运行 <strong>' . PHP_VERSION . '</strong>。' .
									'  您应该升级到 WackoWiki 的最新PHP 版本才能正常工作。',

];
