<?php

if (!defined('IN_WACKO'))
{
	exit;
}

$wacko_translation = [

	// language
	'lang_scheme'	=> [
		'name'		=> 'Inglés',
		'code'		=> 'es',
		'dir'		=> 'ltr',
		'locale'	=> 'es_USA_TF-8',
	],

	// common
	'AddButton'					=> 'Añadir',
	'ArchiveButton'				=> 'Archivar',
	'CancelButton'				=> 'Cancelar',
	'ContinueButton'			=> 'Continuar',
	'ConvertButton'				=> 'Convertir',
	'CreateButton'				=> 'Crear',
	'DeleteButton'				=> 'Eliminar',
	'RemoveButton'				=> 'Eliminar',
	'RenameButton'				=> 'Renombrar',
	'ResetButton'				=> 'Reset',
	'RestoreButton'				=> 'Restaurar',
	'SaveButton'				=> 'Guardar',
	'SearchButton'				=> 'Buscar',
	'SendButton'				=> 'Enviar',
	'SetButton'					=> 'Fijar',
	'SubmitButton'				=> 'Enviar',
	'UpdateButton'				=> 'Actualizar',

	'FormInvalid'				=> 'El formulario enviado no es válido. Intente enviarlo de nuevo.',
	'UnitPixel'					=> 'px',
	'Number'					=> 'Número',

	// logged in panel
	'AccountText'				=> 'Cuenta',
	'AccountTip'				=> 'Ajustes de la cuenta',
	'AdminText'					=> 'Admin',
	'AdminTip'					=> 'Panel administrativo',
	'LogoutLink'				=> 'Cerrar sesión',
	'LogoutButton'				=> 'Cerrar sesión',
	'LogoutAreYouSure'			=> '¿Realmente desea cerrar sesión?',

	// registration panel
	'RegistrationWelcome'		=> 'Registro de nuevo usuario:',
	'RegistrationButton'		=> 'Registrarme',
	'UserNameOwned'				=> 'Este nombre de usuario ya está registrado. Por favor, elija otro.',
	'SiteRegistered'			=> 'Te has registrado correctamente en el sitio %1.',
	'RegistrationEmailInfo'		=> 'Una dirección de correo electrónico válida. Todos los correos del sistema se enviarán a esta dirección. La dirección de correo electrónico no se hace pública y sólo se utilizará si desea recibir una nueva contraseña o si desea recibir ciertas noticias o notificaciones por correo electrónico.',
	'EmailConfirmHint'			=> 'Please confirm your E-mail address by clicking on the link in the instructions sent to you. <br>If you do not verify your email address, you will not be able to retrieve a possible lost password. <br>Furthermore you will not be notified of recent page changes and comments.',
	'EmailConfirmRequired'		=> 'Sin dirección de correo electrónico confirmada no se le permitirá iniciar sesión.',
	'NameTooShort'				=> 'El nombre de usuario es demasiado corto, se requiere un mínimo de %2 caracteres.',
	'NameTooLong'				=> 'El nombre de usuario es demasiado largo, se permite un máximo de caracteres %2.',
	'NameAlphanumOnly'			=> 'El nombre de usuario debe tener entre %1 y %2 caracteres de longitud y utilizar sólo caracteres alfanuméricos. Los caracteres mayúsculas son OK.',
	'NameCamelCaseOnly'			=> 'El nombre de usuario debe tener entre %1 y %2 caracteres de largo y WikiName formateado.',
	'NewUserAccount'			=> 'nueva cuenta de usuario',

	'NewAccountSubject'			=> 'Registro de cuenta',
	'NewAccountAdminCreated'	=> 'El usuario %1 ha creado una cuenta para usted con el nombre de usuario "%2". Para completar su registro, visite la siguiente URL (asegúrese de que se introduce como una sola línea) y establezca su propia contraseña de acceso:',
	'NewAccountUsername'		=> 'Usuario:',
	'AccountLanguage'			=> 'Idioma:',
	'NewAccountEmail'			=> 'Email:',
	'NewAccountIP'				=> 'Dirección IP remota:',
	'NewAccountSignupInfo'		=> 'La siguiente cuenta ha sido creada:',

	'UserWaitingApproval'		=> 'Un correo electrónico ha sido enviado al administrador del sitio. El administrador revisará la información que se ha enviado y aprobará o denegará su solicitud.',
	'UserRequiresApproval'		=> 'Para aprobar o negar el acceso de este usuario a %1 , vaya al panel de administración.',
	'UserApprovalInfo'			=> 'Después de registrarse, su solicitud será enviada al administrador del sitio para su aprobación. Recibirá un correo electrónico con más instrucciones.',
	'UserApprovalHint'			=> 'La activación exitosa de su cuenta será anunciada en un correo electrónico específico. Hasta entonces, no es posible iniciar sesión.',

	'UserApprovalPending'		=> 'Su cuenta todavía está pendiente de aprobación.',
	'UserApprovalDenied'		=> 'Su cuenta ha sido denegada el acceso a este sitio.',

	'RegistrationApproved'		=> 'Registro aprobado',
	'RegistrationDenied'		=> 'Registro denegado',
	'PendingApproval'			=> 'Pendientes de aprobación',

	'UserApprovedInfo'			=> 'Has sido aprobado para acceder a %1.',
	'UserDeniedInfo'			=> 'Se te ha negado el acceso a %1.',

	'RegistrationThreshold'		=> 'El tiempo para rellenar el formulario no debe ser inferior a %1 segundos.',
	'Language'					=> 'Idioma',

	// login panel
	'LoginWelcome'				=> 'Ingresar',
	'CreateAccount'				=> 'Crear nueva cuenta',
	'RegistrationLink'			=> 'Registro',
	'LoginName'					=> 'Usuario',
	'Password'					=> 'Contraseña',
	'LoginButton'				=> 'Ingresar',
	'LoginLink'					=> 'Ingresar',
	'PersistentCookie'			=> 'Permanecer conectado',
	'Session'					=> 'Sesión',
	'SessionTip'				=> 'parámetros de la sesión actual',
	'SessionDuration'			=> 'Duración de la sesión',
	'SessionDurationSession'	=> 'sesión del navegador',
	'SessionDurationDay'		=> '1 día',
	'SessionDurationWeek'		=> '1 semana',
	'SessionDurationMonth'		=> '1 mes',
	'LoggedInAs'				=> 'Has iniciado sesión como',

	'ClearCookies'				=> 'Borrar todas las cookies',
	'BindSessionIp'				=> 'Enlazar sesión a la dirección IP',
	'BindSessionIpOn'			=> 'habilitado (IP actual %1)',
	'TrafficProtection'			=> 'Protección de Tristes',
	'SessionEnds'				=> 'La sesión actual termina',
	'LastVisit'					=> 'La última visita fue registrada',

	'LoginIncorrect'			=> 'El nombre de usuario o contraseña que ha introducido no es válido.',
	'WelcomeBack'				=> 'Bienvenido de nuevo, %1',
	'LoginAttemptsExceeded'		=> 'Ha excedido el número máximo de intentos de inicio de sesión.<br>Además de tu nombre de usuario y contraseña ahora también tienes que resolver el CAPTCHA a continuación.',

	// session notice
	'IPAddressChanged'			=> 'Dirección IP cambiada a %1 (era %2)',

	'SessionReplay'				=> 'Sesión terminada debido a la repetición.',
	'SessionObsolete'			=> 'Sesión está desactualizada.',
	'SessionExpired'			=> 'La sesión ha caducado.',
	'SessionTimeout'			=> 'Sesión terminada debido al tiempo de espera.',
	'SessionInactivity'			=> 'Sesión cancelada por inactividad.',
	'SessionUaChange'			=> 'Sesión terminada debido al cambio de agente de usuario.',
	'SessionTLSChange'			=> 'Sesión terminada debido a un cambio de TLS.',
	'SessionIPChange'			=> 'Sesión terminada debido al cambio de IP.',

	// other
	'Guest'						=> 'Invitado',
	'Everybody'					=> 'Todo el mundo',
	'Help'						=> 'Ayuda',
	'TopicSearchText'			=> 'Buscar solo en títulos',
	'WordprocessorVersion'		=> 'Versión del procesador de Word',

	// notifications
	'EmailHello'				=> 'Hola ',
	'EmailModerator'			=> 'Moderador',
	'WatchedPageChanged'		=> 'Página cambiada ',
	'SomeoneChangedThisPage'	=> ' cambió una página que está viendo: ',
	'NewPageCreatedSubj'		=> 'Una nueva página',
	'NewPageCreatedBody'		=> 'El usuario %1 ha creado una nueva página: ',
	'FileUploadedSubj'			=> 'Un nuevo archivo',
	'FileUploadedBody'			=> 'El usuario %1 ha subido un nuevo archivo: ',
	'FileReplacedBody'			=> 'El usuario %1 ha reemplazado el archivo: ',

	'ActionDenied'				=> 'Aquí se niega la acción.',
	'TocTitle'					=> 'Contenido ',
	'OuterLink2'				=> 'Enlace saliente',
	'FileLink'					=> '',
	'PDFLink'					=> 'Documento PDF',
	'RDFLink'					=> 'Documento RDF',
	'EmailLink'					=> 'Escribe un correo electrónico (lanzamiento del cliente de correo)',
	'JabberLink'				=> 'Chatear vía XMPP (Jabber cliente lanzado)',
	'PermaLink'					=> 'Enlace permanente',
	'PermaLinkTip'				=> 'Enlace permanente a esta revisión de la página',
	'PermaLink0Tip'				=> 'Enlace permanente a esta página',

	'ShowTip'					=> 'Retorno en modo de vista',
	'ShowText'					=> 'Ver',
	'WikieditAutocomplete'		=> 'Completa wikilinks por Ctrl+Espacio',
	'WikiEditInactiveJs'		=> 'Para poder usar WikiEdit, por favor habilite JavaScript en su navegador.',
	'NumerateLinks'				=> 'Numerar enlaces en la vista de impresión',
	'Comment'					=> 'Comentario',
	'Comments0'					=> 'Añade tu comentario',
	'Comments1'					=> 'Leer comentario (1 comentario)',
	'CommentsN'					=> 'Leer comentarios (%1 comentarios)',
	'Comments'					=> 'Comentarios',
	'CommentHint'				=> '<a href="%1">Inicie sesión</a> o <a href="%2">cree una cuenta</a> para publicar un comentario.',
	'CommentEdited'				=> 'editado',
	'Links'						=> 'Enlaces',
	'Version'					=> 'Versión',

	// details formatter
	'ShowHideDetails'			=> 'Detalles',

	'PrivacyPolicy'				=> 'Política de privacidad',
	'TermsOfUse'				=> 'Términos de uso',
	'AcceptTermsOfUse'			=> 'He leído, entendido y acepto las Condiciones de Servicio del sitio.',

	'ShowComments'				=> 'Mostrar comentarios / formulario',
	'HideComments'				=> 'Ocultar comentarios / formulario',
	'AddComment'				=> 'Adjuntar un comentario a esta página:',
	'AddCommentTitle'			=> 'Título del comentario:',
	'CommentTitleRe'			=> 'Re:',
	'AddCommentButton'			=> 'Adjuntar comentario',
	'HereLink'					=> 'aqui',
	'PageHandlerMoreTip'		=> 'más',

	'ThemeCorrupt'				=> 'El tema está corrupto',
	'InvalidNamespace'			=> 'Espacio de nombres inválido.',
	'DoesNotExists'				=> 'Esta página no existe.',
	'PromptCreate'				=> 'Maybe you want to <strong><a href="%1">create</a></strong> it?',
	'RevisionHint'				=> 'Esta es una revisión antigua de <a href="%1">%2</a> de %3 editada por %4.',
	'ReadAccessDenied'			=> 'No tienes permisos para leer esta página.',
	'ReadAccessDeniedHintGuest'	=> 'Para leer esta página, debe iniciar sesión.',
	'PageDeletedInfo'			=> 'Esta página ha sido eliminada.',
	'RevisionDeletedInfo'		=> 'Esta revisión ha sido eliminada.',
	'CommentDeletedInfo'		=> 'Este comentario ha sido eliminado.',

	'LastEditedBy'				=> 'Última edición por',
	'YouAreOwner'				=> 'Usted es el dueño de esta página.',
	'Owner'						=> 'Propietario:',
	'Nobody'					=> 'Nadie',
	'TakeOwnership'				=> 'Tomar posesión',
	'FilesTip'					=> 'Administrar archivos adjuntos',
	'FilesText'					=> 'Adjuntos',
	'DeleteTip'					=> 'Eliminar página, sus archivos y comentarios',
	'DeleteCommentTip'			=> 'Eliminar comentario',
	'DeleteText'				=> 'Eliminar',
	'AclText'					=> 'Permisos',
	'AclTip'					=> 'Editar permisos',

	'PropertiesText'			=> 'Propiedades',
	'PropertiesTip'				=> 'Editar Propiedades de Página',
	'EditTip'					=> 'Editar esta página.',
	'EditText'					=> 'Editar',
	'EditSection'				=> 'Editar sección %1',
	'EditSectionHint'			=> 'Sección %1 de %2',
	'SectionHeadline'			=> 'Sección',
	'EditCommentTip'			=> 'Editar comentario',
	'EditComment'				=> 'Editar este comentario',
	'ReplyComment'				=> 'Responder',
	'ReplyCommentTip'			=> 'Responder a este comentario',
	'RevisionTip'				=> 'Ver revisiones de página',
	'RevisionText'				=> 'Revisiones',
	'ReferrersTip'				=> 'Ver una lista de URLs referentes a esta página',
	'ReferrersText'				=> 'Referentes',
	'ModerateTip'				=> 'Moderación de temas y mensajes del foro',
	'ModerateText'				=> 'Moderado',
	'SearchText'				=> 'Buscar: ',

	'AclUpdated'				=> 'Listas de control de acceso actualizadas',
	'AclGaveOwnership'			=> ' y dio la propiedad a %1.',
	'AclNoNewOwner'				=> 'La propiedad de la página no se ha transferido, porque el usuario %1 no fue encontrado.',
	'NewPageOwnership'			=> 'Propietario de página transferido',
	'YouAreNewOwner'			=> 'el antiguo propietario %1 transfirió la propiedad ' . "\n" . 'de la página siguiente para usted',
	'PageOwnershipInfo'			=> '',
	'AclRead'					=> 'Leído:',
	'AclWrite'					=> 'Escribir:',
	'AclComment'				=> 'Comentarios:',
	'AclCreate'					=> 'Creado:',
	'AclUpload'					=> 'Subir:',
	'AclFor'					=> 'Listas de control de acceso para %1',
	'SetOwner'					=> 'Propietario:',
	'OwnerDontChange'			=> 'No cambiar',
	'AclAccessDenied'			=> 'No eres el dueño de esta página.',
	'AclSyntaxError'			=> 'Error de sintaxis de la lista de control de acceso',
	'AclHelp'					=> '<code>*</code> - everyone is allowed<br>' .
									'<code>$</code> - Solo usuarios registrados<br>' .
									'<code>!</code> - una marca de exclamación anterior niega el derecho respectivo<br>' .
									'<code>[UserName]</code> - nombres de usuarios permitidos<br>' .
									'<code>[GroupName]</code> - nombres de grupo de usuarios permitido (alias)<br>' .
									'<code>(una lista vacía)</code> - sólo el propietario de la página tiene acceso',

	'AccessMode'				=> 'Visibilidad',
	'AccessDenied'				=> 'denegado',
	'AccessPublic'				=> 'público',
	'AccessRegistered'			=> 'registrado',
	'AccessPrivate'				=> 'privado',
	'AccessCustom'				=> 'costumbre',

	// purge handler
	'PurgePage'					=> 'Purge page',
	'NotOwnerAndCantPurge'		=> 'No eres el dueño de la página y no puedes purgarla.',
	'ReallyPurge'				=> 'ATENCIÓN: ¡Purgar la página es irreversible!',
	'SelectPurgeOptions'		=> 'Seleccione las opciones de purga necesarias:',
	'PurgeComments'				=> 'Purgar todos los comentarios de la página',
	'CommentsPurged'			=> 'Se eliminaron todos los comentarios.',
	'PurgeFiles'				=> 'Eliminar todos los archivos adjuntos',
	'FilesPurged'				=> 'Se eliminaron todos los archivos adjuntos.',
	'PurgeRevisions'			=> 'Purgar todas las revisiones de la página',
	'RevisionsPurged'			=> 'Se purgaron las revisiones.',
	'PurgeButton'				=> 'Purge',

	// categories handler
	'Categories'				=> 'Categorías',
	'CategoriesAssign'			=> 'asignar',
	'CategoriesEdit'			=> 'editar',
	'Category'					=> 'Categoría',
	'CategoriesFor'				=> 'Categorías para',
	'CategoriesTip'				=> 'Editar categorías',
	'CategoriesText'			=> 'Categorías',
	'CategoriesUpdated'			=> 'Categorías actualizadas',
	'CategoriesAlreadyExists'	=> 'La categoría %1 ya existe.',
	'CategoriesAdded'			=> 'Categoría %1 añadida correctamente.',
	'CategoriesRenamed'			=> 'Categoría renombrada correctamente.',
	'CategoriesUngrouped'		=> 'Categoría desbaratada correctamente.',
	'CategoriesGrouped'			=> 'La categoría introducida en el nuevo grupo.',
	'NoMultilevelGrouping'		=> 'No es posible agrupar múltiples niveles.',
	'CategoriesDeleted'			=> 'La categoría fue eliminada de la base de datos y de todas las páginas.',
	'CategoriesAdd'				=> 'Añadir una nueva categoría',
	'CategoryDescription'		=> 'Descripción',
	'CategoriesAddGrouped'		=> 'Grupado con la categoría',
	'CategoriesAddGroupedNo'	=> 'No hay grupo.',
	'CategoriesRename'			=> 'Renombrar la categoría %1 a',
	'CategoriesRenameInfo'		=> '* Nota: El cambio afectará a todas las páginas asignadas a esa categoría.',
	'CategoriesGroup'			=> 'Agrupar categorías %1 con',
	'CategoriesGroupInfo'		=> '* Seleccione [ningún grupo] para descomprimir la categoría.',
	'CategoriesNoGroup'			=> '[sin grupo]',
	'CategoriesDelete'			=> '¿Está seguro que desea eliminar la categoría %1?',
	'CategoriesDeleteInfo'		=> '* Nota: El cambio afectará a todas las páginas asignadas a esa categoría. Si la palabra tiene una subcategoría, no se eliminarán, sino que sólo se desbaratarán.',
	'CategoriesStoreInfo'		=> 'Para asignar categorías a una página, seleccione las casillas de verificación.',
	'CategoriesStoreButton'		=> 'Guardar categorías',
	'CategoriesGroupButton'		=> 'Grupo',
	'CategoriesEditInfo'		=> 'Para editar la lista de categorías, seleccione el botón de radio.',
	'NoCategoriesForThisLang'	=> 'Las categorías para este idioma no están especificadas.',
	'PagesCategory'				=> 'Categoría de páginas',
	'CategoryNotExists'			=> 'La categoría no existe.',
	'CategoryEmpty'				=> 'Categoría vacía.',
	'NoCategorySelected'		=> 'Ninguna categoría seleccionada.',
	'NoCategoriesAssigned'		=> 'No hay categorías asignadas para este idioma.',
	'TagCloud'					=> 'Nube de etiquetas',
	'PagesTaggedWith'			=> '%1 páginas etiquetadas con %2',
	'CategoriesOfCluster'		=> 'de cluster',
	'TaggedWithTip'				=> 'show pages tagged %1',

	// source handler
	'SourceText'				=> 'Fuente',
	'SourceTip'					=> 'Ver la fuente wiki',
	'SourceCopyToClipboard'		=> 'copiar al portapapeles',
	'SourceFor'					=> 'Ver fuente de %1',

	// Groups action
	'GroupsSearch'				=> 'Buscar grupos',
	'GroupsNoMatching'			=> 'Grupos coincidentes no encontrados. Prueba con un criterio de búsqueda menos estricto.',
	'GroupsOpenProfile'			=> 'Ver perfil',
	'GroupsName'				=> 'Grupo',
	'GroupsMembers'				=> 'Miembros',
	'GroupsDescription'			=> 'Descripción',
	'GroupsCreated'				=> 'Creado',
	'GroupsNotFound'			=> 'Grupo %2 no encontrado. Haga clic <a href="%1">aquí</a>, para ir a la lista principal.',
	'GroupsProfile'				=> 'Perfil',
	'GroupsList'				=> 'Ver la lista completa de grupos',
	'GroupSpace'				=> 'Espacio de grupo',

	'MetaUpdated'				=> 'Meta datos actualizados',

	'PreviewButton'				=> 'Vista previa',
	'Preview'					=> 'Vista previa',
	'Chars'						=> 'caracteres',
	'PageBody'					=> 'Cuerpo de página',
	'EditNote'					=> 'Editar resumen',
	'EditNoteMissing'			=> 'Editar resumen faltante',
	'EditMinor'					=> 'Edición menor',
	'MinorEditHide'				=> 'Ocultar edición menor',
	'MinorEditShow'				=> 'Mostrar edición menor',
	'PostAnonymously'			=> 'Publica anónimamente sin dar tu nombre',
	'NotifyMe'					=> 'Notificarme sobre nuevos comentarios y cambios de la página',
	'OverwriteAlert'			=> 'AVISO: Esta página fue modificada por alguien mientras la editaba.<br>Por favor copie sus cambios y vuelva a editar esta página.',
	'TextDbOversize'			=> 'Advertencia: Tu texto supera el límite de longitud de caracteres %1 . Por favor, acorte su texto a un número aceptable de caracteres. Sugerencia: Puede colocar el texto restante en una página separada.',
	'EditingRevisionWarning'	=> 'You are editing an old revision of this page. If you publish it, any changes made since then will be removed. <br>You may wish to edit the current revision instead.',
	'WriteAccessDenied'			=> 'No tienes acceso de escritura a esta página.',
	'EmptyPage'					=> 'El cuerpo de la página está vacío - ¡no se ha guardado!',
	'EmptyComment'				=> 'El cuerpo del comentario estaba vacío - ¡no se ha guardado!',
	'CommentAccessDenied'		=> 'Lo sentimos, no puedes publicar comentarios en esta página.',
	'CommentFlooded'			=> 'El intervalo entre la publicación de los posts no debe ser inferior a %1 segundos.',
	'CommentAdded'				=> 'Comentario añadido.',
	'YouAreNowTheOwner'			=> 'Ahora eres el dueño de esta página.',
	'PageSaved'					=> 'Versión de página %1 guardada.',
	'CommentSaved'				=> 'Comentario guardado.',

	'RevisionsFor'				=> 'Revisiones para %1',
	'DefaultDiffMode'			=> 'Modo de diferencia por defecto',
	'DiffMode'		=> [
		'0'		=> 'Diff completo',
		'1'		=> 'Diff simple',
		'2'		=> 'Fuente',
		'3'		=> 'Lado por lado',
		'4'		=> 'En línea',
		'5'		=> 'Fusionado',
		'6'		=> 'Unificado',
		'7'		=> 'Contexto',
	],

	'PreviousEdit'				=> 'Edición anterior',
	'NextEdit'					=> 'Siguiente edición',

	'Diff'						=> 'Diferencia',
	'PreviousVersion'			=> 'Revisión anterior',
	'LatestVersion'				=> 'Última revisión',
	'NextVersion'				=> 'Siguiente revisión',

	'ShowDifferencesButton'		=> 'Mostrar Diferencias',
	'CancelReturnButton'		=> 'Cancelar y volver a la página',
	'Comparison'				=> 'Diferencia entre revisiones para %1',
	'RevisionAsOf'				=> 'Revisión %1 a partir de',
	'SimpleDiffAdditions'		=> 'Adicionales:',
	'SimpleDiffDeletions'		=> 'Borrados:',
	'NoDifferences'				=> 'No hay diferencias.',
	'ReEditOldRevision'			=> 'Re-editar esta revisión antigua',

	'ExternalPages'				=> 'Páginas externas enlazadas a %1 (%2) (<a href="%3">ver lista de dominios</a>):',
	'ExternalPagesGlobal'		=> 'Sitios enlazados a este WackoWiki (%2) (<a href="%1">ver lista de dominios</a>):',
	'Last24Hours'				=> 'últimas 24 horas',
	'LastDays'					=> 'últimos %1 días',
	'DomainsSitesPages'			=> 'Páginas de dominios/sitios enlazados a  %1 (%2) (<a href="%3">ver lista de diferentes URLs</a>):',
	'DomainsSitesPagesGlobal'	=> 'Dominios/sitios enlazados a este WackoWiki (<a href="%1">ver lista de diferentes URLs</a>):',
	'ViewReferrersPage'			=> 'a la página',
	'ViewReferrersPerPage'		=> 'por página',
	'ViewReferrersByTime'		=> 'por hora',
	'ViewReferrersGlobal'		=> 'global',
	'NoneReferrers'				=> 'Ninguna',
	'NotOwnerCantDelete'		=> 'No eres dueño de esta página y no puedes eliminarla',

	// remove
	'RemovePage'				=> 'Eliminar página',
	'RemoveRevision'			=> 'Eliminar revisión',
	'RemoveComment'				=> 'Eliminar comentario',
	'RemoveCluster'				=> 'Eliminar todas las páginas del clúster',
	'RemoveDontKeep'			=> 'No guardar una copia de una página eliminada y comentarios',
	'RemoveDontKeepRevision'	=> 'No guardar una copia de la revisión eliminada',
	'RemoveDontKeepComment'		=> 'No guardar una copia del comentario eliminado',
	'RemoveDontKeepFile'		=> 'No guardar una copia del archivo eliminado',
	'ReferrersRemoved'			=> 'Referentes eliminados.',
	'LinksRemoved'				=> 'Enlaces eliminados.',
	'CategoriesRemoved'			=> 'Categorías de páginas eliminadas.',
	'AclsRemoved'				=> 'Acls de página eliminados.',
	'BookmarksRemoved'			=> 'Marcadores eliminados.',
	'WatchesRemoved'			=> 'Watches eliminados.',
	'CommentsRemoved'			=> 'Comentarios de la página eliminados.',
	'FilesRemoved'				=> 'Archivos de la página eliminados.',
	'PageRemoved'				=> 'Página eliminada.',
	'PageCachePurged'			=> 'Caché purgada.',
	'ClusterRemoved'			=> 'Se han eliminado todas las páginas del cluster.',
	'RevisionRemoved'			=> 'Revisión %1 eliminada.',
	'RevisionsRemoved'			=> 'Revisiones eliminadas.',
	'ActionHaveNoUndo'			=> 'Esta acción no se puede deshacer.',

	// restore
	'PageRestored'				=> 'Página restaurada.',
	'RevisionRestored'			=> 'Revisión restaurada.',
	'LocalFilesRestored'		=> 'Archivos locales restaurados.',

	'PrintVersion'				=> 'Imprimir versión',
	'PrintText'					=> 'Imprimir',
	'LinkedPages'				=> 'Páginas enlazadas:',
	'NoLinkedPages'				=> 'No hay páginas enlazadas',
	'ReferringPages'			=> 'Páginas de referencia:',
	'NoReferringPages'			=> 'No hay páginas de referencia',
	'Footnotes'					=> 'Notas al pie de página:',
	'Footnote'					=> 'Nota al pie',
	'MostPopularPages'			=> 'Páginas más populares',
	'MostCommentedPages'		=> 'Páginas más comentadas',
	'NoAccessToSourcePage'		=> 'No tienes permiso para leer la página de origen de la acción.',
	'SourcePageDoesntExist'		=> 'La página de origen de la acción aún no existe',
	'NotLoggedInThusEdited'		=> 'No estás conectado, por lo tanto no pudimos identificar las páginas que has editado.',
	'DidntEditAnyPage'			=> 'Aún no has editado ninguna página.',
	'NoPagesFound'				=> 'No se encontraron páginas.',
	'MyChangesTitle1'			=> 'Esta es la lista de páginas que has editado, ordenadas por la hora de tu último cambio',
	'MyChangesTitle2'			=> 'Esta es la lista de páginas que has editado, junto con la hora de tu último cambio',
	'OrderABC'					=> 'alfabeto',
	'OrderCreation'				=> 'por creación',
	'OrderChange'				=> 'por cambio',
	'ListOwnedPages'			=> 'Esta es la lista de páginas que tienes (ordenadas alfabéticamente)',
	'ListOwnedPages2'			=> 'Esta es la lista de páginas que usted posee (ordenadas por fecha)',
	'ListOwnedPages3'			=> 'Esta es la lista de páginas que usted posee (ordenadas por cambio)',
	'NotLoggedInThusOwned'		=> 'No has iniciado sesión, por lo tanto no hemos podido recuperar tus páginas.',
	'NoOrphaned'				=> 'No hay páginas huérfanas. Bueno.',
	'NoRecentComments'			=> 'No hay comentarios recientes.',
	'LatestCommentBy'			=> 'último comentario por',
	'NoRecentlyCommented'		=> 'No hay página comentada recientemente.',
	'NoDeletedPages'			=> 'No se encontraron páginas borradas.',
	'NoDeletedRevisions'		=> 'No se encontraron revisiones borradas.',
	'NoDeletedFiles'			=> 'No se encontraron archivos borrados.',
	'CommentsDisabled'			=> 'Los comentarios no están disponibles.',

	'SearchResults'				=> 'Resultados de búsqueda para ',
	'NotFound'					=> 'no encontrado',
	'NoResultsFor'				=> 'Sin resultados para ',
	'SearchFor'					=> 'Buscar:',
	'TopicSearchResults'		=> 'Resultados de búsqueda de temas para ',
	'NotFoundInTopics'			=> 'no encontrado en temas',
	'FilterLangNotAvailable'	=> '¡El idioma seleccionado no está disponible!',

	'PostedBy'					=> 'publicado por',
	'ThisIsCommentOn'			=> 'Este es un comentario sobre',
	'At'						=> 'en',
	'To'						=> 'a',
	'By'						=> 'por',
	'From'						=> 'de',
	'For'						=> 'para',
	'ReturnToCommented'			=> 'Volver a la página comentada',
	'AbandonedComment'			=> 'La página a la que pertenece este comentario ya no existe!',

	'PagesLinkingTo'			=> 'Páginas enlazadas a',
	'NoPageLinkingTo'			=> 'Ninguna página está enlazada a',
	'NoWantedPages'				=> 'No hay páginas deseadas. Bien.',
	'RemoveWatch'				=> 'Eliminar reloj para esta página',
	'SetWatch'					=> 'Ver esta página',
	'WatchText'					=> 'Vigilar',
	'UnwatchText'				=> 'No seguir',
	'UserSettingsStored'		=> 'Ajustes de usuario guardados.',
	'LoggedOut'					=> 'Has cerrado la sesión.',
	'LoggedOutAuto'				=> 'Por seguridad, su sesión ha terminado. Por favor, inicie sesión de nuevo.',

	// user settings
	'EmailConfirmResent'		=> 'Código de confirmación de correo electrónico reenviado a su dirección.',
	'EmailConfirmNotSent'		=> 'No se puede enviar el código de confirmación: el correo electrónico no está especificado!',
	'Hello'						=> 'Hola',
	'UserName'					=> 'Nombre de usuario',
	'EmailAddress'				=> 'Dirección de email',
	'RealName'					=> 'Nombre real',
	'MenuItemsShown'			=> 'Elementos de menú mostrados',
	'RecordsPerPage'			=> 'Registros por página',
	'DoShowComments'			=> 'Mostrar comentarios por defecto',
	'DoubleclickEditing'		=> 'Edición doble',
	'UpdateSettingsButton'		=> 'Actualizar ajustes',

	'AccountDisabled'			=> 'Tu cuenta puede ser deshabilitada o bloqueada.',
	'WrongPassword'				=> 'Contraseña incorrecta!',
	'ConfirmPassword'			=> 'Confirmar contraseña',
	'Email'						=> 'Dirección de email',
	'MustBeWikiName'			=> 'User name must be <a href="https://wackowiki.org/doc/Doc/English/WikiName" target="_blank">WikiName</a> formatted!',
	'SpecifyEmail'				=> 'Debe especificar una dirección de correo electrónico.',
	'NotAEmail'					=> 'Eso no parece una dirección de correo electrónico válida.',
	'EmailTaken'				=> 'La dirección de correo electrónico introducida ya está en uso.',
	'EmailDomainNotAllowed'		=> 'La dirección de correo electrónico ingresada %1 no está en la lista de dominios permitidos.',
	'PasswordsDidntMatch'		=> 'Las contraseñas no coinciden.',
	'SpacesArentAllowed'		=> 'Los espacios no están permitidos en contraseñas.',
	'ListMyPages'				=> 'Listar tus páginas',
	'ListMyChanges'				=> 'Listar los cambios',
	'ListMyWatches'				=> 'Lista de páginas vistas',
	'ListMyChangesWatches'		=> 'Cambios entre páginas vistas',
	'SeeListOfPages'			=> 'Ver una lista de páginas que tienes (MyPages) y páginas que has editado (MyChanges).',
	'AddBookmark'				=> 'Añadir página actual a marcadores',
	'RemoveBookmark'			=> 'Eliminar de marcadores',

	'YourLanguage'				=> 'Seleccionar idioma',
	'ShowSpaces'				=> 'Mostrar espacios en WikiNames',
	'WrongPage4Redirect'		=> 'No se puede redirigir debido a un parámetro de redirección incorrecto',
	'RedirectsToItself'			=> 'La página se redirige a sí misma.',
	'ReallyDeletePage'			=> 'Do you really want to DELETE this page?<br>There is no undo for this action!<br><br>WARNING: Deleting this page will delete all page versions, comments, attachments, ACLs and referrers.',
	'CommentForWatchedPage'		=> 'Nuevo comentario para la página ',
	'SomeoneCommented'			=> ' comentó esta página que está viendo: ',
	'AlertReferringPages'		=> 'Esta página es referida por estas páginas',

	'AccountDelete'				=> 'Eliminar cuenta',
	'AccountDeleteConfirm'		=> '¿Está seguro que desea eliminar la cuenta?',
	'AccountDeleted'			=> 'Cuenta eliminada correctamente',
	'AccountDeleteHeader'		=> 'Eliminar cuenta %1',
	'AccountDeleteInfo'			=> 'De los datos que has creado (por ejemplo, correo electrónico, preferencias, archivos adjuntos, entradas de wiki) se eliminarán en la medida de lo posible. Sin embargo, tenga en cuenta que datos como archivos adjuntos y entradas de wiki no pueden ser borrados sin entorpecer el trabajo de los otros usuarios. Estos datos son reasignados a una cuenta llamada %1. Como los datos de cada cuenta eliminada se reasignan a esta cuenta, no será posible distinguir los datos que creó de los datos de otra cuenta eliminada.',
	'AccountDeleteWarning'		=> 'Eliminar la cuenta de usuario es una acción irreverible.',
	'AccountDeleteHint'			=> 'Su cuenta se eliminará del sistema. Por lo tanto, ya no podrá iniciar sesión con sus credenciales actuales. Si decide volver a ser un usuario de esta aplicación, puede hacerlo utilizando los medios que esta aplicación concede.',
	'AccountDeleteVerify'		=> 'Introduzca su nombre de usuario %1 para verificar la eliminación. Una vez enviado, se le pedirá que confirme su contraseña.',

	'MarkRead'					=> 'Marcar todo como leído',
	'CurrentTime'				=> 'Actualmente está',
	'Created'					=> 'creado',
	'Modified'					=> 'modificado',

	'EditIcon'					=> 'editar',
	'TreeClusterTitle'			=> 'Árbol del clúster %1',
	'TreeSiteTitle'				=> 'Árbol del sitio',
	'TreeEmpty'					=> '%1 no tiene subpáginas',
	'TreeEmptyLevels'			=> '%1 no tiene subpáginas para determinados niveles de profundidad. Incrementa el valor para profundidad.',
	'TreeTooBig'				=> 'demasiadas subpáginas',

	// clone handler
	'ClonePage'					=> 'Clonar página',
	'CloneText'					=> 'Clonar',
	'CloneName'					=> 'Introduzca un nuevo nombre para un clon de esta página',
	'CloneButton'				=> 'Clonar',
	'PageCloned'				=> 'Página %1 clonada.',
	'ClonedFrom'				=> 'Clonado desde %1.',
	'MassClone'					=> 'Clonar todo el clon',
	'MassCloning'				=> 'Clonando cluster.',
	'CloneCannotRead'			=> 'Página no legible %1.',
	'CloneCannotCreate'			=> 'Página no creable %1.',

	'SortComment'				=> 'Ordenar comentarios por',
	'SortCommentAsc'			=> 'Más recientes en la parte inferior',
	'SortCommentDesc'			=> 'Más recientes arriba',

	'RenamePage'				=> 'Renombrar página',
	'RenameText'				=> 'Renombrar',
	'RenameTip'					=> 'Renombrar página',
	'NewName'					=> 'Introduce un nuevo nombre para esta página',
	'AlreadyExists'				=> 'La página %1 ya existe.',
	'AlreadyNamed'				=> 'Esta página ya llamada %1.',
	'PageRenamed'				=> 'Página renombrada.',
	'NewNameOfPage'				=> 'Nuevo nombre de esta página: ',
	'NotOwnerCantRename'		=> 'No eres dueño de esta página y por lo tanto no puedes renombrarla',
	'NeedRedirect'				=> 'Crear redirección a la nueva página en la página anterior',
	'RedirectCreated'			=> 'En la página %1 creó la redirección a la nueva',

	'UserSettings'				=> 'Ajustes de usuario',
	'UserSettingsGeneral'		=> 'General',
	'UserSettingsNotifications'	=> 'Notificaciones',

	'NotifyMinorEdit'			=> 'Notificar también edición menor',
	'NotifyPageEdit'			=> 'Editar',
	'NotifyComment'				=> 'Comentario',
	'NotifyOff'					=> 'Apagado',
	'NotifyAlways'				=> 'Siempre',
	'NotifyPending'				=> 'Pendiente',
	'NotifyDigest'				=> 'Resumen',
	'NotifyPendingPageTip'		=> 'Sólo se envía una notificación para el cambio de página inicial de una página que está viendo.',
	'NotifyPendingCommentTip'	=> 'Sólo se envía una notificación para el primer comentario a una página que estás viendo.',
	'NotifyPendingTip'			=> 'La notificación se vuelve a activar automáticamente cuando visitas la versión actual de la página.',

	'FurtherPending'			=> 'No habrá otras notificaciones en caso de cambios adicionales a menos que visite esta página.',

	'UserSettingsEmailMe'		=> 'Escríbeme cuando ...',

	'UserSettingsExtended'		=> 'Extendido',
	'UserSettingsOther'			=> 'Otros ajustes',
	'UserSpace'					=> 'Espacio de usuario',
	'ChooseTheme'				=> 'Elegir tema',

	'CreatePage'				=> 'Crear esta página',
	'CreateNewPage'				=> 'Crear una nueva página',
	'CreateNewPageText'			=> 'Crear',
	'CreateNewPageTip'			=> 'Crear una nueva página',

	'CreateRandomPage'			=> 'Crear una página aleatoria:',
	'CreateSubPage'				=> 'Crear una subpágina en el cluster:',
	'CreatePageParentCluster'	=> 'Crear una página en el clúster padre:',
	'CreatePageDenied'			=> 'Usted no tiene los derechos de acceso necesarios.',
	'CreatePageDeniedAddress'	=> 'No tiene derecho a crear la página en esta dirección.',
	'PageAlreadyExists'			=> 'Según la dirección proporcionada, la página %1 ya existe.',
	'PageAlreadyExistsEdit'		=> '¿Quieres %1?',
	'PageAlreadyExistsEdit2'	=> 'editar',
	'PageAlreadyExistsEditDenied'	=> 'No puedes editarlo.',

	'SimilarPagesExists'		=> 'Las páginas similares a %1 ya existen:',
	'SimilarPagesHint'			=> 'Existen páginas similares a %1:',

	'PageReservedWord'			=> 'No puedes usar %1 como parte de la dirección ya que es una palabra reservada.',
	'UserReservedWord'			=> 'Los nombres de usuario no pueden contener %1 ya que es una palabra reservada.',

	'DontRedirect'				=> 'No permitir la redirección automática por acción Redirección.',
	'SendWatchEmail'			=> 'Enviar correo electrónico de notificación cuando alguien (excepto tu) cambie cualquier página que esté viendo',
	'AllowIntercom'				=> 'Permitir mensajes personales de usuarios del sistema',
	'AllowMassemail'			=> 'Los administradores me pueden enviar información',
	'HideLastSession'			=> 'Ocultar última sesión',
	'ValidateIP'				=> 'Asignando sesión a IP',
	'AnonymousPub'				=> 'Preferiblemente, publicado anónimamente (para ocultar el nombre)',
	'PageMoved'					=> 'Esta página se ha movido. Puedes encontrarla en',
	'RedirectedFrom'			=> 'Redirigido desde %1',
	'RedirectedTo'				=> 'Redirigido a',
	'CurrentPassword'			=> 'Contraseña actual',
	'NewPassword'				=> 'Nueva contraseña',
	'YouWantChangePassword'		=> 'Cambiar contraseña',
	'ChangePasswordButton'		=> 'Cambiar contraseña',
	'PasswordChanged'			=> 'Contraseña cambiada',
	'EmailWelcome'				=> 'Te has registrado en ',
	'EmailRegistered'			=> 'Te has registrado con éxito en %1.' . "\n" . 'Tu nombre de usuario: %2' . "\n\n",
	'EmailVerify'				=> 'Si quieres recibir notificaciones, debes verificar tu dirección de correo electrónico. Por favor, haz clic en o copia el siguiente enlace a un navegador web: ' . "\n" . '%1',
	'EmailRegisteredLogin'		=> 'Por favor, vuelve al Wiki e inicia sesión con tu nuevo nombre de usuario y contraseña.',
	'EmailRegisteredIgnore'		=> 'Si no has solicitado este registro, ignora este mensaje y no pasará nada.',
	'EmailDoNotReply'			=> 'No responder a este mensaje.',
	'EmailReverify'				=> 'Alguien (tal vez tú) envió tu correo electrónico como dirección de notificación en %1.' . "\n" . 'Tu nombre de usuario: %2'."\n\n" . 'Si quieres recibir notificaciones, necesitas aprobar tu correo electrónico. Por favor, sigue el enlace para hacer esto.' . "\n" . '%3' . "\n\n",
	'EmailConfirm'				=> 'Por favor verifique su correo electrónico',
	'EmailConfirmed'			=> 'Correo electrónico confirmado correctamente.',
	'EmailNotConfirmed'			=> 'El correo electrónico no puede ser confirmado. Esto puede ser debido a un código de confirmación incorrecto o la dirección de correo electrónico puede ya ser confirmada. Puedes comprobar si la dirección de correo electrónico ya está confirmada iniciando sesión y viendo su estado en tu página %1.',
	'EmailNotVerified'			=> '¡Correo no verificado!',
	'EmailNotVerifiedDesc'		=> 'No recibirás notificaciones de cambios o comentarios de páginas vigiladas, ' .
									'o mensajes de otros usuarios. Además, usted <strong>no será capaz de recuperar una contraseña olvidada</strong>, ' .
									'hasta que su dirección de correo electrónico sea confirmada siguiendo el enlace en el correo electrónico que se le ha enviado. ' .
									'Si, dentro de unos días después del registro no recibes un correo electrónico, pídelo de nuevo haciendo clic ',

	'ForgotPasswordHint'		=> 'Introduzca su nombre de usuario y dirección de correo electrónico' . "\n" . 'entonces se le enviará un correo electrónico con las instrucciones.',
	'ForgotPassword'			=> '¿Olvidaste la contraseña?',
	'UserNotFound'				=> 'Usuario con este nombre o dirección de correo electrónico no encontrado.',
	'NotConfirmedEmail'			=> 'Su dirección de correo electrónico no está confirmada.<br>El correo no puede ser enviado a una dirección no confirmada.',
	'EmailForgotSubject'		=> 'Renovación de contraseña para ',
	'EmailForgotMessage'		=> 'Alguien (tal vez tú) olvidó su contraseña para %1.' . "\n" . 'Tu conexión: %2'."\n\n" . 'Haga clic en el enlace o cópielo en la línea de dirección del navegador para cambiar su contraseña.' . "\n" . '%3'."\n\n",
	'CodeWasSent'				=> 'Las instrucciones de recuperación de contraseña se le enviaron por correo electrónico.',
	'WrongCode'					=> 'Código incorrecto',
	'ChangePasswordForUser'		=> 'Cambio de contraseña de %1',

	'Watchers'					=> 'Lista de vigilantes para %1',
	'WatchersFor'				=> 'Watchers para',
	'NoWatchers'				=> 'No hay vigilantes para %1',
	'NotOwnerToViewWatchers'	=> 'No eres el dueño de esta página y no puedes ver la lista de vigilantes para ella.',

	// thumbnail
	'TbnError'					=> 'Error al crear miniatura: %1',
	'TbnImageAreaTooBig'		=> 'Archivo con dimensiones mayores que %1',
	'TbnImageMissing'			=> 'El archivo parece estar ausente: %1',

	// admin_recovery action
	'GenerateRecoveryHash'		=> 'Genera el hash de contraseña para tu <code>recovery_password</code>',

	// import action
	'ImportTo'					=> 'Importar en clúster:',
	'ImportWhat'				=> 'Archivo XML a importar:',
	'ImportButton'				=> 'Importar',
	'ImportSuccess'				=> 'Importado con éxito.',
	'ImportFailed'				=> 'IMPORT falló.',
	'ImportHint'				=> 'Por favor, proporcione un clúster al que desea importar, sin dirección relativa.',
	'ImportAttention'			=> 'Atención: Sobrescribe las mismas páginas en el cluster.',
	'ImportNote'				=> 'Página importada',

	// mywatches action
	'WatchedPages'				=> 'Lista de todas las páginas que sigues para los cambios ',
	'UnwatchedPages'			=> 'Lista de todas las páginas que no ves',
	'NoWatchedPages'			=> 'No tienes páginas vigiladas.',
	'NoUnwatchedPages'			=> 'Observa los cambios en todas las páginas.',
	'ViewWatchedPages'			=> 'Mostrar páginas vistas',
	'ViewUnwatchedPages'		=> 'Mostrar página no vista',
	'NotLoggedInWatches'		=> 'No estás conectado, por lo tanto no pudimos identificar tu lista de relojes.',

	// mychangeswatches action
	'MyChangesWatches'			=> 'Lista de todas las páginas que has visto que han sido editadas por otros desde tu última edición',
	'ResetChangesWatches'		=> 'restablecer la lista de cambios',
	'NoChangesWatches'			=> 'Entre sus páginas vistas no hay cambios...',

	// whatsnew action
	'NewCommentAdded'			=> 'Nuevo comentario añadido',
	'NewFileAdded'				=> 'Nuevo archivo añadido',
	'NewPageCreated'			=> 'Creada una nueva página',
	'NewRevisionAdded'			=> 'Página cambiada',
	'Cluster'					=> 'cluster',
	'PageDeleted'				=> 'Página eliminada',
	'CommentDeleted'			=> 'Comentario eliminado',
	'FileDeleted'				=> 'Archivo eliminado',

	// users action
	'UsersSearch'				=> 'Buscar usuarios',
	'UsersOpenProfile'			=> 'Ver perfil',
	'UsersNoMatching'			=> 'No se encontraron usuarios coincidentes. Prueba con un criterio de búsqueda menos estricto.',
	'UsersName'					=> 'Nombre',
	'UsersPages'				=> 'Páginas',
	'UsersChanges'				=> 'Cambios',
	'UsersSubscription'			=> 'Suscripción',
	'UsersWatches'				=> 'Vistas',
	'UsersComments'				=> 'Comentarios',
	'UsersUploads'				=> 'Subir',
	'UploadQuota'				=> 'Espacio usado',
	'UploadQuotaTip'			=> 'Subir Cuota de Espacio',
	'UsersLogins'				=> 'Entradas',
	'UsersRevisions'			=> 'Revisiones',
	'UsersSignup'				=> 'Registrarse',
	'UsersLastSession'			=> 'Última sesión',
	'UsersNotFound'				=> 'Usuario %2 no encontrado. Haga clic <a href="%1">aquí</a>, para ir a la lista principal.',
	'UsersProfile'				=> 'Perfil',
	'UsersContact'				=> 'Contacto',
	'UsersList'					=> 'Ver la lista completa de usuarios',
	'UsersNA'					=> '[no establecido]',
	'UsersNA2'					=> '[No]',
	'UsersSignupDate'			=> 'Fecha de registro',
	'UsersGroupMembership'		=> 'Miembros del grupo',
	'UsersPersonalInfo'			=> 'Información personal',
	'UsersOwnedPages'			=> 'Páginas propietarias:',
	'UsersCommentsPosted'		=> 'Comentarios publicados:',
	'UsersFilesUploaded'		=> 'Archivos subidos:',
	'UsersRevisionsMade'		=> 'Revisiones realizadas:',
	'UsersDocsSortName'			=> '[Ordenar por nombre]',
	'UsersDocsSortCreation'		=> '[Ordenar por fecha de creación]',
	'UsersChangesSortAsc'		=> '[Ordenar ascendente]',
	'UsersChangesSortDesc'		=> '[Ordenar descendiendo]',
	'UsersSessionNA'			=> '[no grabado]',
	'UsersSessionHidden'		=> '[hidden]',
	'IntercomSubject'			=> 'Asunto:',
	'IntercomMessage'			=> 'Mensaje:',
	'IntercomCopy'				=> 'Enviarme una copia',
	'IntercomSubjectN'			=> '[iniciar un nuevo tema]',
	'IntercomDisabled'			=> 'Lo sentimos, no quieres o no puedes recibir mensajes personales.',
	'IntercomHint'				=> 'Inicie sesión primero y siga el enlace de nuevo, si desea responder al mensaje personal que ha recibido.',
	'IntercomDesc'				=> 'Nota: Enviando mensajes personales en el destinatario del correo electrónico sin revelar su dirección. El destinatario podrá responderle, utilizando un formulario similar en su página de perfil. ',
	'PMOversized'				=> 'La longitud del mensaje excede el tamaño máximo permitido por %1. Por favor, acorte su mensaje y envíelo de nuevo.',
	'PMFlooded'					=> 'El intervalo entre enviar mensajes personales no debe ser inferior a %1 segundos.',
	'PMSent'					=> 'Mensaje personal enviado correctamente al usuario.',
	'PMBody'					=> 'Este mensaje te ha sido enviado por el usuario %1.',
	'PMBodyCopy'				=> 'Enviaste el siguiente mensaje al usuario %1.',
	'PMReply'					=> 'Para responder a este correo electrónico, haga clic en el siguiente enlace (no utilice el botón Responder / Responder en el correo electrónico):',
	'PMNotLoggedIn'				=> 'No está registrado en el sistema y no puede enviar mensajes personales a los usuarios.',

	// admin_replace action
	'ReplaceText'				=> 'Reemplazar texto',
	'TextOriginal'				=> 'Texto original:',
	'TextReplacement'			=> 'Texto de reemplazo:',
	'ReplaceTextRegex'			=> 'Usar expresiones regulares',
	'Namespace'					=> 'Espacio de nombre:',
	'ReplaceTextCluster'		=> 'Buscar y reemplazar sólo dentro de este cluster:',
	'ReplaceTextEditPages'		=> 'Reemplazar texto en el contenido de la página',
	'ReplaceTextEditComments'	=> 'Reemplazar texto en los comentarios',
	'ReplaceTextEditTitles'		=> 'Reemplazar texto en títulos de página',
	'ReplaceTextGiveTarget'		=> 'Debe especificar la cadena a reemplazar.',
	'ReplaceTextNoNamespace'	=> 'Debe seleccionar al menos un espacio de nombres.',
	'ReplaceTextNoDifference'	=> 'No hay diferencia entre el texto de reemplazo y el texto de destino.',
	'ReplaceTextNoOption'		=> 'Debe seleccionar al menos una de las opciones de reemplazo.',
	'ReplaceTextPagesEdit'		=> 'Reemplazar %1 por %2 en el texto de las siguientes páginas %3:',
	'ReplaceTextTitlesEdit'		=> 'Reemplazar %1 por %2 en los títulos de las siguientes páginas %3:',
	'ReplaceTextReplace'		=> 'Reemplazar',
	'ReplaceTextSuccess'		=> '%1 ha sido reemplazado por %2 en páginas %3.',
	'ReplaceTextNoMatch'		=> 'No se han encontrado páginas que contengan la cadena %1.',
	'ReplaceTextNoTitleMatch'	=> 'No se han encontrado páginas que título contenga %1.',
	'ReplaceTextEditFailed'		=> 'Error al reemplazar texto',
	'ReplaceTextTitleTooBig'	=> 'El texto original o de reemplazo es demasiado grande para el título.',
	'ReplaceTextReturn'			=> 'Volver al formulario',
	'ReplaceTextWarning'		=> 'Advertencia: Hay páginas %1 que ya contienen la cadena de reemplazo, %2. Si realiza este reemplazo no podrá separar sus reemplazos de estas cadenas.',
	'ReplaceTextBlankWarning'	=> 'Advertencia: Debido a que la cadena de reemplazo está en blanco, esta operación no será reversible.',
	'ReplaceTextEditSummary'	=> 'Sustitución de texto: %1 → %2',
	'InvertSelection'			=> 'Invertir selección',

	// Properties
	'PropertiesFor'				=> 'Propiedades de la página para %1',
	'MetaTag'					=> 'Etiqueta',
	'MetaTitle'					=> 'Título',
	'MetaKeywords'				=> 'Palabras clave',
	'MetaDescription'			=> 'Descripción',
	'On'						=> 'En',
	'Off'						=> 'Apagado',
	'Registered'				=> 'Registrado',
	'MetaComments'				=> 'Mostrar comentarios',
	'MetaFiles'					=> 'Mostrar panel de archivos',
	'MetaToc'					=> 'Mostrar tabla de contenidos',
	'MetaIndex'					=> 'Mostrar panel de sección de clúster',
	'MetaIndexMode'				=> 'Mostrar modo de nivel',
	'MetaIndexFull'				=> 'Árbol',
	'MetaIndexUpper'			=> 'Superior',
	'MetaIndexLower'			=> 'Menor',
	'MetaHtml'					=> 'Soporte HTML para la página',
	'MetaSafeHtml'				=> 'Filtrado de HTML inseguro',
	'MetaTypografica'			=> 'Revisor tipográfico',
	'MetaNoIndex'				=> 'Bloquear motores de búsqueda',
	'SettingsID'				=> 'ID de página',
	'SettingsSize'				=> 'Tamaño',
	'SettingsSizeTip'			=> 'origen / compilado',
	'SettingsCreated'			=> 'Creado',
	'SettingsCurrent'			=> 'Modificado',
	'SettingsTotalRevs'			=> 'Revisiones',
	'SettingsTotalComs'			=> 'Comentarios',
	'SettingsWatchers'			=> 'Vestidos',
	'SettingsHits'				=> 'Vistas',
	'SettingsText'				=> 'Ajustes',
	'SettingsEdit'				=> 'Editar',
	'SettingsRevisions'			=> 'Revisiones',
	'SettingsClone'				=> 'Clonar',
	'SettingsRename'			=> 'Renombrar',
	'MassRename'				=> 'para todo el clúster',
	'SettingsRemove'			=> 'Eliminar',
	'SettingsPurge'				=> 'Purge',
	'SettingsModerate'			=> 'Moderado',
	'SettingsPermissions'		=> 'Permisos',
	'AclForEntireCluster'		=> 'para todo el clúster',
	'SettingsAttachments'		=> 'Adjuntos',
	'SettingsUpload'			=> 'Subir',
	'SettingsCategories'		=> 'Categorías',
	'SettingsLanguages'			=> 'Idiomas',
	'SettingsReferrers'			=> 'Referentes',
	'SettingsWatch'				=> 'Vigilar',
	'SettingsLatex'				=> 'Versión LaTeX',
	'SettingsXML'				=> 'Exportar a XML',
	'NeedToChangeLang'			=> 'El idioma de la página %1 no soportado necesita ser cambiado.',
	'SetLang'					=> 'Idioma de esta página',
	'SetMenuLabel'				=> 'Etiqueta de menú',
	'SetShowMenuLabel'			=> 'Mostrar en la navegación',

	// upload
	'UploadFiles'				=> 'Subir archivos',
	'UploadFor'					=> 'Carga de archivo:',
	'UploadButton'				=> 'Subir',
	'UploadGlobalText'			=> 'para acceso público',
	'UploadGlobal'				=> 'global',
	'UploadLocalText'			=> 'sólo para usuarios autorizados a ver la página actual',
	'UploadAsName'				=> 'Nombre:',
	'UploadOverwrite'			=> 'Sobrescribir archivos existentes',
	'FileDesc'					=> 'Descripción:',
	'UploadForbidden'			=> 'No tienes permisos para subir archivos aquí.',
	'UploadOverwriteDenied'		=> 'Sólo el dueño del archivo o el administrador pueden sobrescribir el archivo %1.',
	'UploadNoFile'				=> 'No había ningún archivo en forma, por alguna razón.',
	'UploadMaxSizeReached'		=> '¡El tamaño del archivo está por encima del límite permitido!',
	'UploadDirNotWritable'		=> 'No se puede escribir en el directorio de archivos!',
	'UploadNotAPicture'			=> 'Sólo se permiten subidas de fotos. ¿Qué estás intentando subir?',
	'UploadEmptyExtension'		=> 'El nombre del archivo y la extensión no pueden estar vacíos.',
	'FilenameTooLong'			=> 'Los nombres de archivo no pueden tener más de 240 bytes.',
	'BannedFiletype'			=> '%1 no es un tipo de archivo permitido.',
	'PermittedFiletype'			=> 'Tipos de archivos permitidos:',
	'UploadMimeMismatch'		=> 'La extensión de archivo %1 no coincide con el tipo MIME detectado del archivo (%2).',
	'UploadBadMime'				=> 'No se permiten subir archivos del tipo MIME %1.',
	'FileIsDuplicate'			=> 'La carga es un duplicado exacto de la versión actual.',
	'FileHasDuplicate'			=> 'Este archivo es un duplicado de los siguientes archivos:',

	'UploadMaxFileQuota'		=> 'Has alcanzado el límite de subida. Este archivo no se puede subir',
	'UploadDone'				=> 'Archivo subido con éxito',
	'UploadFileForbidden'		=> 'Acceso al archivo prohibido',
	'UploadTitle'				=> 'Archivos accesibles desde esta página',
	'UploadTitleGlobal'			=> 'Archivos accesibles desde cualquier lugar',

	'UploadFile'				=> 'Subir',
	'UploadMax'					=> 'No más de ',
	'UploadUsedStorage'			=> 'Almacenamiento en uso ',

	// attachments
	'Attachments'				=> 'Adjuntos',
	'Attachment'				=> 'Adjunto',
	'AttachmentsToPage'			=> 'a la página',
	'AttachmentsToCluster'		=> 'cluster',
	'AttachmentsByTime'			=> 'por hora',
	'AttachmentsGlobal'			=> 'global',
	'AttachmentsAll'			=> 'todo',
	'AttachmentsLinked'			=> 'usado',

	'FileViewProperties'		=> 'Ver',
	'FileViewPropertiesTip'		=> 'Ver los metadatos de este archivo',
	'FileEditProperties'		=> 'Editar',
	'FileEditPropertiesTip'		=> 'Editar los metadatos de este archivo',
	'FileEditedMeta'			=> 'Metadatos actualizados de este archivo',
	'FileEditDenied'			=> 'No tienes permisos para editar este archivo',
	'FileLabel'					=> 'Etiqueta',
	'FileLabelTip'				=> 'Etiqueta este archivo',
	'FileRemove'				=> 'Eliminar',
	'FileRemovedFromDB'			=> 'Archivo eliminado de la base de datos',
	'FileRemovedFromFS'			=> 'Archivo borrado del alojamiento físico',
	'FileRemovedFromFSError'	=> '¡Parece imposible borrar el archivo!',
	'FileRemoveConfirm'			=> '¿Seguro que quieres eliminar este archivo?',
	'FileRemoveDenied'			=> 'No tienes permisos para eliminar este archivo',
	'FileNotFound'				=> 'Archivo no encontrado.',

	'FileSearch'				=> 'Buscar archivo',
	'UploadBy'					=> 'Subido por:',
	'FileAdded'					=> 'Añadido:',
	'FileModified'				=> 'Modificado:',
	'FileSize'					=> 'Tamaño:',
	'FileDimension'				=> 'Dimensión:',
	'MimeType'					=> 'Mimetype:',
	'FileName'					=> 'Nombre:',
	'FileCaption'				=> 'Leyenda:',
	'FileAuthor'				=> 'Autor:',
	'FileSource'				=> 'Fuente:',
	'FileSourceUrl'				=> 'URL:',
	'FileAttachedTo'			=> 'Adjunto a:',
	'FileSyntax'				=> 'Sintaxis:',
	'FileAbsolutePath'			=> 'ruta absoluta',
	'FileRelativePath'			=> 'ruta relativa',
	'FileUsage'					=> 'Uso de archivo:',
	'FileUsageText'				=> 'Las siguientes páginas enlazan a este archivo:',
	'NoFileUsage'				=> 'No hay páginas enlazadas a este archivo.',

	'FileSortExt'				=> 'extensión',
	'FileSortName'				=> 'nombre',
	'FileSortSize'				=> 'tamaño',
	'FileSortTime'				=> 'creado',

	'SortBy'					=> 'Ordenar por',
	'Ascending'					=> 'ascendente',
	'Decending'					=> 'decreciente',

	'Files0'					=> 'Adjuntar archivos',
	'Files1'					=> 'Mostrar archivos (1 archivo)',
	'FilesN'					=> 'Mostrar archivos ( archivos%1)',
	'Files'						=> 'Archivos',
	'File'						=> 'Fichero',
	'ShowFiles'					=> 'Mostrar archivos / formulario',
	'HideFiles'					=> 'Ocultar archivos / formulario',
	'DoShowFiles'				=> 'Mostrar listas de archivos por defecto',
	'NoAttachments'				=> 'No hay archivos adjuntos para mostrar.',

	'RegistrationLang'			=> 'Tu idioma',
	'InvalidWikiName'			=> 'El nombre elegido no es válido',
	'InvalidUserName'			=> 'El nombre de usuario elegido no es válido',
	'Bookmarks'					=> 'Marcadores',
	'ReallyDeleteComment'		=> '¿Estás seguro de que quieres eliminar este comentario?<br>¡No hay deshacer esta acción!',
	'ReallyDeleteRevision'		=> '¿Realmente desea eliminar esta revisión?<br>¡No hay deshacer esta acción!',

	'RegistrationClosed'		=> 'El registro no está disponible aquí. Intenta contactar con el administrador del sitio.',
	'AclAreYouSure'				=> 'Vas a cambiar las ACL de esta página y todas sus subpáginas. ¿Continuar?',

	'BookmarkDeleteSelected'	=> 'Eliminar seleccionados',
	'BookmarkMark'				=> 'Marca',
	'BookmarkNumber'			=> 'No.',
	'BookmarkNone'				=> 'No tiene marcadores.',
	'BookmarkTitle'				=> 'Título del marcador',
	'BookmarkPage'				=> 'Pgina',
	'BookmarkSaveChanges'		=> 'Guardar cambios',
	'BookmarksAddPage'			=> 'Establecer un marcador para la siguiente página',
	'BookmarkAlreadyExists'		=> 'El marcador ya existe.',

	'PoweredBy'					=> 'Desarrollado por',

	'MassRenaming'				=> 'Renombrar todo el clúster',
	'MassNewName'				=> 'Introduce un nuevo nombre para este clúster',
	'MassNeedRedirect'			=> 'Crear redirección a las nuevas páginas en las páginas antiguas',

	// pagination
	'ToOverview'				=> 'Volver al resumen',
	'Overview'					=> 'Resumen',
	'ToThePage'					=> 'A página:',
	'Next'						=> 'Siguiente',
	'Prev'						=> 'Anterior',
	'NextAcr'					=> 'Siguiente',
	'PrevAcr'					=> 'Anterior',
	'Back'						=> 'Atrás',

	// filter
	'Filter'					=> 'Filtro',
	'OptionalFilters'			=> 'Filtros opcionales:',
	'Any'						=> 'Cualquier',

	// My Groups
	'UserGroups'				=> 'Grupos de usuarios',
	'MyGroups'					=> 'Asociaciones de grupo',
	'Group'						=> 'grupo',
	'Groups'					=> 'grupos',

	// license action
	'DistributedUnder'			=> 'El material se distribuye bajo',
	'AuthorsDisplayHint'		=> 'La lista de autores se mostrará al guardar la página.',
	'AnonymousUsers'			=> 'Usuarios anónimos',
	'License'					=> 'Licencia',
	'LicenseArray'				=> [
		'1'		=> 'Atribución-Sin derivados',
		'2'		=> 'Atribución-No Comercial-CompartirIgual',
		'3'		=> 'Atribución-No comercial-Sin derivados',
		'4'		=> 'Atribución-Compartir Igual',
		'5'		=> 'Atribución-No Comercial',
		'6'		=> 'Atribución',
		'7'		=> 'CC0 1.0 Universal',
		'8'		=> 'Licencia de documentación gratuita de GNU',
		'9'		=> 'Dominio Público / Uso gratuito',
		'10'	=> 'Todos los derechos reservados',
	],
	'LicenseMeta'				=> [
		'1'		=> 'Dominio público',
		'2'		=> 'Algunos derechos reservados',
		'3'		=> 'Todos los derechos reservados',
	],

	// Cache
	'ClearCache'				=> 'Limpiar caché',
	'CacheCleared'				=> 'Caché borrada.',
	'ConfigCache'				=> 'Config cache',
	'FeedCache'					=> 'Caché de alimentación',
	'PageCache'					=> 'Caché de página',
	'SQLCache'					=> 'Caché SQL',
	'TemplateCache'				=> 'Caché de plantillas',
	'ThumbCache'				=> 'Thumbnail cache',

	// Embed
	'EmbedNoURL'				=> 'Por favor especifique una dirección del recurso con la URL de Parameter. (por ejemplo, {{embed url="https://example.com/embed/video.mp4"}} )',

	// Feed
	'FeedTitle'					=> 'Título de la fuente',
	'FeedMulti'					=> 'Multi-Feed',
	'FeedNoURL'					=> 'Por favor especifique una fuente con la URL del parámetro. (ej. {{feed url="https://example.com/feed.xml"}} )',
	'FeedError'					=> 'No se pudo cargar o analizar el feed',
	'FeedSource'				=> 'Fuente:',
	'FeedXMLTip'				=> '',

	// XML / RSS autodiscovery
	'ChangesXMLTitle'			=> ' - Cambios recientes',
	'ChangesXML'				=> 'Cambios recientes en el ',
	'CommentsXMLTitle'			=> ' - Comentarios recientes',
	'CommentsXML'				=> 'Comentarios recientes a ',
	'NewsXMLTitle'				=> ' - Noticias recientes',
	'NewsXML'					=> 'Noticias recientes para el ',
	'RevisionXMLTip'			=> 'Haga clic para ver las revisiones de páginas recientes en formato XML.',
	'CommentsXMLTip'			=> 'Haga clic para ver los comentarios recientes en formato XML.',
	'ChangesXMLTip'				=> 'Haga clic para ver los cambios recientes en formato XML.',
	'NewsXMLTip'				=> 'Haga clic para ver las noticias recientes en formato XML.',
	'RevisionsXML'				=> 'Revisiones de ',
	'ExportClusterXML'			=> 'Exportar todo el clúster de ',
	'AccessDeniedXML'			=> 'No tienes permiso para acceder a esta información.',

	'ChangesFeed'				=> 'Cambios',
	'CommentsFeed'				=> 'Comentarios',
	'NewsFeed'					=> 'Noticias',
	'RevisionsFeed'				=> 'Revisiones de ',

	'LastModification'			=> 'Última modificación',

	// Captcha
	'Captcha'					=> 'Por favor, escribe la palabra que has leído en la imagen',
	'CaptchaFailed'				=> 'Ha introducido incorrectamente la palabra captcha. Por favor, inténtelo de nuevo.',
	'CaptchaReload'				=> 'Nuevo Captcha',
	'CaptchaReloadWarning'		=> 'Lo sentimos, no se puede recargar la imagen de captcha, tendrás que recargar la página para hacer eso',

	// news
	'News'						=> 'Noticias',
	'NewsName'					=> 'Título:',
	'NewsNoName'				=> 'Olvidaste añadir un encabezado de noticias.',
	'NewsNotAvailable'			=> 'No hay noticias disponibles.',
	'NewsNoClusterDefined'		=> 'Ningún clúster de noticias definido.',
	'NewsDiscuss'				=> 'Discutir este artículo...',

	// blog
	'BlogNewTopic'				=> 'Crear una nueva publicación',
	'NoPostAvailable'			=> 'Aún no hay post disponible.',

	// Review
	'Reviewer'					=> 'Revisor',
	'Reviewed'					=> 'revisado',
	'Review'					=> 'reseña',
	'ReviewedBy'				=> 'revisado por',
	'RemoveReview'				=> 'Eliminar reseña de esta página',
	'SetReview'					=> 'Revisada esta página',
	'SetAsReviewed'				=> 'Establecer página como revisada',
	'SetAsUnreviewed'			=> 'Establecer página como no revisada',

	// word filter
	'PotentialSpam'				=> 'Spam Potential Identificado',

	// moderation handler
	'Moderation'				=> 'Moderación',
	'Topics'					=> 'temas',
	'ModerateSection'			=> 'sección / página ',

	'NotModerator'				=> 'No tiene autoridad para moderar esta página / capítulo',
	'ModerateDeleteTopic'		=> 'Eliminar tema / página',
	'ModerateDeletePosts'		=> 'Eliminar comentarios',
	'ModerateMove'				=> 'Mover',
	'ModerateSplit'				=> 'Dividir / Mover comentarios',
	'ModerateMerge'				=> 'Combinar',
	'ModerateLock'				=> 'Bloquear',
	'ModerateUnlock'			=> 'Desbloquear',
	'ModerateAccept'			=> 'Aceptar',
	'ModerateDeleteConfirm'		=> 'Are you sure you want to <strong>remove</strong> the following topics?',
	'ModerateRenameConfirm'		=> 'Introduzca un nuevo título para la página seleccionada',
	'ModerateRenameExists'		=> '¡Ya existe una página con el mismo nombre! Elige un nombre diferente.',
	'ModerateRename1Only'		=> 'Nota: ¡Sólo la primera página seleccionada será renombrada!',
	'ModerateMovesConfirm'		=> 'Seleccione la partición de destino a la que mover el foro',
	'ModerateMoveConfirm'		=> 'Seleccione el foro o especifique el clúster para mover estos temas. Para mover una página a la raíz del sitio, escriba &quot;/&quot;',
	'ModeratePgMoveConfirm'		=> 'Especifique el nombre del clúster en el que colocar la página. Para mover una página a la raíz del sitio, escriba &quot;/&quot;',
	'ModerateMoveExists'		=> 'Operación abortada: En esta sección ya existe un tema con el mismo nombre %1. Si todavía necesita transferir los temas mencionados anteriormente, por favor renombrarlos primero.',
	'ModerateMoveNotExists'		=> 'La página / clúster no existe. Por favor, comprueba el nombre e inténtalo de nuevo.',
	'ModerateMergeConfirm'		=> 'Elija un tema, que combinará el resto',
	'ModerateMerge2Min'			=> 'Para unirte debes seleccionar al menos dos temas!',
	'ModerateComDelConfirm'		=> 'Are you sure you want to <strong>remove</strong> %1 %2?',
	'ModerateComment'			=> 'Comentario',
	'ModerateComments'			=> 'Comentarios',
	'ModerateSplitNewName'		=> 'Especifique un nombre para un tema separable y seleccione un esquema de separación',
	'ModerateSplitPageName'		=> 'Introduzca el nombre de la página / tema, donde mover los comentarios separables, y seleccione un esquema de separación',
	'ModerateSplitAllAfter'		=> 'Separar todos los comentarios después de la primera selección (e incluir)',
	'ModerateSplitSelected'		=> 'Separados sólo los comentarios seleccionados (total %1)',
	'ModerateUserProfile'		=> 'perfil',
	'ModerateNoItemChosen'		=> 'Por favor, seleccione al menos un elemento mediante el botón Configurar.',

	'ModerateSection2'			=> 'moderar sección',
	'ModerateTopicsDeleted'		=> 'Los temas seleccionados se han eliminado correctamente.',
	'ModerateTopicsRelocated'	=> 'Los temas seleccionados se reubicaron correctamente.',
	'ModerateTopicsRenamed'		=> 'Tema renombrado correctamente.',
	'ModerateTopicsMerged'		=> 'Temas seleccionados con éxito fusionados.',
	'ModerateTopicsBlocked'		=> 'Temas seleccionados bloqueados con éxito',
	'ModerateTopicsUnlocked'	=> 'Los temas seleccionados han sido desbloqueados.',
	'ModerateTopicDeleted'		=> 'El tema se ha eliminado correctamente.',
	'ModeratePageMoved'			=> 'Página movida correctamente.',
	'ModerateTopicRenamed'		=> 'Tema renombrado correctamente.',
	'ModerateTopicBlocked'		=> 'Tema bloqueado correctamente',
	'ModerateTopicUnlocked'		=> 'Tema desbloqueado correctamente.',
	'ModerateCommentsDeleted'	=> 'Comentarios seleccionados eliminados con éxito.',
	'ModerateCommentsSplit'		=> 'Los comentarios seleccionados han sido separados con éxito en un nuevo tema.',
	'ModerateCommentsSplitFailed'	=> 'Note: For some reason separating the selected comments to a new topic failed.<br>Usually this should not happen, so please notify the site administrator.<br>As a precaution, the issue has been preserved in its original form.',
	'ModerateCommentsMoved'		=> 'Los comentarios seleccionados han migrado con éxito a la página dada.',

	// forum
	'ForumSubforums'			=> 'Foro',
	'ForumTopic'				=> 'Tema',
	'ForumTopics'				=> 'Temas',
	'ForumPosts'				=> 'Mensajes',
	'ForumReplies'				=> 'Respuestas',
	'ForumAuthor'				=> 'Autor',
	'ForumViews'				=> 'Vistas',
	'ForumCreated'				=> 'Creado',
	'ForumComments'				=> 'Comentarios',
	'ForumLastComment'			=> 'Último comentario',
	'ForumNoComments'			=> 'No hay comentarios',
	'ForumNoTopics'				=> 'No hay temas o mensajes en este foro.',
	'ForumNewTopic'				=> 'Empezar una nueva discusión',
	'ForumTopicName'			=> 'Nombre del tema:',
	'ForumTopicSubmit'			=> 'Enviar tema',
	'ForumNoTopicName'			=> 'Especifique un nombre para la nueva página.',
	'ForumNewPosts'				=> 'nuevo post',
	'ForumLocked'				=> 'sección bloqueada',
	'ForumUpdated'				=> 'actualizado',
	'ForumNoClusterDefined'		=> 'Ningún clúster del foro definido.',
	'ForumOutsideCluster'		=> 'Asegúrese de que la acción %1 se encuentra dentro del clúster del foro.',

	// password complexity
	'PwdCplxShort'				=> 'La contraseña es demasiado corta.',
	'PwdCplxEquals'				=> 'La contraseña contiene el nombre de usuario.',
	'PwdCplxWeak'				=> 'La contraseña no cumple con los requisitos de complejidad.',
	'PwdCplxDesc1'				=> 'Requisitos para la contraseña: ',
	'PwdCplxDesc2'				=> 'la contraseña no debe tener menos de %1 caracteres',
	'PwdCplxDesc3'				=> 'no debe contener su nombre de usuario',
	'PwdCplxDesc4'				=> 'debe consistir en ',
	'PwdCplxDesc41'				=> 'letras y números',
	'PwdCplxDesc42'				=> 'mayúsculas y minúsculas y números',
	'PwdCplxDesc43'				=> 'letras mayúsculas y minúsculas, dígitos y caracteres no alfanuméricos',
	'PwdCplxDesc5'				=> 'Puede utilizar cualquier letra, números y caracteres especiales excepto espacios.',

	'PasswordTooShort'			=> 'Contraseña demasiado corta.',
	'PasswordTooCommon'			=> 'Esa contraseña es demasiado común.',
	'PasswordSameAsUsername'	=> 'Su contraseña es la misma que su nombre de usuario.',
	'PasswordSameAsEmail'		=> 'Su contraseña es la misma que su correo electrónico.',

	'Timezone'					=> 'Timezone',

	'LanguageArray'	=> [
		'bg' => 'Búlgaro',
		'da' => 'Danés',
		'de' => 'Alemán',
		'el' => 'Griego',
		'en' => 'Inglés',
		'es' => 'Español',
		'et' => 'Estonio',
		'fa' => 'Persa',
		'fr' => 'Francés',
		'hi' => 'Hindú',
		'hu' => 'Húngaro',
		'it' => 'Italiano',
		'ja' => 'Japonés',
		'ko' => 'Coreano',
		'nl' => 'Holandés',
		'pl' => 'Polaco',
		'pt' => 'Portugués',
		'ru' => 'Ruso',
		'ta' => 'Tamil',
		'zh' => 'Chino',
		'zh-tw' => 'Chino',
	],

	'AccountStatus'				=> 'Estado de la cuenta',
	'AccountStatusArray' => [
		'0' => 'activo',
		'1' => 'pendiente',
		'2' => 'bloqueado',
		'3' => 'inactivo',
	],

	'JustNow'		=> 'justo ahora',
	'MinuteAgo'		=> 'hace un minuto',
	'MinutesAgo'	=> '%1 minutes ago',
	'HourAgo'		=> 'hace una hora',
	'HoursAgo'		=> '%1 hours ago',
	'DayAgo'		=> 'ayer',
	'DaysAgo'		=> '%1 days ago',
	'WeekAgo'		=> 'hace una semana',
	'WeeksAgo'		=> '%1 weeks ago',
	'MonthAgo'		=> 'hace un mes',
	'MonthsAgo'		=> '%1 months ago',
	'YearAgo'		=> 'hace un año',
	'YearsAgo'		=> '%1 years ago',

	'InAMoment'		=> 'en un momento',
	'InAMinute'		=> 'en un minuto',
	'InMinutes'		=> 'en %1 minutos',
	'InAnHour'		=> 'en una hora',
	'InHours'		=> 'en %1 horas',
	'Tomorrow'		=> 'mañana',
	'InDays'		=> 'en %1 días',
	'InAWeek'		=> 'en una semana',
	'InWeeks'		=> 'en %1 semanas',
	'InAMonth'		=> 'en un mes',
	'InMonths'		=> 'en %1 meses',
	'InAYear'		=> 'en un año',
	'InYears'		=> 'en %1 años',

	// norm multiples
	'ByteDecimalShort'			=> ['B', 'kB', 'Mb', 'GR', 'TB', 'PB', 'EB', 'ZB', 'YB'],
	'ByteDecimalLong'			=> ['Byte', 'Kilobyte', 'Megabyte', 'Gigabyte', 'Terabyte', 'Petabyte', 'Exabyte', 'Zettabyte', 'Yottabyte'],
	'ByteBinaryShort'			=> ['B', 'KiB', 'MiB', 'GiB', 'TiB', 'PiB', 'EiB', 'ZiB', 'YiB'],
	'ByteBinaryLong'			=> ['Byte', 'Kibibyte', 'Mebibyte', 'Gibibyte', 'Tebibyte', 'Pebibyte', 'Exbibyte', 'Zebibyte', 'Yobibyte'],
	'PixelDecimalShort'			=> ['px', 'KP', 'MP', 'MP', 'TP', 'PP', 'EP', 'ZP', 'YP'],
	'PixelDecimalLong'			=> ['píxel', 'Kpx', 'Mpx', 'Gpx', 'Tpx', 'Px', 'Ex', 'Zpx', 'Ypx'],

	// loading error
	'UnknownAction'				=> 'Acción desconocida',
	'UnknownMethod'				=> 'Método desconocido',
	'FormatterNotFound'			=> 'Formateo %1 no encontrado',

	// log
	'LogAdminLoginSuccess'		=> 'Inicio de sesión exitoso en el panel administrativo',
	'LogAdminLogout'			=> 'Cerrar sesión del panel administrativo',
	'LogAdminLoginFailed'		=> '!!No autoriza el acceso al panel administrativo!!',
	'LogAdminLoginLocked'		=> 'Inicio de sesión bloqueado en el panel administrativo',
	'LogUserCookieForged'		=> '!!**Un intento de iniciar sesión en una cookie forjada con inicio de sesión ##%1##**!!',
	'LogInvalidFormToken'		=> 'Ataque de CSRF Potential en progreso detectado: %1',
	'LogRemovedPage'			=> '!!Eliminó la página ##%1## (usuario %2)!!',
	'LogRemovedCluster'			=> '!!Eliminado **cluster** ##%1## (usuario %2)!!',
	'LogRemovedRevision'		=> '!!Eliminó la revisión ##%3## de la página [[/%1]] (usuario %2)!!',
	'LogRemovedComment'			=> '!!Eliminó el comentario de %3 en la página [[/%1]] (usuario %2)!!',
	'LogRemovedFile'			=> '!!Eliminado el archivo ##%2## de la página [[/%1]]!!',
	'LogRemovedAllComments'		=> '!!Eliminado todos los comentarios de la página [[/%1]]!!',
	'LogRemovedAllRevisions'	=> '!!Eliminó todas las revisiones de la página [[/%1]]!!',
	'LogRemovedAllFiles'		=> '!!Eliminados todos los archivos, adjuntos a [[/%1]]!!',
	'LogTopicLocked'			=> 'Tema del foro está bloqueado [[/%1]]',
	'LogTopicUnlocked'			=> 'Tema del foro desbloqueado [[/%1]]',
	'LogAclUpdated'				=> 'Página ACL actualizada [[/%1]]',
	'LogOwnershipChanged'		=> 'Propiedad de la página [[/%1]] transferida al usuario ##%2##',
	'LogUserLoginFailed'		=> '!!¡Intenta iniciar sesión con ##~%1##!!',
	'LogClonedPage'				=> 'Página ##%1## clonado en [[/%2]]',
	'LogRenamedPage'			=> 'Página ##%1## renombrada a [[/%2]]',
	'LogRenamedPage2'			=> '. La página anterior se estableció como el enlace a la nueva',
	'LogSplittedPage'			=> 'Comentarios en la página [[/%1]] dividir en página [[/%2]]',
	'LogMergedPages'			=> 'Páginas %1 combinadas a la página [[/%2]]',
	'LogUserPasswordReminded'	=> 'El usuario ##%1## solicitó el proceso de recuperación de contraseña para la dirección ##%2##',
	'LogUserPasswordRecovered'	=> 'Usuario ##%1## recuperó con éxito la contraseña olvidada',
	'LogUserPasswordChanged'	=> 'Usuario ##%1## actualizado correctamente (cambiado) la contraseña',
	'LogUserPasswordMismatch'	=> '!!User ##%1## falló al cambiar la contraseña: la contraseña actual no coincide!!',
	'LogUserIPSwitched'			=> 'Cambio de dirección IP no autorizado del usuario %1 de %2 a %3',
	'LogPageImported'			=> 'Página importada [[/%1]]',
	'LogSaveNoRights'			=> 'No hay permisos apropiados para guardar la página [[/%1]]',
	'LogPageCreated'			=> 'Nueva página creada [[/%1]]',
	'LogPagePropertiesUpdated'	=> 'Propiedades de página actualizadas [[/%1]]',
	'LogPageOwnershipClaimed'	=> 'El usuario tiene la propiedad de la página [[/%1]]',
	'LogFileUploadedLocal'		=> 'Nuevo archivo ##%2## subido a la página [[/%1]] (tamaño %3)',
	'LogFileUploadedGlobal'		=> 'Nuevo archivo ##%2## subido a la carpeta global (tamaño %3)',
	'LogPMSent'					=> 'Mensaje personal ##%1## -> ##%2## enviado correctamente',
	'LogUserSimilarName'		=> 'Hubo intentos de registrarse con el mismo nombre de usuario: ##%1##',
	'LogUserEmailNotAllowed'	=> 'El correo electrónico ##%1## no está en la lista de dominios permitidos',
	'LogRegisterTiming'			=> 'Registro fallido, el umbral de tiempo del formulario es ##%1## segundos (fue ##%2##)',
	'LogUserRegistered'			=> 'Registrado con éxito un nuevo usuario ##%1## (##%2##)',
	'LogUserEmailActivated'		=> 'Correo electrónico activado con éxito ##%1## del usuario ##%2##',
	'LogCommentPosted'			=> 'Se añadieron [[/%1 nuevos comentario(s)]] a la página [[/%2]]',
	'LogUserLoginOK'			=> 'Usuario ##%1## registrado correctamente en el sistema',
	'LogUserLoggedOut'			=> 'Usuario ##%1## ha cerrado correctamente la sesión del sistema',
	'LogUserSessionContinued'	=> 'Usuario ##%1## continuó la sesión suspendida',
	'LogUserSettingsUpdate'		=> 'Usuario ##%1## actualizó los ajustes personales',
	'LogPageEdited'				=> 'Página editada [[/%1]]',
	'LogCommentEdited'			=> 'Comentario editado [[/%1]]',
	'LogUpdatedFileMeta'		=> 'Metadatos de archivo actualizados para ##%2## desde la página [[/%1]]',
	'LogUpdatedFileCategories'	=> 'Categorías de archivo actualizadas para ##%2## desde la página [[/%1]]',

	'LogXmlSitemapGenerated'	=> 'XML Sitemap generado',
	'LogReferrersPurged'		=> 'Mantenimiento: referencias purgadas',
	'LogRevisionsPurged'		=> 'Mantenimiento: revisiones de páginas obsoletas purgadas',
	'LogDeletedPagesPurged'		=> 'Mantenimiento: páginas borradas',
	'LogSystemLogPurged'		=> 'Mantenimiento: registro del sistema purgado',
	'LogCachedPagesPurged'		=> 'Mantenimiento: páginas cacheadas purgadas',
	'LogSqlCachePurged'			=> 'Mantenimiento: resultados sql en caché purgados',
	'LogExpiredTokensPurged'	=> 'Mantenimiento: purgado cookie_tokens caducado',
	'LogErrorSplitComments'		=> 'Error al separar los comentarios del tema [[/%1]] un nuevo tema ##%2##: página no fue creada',
	'LogCategoriesUpdated'		=> 'Categorías de página actualizadas [[/%1]]',
	'LogCategoryCreated'		=> 'Creó una nueva categoría //%1//',
	'LogCategoryRenamed'		=> 'Categoría ##%1## renombrado a ##%2##',
	'LogCategoryDebundled'		=> 'Categoría ##%1## desbaratada',
	'LogCategoryGrouped'		=> 'Categoría ##%1## agrupada con la palabra ##%2##',
	'LogCategoryRemoved'		=> 'Categoría ##%1## eliminada de la base de datos',
	'LogThumbnailGeneration'	=> 'Generación de miniaturas %1 seg.',

	'ErrorMinPHPVersion'		=> 'La versión PHP debe ser mayor que <strong>' . PHP_MIN_VERSION . '</strong>,' .
									' tu servidor parece estar ejecutando <strong>' . PHP_VERSION . '</strong>.' .
									'  Debería actualizar a una versión más reciente de PHP para que WackoWiki funcione correctamente.',

];
