<?php

if (!defined('IN_WACKO'))
{
	exit;
}

$wacko_translation = [

	// language
	'lang_scheme'	=> [
		'name'		=> 'Nederlands',
		'code'		=> 'nl',
		'dir'		=> 'ltr',
		'locale'	=> 'nl_NL.UTF-8',
	],

	// common
	'AddButton'					=> 'Toevoegen',
	'ArchiveButton'				=> 'Archief',
	'CancelButton'				=> 'annuleren',
	'ContinueButton'			=> 'Doorgaan',
	'ConvertButton'				=> 'Converteren',
	'CreateButton'				=> 'Aanmaken',
	'DeleteButton'				=> 'Verwijderen',
	'RemoveButton'				=> 'Verwijderen',
	'RenameButton'				=> 'Hernoem',
	'ResetButton'				=> 'Reset',
	'RestoreButton'				=> 'Herstellen',
	'SaveButton'				=> 'Opslaan',
	'SearchButton'				=> 'Zoeken',
	'SendButton'				=> 'Verzenden',
	'SetButton'					=> 'Instellen',
	'SubmitButton'				=> 'Bevestigen',
	'UpdateButton'				=> 'Vernieuwen',

	'FormInvalid'				=> 'Het ingediende formulier was ongeldig. Probeer het opnieuw.',
	'UnitPixel'					=> 'px',
	'Number'					=> 'Nummer',

	// logged in panel
	'AccountText'				=> 'Rekening',
	'AccountTip'				=> 'Account Instellingen',
	'AdminText'					=> 'Beheerder',
	'AdminTip'					=> 'Administratief paneel',
	'LogoutLink'				=> 'Afmelden',
	'LogoutButton'				=> 'Log uit',
	'LogoutAreYouSure'			=> 'Weet je zeker dat je wilt uitloggen?',

	// registration panel
	'RegistrationWelcome'		=> 'Nieuwe gebruikersregistratie:',
	'RegistrationButton'		=> 'Registreer mij',
	'UserNameOwned'				=> 'Deze gebruikersnaam is al geregistreerd. Kies een andere.',
	'SiteRegistered'			=> 'U bent succesvol geregistreerd op de site %1.',
	'RegistrationEmailInfo'		=> 'Een geldig e-mailadres. Alle e-mails uit het systeem worden naar dit adres verzonden. Het e-mailadres is niet openbaar gemaakt en wordt alleen gebruikt als u een nieuw wachtwoord wilt ontvangen of een bepaald nieuws of meldingen per e-mail wilt ontvangen.',
	'EmailConfirmHint'			=> 'Bevestig uw e-mailadres door te klikken op de link in de instructies die naar u is verzonden. <br>Als je je e-mailadres niet verifieert, kun je geen mogelijk verloren wachtwoord opvragen. <br>Bovendien wordt u niet geïnformeerd over recente pagina-wijzigingen en commentaren.',
	'EmailConfirmRequired'		=> 'Zonder bevestigd e-mailadres mag u niet inloggen.',
	'NameTooShort'				=> 'De gebruikersnaam is te kort, een minimum van %2 tekens is vereist.',
	'NameTooLong'				=> 'De gebruikersnaam is te lang, maximaal %2 tekens zijn toegestaan.',
	'NameAlphanumOnly'			=> 'Gebruikersnaam moet tussen %1 en %2 tekens lang zijn en mag alleen alfanumerieke tekens bevatten. Hoofdletters zijn OK.',
	'NameCamelCaseOnly'			=> 'Gebruikersnaam moet tussen %1 en %2 karakters lang en WikiName opgemaakt.',
	'NewUserAccount'			=> 'nieuw gebruikersaccount',

	'NewAccountSubject'			=> 'Account registratie',
	'NewAccountAdminCreated'	=> 'De gebruiker %1 heeft een account voor u aangemaakt met gebruikersnaam "%2". Om uw registratie te voltooien, bezoek de volgende URL (zorg ervoor dat deze is ingevoerd als de enkele regel) en stel uw eigen toegangswachtwoord in:',
	'NewAccountUsername'		=> 'Gebruikersnaam:',
	'AccountLanguage'			=> 'Taal:',
	'NewAccountEmail'			=> 'Email:',
	'NewAccountIP'				=> 'Extern IP-adres:',
	'NewAccountSignupInfo'		=> 'Het volgende account is aangemaakt:',

	'UserWaitingApproval'		=> 'Een e-mail is verstuurd naar de site administrator. De beheerder zal de informatie beoordelen die is ingediend en uw verzoek goedkeuren of weigeren.',
	'UserRequiresApproval'		=> 'Om deze gebruiker toegang tot %1 goed te keuren of te weigeren, gaat u naar het beheerderspaneel.',
	'UserApprovalInfo'			=> 'Nadat u zich heeft geregistreerd, zal uw verzoek worden verzonden naar de sitebeheerder ter goedkeuring. U ontvangt vervolgens een e-mail met verdere instructies.',
	'UserApprovalHint'			=> 'De succesvolle activering van uw account zal in een specifiek e-mail worden aangekondigd. Tot die tijd is een login niet mogelijk.',

	'UserApprovalPending'		=> 'Uw account is nog in afwachting van goedkeuring.',
	'UserApprovalDenied'		=> 'Uw account heeft geen toegang tot deze site gekregen.',

	'RegistrationApproved'		=> 'Registratie goedgekeurd',
	'RegistrationDenied'		=> 'Registratie geweigerd',
	'PendingApproval'			=> 'Wachten op goedkeuring',

	'UserApprovedInfo'			=> 'U bent goedgekeurd voor toegang %1.',
	'UserDeniedInfo'			=> 'U hebt de toegang tot %1 geweigerd.',

	'RegistrationThreshold'		=> 'De tijd voor het invullen van het formulier mag niet minder zijn dan %1 seconden.',
	'Language'					=> 'Taal',

	// login panel
	'LoginWelcome'				=> 'Aanmelden',
	'CreateAccount'				=> 'Nieuw account aanmaken',
	'RegistrationLink'			=> 'Registratie',
	'LoginName'					=> 'Gebruikersnaam',
	'Password'					=> 'Wachtwoord',
	'LoginButton'				=> 'Aanmelden',
	'LoginLink'					=> 'Aanmelden',
	'PersistentCookie'			=> 'Aangemeld blijven',
	'Session'					=> 'Sessie',
	'SessionTip'				=> 'parameters van de huidige sessie',
	'SessionDuration'			=> 'Sessie duur',
	'SessionDurationSession'	=> 'browser sessie',
	'SessionDurationDay'		=> '1 dag',
	'SessionDurationWeek'		=> '1 week',
	'SessionDurationMonth'		=> '1 maand',
	'LoggedInAs'				=> 'U bent ingelogd als',

	'ClearCookies'				=> 'Alle cookies verwijderen',
	'BindSessionIp'				=> 'Sessie koppelen aan IP adres',
	'BindSessionIpOn'			=> 'ingeschakeld (huidige IP %1)',
	'TrafficProtection'			=> 'Data bescherming',
	'SessionEnds'				=> 'De huidige sessie eindigt',
	'LastVisit'					=> 'Laatste bezoek werd opgenomen',

	'LoginIncorrect'			=> 'De ingevoerde gebruikersnaam of wachtwoord is ongeldig.',
	'WelcomeBack'				=> 'Welkom terug, %1',
	'LoginAttemptsExceeded'		=> 'U heeft het maximaal toegestane aantal login pogingen overschreden.<br>Naast uw gebruikersnaam en wachtwoord moet u nu ook de onderstaande CAPTCHA oplossen.',

	// session notice
	'IPAddressChanged'			=> 'IP adres veranderd naar %1 (was %2)',

	'SessionReplay'				=> 'Sessie beëindigd als gevolg van herhaling.',
	'SessionObsolete'			=> 'Sessie is verouderd.',
	'SessionExpired'			=> 'Sessie is verlopen.',
	'SessionTimeout'			=> 'Sessie beëindigd als gevolg van time-out.',
	'SessionInactivity'			=> 'Sessie beëindigd door inactiviteit.',
	'SessionUaChange'			=> 'Sessie beëindigd als gevolg van wijziging van de useragent.',
	'SessionTLSChange'			=> 'Sessie beëindigd als gevolg van TLS.',
	'SessionIPChange'			=> 'Sessie beëindigd als gevolg van IP-wijziging.',

	// other
	'Guest'						=> 'Gast',
	'Everybody'					=> 'Iedereen',
	'Help'						=> 'Hulp',
	'TopicSearchText'			=> 'Alleen in titels zoeken',
	'WordprocessorVersion'		=> 'Woord processor versie',

	// notifications
	'EmailHello'				=> 'Hallo ',
	'EmailModerator'			=> 'Moderator',
	'WatchedPageChanged'		=> 'Pagina gewijzigd ',
	'SomeoneChangedThisPage'	=> ' heeft een pagina gewijzigd die u bekijkt: ',
	'NewPageCreatedSubj'		=> 'Een nieuwe pagina',
	'NewPageCreatedBody'		=> 'Gebruiker %1 heeft een nieuwe pagina gemaakt: ',
	'FileUploadedSubj'			=> 'Een nieuw bestand',
	'FileUploadedBody'			=> 'Gebruiker %1 heeft een nieuw bestand geüpload: ',
	'FileReplacedBody'			=> 'Gebruiker %1 heeft het bestand vervangen: ',

	'ActionDenied'				=> 'Actie wordt hier geweigerd.',
	'TocTitle'					=> 'Inhoud ',
	'OuterLink2'				=> 'Uitgaande link',
	'FileLink'					=> '',
	'PDFLink'					=> 'PDF Document',
	'RDFLink'					=> 'RDF Document',
	'EmailLink'					=> 'Schrijf een e-mail (mail client launch)',
	'JabberLink'				=> 'Chat via XMPP (Jabber client launch)',
	'PermaLink'					=> 'Permalink',
	'PermaLinkTip'				=> 'Permanente link naar deze herziening van de pagina',
	'PermaLink0Tip'				=> 'Permanente link naar deze pagina',

	'ShowTip'					=> 'Retour in weergavemodus',
	'ShowText'					=> 'Bekijken',
	'WikieditAutocomplete'		=> 'Voltooi wikilinks door Ctrl+Space',
	'WikiEditInactiveJs'		=> 'Schakel Javascript in om WikiEdit te kunnen gebruiken.',
	'NumerateLinks'				=> 'Numerieke links in afdrukweergave',
	'Comment'					=> 'Opmerking',
	'Comments0'					=> 'Voeg uw opmerking toe',
	'Comments1'					=> 'Lees reactie (1 commentaar)',
	'CommentsN'					=> 'Leesopmerkingen (%1 commentaar)',
	'Comments'					=> 'Opmerkingen',
	'CommentHint'				=> '<a href="%1">Log in</a> of <a href="%2">maak een account aan</a> om een opmerking te plaatsen.',
	'CommentEdited'				=> 'bewerkt',
	'Links'						=> 'Koppelingen',
	'Version'					=> 'Versie',

	// details formatter
	'ShowHideDetails'			=> 'Beschrijving',

	'PrivacyPolicy'				=> 'Privacy Beleid',
	'TermsOfUse'				=> 'Gebruiksvoorwaarden',
	'AcceptTermsOfUse'			=> 'Ik heb de Algemene Voorwaarden van de site gelezen, begrepen en ga hiermee akkoord.',

	'ShowComments'				=> 'Toon reacties / formulier',
	'HideComments'				=> 'Opmerkingen verbergen / formulier',
	'AddComment'				=> 'Voeg een opmerking toe aan deze pagina:',
	'AddCommentTitle'			=> 'Titel van de reactie:',
	'CommentTitleRe'			=> 'Re:',
	'AddCommentButton'			=> 'Opmerking toevoegen',
	'HereLink'					=> 'Hier',
	'PageHandlerMoreTip'		=> 'meer',

	'ThemeCorrupt'				=> 'Thema is beschadigd',
	'InvalidNamespace'			=> 'Ongeldige namespace gegeven.',
	'DoesNotExists'				=> 'Deze pagina bestaat niet.',
	'PromptCreate'				=> 'Misschien wil je <strong><a href="%1">maken</a></strong>?',
	'RevisionHint'				=> 'Dit is een oude herziening van <a href="%1">%2</a> van %3 bewerkt door %4.',
	'ReadAccessDenied'			=> 'Je hebt geen toestemming om deze pagina te lezen.',
	'ReadAccessDeniedHintGuest'	=> 'Om deze pagina te lezen, moet u zich aanmelden.',
	'PageDeletedInfo'			=> 'Deze pagina is verwijderd.',
	'RevisionDeletedInfo'		=> 'Deze revisie is verwijderd.',
	'CommentDeletedInfo'		=> 'Deze reactie is verwijderd.',

	'LastEditedBy'				=> 'Laatst bewerkt door',
	'YouAreOwner'				=> 'U bent de eigenaar van deze pagina.',
	'Owner'						=> 'Eigenaar:',
	'Nobody'					=> 'Niemand',
	'TakeOwnership'				=> 'Verantwoordelijkheid nemen',
	'FilesTip'					=> 'Bijgevoegde bestanden beheren',
	'FilesText'					=> 'Bijlagen',
	'DeleteTip'					=> 'Pagina verwijderen, alle bestanden en commentaren verwijderen',
	'DeleteCommentTip'			=> 'Commentaar verwijderen',
	'DeleteText'				=> 'Verwijderen',
	'AclText'					=> 'Machtigingen',
	'AclTip'					=> 'Rechten bewerken',

	'PropertiesText'			=> 'Eigenschappen',
	'PropertiesTip'				=> 'Pagina-eigenschappen bewerken',
	'EditTip'					=> 'Bewerk deze pagina.',
	'EditText'					=> 'Bewerken',
	'EditSection'				=> 'Bewerk sectie %1',
	'EditSectionHint'			=> 'Sectie %1 van %2',
	'SectionHeadline'			=> 'Sectie',
	'EditCommentTip'			=> 'Commentaar bewerken',
	'EditComment'				=> 'Deze reactie bewerken',
	'ReplyComment'				=> 'Beantwoorden',
	'ReplyCommentTip'			=> 'Reageer op deze reactie',
	'RevisionTip'				=> 'Bekijk pagina revisies',
	'RevisionText'				=> 'Herzieningen',
	'ReferrersTip'				=> 'Een lijst met URL\'s die verwijzen naar deze pagina weergeven',
	'ReferrersText'				=> 'Verwijzers',
	'ModerateTip'				=> 'Moderatie van onderwerpen en forum berichten',
	'ModerateText'				=> 'Matig',
	'SearchText'				=> 'Zoek: ',

	'AclUpdated'				=> 'Toegangscontrolelijsten bijgewerkt',
	'AclGaveOwnership'			=> ' en gaf %1 eigendom aan.',
	'AclNoNewOwner'				=> 'Pagina eigendom is niet overgedragen, omdat de gebruiker %1 niet werd gevonden.',
	'NewPageOwnership'			=> 'Eigenaarschap pagina overdragen',
	'YouAreNewOwner'			=> 'voormalige eigenaar %1 heeft eigendom overgedragen ' . "\n" . 'van de volgende pagina aan u',
	'PageOwnershipInfo'			=> '',
	'AclRead'					=> 'Lezen:',
	'AclWrite'					=> 'Schrijf:',
	'AclComment'				=> 'Opmerkingen:',
	'AclCreate'					=> 'Aangemaakt:',
	'AclUpload'					=> 'Uploaden:',
	'AclFor'					=> 'Toegangscontrolelijsten voor %1',
	'SetOwner'					=> 'Eigenaar instellen:',
	'OwnerDontChange'			=> 'Niet wijzigen',
	'AclAccessDenied'			=> 'U bent niet de eigenaar van deze pagina.',
	'AclSyntaxError'			=> 'Toegangs controlelijst syntaxis fout',
	'AclHelp'					=> '<code>*</code> - iedereen is toegestaan<br>' .
									'<code>$</code> - alleen geregistreerde gebruikers<br>' .
									'<code>!</code> - een voorafgaand uitroepteken ontkent de desbetreffende rechter<br>' .
									'<code>[UserName]</code> - namen van toegestane gebruikers<br>' .
									'<code>[GroupName]</code> - namen van toegestane gebruikersgroep (alias)<br>' .
									'<code>(een lege lijst)</code> - alleen de eigenaar van de pagina heeft toegang',

	'AccessMode'				=> 'Zichtbaarheid',
	'AccessDenied'				=> 'geweigerd',
	'AccessPublic'				=> 'Publiek',
	'AccessRegistered'			=> 'geregistreerd',
	'AccessPrivate'				=> 'Privé',
	'AccessCustom'				=> 'Aangepast',

	// purge handler
	'PurgePage'					=> 'Purge page',
	'NotOwnerAndCantPurge'		=> 'U bent niet de eigenaar van de pagina en kunt deze niet opschonen.',
	'ReallyPurge'				=> 'LET OP: Wissen van de pagina is onomkeerbaar!',
	'SelectPurgeOptions'		=> 'Selecteer de benodigde opruimingsopties:',
	'PurgeComments'				=> 'Alle opmerkingen van de pagina verwijderen',
	'CommentsPurged'			=> 'Alle reacties zijn verwijderd.',
	'PurgeFiles'				=> 'Verwijder alle bijgevoegde bestanden',
	'FilesPurged'				=> 'Alle bijgevoegde bestanden zijn verwijderd.',
	'PurgeRevisions'			=> 'Alle herzieningen van de pagina wissen',
	'RevisionsPurged'			=> 'Revisies zijn gewist.',
	'PurgeButton'				=> 'Purge',

	// categories handler
	'Categories'				=> 'Categoriechar@@0n',
	'CategoriesAssign'			=> 'toewijzen',
	'CategoriesEdit'			=> 'bewerken',
	'Category'					=> 'categorie',
	'CategoriesFor'				=> 'Categorieën voor',
	'CategoriesTip'				=> 'Categorieën bewerken',
	'CategoriesText'			=> 'Categoriechar@@0n',
	'CategoriesUpdated'			=> 'Categorieën bijgewerkt',
	'CategoriesAlreadyExists'	=> 'Categorie %1 bestaat al.',
	'CategoriesAdded'			=> 'Categorie %1 succesvol toegevoegd.',
	'CategoriesRenamed'			=> 'Categorie hernoemd geslaagd.',
	'CategoriesUngrouped'		=> 'Categorie succesvol ontkoppeld.',
	'CategoriesGrouped'			=> 'De categorie die is ingevoerd in de nieuwe groep.',
	'NoMultilevelGrouping'		=> 'Multi-level groepering categorieën is niet mogelijk.',
	'CategoriesDeleted'			=> 'De categorie is verwijderd uit de database en alle pagina\'s.',
	'CategoriesAdd'				=> 'Voeg een nieuwe categorie toe',
	'CategoryDescription'		=> 'Beschrijving',
	'CategoriesAddGrouped'		=> 'Gegroepeerd met de categorie',
	'CategoriesAddGroupedNo'	=> 'Geen groep.',
	'CategoriesRename'			=> 'Hernoem de categorie %1 naar',
	'CategoriesRenameInfo'		=> '* NB: Wijzigen heeft invloed op alle pagina\'s die aan die categorie zijn toegewezen.',
	'CategoriesGroup'			=> 'Groepeer categorieën %1 met',
	'CategoriesGroupInfo'		=> '* Selecteer [geen groep] om de categorie uit te schakelen.',
	'CategoriesNoGroup'			=> '[geen groep]',
	'CategoriesDelete'			=> 'Weet u zeker dat u categorie %1 wilt verwijderen?',
	'CategoriesDeleteInfo'		=> '* NB: Wijzigen heeft invloed op alle pagina\'s die aan die categorie zijn toegewezen. Als het woord een subcategorie heeft, worden ze niet verwijderd, maar alleen gebundeld.',
	'CategoriesStoreInfo'		=> 'Selecteer de selectievakjes om categorieën toe te wijzen aan een pagina.',
	'CategoriesStoreButton'		=> 'Categorieën opslaan',
	'CategoriesGroupButton'		=> 'Groeperen',
	'CategoriesEditInfo'		=> 'Om de categorie lijst te bewerken, selecteer de radio knop.',
	'NoCategoriesForThisLang'	=> 'Categorieën voor deze taal zijn niet gespecificeerd.',
	'PagesCategory'				=> 'Pagina\'s categorie',
	'CategoryNotExists'			=> 'Categorie bestaat niet.',
	'CategoryEmpty'				=> 'Categorie leeg.',
	'NoCategorySelected'		=> 'Geen categorie geselecteerd.',
	'NoCategoriesAssigned'		=> 'Geen toegewezen categorieën voor deze taal.',
	'TagCloud'					=> 'Tag Cloud',
	'PagesTaggedWith'			=> '%1 pagina\'s gelabeld met %2',
	'CategoriesOfCluster'		=> 'van cluster',
	'TaggedWithTip'				=> 'toon pagina\'s gelabeld %1',

	// source handler
	'SourceText'				=> 'Bron',
	'SourceTip'					=> 'Bekijk de wiki bron',
	'SourceCopyToClipboard'		=> 'naar klembord kopiëren',
	'SourceFor'					=> 'Bron van %1 weergeven',

	// Groups action
	'GroupsSearch'				=> 'Groepen zoeken',
	'GroupsNoMatching'			=> 'Overeenkomende groepen niet gevonden. Probeer een minder strenge zoekcriteria.',
	'GroupsOpenProfile'			=> 'Profiel bekijken',
	'GroupsName'				=> 'Groeperen',
	'GroupsMembers'				=> 'leden',
	'GroupsDescription'			=> 'Beschrijving',
	'GroupsCreated'				=> 'Aangemaakt',
	'GroupsNotFound'			=> 'Groep %2 niet gevonden. Klik <a href="%1">hier</a>om naar de hoofdlijst te gaan.',
	'GroupsProfile'				=> 'Profiel',
	'GroupsList'				=> 'De volledige groepenlijst bekijken',
	'GroupSpace'				=> 'Groep ruimte',

	'MetaUpdated'				=> 'Meta-gegevens bijgewerkt',

	'PreviewButton'				=> 'Voorvertoning',
	'Preview'					=> 'Voorvertoning',
	'Chars'						=> 'tekens',
	'PageBody'					=> 'Pagina inhoud',
	'EditNote'					=> 'Samenvatting bewerken',
	'EditNoteMissing'			=> 'Bewerk samenvatting ontbreekt',
	'EditMinor'					=> 'Kleine wijziging',
	'MinorEditHide'				=> 'Kleine bewerking verbergen',
	'MinorEditShow'				=> 'Kleine bewerking tonen',
	'PostAnonymously'			=> 'Anoniem post zonder je naam op te geven',
	'NotifyMe'					=> 'Informeer mij over nieuwe opmerkingen en wijzigingen van de pagina',
	'OverwriteAlert'			=> 'OVERSCHRIJVEN ALERT: Deze pagina is gewijzigd door iemand anders terwijl u deze aan het bewerken was.<br>Kopieer uw wijzigingen en bewerk deze pagina opnieuw.',
	'TextDbOversize'			=> 'Waarschuwing: Uw tekst overschrijdt de maximale lengte met %1 tekens. Kort je tekst in op een aanvaardbaar aantal tekens. Tip: Je kunt de rest op een aparte pagina plaatsen.',
	'EditingRevisionWarning'	=> 'U bewerkt een oude herziening van deze pagina. Als u het publiceert, zullen eventuele wijzigingen die sindsdien zijn aangebracht, worden verwijderd. <br>Je kunt de huidige versie misschien wel wijzigen.',
	'WriteAccessDenied'			=> 'U heeft geen schrijftoegang tot deze pagina.',
	'EmptyPage'					=> 'Pagina tekst was leeg - niet opgeslagen!',
	'EmptyComment'				=> 'Commentaar lichaam was leeg - niet opgeslagen!',
	'CommentAccessDenied'		=> 'Sorry, je mag geen reacties plaatsen op deze pagina.',
	'CommentFlooded'			=> 'Het interval tussen de publicatie van de berichten mag niet kleiner zijn dan %1 seconden.',
	'CommentAdded'				=> 'Commentaar toegevoegd.',
	'YouAreNowTheOwner'			=> 'U bent nu de eigenaar van deze pagina.',
	'PageSaved'					=> 'Paginaversie %1 opgeslagen.',
	'CommentSaved'				=> 'Reactie opgeslagen.',

	'RevisionsFor'				=> 'Revisies voor %1',
	'DefaultDiffMode'			=> 'Standaard diff modus',
	'DiffMode'		=> [
		'0'		=> 'Volledige diff',
		'1'		=> 'Simpele diff',
		'2'		=> 'Bron',
		'3'		=> 'Kant naast elkaar',
		'4'		=> 'Inline',
		'5'		=> 'Samengevoegd',
		'6'		=> 'Gecombineerd',
		'7'		=> 'Context',
	],

	'PreviousEdit'				=> 'Vorige wijziging',
	'NextEdit'					=> 'Volgende bewerking',

	'Diff'						=> 'Verschil',
	'PreviousVersion'			=> 'Vorige revisie',
	'LatestVersion'				=> 'Laatste revisie',
	'NextVersion'				=> 'Volgende revisie',

	'ShowDifferencesButton'		=> 'Verschillen tonen',
	'CancelReturnButton'		=> 'Annuleer en ga terug naar pagina',
	'Comparison'				=> 'Verschil tussen herzieningen voor %1',
	'RevisionAsOf'				=> 'Revisie %1 vanaf',
	'SimpleDiffAdditions'		=> 'Aanvullingen:',
	'SimpleDiffDeletions'		=> 'Verwijderingen:',
	'NoDifferences'				=> 'Geen verschillen.',
	'ReEditOldRevision'			=> 'Deze oude revisie opnieuw bewerken',

	'ExternalPages'				=> 'Externe pagina\'s die verwijzen naar %1 (%2) (<a href="%3">zie lijst van domeinen</a>):',
	'ExternalPagesGlobal'		=> 'Websites die linken aan deze WackoWiki (%2) (<a href="%1">zie lijst van domeinen</a>):',
	'Last24Hours'				=> 'afgelopen 24 uur',
	'LastDays'					=> 'laatste %1 dagen',
	'DomainsSitesPages'			=> 'Domeinen/sites pagina\'s linken naar  %1 (%2) (<a href="%3">zie lijst van verschillende URL\'s</a>):',
	'DomainsSitesPagesGlobal'	=> 'Domeinen/websites die linken naar deze WackoWiki (<a href="%1">zie lijst van verschillende URL\'s</a>):',
	'ViewReferrersPage'			=> 'naar pagina',
	'ViewReferrersPerPage'		=> 'per pagina',
	'ViewReferrersByTime'		=> 'volgens tijd',
	'ViewReferrersGlobal'		=> 'globaal',
	'NoneReferrers'				=> 'geen',
	'NotOwnerCantDelete'		=> 'U bent geen eigenaar van deze pagina en kunt deze niet verwijderen',

	// remove
	'RemovePage'				=> 'Pagina verwijderen',
	'RemoveRevision'			=> 'Verwijder revisie',
	'RemoveComment'				=> 'Commentaar verwijderen',
	'RemoveCluster'				=> 'Verwijder alle pagina\'s van de cluster',
	'RemoveDontKeep'			=> 'Bewaar geen kopie van een verwijderde pagina en reacties',
	'RemoveDontKeepRevision'	=> 'Bewaar geen kopie van de verwijderde revisie',
	'RemoveDontKeepComment'		=> 'Bewaar geen kopie van de verwijderde opmerking',
	'RemoveDontKeepFile'		=> 'Bewaar geen kopie van het verwijderde bestand',
	'ReferrersRemoved'			=> 'Verwijzers verwijderd.',
	'LinksRemoved'				=> 'Links verwijderd.',
	'CategoriesRemoved'			=> 'Pagina\'s verwijderd.',
	'AclsRemoved'				=> 'Pagina acls verwijderd.',
	'BookmarksRemoved'			=> 'Bladwijzers verwijderd.',
	'WatchesRemoved'			=> 'Horloges verwijderd.',
	'CommentsRemoved'			=> 'Reacties van pagina verwijderd.',
	'FilesRemoved'				=> 'Bestanden van pagina verwijderd.',
	'PageRemoved'				=> 'Pagina verwijderd.',
	'PageCachePurged'			=> 'Cache opgeruimd.',
	'ClusterRemoved'			=> 'Alle pagina\'s van het cluster verwijderd.',
	'RevisionRemoved'			=> 'Revisie %1 verwijderd.',
	'RevisionsRemoved'			=> 'Revisies verwijderd.',
	'ActionHaveNoUndo'			=> 'Deze actie kan niet ongedaan worden gemaakt.',

	// restore
	'PageRestored'				=> 'Pagina hersteld.',
	'RevisionRestored'			=> 'Herziening hersteld.',
	'LocalFilesRestored'		=> 'Lokale bestanden hersteld.',

	'PrintVersion'				=> 'Versie afdrukken',
	'PrintText'					=> 'Afdrukken',
	'LinkedPages'				=> 'Gekoppelde pagina\'s:',
	'NoLinkedPages'				=> 'Er zijn geen gekoppelde pagina\'s',
	'ReferringPages'			=> 'Verwijzende pagina\'s:',
	'NoReferringPages'			=> 'Er zijn geen verwijzingspagina\'s',
	'Footnotes'					=> 'Voetnota\'s:',
	'Footnote'					=> 'Voetnoot',
	'MostPopularPages'			=> 'Meest populaire pagina\'s',
	'MostCommentedPages'		=> 'Pagina\'s met meeste reacties',
	'NoAccessToSourcePage'		=> 'Je hebt geen toestemming om de bronpagina van de actie te lezen.',
	'SourcePageDoesntExist'		=> 'Actie bron pagina bestaat nog niet',
	'NotLoggedInThusEdited'		=> 'U bent niet ingelogd, dus we konden de pagina\'s die u heeft bewerkt niet identificeren.',
	'DidntEditAnyPage'			=> 'U heeft nog geen pagina\'s gewijzigd.',
	'NoPagesFound'				=> 'Geen pagina\'s gevonden.',
	'MyChangesTitle1'			=> 'Dit is de lijst met pagina\'s die u heeft bewerkt, gerangschikt op het moment van uw laatste wijziging',
	'MyChangesTitle2'			=> 'Dit is de lijst van pagina\'s die u heeft bewerkt, samen met de tijd van uw laatste wijziging',
	'OrderABC'					=> 'alfabetisch',
	'OrderCreation'				=> 'op creatie',
	'OrderChange'				=> 'op verandering',
	'ListOwnedPages'			=> 'Dit is de lijst van pagina\'s die u bezit (geordend alfabetisch)',
	'ListOwnedPages2'			=> 'Dit is de lijst van pagina\'s die je bezit (op datum besteld)',
	'ListOwnedPages3'			=> 'Dit is de lijst van pagina\'s die u bezit (gesorteerd bij wijziging)',
	'NotLoggedInThusOwned'		=> 'Je bent niet ingelogd, daarom konden we je pagina\'s niet ophalen.',
	'NoOrphaned'				=> 'Geen weespagina\'s. Goed.',
	'NoRecentComments'			=> 'Geen recente reacties.',
	'LatestCommentBy'			=> 'laatste opmerking door',
	'NoRecentlyCommented'		=> 'Geen recente commentaar pagina.',
	'NoDeletedPages'			=> 'Geen verwijderde pagina\'s gevonden.',
	'NoDeletedRevisions'		=> 'Geen verwijderde revisies gevonden.',
	'NoDeletedFiles'			=> 'Geen verwijderde bestanden gevonden.',
	'CommentsDisabled'			=> 'Reacties zijn niet beschikbaar.',

	'SearchResults'				=> 'Zoekresultaten voor ',
	'NotFound'					=> 'niet gevonden',
	'NoResultsFor'				=> 'Geen resultaten voor ',
	'SearchFor'					=> 'Zoek naar:',
	'TopicSearchResults'		=> 'Zoekresultaten op topics voor ',
	'NotFoundInTopics'			=> 'niet gevonden in onderwerpen',
	'FilterLangNotAvailable'	=> 'De geselecteerde taal is niet beschikbaar!',

	'PostedBy'					=> 'gepost door',
	'ThisIsCommentOn'			=> 'Dit is een opmerking over',
	'At'						=> 'bij',
	'To'						=> 'naar',
	'By'						=> 'door',
	'From'						=> 'van',
	'For'						=> 'voor',
	'ReturnToCommented'			=> 'Terug naar commentaarpagina',
	'AbandonedComment'			=> 'De pagina waar dit commentaar toe behoort, bestaat niet meer!',

	'PagesLinkingTo'			=> 'Pagina\'s linken naar',
	'NoPageLinkingTo'			=> 'Geen enkele pagina linkt naar',
	'NoWantedPages'				=> 'Geen gezochte pagina\'s. Goed.',
	'RemoveWatch'				=> 'Bekijken van deze pagina verwijderen',
	'SetWatch'					=> 'Bekijk deze pagina',
	'WatchText'					=> 'Horloge',
	'UnwatchText'				=> 'Niet volgen',
	'UserSettingsStored'		=> 'Gebruikersinstellingen opgeslagen.',
	'LoggedOut'					=> 'Je bent nu uitgelogd.',
	'LoggedOutAuto'				=> 'Voor de veiligheid is je sessie beëindigd. Log opnieuw in.',

	// user settings
	'EmailConfirmResent'		=> 'E-mail bevestigingscode opnieuw naar uw adres verzonden.',
	'EmailConfirmNotSent'		=> 'Niet in staat om de bevestigingscode te verzenden: e-mail is niet opgegeven!',
	'Hello'						=> 'Hallo',
	'UserName'					=> 'Gebruikers naam',
	'EmailAddress'				=> 'E-mail adres',
	'RealName'					=> 'Echte naam',
	'MenuItemsShown'			=> 'Menu-items weergegeven',
	'RecordsPerPage'			=> 'Records per pagina',
	'DoShowComments'			=> 'Toon reacties standaard',
	'DoubleclickEditing'		=> 'Dubbelklik bewerken',
	'UpdateSettingsButton'		=> 'Instellingen bijwerken',

	'AccountDisabled'			=> 'Uw account kan worden uitgeschakeld of geblokkeerd.',
	'WrongPassword'				=> 'Verkeerd wachtwoord!',
	'ConfirmPassword'			=> 'Bevestig wachtwoord',
	'Email'						=> 'E-mail adres',
	'MustBeWikiName'			=> 'Gebruikersnaam moet <a href="https://wackowiki.org/doc/Doc/English/WikiName" target="_blank">WikiName</a> geformatteerd zijn!',
	'SpecifyEmail'				=> 'U moet een e-mailadres opgeven.',
	'NotAEmail'					=> 'Dat lijkt niet op een geldig e-mailadres.',
	'EmailTaken'				=> 'Het ingevoerde e-mailadres is al in gebruik.',
	'EmailDomainNotAllowed'		=> 'Het ingevoerde e-mailadres %1 staat niet in de toegestane domeinenlijst.',
	'PasswordsDidntMatch'		=> 'Wachtwoorden komen niet overeen.',
	'SpacesArentAllowed'		=> 'Spaties zijn niet toegestaan in wachtwoorden.',
	'ListMyPages'				=> 'Laat je pagina\'s zien',
	'ListMyChanges'				=> 'Vermeld je wijzigingen',
	'ListMyWatches'				=> 'Lijst van bekeken pagina\'s',
	'ListMyChangesWatches'		=> 'Wijzigingen van bekeken pagina\'s',
	'SeeListOfPages'			=> 'Zie een lijst van pagina\'s die u bezit (MyPages) en pagina\'s die u hebt bewerkt (MyChanges).',
	'AddBookmark'				=> 'Huidige pagina aan bladwijzers toevoegen',
	'RemoveBookmark'			=> 'Verwijder uit bladwijzers',

	'YourLanguage'				=> 'Taal selecteren',
	'ShowSpaces'				=> 'Toon spaties in WikiNames',
	'WrongPage4Redirect'		=> 'Kan niet omleiden vanwege de verkeerde omleiding parameter',
	'RedirectsToItself'			=> 'De pagina verwijst naar zichzelf.',
	'ReallyDeletePage'			=> 'Wilt u deze pagina echt VERWIJDEREN?<br>Deze actie kan niet ongedaan worden gemaakt!<br><br>WAARSCHUWING: Het verwijderen van deze pagina zal alle pagina, opmerkingen, bijlagen, ACL\'s en verwijzingen verwijderen.',
	'CommentForWatchedPage'		=> 'Nieuwe opmerking voor pagina ',
	'SomeoneCommented'			=> ' heeft gereageerd op deze pagina die u bekijkt: ',
	'AlertReferringPages'		=> 'Deze pagina wordt verwezen naar deze pagina\'s',

	'AccountDelete'				=> 'Verwijder account',
	'AccountDeleteConfirm'		=> 'Weet je zeker dat je dit account wilt verwijderen?',
	'AccountDeleted'			=> 'Account succesvol verwijderd',
	'AccountDeleteHeader'		=> 'Account verwijderen %1',
	'AccountDeleteInfo'			=> 'Van de gegevens die u heeft gemaakt (bijvoorbeeld e-mail, voorkeuren, bijlagen, wiki-inzendingen) zal zoveel mogelijk worden verwijderd. Merk echter op dat gegevens zoals bijlagen en wiki-items niet kunnen worden verwijderd zonder het werk van de andere gebruikers te belemmeren. Dergelijke gegevens worden dus opnieuw toegewezen aan een account genaamd %1. Aangezien de gegevens van elk verwijderd account opnieuw zijn toegewezen aan dit account, zal het niet mogelijk zijn om de gegevens die u hebt aangemaakt te onderscheiden van de gegevens van een ander verwijderd account.',
	'AccountDeleteWarning'		=> 'Het verwijderen van de gebruikersaccount is een onomkeerbare actie.',
	'AccountDeleteHint'			=> 'Uw account zal worden verwijderd uit het systeem. Daarom is het niet langer mogelijk om in te loggen met uw huidige inloggegevens. Als u ervoor kiest om opnieuw gebruiker van deze applicatie te worden, kunt u dit doen met behulp van de middelen die deze applicatie verleent.',
	'AccountDeleteVerify'		=> 'Voer uw login %1 in om de verwijdering te controleren. Zodra deze is ingegeven, zal u worden gevraagd uw wachtwoord te bevestigen.',

	'MarkRead'					=> 'Alles als gelezen markeren',
	'CurrentTime'				=> 'Het is momenteel',
	'Created'					=> 'gecre�erd',
	'Modified'					=> 'gewijzigd',

	'EditIcon'					=> 'bewerken',
	'TreeClusterTitle'			=> 'Boom van cluster %1',
	'TreeSiteTitle'				=> 'Site structuur',
	'TreeEmpty'					=> '%1 heeft geen subpagina\'s',
	'TreeEmptyLevels'			=> '%1 heeft geen subpagina\'s voor de gegeven niveaus van diepte. Verhoog de waarde voor diepte.',
	'TreeTooBig'				=> 'te veel subpagina\'s',

	// clone handler
	'ClonePage'					=> 'Pagina dupliceren',
	'CloneText'					=> 'Dupliceren',
	'CloneName'					=> 'Voer een nieuwe naam in voor een kloon van deze pagina',
	'CloneButton'				=> 'Dupliceren',
	'PageCloned'				=> 'Pagina %1 gekloond.',
	'ClonedFrom'				=> 'Gloond van %1.',
	'MassClone'					=> 'Kloon hele cluster',
	'MassCloning'				=> 'Klonen cluster.',
	'CloneCannotRead'			=> 'Unreadable page %1.',
	'CloneCannotCreate'			=> 'Onbewerkbare pagina %1.',

	'SortComment'				=> 'Sorteer opmerkingen op',
	'SortCommentAsc'			=> 'Meest recente onderaan',
	'SortCommentDesc'			=> 'Meest recente bovenaan',

	'RenamePage'				=> 'Pagina hernoemen',
	'RenameText'				=> 'Hernoem',
	'RenameTip'					=> 'Pagina hernoemen',
	'NewName'					=> 'Voer een nieuwe naam in voor deze pagina',
	'AlreadyExists'				=> 'Pagina %1 bestaat al.',
	'AlreadyNamed'				=> 'Deze pagina is al %1 genoemd.',
	'PageRenamed'				=> 'Pagina hernoemd.',
	'NewNameOfPage'				=> 'Nieuwe naam van deze pagina: ',
	'NotOwnerCantRename'		=> 'U bent geen eigenaar van deze pagina en kunt deze daarom niet hernoemen',
	'NeedRedirect'				=> 'Redirect maken naar de nieuwe pagina op de oude pagina',
	'RedirectCreated'			=> 'In de pagina %1 aangemaakte doorverwijzing naar de nieuwe',

	'UserSettings'				=> 'Gebruikers instellingen',
	'UserSettingsGeneral'		=> 'Algemeen',
	'UserSettingsNotifications'	=> 'Notificaties',

	'NotifyMinorEdit'			=> 'Melden ook voor kleine bewerken',
	'NotifyPageEdit'			=> 'Bewerken',
	'NotifyComment'				=> 'Opmerking',
	'NotifyOff'					=> 'UIT',
	'NotifyAlways'				=> 'altijd',
	'NotifyPending'				=> 'Lopende',
	'NotifyDigest'				=> 'Samenvatting',
	'NotifyPendingPageTip'		=> 'Er wordt slechts één melding verzonden voor de eerste pagina die u bekijkt.',
	'NotifyPendingCommentTip'	=> 'Er wordt slechts één melding verzonden voor de eerste reactie op een pagina die u bekijkt.',
	'NotifyPendingTip'			=> 'Kennisgeving wordt automatisch opnieuw ingeschakeld wanneer u de huidige versie van de pagina bezoekt.',

	'FurtherPending'			=> 'Er zullen geen andere meldingen zijn in geval van verdere wijzigingen, tenzij je deze pagina bezoekt.',

	'UserSettingsEmailMe'		=> 'Stuur me een e-mailnotificatie wan...',

	'UserSettingsExtended'		=> 'Uitgebreid',
	'UserSettingsOther'			=> 'Andere instellingen',
	'UserSpace'					=> 'Gebruikers ruimte',
	'ChooseTheme'				=> 'Kies thema',

	'CreatePage'				=> 'Deze pagina maken',
	'CreateNewPage'				=> 'Maak een nieuwe pagina',
	'CreateNewPageText'			=> 'Aanmaken',
	'CreateNewPageTip'			=> 'Maak een nieuwe pagina',

	'CreateRandomPage'			=> 'Maak een willekeurige pagina:',
	'CreateSubPage'				=> 'Maak een subpagina in het cluster:',
	'CreatePageParentCluster'	=> 'Maak een pagina in het bovenliggende cluster:',
	'CreatePageDenied'			=> 'U heeft niet de benodigde toegang.',
	'CreatePageDeniedAddress'	=> 'U heeft het recht niet om de pagina aan te maken op dit adres.',
	'PageAlreadyExists'			=> 'Volgens het opgegeven adres bestaat de pagina %1 al.',
	'PageAlreadyExistsEdit'		=> 'Wilt u %1 het?',
	'PageAlreadyExistsEdit2'	=> 'bewerken',
	'PageAlreadyExistsEditDenied'	=> 'U kunt het niet bewerken.',

	'SimilarPagesExists'		=> 'Vergelijkbare pagina\'s met %1 bestaan al:',
	'SimilarPagesHint'			=> 'Er zijn vergelijkbare pagina\'s naar %1:',

	'PageReservedWord'			=> 'U kunt %1 niet gebruiken als deel van het adres als voorbehouden woord.',
	'UserReservedWord'			=> 'Gebruikersnamen kunnen %1 niet als gereserveerd woord bevatten.',

	'DontRedirect'				=> 'Automatisch omleiden door actie doorsturen niet toestaan.',
	'SendWatchEmail'			=> 'Stuur notificatie als iemand (behalve jij) elke pagina die je bekijkt wijzigt',
	'AllowIntercom'				=> 'Sta persoonlijke berichten van gebruikers van het systeem toe',
	'AllowMassemail'			=> 'Beheerders kunnen mij informatie e-mailen',
	'HideLastSession'			=> 'Laatste sessie verbergen',
	'ValidateIP'				=> 'Tying sessie naar IP',
	'AnonymousPub'				=> 'Bij voorkeur anoniem gepubliceerd (om de naam te verbergen)',
	'PageMoved'					=> 'Deze pagina verplaatst. U vindt deze op',
	'RedirectedFrom'			=> 'Omgeleid van %1',
	'RedirectedTo'				=> 'Doorverwezen naar',
	'CurrentPassword'			=> 'Huidig wachtwoord',
	'NewPassword'				=> 'Nieuw wachtwoord',
	'YouWantChangePassword'		=> 'Wachtwoord wijzigen',
	'ChangePasswordButton'		=> 'Wachtwoord wijzigen',
	'PasswordChanged'			=> 'Wachtwoord gewijzigd',
	'EmailWelcome'				=> 'U heeft zich aangemeld bij ',
	'EmailRegistered'			=> 'Je bent succesvol geregistreerd bij %1.' . "\n" . 'Uw gebruikersnaam: %2' . "\n\n",
	'EmailVerify'				=> 'Als u meldingen wilt ontvangen, moet u uw e-mailadres verifiëren. Klik op of kopieer de volgende link naar een webbrowser: ' . "\n" . '%1',
	'EmailRegisteredLogin'		=> 'Ga terug naar de Wiki en log in met je nieuwe gebruikersnaam en wachtwoord.',
	'EmailRegisteredIgnore'		=> 'Als je deze registratie niet hebt aangevraagd, negeer dan dit bericht en er gebeurt niets.',
	'EmailDoNotReply'			=> 'Antwoord niet op dit bericht.',
	'EmailReverify'				=> 'Iemand (misschien jij) heeft uw e-mail als notificatieadres bij %1 ingediend.' . "\n" . 'Uw gebruikersnaam: %2'."\n\n" . 'Als je meldingen wilt ontvangen, moet je je e-mail goedkeuren. Klik op de link om dit te doen.' . "\n" . '%3' . "\n\n",
	'EmailConfirm'				=> 'Verifieer je e-mailadres',
	'EmailConfirmed'			=> 'E-mail succesvol bevestigd.',
	'EmailNotConfirmed'			=> 'E-mail kan niet worden bevestigd. Dit is mogelijk te wijten aan een onjuiste bevestigingscode of het e-mailadres is mogelijk al bevestigd. U kunt controleren of het e-mailadres al is bevestigd door in te loggen en de status ervan op uw %1 pagina te bekijken.',
	'EmailNotVerified'			=> 'E-mail niet geverifieerd!',
	'EmailNotVerifiedDesc'		=> 'U ontvangt geen meldingen van wijzigingen of reacties van bekeken pagina\'s, ' .
									'of berichten van andere gebruikers. Ook kan je <strong>geen vergeten wachtwoord</strong>herstellen, ' .
									'totdat uw e-mailadres is bevestigd door de link in de naar u verzonden e-mail te volgen. ' .
									'Als u binnen dagen na de registratie geen e-mail ontvangt, vraag het opnieuw door te klikken op ',

	'ForgotPasswordHint'		=> 'Voer uw inlog- en e-mailadres in,' . "\n" . 'dan wordt er een e-mail met instructies naar je verzonden.',
	'ForgotPassword'			=> 'Wachtwoord vergeten?',
	'UserNotFound'				=> 'Gebruiker met deze naam of e-mailadres is niet gevonden.',
	'NotConfirmedEmail'			=> 'Uw e-mailadres is niet bevestigd.<br>Mail kan niet worden verzonden naar een niet-bevestigd adres.',
	'EmailForgotSubject'		=> 'Wachtwoord verlenging voor ',
	'EmailForgotMessage'		=> 'Iemand (misschien jij) bent je wachtwoord voor %1 vergeten.' . "\n" . 'Je inlog: %2'."\n\n" . 'Klik op de link of kopieer de link naar de adresregel van de browser om uw wachtwoord te wijzigen.' . "\n" . '%3'."\n\n",
	'CodeWasSent'				=> 'Wachtwoord herstel instructie is per e-mail naar u verzonden.',
	'WrongCode'					=> 'Verkeerde code',
	'ChangePasswordForUser'		=> '%1\'s wachtwoord wijziging',

	'Watchers'					=> 'Lijst van volgers voor %1',
	'WatchersFor'				=> 'Volgers voor',
	'NoWatchers'				=> 'Er zijn geen volgers voor %1',
	'NotOwnerToViewWatchers'	=> 'U bent niet de eigenaar van deze pagina en u kunt geen lijst zien van de watchers ervoor.',

	// thumbnail
	'TbnError'					=> 'Fout bij maken miniatuur: %1',
	'TbnImageAreaTooBig'		=> 'Bestand met afmetingen groter dan %1',
	'TbnImageMissing'			=> 'Bestand lijkt te ontbreken: %1',

	// admin_recovery action
	'GenerateRecoveryHash'		=> 'Genereer de wachtwoordhash voor uw <code>recovery_password</code>',

	// import action
	'ImportTo'					=> 'Importeer in cluster:',
	'ImportWhat'				=> 'XML-bestand om te importeren:',
	'ImportButton'				=> 'Importeren',
	'ImportSuccess'				=> 'Succesvol geïmporteerd.',
	'ImportFailed'				=> 'IMPORT is mislukt.',
	'ImportHint'				=> 'Vul een cluster in waar u naar wilt importeren, geen relatief adres.',
	'ImportAttention'			=> 'Let op: dezelfde pagina\'s in het cluster overschrijven.',
	'ImportNote'				=> 'Geïmporteerde pagina',

	// mywatches action
	'WatchedPages'				=> 'Lijst van alle pagina\'s die u volgt voor wijzigingen ',
	'UnwatchedPages'			=> 'Lijst van alle pagina\'s die u niet bekijkt',
	'NoWatchedPages'			=> 'Je hebt geen bekeken pagina\'s.',
	'NoUnwatchedPages'			=> 'Bekijk voor wijzigingen in alle pagina\'s.',
	'ViewWatchedPages'			=> 'Bekeken pagina\'s weergeven',
	'ViewUnwatchedPages'		=> 'Toon onbekeken pagina',
	'NotLoggedInWatches'		=> 'U bent niet ingelogd, daarom konden we uw lijst met horloges niet identificeren.',

	// mychangeswatches action
	'MyChangesWatches'			=> 'Lijst van alle pagina\'s die u heeft bekeken die door anderen zijn gewijzigd sinds uw laatste bewerking',
	'ResetChangesWatches'		=> 'reset de lijst met wijzigingen',
	'NoChangesWatches'			=> 'Onder uw bekeken pagina\'s zijn geen wijzigingen...',

	// whatsnew action
	'NewCommentAdded'			=> 'Nieuwe reactie toegevoegd',
	'NewFileAdded'				=> 'Nieuw bestand toegevoegd',
	'NewPageCreated'			=> 'Nieuwe pagina aangemaakt',
	'NewRevisionAdded'			=> 'Gewijzigde pagina',
	'Cluster'					=> 'clusteren',
	'PageDeleted'				=> 'Pagina verwijderd',
	'CommentDeleted'			=> 'Reactie verwijderd',
	'FileDeleted'				=> 'Bestand verwijderd',

	// users action
	'UsersSearch'				=> 'Gebruikers zoeken',
	'UsersOpenProfile'			=> 'Profiel bekijken',
	'UsersNoMatching'			=> 'Overeenkomende gebruikers niet gevonden. Probeer een minder strenge zoekcriteria.',
	'UsersName'					=> 'naam',
	'UsersPages'				=> 'Pagina\'s',
	'UsersChanges'				=> 'Veranderingen',
	'UsersSubscription'			=> 'Abonnement',
	'UsersWatches'				=> 'Horloges',
	'UsersComments'				=> 'Opmerkingen',
	'UsersUploads'				=> 'Uploads',
	'UploadQuota'				=> 'Gebruikte ruimte',
	'UploadQuotaTip'			=> 'Ruimte Quota uploaden',
	'UsersLogins'				=> 'Aanmeldingen',
	'UsersRevisions'			=> 'Herzieningen',
	'UsersSignup'				=> 'Registratie',
	'UsersLastSession'			=> 'Laatste sessie',
	'UsersNotFound'				=> 'Gebruiker %2 niet gevonden. Klik <a href="%1">hier</a>om naar de hoofdlijst te gaan.',
	'UsersProfile'				=> 'Profiel',
	'UsersContact'				=> 'Contactpersoon',
	'UsersList'					=> 'Bekijk de volledige lijst van gebruikers',
	'UsersNA'					=> '[niet gezet]',
	'UsersNA2'					=> '[No]',
	'UsersSignupDate'			=> 'Inschrijving datum',
	'UsersGroupMembership'		=> 'Lidmaatschap groep',
	'UsersPersonalInfo'			=> 'Persoonlijke informatie',
	'UsersOwnedPages'			=> 'Bezit pagina\'s:',
	'UsersCommentsPosted'		=> 'Opmerkingen geplaatst:',
	'UsersFilesUploaded'		=> 'Bestanden geüpload:',
	'UsersRevisionsMade'		=> 'Gemaakte herzieningen:',
	'UsersDocsSortName'			=> '[Sorteren op naam]',
	'UsersDocsSortCreation'		=> '[Sorteren op aanmaakdatum]',
	'UsersChangesSortAsc'		=> '[Sorteren oplopen]',
	'UsersChangesSortDesc'		=> '[Sorteer aflopening]',
	'UsersSessionNA'			=> '[niet opgenomen ]',
	'UsersSessionHidden'		=> '[hidden]',
	'IntercomSubject'			=> 'Betreft:',
	'IntercomMessage'			=> 'Bericht:',
	'IntercomCopy'				=> 'Stuur me een kopie',
	'IntercomSubjectN'			=> '[Start een nieuw onderwerp]',
	'IntercomDisabled'			=> 'Sorry, u kunt geen persoonlijke berichten ontvangen of niet meer ontvangen.',
	'IntercomHint'				=> 'Log eerst in en volg de link opnieuw, als u het persoonlijke bericht dat u hebt ontvangen wilt beantwoorden.',
	'IntercomDesc'				=> 'Opmerking: Persoonlijke berichten verzenden die worden uitgevoerd naar de e-mailontvanger zonder uw adres te onthullen. De ontvanger zal in staat zijn om op jou te reageren, met behulp van een vergelijkbaar formulier op je profielpagina. ',
	'PMOversized'				=> 'De lengte van het bericht overschrijdt de maximaal toegestane grootte met %1. Verkort het bericht en verzend het opnieuw.',
	'PMFlooded'					=> 'Het interval tussen verzenden van persoonlijke berichten mag niet minder zijn dan %1 seconden.',
	'PMSent'					=> 'Persoonlijk bericht werd met succes naar de gebruiker verzonden.',
	'PMBody'					=> 'Dit bericht is naar u verzonden door gebruiker %1.',
	'PMBodyCopy'				=> 'U heeft het volgende bericht verzonden naar gebruiker %1.',
	'PMReply'					=> 'Om deze e-mail te beantwoorden, klik op de volgende link (gebruik niet de antwoord knop / Antwoord in de mailer):',
	'PMNotLoggedIn'				=> 'U bent niet geregistreerd in het systeem en kunt geen persoonlijke berichten verzenden aan gebruikers.',

	// admin_replace action
	'ReplaceText'				=> 'Tekst vervangen',
	'TextOriginal'				=> 'Originele tekst:',
	'TextReplacement'			=> 'Vervangende tekst:',
	'ReplaceTextRegex'			=> 'Gebruik reguliere expressies',
	'Namespace'					=> 'Namespace',
	'ReplaceTextCluster'		=> 'Alleen binnen dit cluster zoeken en vervangen:',
	'ReplaceTextEditPages'		=> 'Vervang tekst in pagina-inhoud',
	'ReplaceTextEditComments'	=> 'Vervang tekst in opmerkingen',
	'ReplaceTextEditTitles'		=> 'Vervang tekst in paginatitels',
	'ReplaceTextGiveTarget'		=> 'Je moet een te vervangen tekenreeks opgeven.',
	'ReplaceTextNoNamespace'	=> 'U moet ten minste één namespace selecteren.',
	'ReplaceTextNoDifference'	=> 'Er is geen verschil tussen de vervangende tekst en de doeltekst.',
	'ReplaceTextNoOption'		=> 'U moet ten minste één van de vervangende opties selecteren.',
	'ReplaceTextPagesEdit'		=> 'Vervang %1 met %2 in de tekst van de volgende %3 pagina\'s:',
	'ReplaceTextTitlesEdit'		=> 'Vervang %1 met %2 in de titels van de volgende %3 pagina\'s:',
	'ReplaceTextReplace'		=> 'Vervangen',
	'ReplaceTextSuccess'		=> '%1 is vervangen door %2 in %3 pagina\'s.',
	'ReplaceTextNoMatch'		=> 'Er zijn geen pagina\'s gevonden met de tekenreeks %1.',
	'ReplaceTextNoTitleMatch'	=> 'Er zijn geen pagina\'s gevonden met de titel %1.',
	'ReplaceTextEditFailed'		=> 'Tekst vervangen is mislukt',
	'ReplaceTextTitleTooBig'	=> 'De oorspronkelijke of vervangende tekst is te groot voor de titel.',
	'ReplaceTextReturn'			=> 'Terug naar formulier',
	'ReplaceTextWarning'		=> 'Waarschuwing: Er zijn %1 pagina\'s die al de vervangende tekenreeks bevatten, %2. Als je deze vervanging maakt, kun je je vervangingen niet van deze strings scheiden.',
	'ReplaceTextBlankWarning'	=> 'Waarschuwing: Omdat de vervangende tekenreeks leeg is, zal deze bewerking niet omkeerbaar zijn.',
	'ReplaceTextEditSummary'	=> 'Tekstvervanging: %1 → %2',
	'InvertSelection'			=> 'Selectie omkeren',

	// Properties
	'PropertiesFor'				=> 'Pagina eigenschappen voor %1',
	'MetaTag'					=> 'Tagnaam',
	'MetaTitle'					=> 'Aanspreektitel',
	'MetaKeywords'				=> 'Sleutelwoorden',
	'MetaDescription'			=> 'Beschrijving',
	'On'						=> 'op',
	'Off'						=> 'UIT',
	'Registered'				=> 'Geregistreerd',
	'MetaComments'				=> 'Toon reacties',
	'MetaFiles'					=> 'Toon bestanden paneel',
	'MetaToc'					=> 'Toon inhoudsopgave',
	'MetaIndex'					=> 'Toon fragmentsectie paneel',
	'MetaIndexMode'				=> 'Toon Niveau Modus',
	'MetaIndexFull'				=> 'Boom',
	'MetaIndexUpper'			=> 'Bovenste',
	'MetaIndexLower'			=> 'Lager',
	'MetaHtml'					=> 'HTML-ondersteuning voor pagina',
	'MetaSafeHtml'				=> 'Filteren van onveilige HTML',
	'MetaTypografica'			=> 'Typografische proeflezer',
	'MetaNoIndex'				=> 'Zoekmachines blokkeren',
	'SettingsID'				=> 'Pagina ID',
	'SettingsSize'				=> 'Grootte',
	'SettingsSizeTip'			=> 'bron / gecompileerd',
	'SettingsCreated'			=> 'Aangemaakt',
	'SettingsCurrent'			=> 'Gewijzigd',
	'SettingsTotalRevs'			=> 'Herzieningen',
	'SettingsTotalComs'			=> 'Opmerkingen',
	'SettingsWatchers'			=> 'Volgers',
	'SettingsHits'				=> 'Weergaven',
	'SettingsText'				=> 'Instellingen',
	'SettingsEdit'				=> 'Bewerken',
	'SettingsRevisions'			=> 'Herzieningen',
	'SettingsClone'				=> 'Dupliceren',
	'SettingsRename'			=> 'Hernoem',
	'MassRename'				=> 'voor de gehele cluster',
	'SettingsRemove'			=> 'Verwijderen',
	'SettingsPurge'				=> 'Purge',
	'SettingsModerate'			=> 'Matig',
	'SettingsPermissions'		=> 'Machtigingen',
	'AclForEntireCluster'		=> 'voor de gehele cluster',
	'SettingsAttachments'		=> 'Bijlagen',
	'SettingsUpload'			=> 'Uploaden',
	'SettingsCategories'		=> 'Categoriechar@@0n',
	'SettingsLanguages'			=> 'Leren',
	'SettingsReferrers'			=> 'Verwijzers',
	'SettingsWatch'				=> 'Horloge',
	'SettingsLatex'				=> 'LaTeX versie',
	'SettingsXML'				=> 'Exporteren naar XML',
	'NeedToChangeLang'			=> 'Niet-ondersteunde paginetaal %1 moet worden gewijzigd.',
	'SetLang'					=> 'Taal van deze pagina',
	'SetMenuLabel'				=> 'Menu label',
	'SetShowMenuLabel'			=> 'Weergeven in navigatie',

	// upload
	'UploadFiles'				=> 'Bestanden uploaden',
	'UploadFor'					=> 'Bestand upload:',
	'UploadButton'				=> 'Uploaden',
	'UploadGlobalText'			=> 'voor publieke toegang',
	'UploadGlobal'				=> 'globaal',
	'UploadLocalText'			=> 'alleen voor gebruikers die de huidige pagina mogen bekijken',
	'UploadAsName'				=> 'Naam:',
	'UploadOverwrite'			=> 'Bestaande bestanden overschrijven',
	'FileDesc'					=> 'Omschrijving:',
	'UploadForbidden'			=> 'U heeft geen toestemming om bestanden hier te uploaden.',
	'UploadOverwriteDenied'		=> 'Alleen de bestandseigenaar of beheerder kan het %1 bestand overschrijven.',
	'UploadNoFile'				=> 'Er was geen bestand in de vorm, om een of andere reden.',
	'UploadMaxSizeReached'		=> 'Bestandsgrootte is groter dan de toegestane limiet!',
	'UploadDirNotWritable'		=> 'Bestandsmap is niet beschrijfbaar!',
	'UploadNotAPicture'			=> 'Beeld uploads zijn alleen toegestaan. Wat probeert u te uploaden?',
	'UploadEmptyExtension'		=> 'De bestandsnaam en de extensie kunnen niet leeg zijn.',
	'FilenameTooLong'			=> 'Bestandsnamen mogen niet langer zijn dan 240 bytes.',
	'BannedFiletype'			=> '%1 is geen toegestaan bestandstype.',
	'PermittedFiletype'			=> 'Toegestane bestandstypes:',
	'UploadMimeMismatch'		=> 'Bestandsextensie %1 komt niet overeen met het gedetecteerde MIME-type van het bestand (%2).',
	'UploadBadMime'				=> 'Bestanden van het MIME-type %1 zijn niet toegestaan om te worden geüpload.',
	'FileIsDuplicate'			=> 'De upload is een exact duplicaat van de huidige versie.',
	'FileHasDuplicate'			=> 'Dit bestand is een kopie van de volgende bestanden:',

	'UploadMaxFileQuota'		=> 'U hebt uw upload limiet bereikt. Dit bestand kan niet worden geüpload',
	'UploadDone'				=> 'Bestand uploaden geslaagd',
	'UploadFileForbidden'		=> 'Toegang tot bestand verboden',
	'UploadTitle'				=> 'Bestanden toegankelijk vanaf deze pagina',
	'UploadTitleGlobal'			=> 'Bestanden toegankelijk vanaf waar dan ook',

	'UploadFile'				=> 'Uploaden',
	'UploadMax'					=> 'Niet meer dan ',
	'UploadUsedStorage'			=> 'Opslag in gebruik ',

	// attachments
	'Attachments'				=> 'Bijlagen',
	'Attachment'				=> 'Bijlage',
	'AttachmentsToPage'			=> 'naar pagina',
	'AttachmentsToCluster'		=> 'clusteren',
	'AttachmentsByTime'			=> 'volgens tijd',
	'AttachmentsGlobal'			=> 'globaal',
	'AttachmentsAll'			=> 'alle',
	'AttachmentsLinked'			=> 'gebruikt',

	'FileViewProperties'		=> 'Bekijken',
	'FileViewPropertiesTip'		=> 'Bekijk de metadata van dit bestand',
	'FileEditProperties'		=> 'Bewerken',
	'FileEditPropertiesTip'		=> 'Bewerk de metadata van dit bestand',
	'FileEditedMeta'			=> 'Bijgewerkte metadata van dit bestand',
	'FileEditDenied'			=> 'U bent niet bevoegd om dit bestand te bewerken',
	'FileLabel'					=> 'Omschrijving',
	'FileLabelTip'				=> 'Label dit bestand',
	'FileRemove'				=> 'Verwijderen',
	'FileRemovedFromDB'			=> 'Bestand verwijderd uit de database',
	'FileRemovedFromFS'			=> 'Bestand gewist van fysieke hosting',
	'FileRemovedFromFSError'	=> 'Het lijkt onmogelijk om bestand te verwijderen!',
	'FileRemoveConfirm'			=> 'Weet u zeker dat u dit bestand wilt verwijderen?',
	'FileRemoveDenied'			=> 'U heeft geen toestemming om dit bestand te verwijderen',
	'FileNotFound'				=> 'Bestand niet gevonden.',

	'FileSearch'				=> 'Bestand zoeken',
	'UploadBy'					=> 'Geüpload door:',
	'FileAdded'					=> 'Toegevoegd:',
	'FileModified'				=> 'Gewijzigd:',
	'FileSize'					=> 'Grootte:',
	'FileDimension'				=> 'Dimensie:',
	'MimeType'					=> 'Mimetype:',
	'FileName'					=> 'Naam:',
	'FileCaption'				=> 'Onderschrift:',
	'FileAuthor'				=> 'Auteur:',
	'FileSource'				=> 'Bron:',
	'FileSourceUrl'				=> 'URL:',
	'FileAttachedTo'			=> 'Bijgevoegd aan:',
	'FileSyntax'				=> 'Syntaxis:',
	'FileAbsolutePath'			=> 'absoluut pad',
	'FileRelativePath'			=> 'relatief pad',
	'FileUsage'					=> 'Bestand gebruik:',
	'FileUsageText'				=> 'De volgende pagina\'s link naar dit bestand:',
	'NoFileUsage'				=> 'Er zijn geen pagina\'s gekoppeld aan dit bestand.',

	'FileSortExt'				=> 'extensie',
	'FileSortName'				=> 'Naam',
	'FileSortSize'				=> 'grootte',
	'FileSortTime'				=> 'gecre�erd',

	'SortBy'					=> 'Sorteren op',
	'Ascending'					=> 'oplopend',
	'Decending'					=> 'aflopend',

	'Files0'					=> 'Bestanden toevoegen',
	'Files1'					=> 'Bestanden weergeven (1 bestand)',
	'FilesN'					=> 'Toon bestanden (%1 bestanden)',
	'Files'						=> 'Bestanden',
	'File'						=> 'Bestand',
	'ShowFiles'					=> 'Bestanden weergeven / formulier',
	'HideFiles'					=> 'Bestanden verbergen / formulier',
	'DoShowFiles'				=> 'Bestanden lijsten standaard weergeven',
	'NoAttachments'				=> 'Er zijn geen bijgevoegde bestanden om weer te geven.',

	'RegistrationLang'			=> 'Jouw taal',
	'InvalidWikiName'			=> 'De gekozen naam is ongeldig',
	'InvalidUserName'			=> 'Gekozen gebruikersnaam is ongeldig',
	'Bookmarks'					=> 'Bladwijzers',
	'ReallyDeleteComment'		=> 'Wilt u deze reactie echt VERWIJDEREN?<br>Deze actie kan niet ongedaan worden gemaakt!',
	'ReallyDeleteRevision'		=> 'Wil je deze wijziging echt verwijderen?<br>Deze actie kan niet ongedaan worden gemaakt!',

	'RegistrationClosed'		=> 'Registratie is hier niet beschikbaar. Neem contact op met de beheerder van de site.',
	'AclAreYouSure'				=> 'U gaat ACL\'s van deze pagina en alle bijbehorende subpagina\'s wijzigen. Doorgaan?',

	'BookmarkDeleteSelected'	=> 'Verwijder geselecteerde items',
	'BookmarkMark'				=> 'Markeren',
	'BookmarkNumber'			=> 'Nee.',
	'BookmarkNone'				=> 'U heeft geen bladwijzers.',
	'BookmarkTitle'				=> 'Titel bladwijzer',
	'BookmarkPage'				=> 'Pagina',
	'BookmarkSaveChanges'		=> 'Wijzigingen opslaan',
	'BookmarksAddPage'			=> 'Stel een bladwijzer in voor de volgende pagina',
	'BookmarkAlreadyExists'		=> 'De bladwijzer bestaat al.',

	'PoweredBy'					=> 'Mogelijk gemaakt door',

	'MassRenaming'				=> 'Hernoem hele cluster',
	'MassNewName'				=> 'Voer een nieuwe naam in voor deze cluster',
	'MassNeedRedirect'			=> 'Omleiden naar nieuwe pagina\'s op oude pagina\'s maken',

	// pagination
	'ToOverview'				=> 'Terug naar overzicht',
	'Overview'					=> 'Overzicht.',
	'ToThePage'					=> 'Naar pagina:',
	'Next'						=> 'Volgende',
	'Prev'						=> 'Vorige',
	'NextAcr'					=> 'Volgende',
	'PrevAcr'					=> 'Vorige',
	'Back'						=> 'Achterzijde',

	// filter
	'Filter'					=> 'Filteren',
	'OptionalFilters'			=> 'Optionele filters:',
	'Any'						=> 'Elk',

	// My Groups
	'UserGroups'				=> 'Groepen gebruikers',
	'MyGroups'					=> 'Groep associaties',
	'Group'						=> 'Groep',
	'Groups'					=> 'Groepen',

	// license action
	'DistributedUnder'			=> 'Materiaal wordt onder verdeeld',
	'AuthorsDisplayHint'		=> 'De lijst met auteurs wordt getoond bij het opslaan van de pagina.',
	'AnonymousUsers'			=> 'Anonieme gebruikers',
	'License'					=> 'Licentie',
	'LicenseArray'				=> [
		'1'		=> 'Naamsvermelding-GeenAfgeleiden',
		'2'		=> 'Naamsvermelding-NietCommercieel-GelijkDelen',
		'3'		=> 'Naamsvermelding-NietCommercieel-GeenAfgeleiden',
		'4'		=> 'Naamsvermelding-GelijkDelen',
		'5'		=> 'Naamsvermelding-NietCommercieel',
		'6'		=> 'Naamsvermelding',
		'7'		=> 'CC0 1.0 Universal',
		'8'		=> 'GNU Free Documentatie Licentie',
		'9'		=> 'Publiek domein / gratis gebruik',
		'10'	=> 'Alle rechten voorbehouden',
	],
	'LicenseMeta'				=> [
		'1'		=> 'Openbaar domein',
		'2'		=> 'Sommige rechten voorbehouden',
		'3'		=> 'Alle rechten voorbehouden',
	],

	// Cache
	'ClearCache'				=> 'Cache legen',
	'CacheCleared'				=> 'Cache gewist.',
	'ConfigCache'				=> 'Configuratie-cache',
	'FeedCache'					=> 'Feed cache',
	'PageCache'					=> 'Pagina cache',
	'SQLCache'					=> 'SQL cache',
	'TemplateCache'				=> 'Sjabloon cache',
	'ThumbCache'				=> 'Thumbnail cache',

	// Embed
	'EmbedNoURL'				=> 'Geef een bronadres met de parameter-URL op. (bijv. {{embed url="https://example.com/embed/video.mp4"}} )',

	// Feed
	'FeedTitle'					=> 'Feed Titel',
	'FeedMulti'					=> 'Multi-feed',
	'FeedNoURL'					=> 'Geef een feed met de parameter-URL op. (bijv. {{feed url="https://example.com/feed.xml"}} )',
	'FeedError'					=> 'Kan de feed niet laden of parsen',
	'FeedSource'				=> 'Bron:',
	'FeedXMLTip'				=> '',

	// XML / RSS autodiscovery
	'ChangesXMLTitle'			=> ' - Recente wijzigingen',
	'ChangesXML'				=> 'Recente wijzigingen aan de ',
	'CommentsXMLTitle'			=> ' - Recente reacties',
	'CommentsXML'				=> 'Recente reacties op de ',
	'NewsXMLTitle'				=> ' - Recent nieuws',
	'NewsXML'					=> 'Recent nieuws voor de ',
	'RevisionXMLTip'			=> 'Klik om recente wijzigingen van de pagina in XML formaat te bekijken.',
	'CommentsXMLTip'			=> 'Klik om recente opmerkingen in XML formaat te bekijken.',
	'ChangesXMLTip'				=> 'Klik om recente wijzigingen in XML formaat te bekijken.',
	'NewsXMLTip'				=> 'Klik om recent nieuws in XML formaat te bekijken.',
	'RevisionsXML'				=> 'Herzieningen van ',
	'ExportClusterXML'			=> 'Exporteer hele cluster van ',
	'AccessDeniedXML'			=> 'Je hebt geen toegang tot deze informatie.',

	'ChangesFeed'				=> 'Veranderingen',
	'CommentsFeed'				=> 'Opmerkingen',
	'NewsFeed'					=> 'Nieuws',
	'RevisionsFeed'				=> 'Herzieningen van ',

	'LastModification'			=> 'Laatste wijziging',

	// Captcha
	'Captcha'					=> 'Typ het woord dat je in de afbeelding hebt gelezen',
	'CaptchaFailed'				=> 'Je hebt het captcha woord onjuist ingevoerd. Probeer het opnieuw.',
	'CaptchaReload'				=> 'Nieuwe captcha',
	'CaptchaReloadWarning'		=> 'Sorry, kan de captcha afbeelding niet herladen, u moet de pagina herladen om dat te doen',

	// news
	'News'						=> 'Nieuws',
	'NewsName'					=> 'Titel:',
	'NewsNoName'				=> 'Je bent vergeten nieuws nieuws te toevoegen.',
	'NewsNotAvailable'			=> 'Geen nieuws beschikbaar',
	'NewsNoClusterDefined'		=> 'Geen nieuwscluster gedefinieerd.',
	'NewsDiscuss'				=> 'Bespreek dit artikel...',

	// blog
	'BlogNewTopic'				=> 'Maak een nieuw bericht',
	'NoPostAvailable'			=> 'Nog geen bericht beschikbaar.',

	// Review
	'Reviewer'					=> 'Beoordelaar',
	'Reviewed'					=> 'beoordeeld',
	'Review'					=> 'beoordeling',
	'ReviewedBy'				=> 'beoordeeld door',
	'RemoveReview'				=> 'Recensie voor deze pagina verwijderen',
	'SetReview'					=> 'Beoordeelde deze pagina',
	'SetAsReviewed'				=> 'Pagina instellen als nagekeken',
	'SetAsUnreviewed'			=> 'Stel pagina in als niet nagekeken',

	// word filter
	'PotentialSpam'				=> 'Geïdentificeerd Potentieel Spam',

	// moderation handler
	'Moderation'				=> 'Moderatie',
	'Topics'					=> 'onderwerpen',
	'ModerateSection'			=> 'sectie / pagina ',

	'NotModerator'				=> 'Je bent niet bevoegd om deze pagina / hoofdstuk te modereren',
	'ModerateDeleteTopic'		=> 'Topic verwijderen / pagina',
	'ModerateDeletePosts'		=> 'Opmerkingen verwijderen',
	'ModerateMove'				=> 'Verplaatsen',
	'ModerateSplit'				=> 'Splits / Verplaats reacties',
	'ModerateMerge'				=> 'Samenvoegen',
	'ModerateLock'				=> 'Vergrendelen',
	'ModerateUnlock'			=> 'Ontgrendelen',
	'ModerateAccept'			=> 'Accepteren',
	'ModerateDeleteConfirm'		=> 'Are you sure you want to <strong>remove</strong> the following topics?',
	'ModerateRenameConfirm'		=> 'Voer een nieuwe titel in voor de geselecteerde pagina',
	'ModerateRenameExists'		=> 'Pagina met dezelfde naam bestaat al! Kies een andere naam.',
	'ModerateRename1Only'		=> 'Opmerking: alleen de eerste pagina die je hebt geselecteerd zal worden hernoemd!',
	'ModerateMovesConfirm'		=> 'Selecteer de doel partitie om het forum naar te verplaatsen',
	'ModerateMoveConfirm'		=> 'Selecteer het forum of geef het cluster op om deze onderwerpen te verplaatsen. Om een pagina te verplaatsen naar de hoofdmap van de site, typ &quot;/&quot;',
	'ModeratePgMoveConfirm'		=> 'Geef de naam op van het cluster waarin de pagina geplaatst moet worden. Om een pagina naar de hoofdmap van de site te verplaatsen, typ &quot;/&quot;',
	'ModerateMoveExists'		=> 'Bewerking afgebroken: In deze sectie bestaat al onderwerpen met dezelfde naam %1. Als je de bovenvermelde onderwerpen nog steeds wilt verplaatsen, hernoem ze dan eerst.',
	'ModerateMoveNotExists'		=> 'De pagina / cluster bestaat niet. Controleer de naam en probeer het opnieuw.',
	'ModerateMergeConfirm'		=> 'Kies een onderwerp, dat het resterende onderwerp moet combineren',
	'ModerateMerge2Min'			=> 'Om lid te worden moet je minstens twee onderwerpen selecteren!',
	'ModerateComDelConfirm'		=> 'Are you sure you want to <strong>remove</strong> %1 %2?',
	'ModerateComment'			=> 'Opmerking',
	'ModerateComments'			=> 'Opmerkingen',
	'ModerateSplitNewName'		=> 'Geef een naam op voor een afzonderlijk onderwerp en selecteer een scheidingsschema',
	'ModerateSplitPageName'		=> 'Voer de naam van de pagina / onderwerp in, waar u afneembare opmerkingen kunt verplaatsen en selecteer een scheidingsschema',
	'ModerateSplitAllAfter'		=> 'Alle reacties na de eerste geselecteerd (en inclusief) loskoppelen',
	'ModerateSplitSelected'		=> 'Geselecteerde commentaren gescheiden (totaal %1)',
	'ModerateUserProfile'		=> 'Profiel',
	'ModerateNoItemChosen'		=> 'Selecteer ten minste één item via de knop instellen.',

	'ModerateSection2'			=> 'gematigde sectie',
	'ModerateTopicsDeleted'		=> 'Geselecteerde onderwerpen zijn succesvol verwijderd.',
	'ModerateTopicsRelocated'	=> 'Geselecteerde onderwerpen met succes verplaatst',
	'ModerateTopicsRenamed'		=> 'Naam onderwerp succesvol gewijzigd.',
	'ModerateTopicsMerged'		=> 'Geselecteerde topics zijn succesvol samengevoegd.',
	'ModerateTopicsBlocked'		=> 'Geselecteerde topics zijn succesvol geblokkeerd',
	'ModerateTopicsUnlocked'	=> 'Geselecteerde onderwerpen met succes ontgrendeld.',
	'ModerateTopicDeleted'		=> 'Onderwerp is succesvol verwijderd.',
	'ModeratePageMoved'			=> 'Pagina met succes verplaatst.',
	'ModerateTopicRenamed'		=> 'Naam onderwerp succesvol gewijzigd.',
	'ModerateTopicBlocked'		=> 'Onderwerp succesvol geblokkeerd',
	'ModerateTopicUnlocked'		=> 'Onderwerp ontgrendelen geslaagd.',
	'ModerateCommentsDeleted'	=> 'Geselecteerde opmerkingen met succes verwijderd.',
	'ModerateCommentsSplit'		=> 'Geselecteerde commentaren zijn succesvol gescheiden in een nieuw onderwerp.',
	'ModerateCommentsSplitFailed'	=> 'Opmerking: Het scheiden van de geselecteerde reacties naar een nieuwe topic is om een of andere reden mislukt.<br>Dit mag meestal niet gebeuren, dus neem dan contact op met de beheerder van de site.<br>Als voorzorgsmaatregel is de kwestie in haar oorspronkelijke vorm in stand gehouden.',
	'ModerateCommentsMoved'		=> 'Geselecteerde reacties succesvol gemigreerd naar de gegeven pagina.',

	// forum
	'ForumSubforums'			=> 'Forum',
	'ForumTopic'				=> 'Onderwerp',
	'ForumTopics'				=> 'Onderwerpen',
	'ForumPosts'				=> 'Berichten',
	'ForumReplies'				=> 'Antwoorden',
	'ForumAuthor'				=> 'Auteur',
	'ForumViews'				=> 'Weergaven',
	'ForumCreated'				=> 'Aangemaakt',
	'ForumComments'				=> 'Opmerkingen',
	'ForumLastComment'			=> 'Laatste opmerking',
	'ForumNoComments'			=> 'Geen opmerkingen',
	'ForumNoTopics'				=> 'Er zijn geen onderwerpen of berichten in dit forum.',
	'ForumNewTopic'				=> 'Een nieuwe discussie starten',
	'ForumTopicName'			=> 'Onderwerp naam:',
	'ForumTopicSubmit'			=> 'Topic verzenden',
	'ForumNoTopicName'			=> 'Geef een naam op voor de nieuwe pagina.',
	'ForumNewPosts'				=> 'nieuw bericht',
	'ForumLocked'				=> 'sectie vergrendeld',
	'ForumUpdated'				=> 'bijgewerkt',
	'ForumNoClusterDefined'		=> 'Geen Forum cluster gedefinieerd.',
	'ForumOutsideCluster'		=> 'Zorg ervoor dat de %1 actie zich in de forumclub bevindt.',

	// password complexity
	'PwdCplxShort'				=> 'Het wachtwoord is te kort.',
	'PwdCplxEquals'				=> 'Wachtwoord bevat de gebruikersnaam.',
	'PwdCplxWeak'				=> 'Wachtwoord voldoet niet aan de vereisten',
	'PwdCplxDesc1'				=> 'Vereisten voor het wachtwoord: ',
	'PwdCplxDesc2'				=> 'wachtwoord mag niet minder zijn dan %1 tekens',
	'PwdCplxDesc3'				=> 'mag uw gebruikersnaam niet bevatten',
	'PwdCplxDesc4'				=> 'moet bestaan uit ',
	'PwdCplxDesc41'				=> 'letters en cijfers',
	'PwdCplxDesc42'				=> 'hoofdletters en kleine letters en cijfers',
	'PwdCplxDesc43'				=> 'hoofdletters en kleine letters, cijfers en niet-alfanumerieke tekens',
	'PwdCplxDesc5'				=> 'U kunt alle letters, cijfers en speciale tekens behalve spaties gebruiken.',

	'PasswordTooShort'			=> 'Wachtwoord te kort.',
	'PasswordTooCommon'			=> 'Dat wachtwoord komt te vaak voor.',
	'PasswordSameAsUsername'	=> 'Je wachtwoord is hetzelfde als je gebruikersnaam.',
	'PasswordSameAsEmail'		=> 'Je wachtwoord is hetzelfde als je e-mail.',

	'Timezone'					=> 'Timezone',

	'LanguageArray'	=> [
		'bg' => 'Bulgaars',
		'da' => 'Deens',
		'de' => 'Duits',
		'el' => 'Grieks',
		'en' => 'Nederlands',
		'es' => 'Spaans',
		'et' => 'Estlands',
		'fa' => 'Perzisch',
		'fr' => 'Frans',
		'hi' => 'Hindoestani',
		'hu' => 'Hongaars',
		'it' => 'Italiaans',
		'ja' => 'Afrikaans',
		'ko' => 'Koreaans',
		'nl' => 'Nederlands',
		'pl' => 'Pools',
		'pt' => 'Portugees',
		'ru' => 'Russisch',
		'ta' => 'Tamil',
		'zh' => 'Chinees',
		'zh-tw' => 'Chinees',
	],

	'AccountStatus'				=> 'Klant status',
	'AccountStatusArray' => [
		'0' => 'Actief',
		'1' => 'openstaande',
		'2' => 'geblokkeerd',
		'3' => 'Inactief',
	],

	'JustNow'		=> 'op dit moment',
	'MinuteAgo'		=> 'een minuut geleden',
	'MinutesAgo'	=> '%1 minuten geleden',
	'HourAgo'		=> 'een uur geleden',
	'HoursAgo'		=> '%1 uur geleden',
	'DayAgo'		=> 'gisteren',
	'DaysAgo'		=> '%1 dagen geleden',
	'WeekAgo'		=> 'een week geleden',
	'WeeksAgo'		=> '%1 weken geleden',
	'MonthAgo'		=> 'een maand geleden',
	'MonthsAgo'		=> '%1 maanden geleden',
	'YearAgo'		=> 'een jaar geleden',
	'YearsAgo'		=> '%1 jaar geleden',

	'InAMoment'		=> 'over een moment',
	'InAMinute'		=> 'in een minuut',
	'InMinutes'		=> 'in %1 minuten',
	'InAnHour'		=> 'in een uur',
	'InHours'		=> 'in %1 uren',
	'Tomorrow'		=> 'morgen',
	'InDays'		=> 'in %1 dagen',
	'InAWeek'		=> 'in een week',
	'InWeeks'		=> 'in %1 weken',
	'InAMonth'		=> 'in een maand',
	'InMonths'		=> 'in %1 maanden',
	'InAYear'		=> 'over een jaar',
	'InYears'		=> 'in %1 jaar',

	// norm multiples
	'ByteDecimalShort'			=> ['B', 'KB', 'Mb', 'GB', 'TB', 'PB', 'EB', 'ZB', 'JB'],
	'ByteDecimalLong'			=> ['Byte', 'Kilobyte', 'Megabyte', 'Gigabyte', 'Terabyte', 'Petabyte', 'Exabyte', 'Zettabyte', 'Yottabyte'],
	'ByteBinaryShort'			=> ['B', 'KiB', 'MiB', 'GiB', 'TiB', 'PiB', 'EiB', 'ZiB', 'YiB'],
	'ByteBinaryLong'			=> ['Byte', 'Kibibyte', 'Mebibyte', 'Gibibyte', 'Tebibyte', 'Pebibyte', 'Exbibyte', 'Zebibyte', 'Yobibyte'],
	'PixelDecimalShort'			=> ['px', 'KP', 'MP', 'Guadelego', 'TTP', 'PP', 'EP', 'ZP', 'JP'],
	'PixelDecimalLong'			=> ['pixel', 'Kpx', 'Mpx', 'Gpx', 'Tpx', 'Ppx', 'Aflevering', 'Zpx', 'Ypx'],

	// loading error
	'UnknownAction'				=> 'Onbekende actie',
	'UnknownMethod'				=> 'Onbekende methode',
	'FormatterNotFound'			=> 'Formulier %1 niet gevonden',

	// log
	'LogAdminLoginSuccess'		=> 'Succesvolle login in het beheerpaneel',
	'LogAdminLogout'			=> 'Uitloggen van het beheerpaneel',
	'LogAdminLoginFailed'		=> '!!Mislukt om toegang tot het administratief paneel te geven!!',
	'LogAdminLoginLocked'		=> 'Geblokkeerde login in het beheerpaneel',
	'LogUserCookieForged'		=> '!!**Een poging om in te loggen op een vervalste cookie met login ##%1##**!!',
	'LogInvalidFormToken'		=> 'Mogelijke CSRF aanval in uitvoering gedetecteerd: %1',
	'LogRemovedPage'			=> '!!Verwijder pagina ##%1## (gebruiker %2)!!',
	'LogRemovedCluster'			=> '!!Verwijderde **cluster** ##%1## (gebruiker %2)!!',
	'LogRemovedRevision'		=> '!!Revisie ##%3## van pagina [[/%1]] (gebruiker %2)!!',
	'LogRemovedComment'			=> '!!Reactie van %3 op pagina [[/%1]] (gebruiker %2)!!',
	'LogRemovedFile'			=> '!!Het bestand ##%2## van pagina [[/%1]]!!',
	'LogRemovedAllComments'		=> '!!Alle opmerkingen van de pagina [[/%1]]!!',
	'LogRemovedAllRevisions'	=> '!!Alle herzieningen van de pagina [[/%1]]!!',
	'LogRemovedAllFiles'		=> '!!Alle bestanden verwijderd, gekoppeld aan [[/%1]]!!',
	'LogTopicLocked'			=> 'Forum onderwerp is vergrendeld [[/%1]]',
	'LogTopicUnlocked'			=> 'Ontgrendeld forumonderwerp [[/%1]]',
	'LogAclUpdated'				=> 'Bijgewerkt ACL pagina [[/%1]]',
	'LogOwnershipChanged'		=> 'Eigendom van de pagina [[/%1]] overgedragen aan de gebruiker ##%2##',
	'LogUserLoginFailed'		=> '!!Mislukte pogingen om in te loggen met ##~%1##!!',
	'LogClonedPage'				=> 'Pagina ##%1## gekloond tot [[/%2]]',
	'LogRenamedPage'			=> 'Pagina ##%1## hernoemd naar [[/%2]]',
	'LogRenamedPage2'			=> '. De oude pagina is ingesteld als de link naar de nieuwe',
	'LogSplittedPage'			=> 'Reacties op de pagina [[/%1]] gesplitst naar pagina [[/%2]]',
	'LogMergedPages'			=> 'Pagina\'s %1 samengevoegd met pagina [[/%2]]',
	'LogUserPasswordReminded'	=> 'Gebruiker ##%1## heeft gevraagd om het wachtwoord te herstellen om ##%2##',
	'LogUserPasswordRecovered'	=> 'Gebruiker ##%1## heeft het vergeten wachtwoord succesvol hersteld',
	'LogUserPasswordChanged'	=> 'Gebruiker ##%1## succesvol bijgewerkt (gewijzigd)',
	'LogUserPasswordMismatch'	=> '!!Gebruiker ##%1## kan het wachtwoord niet wijzigen: huidige wachtwoord komt niet overeen!',
	'LogUserIPSwitched'			=> 'Ongeautoriseerde verandering van IP adres van gebruiker %1 van %2 naar %3',
	'LogPageImported'			=> 'Geïmporteerde pagina [[/%1]]',
	'LogSaveNoRights'			=> 'Geen rechten om de pagina [[/%1] ] op te slaan',
	'LogPageCreated'			=> 'Nieuwe pagina gemaakt [[/%1]]',
	'LogPagePropertiesUpdated'	=> 'Pagina-eigenschappen bijgewerkt [[/%1]]',
	'LogPageOwnershipClaimed'	=> 'De gebruiker is eigenaar van de pagina [[/%1]]',
	'LogFileUploadedLocal'		=> 'Nieuw bestand ##%2## geüpload naar de pagina [[/%1]] (grootte %3)',
	'LogFileUploadedGlobal'		=> 'Nieuw bestand ##%2## geüpload naar de globale map (grootte %3)',
	'LogPMSent'					=> 'Personal message ##%1## -> ##%2## successfully sent',
	'LogUserSimilarName'		=> 'Er zijn pogingen gedaan om je te registreren onder dezelfde gebruikersnaam: ##%1##',
	'LogUserEmailNotAllowed'	=> 'E-mail ##%1## niet in de toegestane domeinenlijst',
	'LogRegisterTiming'			=> 'Registration failed, form time threshold is ##%1## seconds (was ##%2##)',
	'LogUserRegistered'			=> 'Succesvol een nieuwe gebruiker geregistreerd ##%1(##%2##)',
	'LogUserEmailActivated'		=> 'E-mail succesvol geactiveerd ##%1## of gebruiker ##%2##',
	'LogCommentPosted'			=> '[[/%1 nieuwe comment(en)]] toegevoegd aan pagina [[/%2]]',
	'LogUserLoginOK'			=> 'Gebruiker ##%1## succesvol ingelogd op het systeem',
	'LogUserLoggedOut'			=> 'Gebruiker ##%1## heeft het systeem succesvol uitgelogd',
	'LogUserSessionContinued'	=> 'Gebruiker ##%1## heeft de geschorste sessie voortgezet',
	'LogUserSettingsUpdate'		=> 'Gebruiker ##%1## persoonlijke instellingen bijgewerkt',
	'LogPageEdited'				=> 'Pagina bewerkt [[/%1]]',
	'LogCommentEdited'			=> 'Bewerkte reactie [[/%1]]',
	'LogUpdatedFileMeta'		=> 'Bestanden metadata bijgewerkt voor ##%2## van pagina [[/%1]]',
	'LogUpdatedFileCategories'	=> 'Bestandscategorieën bijgewerkt voor ##%2van pagina [[/%1]]',

	'LogXmlSitemapGenerated'	=> 'XML Sitemap gegenereerd',
	'LogReferrersPurged'		=> 'Onderhoud: verwijzingen verwijderd',
	'LogRevisionsPurged'		=> 'Onderhoud: verouderde pagina\'s verwijderd',
	'LogDeletedPagesPurged'		=> 'Onderhoud: verwijderde pagina\'s verwijderd',
	'LogSystemLogPurged'		=> 'Onderhoud: systeemlog verwijderd',
	'LogCachedPagesPurged'		=> 'Onderhoud: opgeslagen pagina\'s verwijderd',
	'LogSqlCachePurged'			=> 'Onderhoud: uitgebufferde SQL resultaten verwijderd',
	'LogExpiredTokensPurged'	=> 'Onderhoud: verlopen cookie_tokens verwijderd',
	'LogErrorSplitComments'		=> 'Fout bij het scheiden van reacties uit het topic [[/%1]] een nieuw onderwerp ##%2##: pagina is niet aangemaakt',
	'LogCategoriesUpdated'		=> 'Bijgewerkte paginacategorieën [[/%1]]',
	'LogCategoryCreated'		=> 'Een nieuwe categorie aangemaakt //%1//',
	'LogCategoryRenamed'		=> 'Categorie ##%1## hernoemd tot ##%2##',
	'LogCategoryDebundled'		=> 'Categorie ##%1## gedebundled',
	'LogCategoryGrouped'		=> 'Categorie ##%1## gegroepeerd met het woord ##%2##',
	'LogCategoryRemoved'		=> 'Categorie ##%1## verwijderd uit de database',
	'LogThumbnailGeneration'	=> 'Thumbnail generation %1 sec.',

	'ErrorMinPHPVersion'		=> 'De PHP versie moet groter zijn dan <strong>' . PHP_MIN_VERSION . '</strong>,' .
									' uw server lijkt te draaien <strong>' . PHP_VERSION . '</strong>.' .
									'  Je moet upgraden naar een recentere PHP-versie om WackoWiki goed te laten werken.',

];
