<?php

if (!defined('IN_WACKO'))
{
	exit;
}

$wacko_translation = [

	// language
	'lang_scheme'	=> [
		'name'		=> 'Engelsk',
		'code'		=> 'da',
		'dir'		=> 'ltr',
		'locale'	=> 'da_US.UTF-8',
	],

	// common
	'AddButton'					=> 'Tilføj',
	'ArchiveButton'				=> 'Arkiv',
	'CancelButton'				=> 'Annuller',
	'ContinueButton'			=> 'Fortsæt',
	'ConvertButton'				=> 'Konverter',
	'CreateButton'				=> 'Opret',
	'DeleteButton'				=> 'Slet',
	'RemoveButton'				=> 'Fjern',
	'RenameButton'				=> 'Omdøb',
	'ResetButton'				=> 'Reset',
	'RestoreButton'				=> 'Gendan',
	'SaveButton'				=> 'Gem',
	'SearchButton'				=> 'Søg',
	'SendButton'				=> 'Send',
	'SetButton'					=> 'Indstil',
	'SubmitButton'				=> 'Indsend',
	'UpdateButton'				=> 'Opdater',

	'FormInvalid'				=> 'Den indsendte formular er ugyldig. Prøv at indsende igen.',
	'UnitPixel'					=> 'px',
	'Number'					=> 'Nummer',

	// logged in panel
	'AccountText'				=> 'Konto',
	'AccountTip'				=> 'Konto Indstillinger',
	'AdminText'					=> 'Administrator',
	'AdminTip'					=> 'Administrativt Panel',
	'LogoutLink'				=> 'Log Ud',
	'LogoutButton'				=> 'Log ud',
	'LogoutAreYouSure'			=> 'Vil du virkelig logge ud?',

	// registration panel
	'RegistrationWelcome'		=> 'Ny brugerregistrering:',
	'RegistrationButton'		=> 'Registrer mig',
	'UserNameOwned'				=> 'Dette brugernavn er allerede registreret. Vælg venligst et andet.',
	'SiteRegistered'			=> 'Du har registreret dig på siden %1.',
	'RegistrationEmailInfo'		=> 'En gyldig e-mail-adresse. Alle e-mails fra systemet vil blive sendt til denne adresse. E-mailadressen er ikke offentliggjort og vil kun blive brugt, hvis du ønsker at modtage en ny adgangskode eller ønsker at modtage visse nyheder eller meddelelser via e-mail.',
	'EmailConfirmHint'			=> 'Bekræft venligst din e-mail-adresse ved at klikke på linket i de instruktioner, der sendes til dig. <br>Hvis du ikke verificerer din e-mailadresse, vil du ikke kunne hente en mulig tabt adgangskode. <br>Desuden vil du ikke blive underrettet om seneste sideændringer og kommentarer.',
	'EmailConfirmRequired'		=> 'Uden bekræftet e-mailadresse får du ikke lov til at logge ind.',
	'NameTooShort'				=> 'Brugernavnet er for kort, minimum %2 tegn er påkrævet.',
	'NameTooLong'				=> 'Brugernavnet er for langt, højst %2 tegn er tilladt.',
	'NameAlphanumOnly'			=> 'Brugernavn skal være mellem %1 og %2 tegn langt og kun bruge alfanumeriske tegn. Store bogstaver er OK.',
	'NameCamelCaseOnly'			=> 'Brugernavn skal være mellem %1 og %2 tegn langt og WikiName formateret.',
	'NewUserAccount'			=> 'ny brugerkonto',

	'NewAccountSubject'			=> 'Konto registrering',
	'NewAccountAdminCreated'	=> 'Brugeren %1 har oprettet en konto til dig med brugernavn "%2". For at fuldføre din registrering, besøg følgende URL (sørg for at den er angivet som enkelt linje) og angiv din egen adgangskode:',
	'NewAccountUsername'		=> 'Brugernavn:',
	'AccountLanguage'			=> 'Sprog:',
	'NewAccountEmail'			=> 'Email:',
	'NewAccountIP'				=> 'Ekstern IP- adresse:',
	'NewAccountSignupInfo'		=> 'Den følgende konto er blevet oprettet:',

	'UserWaitingApproval'		=> 'En e-mail er blevet sendt til webstedets administrator. Administratoren vil gennemgå de indsendte oplysninger og enten godkende eller afvise din anmodning.',
	'UserRequiresApproval'		=> 'For at godkende eller nægte denne bruger adgang til %1 gå til admin-panelet.',
	'UserApprovalInfo'			=> 'Når du er registreret, vil din anmodning blive sendt til webstedsadministratoren til godkendelse. Du vil derefter modtage en e-mail med yderligere instruktioner.',
	'UserApprovalHint'			=> 'Den vellykkede aktivering af din konto vil blive annonceret i en specifik e-mail. Indtil da er et login ikke muligt.',

	'UserApprovalPending'		=> 'Din konto afventer stadig godkendelse.',
	'UserApprovalDenied'		=> 'Din konto er blevet nægtet adgang til dette websted.',

	'RegistrationApproved'		=> 'Registrering Godkendt',
	'RegistrationDenied'		=> 'Registrering Nægtet',
	'PendingApproval'			=> 'Afventer Godkendelse',

	'UserApprovedInfo'			=> 'Du er blevet godkendt til at tilgå %1.',
	'UserDeniedInfo'			=> 'Du er blevet nægtet adgang til %1.',

	'RegistrationThreshold'		=> 'Tiden til udfyldelse af formularen bør ikke være mindre end %1 sekunder.',
	'Language'					=> 'Sprog',

	// login panel
	'LoginWelcome'				=> 'Login',
	'CreateAccount'				=> 'Opret ny konto',
	'RegistrationLink'			=> 'Registrering',
	'LoginName'					=> 'Brugernavn',
	'Password'					=> 'Adgangskode',
	'LoginButton'				=> 'Login',
	'LoginLink'					=> 'Login',
	'PersistentCookie'			=> 'Bliv logget ind',
	'Session'					=> 'Session',
	'SessionTip'				=> 'parametre for nuværende session',
	'SessionDuration'			=> 'Session varighed',
	'SessionDurationSession'	=> 'browser session',
	'SessionDurationDay'		=> '1 dag',
	'SessionDurationWeek'		=> '1 uge',
	'SessionDurationMonth'		=> '1 måned',
	'LoggedInAs'				=> 'Du er logget ind som',

	'ClearCookies'				=> 'Slet alle cookies',
	'BindSessionIp'				=> 'Bind session til IP-adressen',
	'BindSessionIpOn'			=> 'aktiveret (nuværende IP %1)',
	'TrafficProtection'			=> 'Trafikbeskyttelse',
	'SessionEnds'				=> 'Den aktuelle session slutter',
	'LastVisit'					=> 'Sidste besøg blev registreret',

	'LoginIncorrect'			=> 'Brugernavnet eller adgangskoden du har indtastet er ugyldigt.',
	'WelcomeBack'				=> 'Velkommen tilbage, %1',
	'LoginAttemptsExceeded'		=> 'Du overskred det maksimale tilladte antal loginforsøg.<br>Ud over dit brugernavn og din adgangskode skal du nu også løse CAPTCHA nedenfor.',

	// session notice
	'IPAddressChanged'			=> 'IP-adressen ændret til %1 (var %2)',

	'SessionReplay'				=> 'Session afsluttet på grund af genafspilning.',
	'SessionObsolete'			=> 'Session er forældet.',
	'SessionExpired'			=> 'Sessionen er udløbet.',
	'SessionTimeout'			=> 'Session afsluttet på grund af timeout.',
	'SessionInactivity'			=> 'Session afsluttet på grund af inaktivitet.',
	'SessionUaChange'			=> 'Session afsluttet på grund af brugeragent ændring.',
	'SessionTLSChange'			=> 'Session afsluttet på grund af TLS-ændring.',
	'SessionIPChange'			=> 'Session afsluttet på grund af IP ændring.',

	// other
	'Guest'						=> 'Gæst',
	'Everybody'					=> 'Alle',
	'Help'						=> 'Hjælp',
	'TopicSearchText'			=> 'Søg kun i titler',
	'WordprocessorVersion'		=> 'Word processor version',

	// notifications
	'EmailHello'				=> 'Hej ',
	'EmailModerator'			=> 'Moderator',
	'WatchedPageChanged'		=> 'Siden er ændret ',
	'SomeoneChangedThisPage'	=> ' ændrede en side, som du kigger: ',
	'NewPageCreatedSubj'		=> 'En ny side',
	'NewPageCreatedBody'		=> 'Bruger %1 har oprettet en ny side: ',
	'FileUploadedSubj'			=> 'En ny fil',
	'FileUploadedBody'			=> 'Bruger %1 har uploadet en ny fil: ',
	'FileReplacedBody'			=> 'Bruger %1 har erstattet filen: ',

	'ActionDenied'				=> 'Handling nægtes her.',
	'TocTitle'					=> 'Indhold ',
	'OuterLink2'				=> 'Udgående link',
	'FileLink'					=> '',
	'PDFLink'					=> 'PDF Dokument',
	'RDFLink'					=> 'Rdf Dokument',
	'EmailLink'					=> 'Skriv en e-mail (mail klient launch)',
	'JabberLink'				=> 'Chat via XMPP (Jabber klient lancering)',
	'PermaLink'					=> 'Permalink',
	'PermaLinkTip'				=> 'Permanent link til denne revision af siden',
	'PermaLink0Tip'				=> 'Permanent link til denne side',

	'ShowTip'					=> 'Vend tilbage i visningstilstand',
	'ShowText'					=> 'Vis',
	'WikieditAutocomplete'		=> 'Komplet wikilinks af Ctrl + Space',
	'WikiEditInactiveJs'		=> 'For at kunne bruge WikiEdit, skal du aktivere JavaScript i din browser.',
	'NumerateLinks'				=> 'Numerér links i udskriftsvisning',
	'Comment'					=> 'Kommentar',
	'Comments0'					=> 'Tilføj din kommentar',
	'Comments1'					=> 'Læs kommentar (1 kommentar)',
	'CommentsN'					=> 'Læs kommentarer (%1 kommentarer)',
	'Comments'					=> 'Kommentarer',
	'CommentHint'				=> '<a href="%1">Log ind</a> eller <a href="%2">opret en konto</a> for at sende en kommentar.',
	'CommentEdited'				=> 'redigeret',
	'Links'						=> 'Links',
	'Version'					=> 'Version',

	// details formatter
	'ShowHideDetails'			=> 'Detaljer',

	'PrivacyPolicy'				=> 'Privat Politik',
	'TermsOfUse'				=> 'Vilkår for anvendelse',
	'AcceptTermsOfUse'			=> 'Jeg har læst, forstået og accepterer vilkårene for webstedets tjeneste.',

	'ShowComments'				=> 'Vis kommentarer / formular',
	'HideComments'				=> 'Skjul kommentarer / formular',
	'AddComment'				=> 'Vedhæft en kommentar til denne side:',
	'AddCommentTitle'			=> 'Titel på bemærkningen:',
	'CommentTitleRe'			=> 'Svar:',
	'AddCommentButton'			=> 'Vedhæft Kommentar',
	'HereLink'					=> 'her',
	'PageHandlerMoreTip'		=> 'mere',

	'ThemeCorrupt'				=> 'Tema er korrupt',
	'InvalidNamespace'			=> 'Ugyldigt navneområde angivet.',
	'DoesNotExists'				=> 'Denne side findes ikke.',
	'PromptCreate'				=> 'Måske ønsker du at <strong><a href="%1">oprette</a></strong> det?',
	'RevisionHint'				=> 'Dette er en gammel revision af <a href="%1">%2</a> fra %3 redigeret af %4.',
	'ReadAccessDenied'			=> 'Du har ikke tilladelse til at læse denne side.',
	'ReadAccessDeniedHintGuest'	=> 'For at læse denne side, skal du logge ind.',
	'PageDeletedInfo'			=> 'Denne side er blevet slettet.',
	'RevisionDeletedInfo'		=> 'Denne revision er blevet slettet.',
	'CommentDeletedInfo'		=> 'Denne kommentar er blevet slettet.',

	'LastEditedBy'				=> 'Sidst redigeret af',
	'YouAreOwner'				=> 'Du er ejer af denne side.',
	'Owner'						=> 'Ejer:',
	'Nobody'					=> 'Ingen',
	'TakeOwnership'				=> 'Tag Ejerskab',
	'FilesTip'					=> 'Håndtér vedhæftede filer',
	'FilesText'					=> 'Vedhæftninger',
	'DeleteTip'					=> 'Slet side, dens filer og kommentarer',
	'DeleteCommentTip'			=> 'Slet kommentar',
	'DeleteText'				=> 'Slet',
	'AclText'					=> 'Rettigheder',
	'AclTip'					=> 'Rediger Tilladelser',

	'PropertiesText'			=> 'Egenskaber',
	'PropertiesTip'				=> 'Rediger Sideegenskaber',
	'EditTip'					=> 'Rediger denne side.',
	'EditText'					=> 'Rediger',
	'EditSection'				=> 'Rediger sektion %1',
	'EditSectionHint'			=> 'Afdeling %1 af %2',
	'SectionHeadline'			=> 'Afsnit',
	'EditCommentTip'			=> 'Rediger kommentar',
	'EditComment'				=> 'Rediger denne kommentar',
	'ReplyComment'				=> 'Svar',
	'ReplyCommentTip'			=> 'Besvar denne kommentar',
	'RevisionTip'				=> 'Vis siderevisioner',
	'RevisionText'				=> 'Revisioner',
	'ReferrersTip'				=> 'Se en liste over URLer der refererer til denne side',
	'ReferrersText'				=> 'Henvisere',
	'ModerateTip'				=> 'Moderation af emner og forumindlæg',
	'ModerateText'				=> 'Moderat',
	'SearchText'				=> 'Søg: ',

	'AclUpdated'				=> 'Adgangskontrollister opdateret',
	'AclGaveOwnership'			=> ' og gav ejerskab til %1.',
	'AclNoNewOwner'				=> 'Page ownership is not transfered, because the user %1 was not found. (Automatic Copy)',
	'NewPageOwnership'			=> 'Ejerskab af overførte sider',
	'YouAreNewOwner'			=> 'Tidligere ejer %1 overførte ejerskab ' . "\n" . 'af følgende side til dig',
	'PageOwnershipInfo'			=> '',
	'AclRead'					=> 'Læs:',
	'AclWrite'					=> 'Skriv:',
	'AclComment'				=> 'Bemærkninger:',
	'AclCreate'					=> 'Opret:',
	'AclUpload'					=> 'Upload:',
	'AclFor'					=> 'Adgangskontrol Lister for %1',
	'SetOwner'					=> 'Sæt Ejer:',
	'OwnerDontChange'			=> 'Ændr ikke',
	'AclAccessDenied'			=> 'Du er ikke ejeren af denne side.',
	'AclSyntaxError'			=> 'Adgangskontrol liste syntaks fejl',
	'AclHelp'					=> '<code>*</code> - alle er tilladt<br>' .
									'<code>$</code> - kun registrerede brugere<br>' .
									'<code>!</code> - et forudgående udråbstegn nægter den respektive højre<br>' .
									'<code>[UserName]</code> - navne på tilladte brugere<br>' .
									'<code>[GroupName]</code> - navne på tilladte brugergruppe (alias)<br>' .
									'<code>(en tom liste)</code> - kun sideejeren har adgang',

	'AccessMode'				=> 'Synlighed',
	'AccessDenied'				=> 'afvist',
	'AccessPublic'				=> 'offentlig',
	'AccessRegistered'			=> 'registreret',
	'AccessPrivate'				=> 'privat',
	'AccessCustom'				=> 'brugerdefineret',

	// purge handler
	'PurgePage'					=> 'Purge page',
	'NotOwnerAndCantPurge'		=> 'Du er ikke ejeren af siden, og du kan ikke rense den.',
	'ReallyPurge'				=> 'BEMÆRK: At opfordre siden er uigenkaldelig!',
	'SelectPurgeOptions'		=> 'Vælg de nødvendige udrensningsmuligheder:',
	'PurgeComments'				=> 'Ryd alle kommentarer på siden',
	'CommentsPurged'			=> 'Alle kommentarer blev slettet.',
	'PurgeFiles'				=> 'Fjern alle vedhæftede filer',
	'FilesPurged'				=> 'Alle vedhæftede filer blev fjernet.',
	'PurgeRevisions'			=> 'Ryd alle revisioner af siden',
	'RevisionsPurged'			=> 'Revisioner blev renset.',
	'PurgeButton'				=> 'Purge',

	// categories handler
	'Categories'				=> 'Kategorier',
	'CategoriesAssign'			=> 'tildel',
	'CategoriesEdit'			=> 'rediger',
	'Category'					=> 'Kategori',
	'CategoriesFor'				=> 'Kategorier for',
	'CategoriesTip'				=> 'Rediger kategorier',
	'CategoriesText'			=> 'Kategorier',
	'CategoriesUpdated'			=> 'Kategorier opdateret',
	'CategoriesAlreadyExists'	=> 'Kategori %1 findes allerede.',
	'CategoriesAdded'			=> 'Kategori %1 tilføjet.',
	'CategoriesRenamed'			=> 'Kategori omdøbt.',
	'CategoriesUngrouped'		=> 'Kategori debunderet med succes.',
	'CategoriesGrouped'			=> 'Kategorien indtastet i den nye gruppe.',
	'NoMultilevelGrouping'		=> 'Grupperingskategorier på flere niveauer er ikke muligt.',
	'CategoriesDeleted'			=> 'Kategorien blev slettet fra databasen og alle sider.',
	'CategoriesAdd'				=> 'Tilføj en ny kategori',
	'CategoryDescription'		=> 'Varebeskrivelse',
	'CategoriesAddGrouped'		=> 'Grupperet med kategorien',
	'CategoriesAddGroupedNo'	=> 'Ingen gruppe.',
	'CategoriesRename'			=> 'Omdøb kategorien %1 til',
	'CategoriesRenameInfo'		=> '* Bemærk: Ændringen vil påvirke alle sider, der er tilknyttet til denne kategori.',
	'CategoriesGroup'			=> 'Grupper kategorier %1 med',
	'CategoriesGroupInfo'		=> '* Vælg [ingen gruppe] for at debundle kategorien.',
	'CategoriesNoGroup'			=> '[ingen gruppe]',
	'CategoriesDelete'			=> 'Er du sikker på, at du vil fjerne kategori %1?',
	'CategoriesDeleteInfo'		=> '* Bemærk: Ændringen vil påvirke alle sider, der er tilknyttet til denne kategori. Hvis ordet har en underkategori, vil de ikke blive slettet, men kun debundet.',
	'CategoriesStoreInfo'		=> 'For at tildele kategorier til en side, vælges afkrydsningsfelterne.',
	'CategoriesStoreButton'		=> 'Gem Kategorier',
	'CategoriesGroupButton'		=> 'Gruppe',
	'CategoriesEditInfo'		=> 'For at redigere kategorilisten vælges radioknappen.',
	'NoCategoriesForThisLang'	=> 'Kategorier for dette sprog er ikke angivet.',
	'PagesCategory'				=> 'Sider kategori',
	'CategoryNotExists'			=> 'Kategori eksisterer ikke.',
	'CategoryEmpty'				=> 'Kategori tom.',
	'NoCategorySelected'		=> 'Ingen kategori valgt.',
	'NoCategoriesAssigned'		=> 'Ingen tildelte kategorier for dette sprog.',
	'TagCloud'					=> 'Tag Sky',
	'PagesTaggedWith'			=> '%1 sider markeret med %2',
	'CategoriesOfCluster'		=> 'af klynge',
	'TaggedWithTip'				=> 'vis sider tagget %1',

	// source handler
	'SourceText'				=> 'Kilde',
	'SourceTip'					=> 'Se wiki-kilden',
	'SourceCopyToClipboard'		=> 'kopier til udklipsholder',
	'SourceFor'					=> 'Vis kilde til %1',

	// Groups action
	'GroupsSearch'				=> 'Find Grupper',
	'GroupsNoMatching'			=> 'Matchende grupper ikke fundet. Prøv et mindre strengt søgekriterium.',
	'GroupsOpenProfile'			=> 'Vis Profil',
	'GroupsName'				=> 'Gruppe',
	'GroupsMembers'				=> 'Medlemmer',
	'GroupsDescription'			=> 'Varebeskrivelse',
	'GroupsCreated'				=> 'Oprettet',
	'GroupsNotFound'			=> 'Gruppe %2 blev ikke fundet. Klik på <a href="%1">her</a>for at gå til hovedlisten.',
	'GroupsProfile'				=> 'Profil',
	'GroupsList'				=> 'Se hele listen over grupper',
	'GroupSpace'				=> 'Gruppér plads',

	'MetaUpdated'				=> 'Meta data opdateret',

	'PreviewButton'				=> 'Eksempelvisning',
	'Preview'					=> 'Eksempelvisning',
	'Chars'						=> 'tegn',
	'PageBody'					=> 'Side tekst',
	'EditNote'					=> 'Rediger resumé',
	'EditNoteMissing'			=> 'Rediger resumé mangler',
	'EditMinor'					=> 'Mindre redigering',
	'MinorEditHide'				=> 'Skjul mindre redigering',
	'MinorEditShow'				=> 'Vis mindre redigering',
	'PostAnonymously'			=> 'Skriv anonymt uden at give dit navn',
	'NotifyMe'					=> 'Advisér mig om nye kommentarer og ændringer af siden',
	'OverwriteAlert'			=> 'OVERWRITE ALERT: Denne side blev ændret af en anden, mens du redigerede den.<br>Kopier dine ændringer og rediger venligst denne side.',
	'TextDbOversize'			=> 'Advarsel: Din tekst overskrider længdegrænsen med %1 tegn. Forkort venligst din tekst til et acceptabelt antal tegn. Tip: Du kan placere den resterende tekst på en separat side.',
	'EditingRevisionWarning'	=> 'Du redigerer en gammel revision af denne side. Hvis du offentliggør den, vil eventuelle ændringer, der er foretaget siden da blive fjernet. <br>Du kan i stedet ønske at redigere den aktuelle revision.',
	'WriteAccessDenied'			=> 'Du har ikke skriveadgang til denne side.',
	'EmptyPage'					=> 'Page body was empty - not saved!',
	'EmptyComment'				=> 'Kommentar indhold var tomt - ikke gemt!',
	'CommentAccessDenied'		=> 'Beklager, du har ikke tilladelse til at skrive kommentarer til denne side.',
	'CommentFlooded'			=> 'Intervallet mellem offentliggørelsen af stillingerne må ikke være mindre end %1 sekunder.',
	'CommentAdded'				=> 'Kommentar tilføjet.',
	'YouAreNowTheOwner'			=> 'Du er nu ejer af denne side.',
	'PageSaved'					=> 'Side version %1 gemt.',
	'CommentSaved'				=> 'Kommentar gemt.',

	'RevisionsFor'				=> 'Revisioner for %1',
	'DefaultDiffMode'			=> 'Standard diff- tilstand',
	'DiffMode'		=> [
		'0'		=> 'Fuld diff',
		'1'		=> 'Simpel diff',
		'2'		=> 'Kilde',
		'3'		=> 'Side om side',
		'4'		=> 'Indlejret',
		'5'		=> 'Sammenflettet',
		'6'		=> 'Forenet',
		'7'		=> 'Kontekst',
	],

	'PreviousEdit'				=> 'Forrige redigering',
	'NextEdit'					=> 'Næste redigering',

	'Diff'						=> 'Diff',
	'PreviousVersion'			=> 'Tidligere revision',
	'LatestVersion'				=> 'Seneste revision',
	'NextVersion'				=> 'Næste revision',

	'ShowDifferencesButton'		=> 'Vis Forskelle',
	'CancelReturnButton'		=> 'Annuller og vend tilbage til siden',
	'Comparison'				=> 'Forskel mellem revisioner for %1',
	'RevisionAsOf'				=> 'Revision %1 fra',
	'SimpleDiffAdditions'		=> 'Tilføjelser:',
	'SimpleDiffDeletions'		=> 'Sletninger:',
	'NoDifferences'				=> 'Ingen forskelle.',
	'ReEditOldRevision'			=> 'Genrediger denne gamle revision',

	'ExternalPages'				=> 'Eksterne sider, der linker til %1 (%2) (<a href="%3">se liste over domæner</a>):',
	'ExternalPagesGlobal'		=> 'Websteder, der linker til denne WackoWiki (%2) (<a href="%1">se liste over domæner</a>):',
	'Last24Hours'				=> 'seneste 24 timer',
	'LastDays'					=> 'seneste %1 dage',
	'DomainsSitesPages'			=> 'Domæner/sider der linker til  %1 (%2) (<a href="%3">se listen over forskellige URL\'er</a>):',
	'DomainsSitesPagesGlobal'	=> 'Domæner/websteder, der linker til denne WackoWiki (<a href="%1">se liste over forskellige URL\'er</a>):',
	'ViewReferrersPage'			=> 'til side',
	'ViewReferrersPerPage'		=> 'pr. side',
	'ViewReferrersByTime'		=> 'efter tid',
	'ViewReferrersGlobal'		=> 'global',
	'NoneReferrers'				=> 'Ingen',
	'NotOwnerCantDelete'		=> 'Du er ikke ejer af denne side og kan ikke slette den',

	// remove
	'RemovePage'				=> 'Fjern side',
	'RemoveRevision'			=> 'Fjern revision',
	'RemoveComment'				=> 'Slet kommentar',
	'RemoveCluster'				=> 'Fjern alle sider i klyngen',
	'RemoveDontKeep'			=> 'Gem ikke en kopi af en fjernet side og kommentarer',
	'RemoveDontKeepRevision'	=> 'Gem ikke en kopi af den fjernede revision',
	'RemoveDontKeepComment'		=> 'Gem ikke en kopi af den fjernede kommentar',
	'RemoveDontKeepFile'		=> 'Gem ikke en kopi af den fjernede fil',
	'ReferrersRemoved'			=> 'Henvisere fjernet.',
	'LinksRemoved'				=> 'Links fjernet.',
	'CategoriesRemoved'			=> 'Sider kategorier slettet.',
	'AclsRemoved'				=> 'Side acls fjernet.',
	'BookmarksRemoved'			=> 'Bogmærker fjernet.',
	'WatchesRemoved'			=> 'Ure fjernet.',
	'CommentsRemoved'			=> 'Kommentarer fra siden fjernet.',
	'FilesRemoved'				=> 'Filer fra siden fjernet.',
	'PageRemoved'				=> 'Side fjernet.',
	'PageCachePurged'			=> 'Cache udrenset.',
	'ClusterRemoved'			=> 'Alle sider i klyngen fjernet.',
	'RevisionRemoved'			=> 'Revision %1 fjernet.',
	'RevisionsRemoved'			=> 'Revisioner fjernet.',
	'ActionHaveNoUndo'			=> 'Denne handling kan ikke fortrydes.',

	// restore
	'PageRestored'				=> 'Side gendannet.',
	'RevisionRestored'			=> 'Revision genoprettet.',
	'LocalFilesRestored'		=> 'Lokale filer gendannet.',

	'PrintVersion'				=> 'Udskriv version',
	'PrintText'					=> 'Udskriv',
	'LinkedPages'				=> 'Linkede sider:',
	'NoLinkedPages'				=> 'Der er ingen linkede sider',
	'ReferringPages'			=> 'Henviste sider:',
	'NoReferringPages'			=> 'Der er ingen henvisende sider',
	'Footnotes'					=> 'Fodnoter:',
	'Footnote'					=> 'Fodnote',
	'MostPopularPages'			=> 'Mest populære sider',
	'MostCommentedPages'		=> 'Mest kommenterede sider',
	'NoAccessToSourcePage'		=> 'Du har ikke tilladelse til at læse handling kilde side.',
	'SourcePageDoesntExist'		=> 'Handling kilde side findes ikke endnu',
	'NotLoggedInThusEdited'		=> 'Du er ikke logget ind, derfor kunne vi ikke identificere de sider, du har redigeret.',
	'DidntEditAnyPage'			=> 'Du har ikke redigeret nogen sider endnu.',
	'NoPagesFound'				=> 'Ingen sider fundet.',
	'MyChangesTitle1'			=> 'Dette er listen over sider, du har redigeret, sorteret efter tidspunktet for din seneste ændring',
	'MyChangesTitle2'			=> 'Dette er listen over sider, du har redigeret, sammen med tidspunktet for din sidste ændring',
	'OrderABC'					=> 'alfabetisk',
	'OrderCreation'				=> 'ved oprettelse',
	'OrderChange'				=> 'ved ændring',
	'ListOwnedPages'			=> 'Dette er listen over sider du ejer (sorteret alfabetisk)',
	'ListOwnedPages2'			=> 'Dette er listen over sider du ejer (sorteret efter dato)',
	'ListOwnedPages3'			=> 'Dette er listen over sider du ejer (sorteret efter ændring)',
	'NotLoggedInThusOwned'		=> 'Du er ikke logget ind, derfor kunne vi ikke hente dine sider.',
	'NoOrphaned'				=> 'Ingen forældreløse sider. Godt.',
	'NoRecentComments'			=> 'Ingen seneste kommentarer.',
	'LatestCommentBy'			=> 'seneste kommentar af',
	'NoRecentlyCommented'		=> 'Ingen nyligt kommenterede side.',
	'NoDeletedPages'			=> 'Ingen slettede sider fundet.',
	'NoDeletedRevisions'		=> 'Ingen slettede revisioner fundet.',
	'NoDeletedFiles'			=> 'Ingen slettede filer fundet.',
	'CommentsDisabled'			=> 'Kommentarer er ikke tilgængelige.',

	'SearchResults'				=> 'Søgeresultater for ',
	'NotFound'					=> 'ikke fundet',
	'NoResultsFor'				=> 'Ingen resultater for ',
	'SearchFor'					=> 'Søg efter:',
	'TopicSearchResults'		=> 'Emner søgeresultater for ',
	'NotFoundInTopics'			=> 'ikke fundet i emner',
	'FilterLangNotAvailable'	=> 'Det valgte sprog er ikke tilgængelig!',

	'PostedBy'					=> 'postet af',
	'ThisIsCommentOn'			=> 'Dette er en kommentar på',
	'At'						=> 'på',
	'To'						=> 'til',
	'By'						=> 'af',
	'From'						=> 'fra',
	'For'						=> 'til',
	'ReturnToCommented'			=> 'Returnér til kommenteret side',
	'AbandonedComment'			=> 'Den side, som denne kommentar hører til, eksisterer ikke længere!',

	'PagesLinkingTo'			=> 'Sider, der forbinder til',
	'NoPageLinkingTo'			=> 'Ingen side linker til',
	'NoWantedPages'				=> 'Ingen ønskede sider. Godt.',
	'RemoveWatch'				=> 'Fjern ur for denne side',
	'SetWatch'					=> 'Se denne side',
	'WatchText'					=> 'Se',
	'UnwatchText'				=> 'Følg ikke',
	'UserSettingsStored'		=> 'Brugerindstillinger gemt.',
	'LoggedOut'					=> 'Du er nu logget ud.',
	'LoggedOutAuto'				=> 'For sikkerhed, din session er afsluttet. Log venligst ind igen.',

	// user settings
	'EmailConfirmResent'		=> 'E-mail bekræftelseskode sendes tilbage til din adresse.',
	'EmailConfirmNotSent'		=> 'Kan ikke sende bekræftelseskoden. E-mailen er ikke angivet!',
	'Hello'						=> 'Hej',
	'UserName'					=> 'Bruger navn',
	'EmailAddress'				=> 'E-mail adresse',
	'RealName'					=> 'Rigtigt navn',
	'MenuItemsShown'			=> 'Menupunkter vist',
	'RecordsPerPage'			=> 'Poster pr. side',
	'DoShowComments'			=> 'Vis kommentarer som standard',
	'DoubleclickEditing'		=> 'Dobbeltklik Redigering',
	'UpdateSettingsButton'		=> 'Opdater Indstillinger',

	'AccountDisabled'			=> 'Din konto kan være deaktiveret eller blokeret.',
	'WrongPassword'				=> 'Forkert adgangskode!',
	'ConfirmPassword'			=> 'Bekræft adgangskode',
	'Email'						=> 'E-mail adresse',
	'MustBeWikiName'			=> 'Brugernavn skal være <a href="https://wackowiki.org/doc/Doc/English/WikiName" target="_blank">WikiName</a> formateret!',
	'SpecifyEmail'				=> 'Du skal angive en e-mail adresse.',
	'NotAEmail'					=> 'Det ligner ikke en gyldig e-mail-adresse.',
	'EmailTaken'				=> 'Den indtastede e-mail adresse er allerede i brug.',
	'EmailDomainNotAllowed'		=> 'Den indtastede e-mail-adresse %1 er ikke i tilladte domæner liste.',
	'PasswordsDidntMatch'		=> 'Adgangskoder matcher ikke.',
	'SpacesArentAllowed'		=> 'Mellemrum er ikke tilladt i adgangskoder.',
	'ListMyPages'				=> 'Liste over dine sider',
	'ListMyChanges'				=> 'List dine ændringer',
	'ListMyWatches'				=> 'Liste over sete sider',
	'ListMyChangesWatches'		=> 'Ændringer blandt sete sider',
	'SeeListOfPages'			=> 'Se en liste over sider, du ejer (MyPages) og sider, du har redigeret (MyChanges).',
	'AddBookmark'				=> 'Tilføj aktuel side til bogmærker',
	'RemoveBookmark'			=> 'Fjern fra bogmærker',

	'YourLanguage'				=> 'Vælg sprog',
	'ShowSpaces'				=> 'Vis mellemrum i WikiNames',
	'WrongPage4Redirect'		=> 'Kan ikke omdirigere på grund af forkert omdirigeringsparameter',
	'RedirectsToItself'			=> 'Siden omdirigerer til sig selv.',
	'ReallyDeletePage'			=> 'Vil du virkelig slette denne side?<br>Der er ingen fortryd for denne handling!<br><br>ADVARSEL: Sletning af denne side vil slette alle sideversioner, kommentarer, vedhæftede filer, ACL og henvisninger.',
	'CommentForWatchedPage'		=> 'Ny kommentar til siden ',
	'SomeoneCommented'			=> ' kommenterede denne side, som du kigger: ',
	'AlertReferringPages'		=> 'Denne side henvises til af disse sider',

	'AccountDelete'				=> 'Slet konto',
	'AccountDeleteConfirm'		=> 'Er du sikker på, at du vil slette denne konto?',
	'AccountDeleted'			=> 'Konto blev slettet',
	'AccountDeleteHeader'		=> 'Slet konto %1',
	'AccountDeleteInfo'			=> 'Af de data, du har oprettet (f.eks. e-mail, præferencer, vedhæftede filer, wikiposter) så meget som muligt vil blive slettet. Bemærk, dog, at data som vedhæftede filer og wiki poster kan ikke slettes uden at hæmme de andre brugeres arbejde. Sådanne data er derfor genoprettet til en konto kaldet %1. Da dataene for hver slettet konto bliver overført til denne konto, vil det ikke være muligt at skelne de data, du har oprettet, fra data fra en anden slettet konto.',
	'AccountDeleteWarning'		=> 'Sletning af brugerkontoen er en uigenkaldelig handling.',
	'AccountDeleteHint'			=> 'Din konto vil blive slettet fra systemet. Derfor vil du ikke længere kunne logge ind med dine aktuelle legitimationsoplysninger. Hvis du vælger at blive bruger af dette program igen, kan du gøre det ved hjælp af de midler, dette program giver.',
	'AccountDeleteVerify'		=> 'Indtast dit login %1 for at bekræfte sletningen. Når du er indsendt, vil du blive bedt om at bekræfte din adgangskode.',

	'MarkRead'					=> 'Markér alle som læst',
	'CurrentTime'				=> 'Det er i øjeblikket',
	'Created'					=> 'oprettet',
	'Modified'					=> 'ændret',

	'EditIcon'					=> 'rediger',
	'TreeClusterTitle'			=> 'Træ af klynge %1',
	'TreeSiteTitle'				=> 'Sted træ',
	'TreeEmpty'					=> '%1 har ingen undersider',
	'TreeEmptyLevels'			=> '%1 har ingen undersider for givne niveauer af dybde. Øg værdien for dybde.',
	'TreeTooBig'				=> 'for mange undersider',

	// clone handler
	'ClonePage'					=> 'Klon side',
	'CloneText'					=> 'Klon',
	'CloneName'					=> 'Indtast nyt navn for en klon af denne side',
	'CloneButton'				=> 'Klon',
	'PageCloned'				=> 'Side %1 klonet.',
	'ClonedFrom'				=> 'Klonet fra %1.',
	'MassClone'					=> 'Klon hele klynge',
	'MassCloning'				=> 'Kloning klynge.',
	'CloneCannotRead'			=> 'Ulæselig side %1.',
	'CloneCannotCreate'			=> 'Uncreatable page %1.',

	'SortComment'				=> 'Sorter kommentarer efter',
	'SortCommentAsc'			=> 'Seneste nederst',
	'SortCommentDesc'			=> 'Seneste øverst',

	'RenamePage'				=> 'Omdøb side',
	'RenameText'				=> 'Omdøb',
	'RenameTip'					=> 'Omdøb side',
	'NewName'					=> 'Indtast nyt navn for denne side',
	'AlreadyExists'				=> 'Side %1 findes allerede.',
	'AlreadyNamed'				=> 'Denne side hedder allerede %1.',
	'PageRenamed'				=> 'Side omdøbt.',
	'NewNameOfPage'				=> 'Nyt navn på denne side: ',
	'NotOwnerCantRename'		=> 'Du er ikke ejer af denne side og kan derfor ikke omdøbe den',
	'NeedRedirect'				=> 'Opret omdirigering til den nye side på den gamle side',
	'RedirectCreated'			=> 'På siden %1 oprettet omdirigering til den nye',

	'UserSettings'				=> 'Bruger indstillinger',
	'UserSettingsGeneral'		=> 'Generelt',
	'UserSettingsNotifications'	=> 'Notifikationer',

	'NotifyMinorEdit'			=> 'Underret også mindre redigering',
	'NotifyPageEdit'			=> 'Rediger',
	'NotifyComment'				=> 'Kommentar',
	'NotifyOff'					=> 'Fra',
	'NotifyAlways'				=> 'Altid',
	'NotifyPending'				=> 'Afventer',
	'NotifyDigest'				=> 'Digest',
	'NotifyPendingPageTip'		=> 'Kun én notifikation sendes for den første side ændring af en side, du ser.',
	'NotifyPendingCommentTip'	=> 'Kun én notifikation sendes for den første kommentar til en side, du ser.',
	'NotifyPendingTip'			=> 'Notifikation aktiveres automatisk, når du besøger den aktuelle version af siden.',

	'FurtherPending'			=> 'Der vil ikke være andre notifikationer i tilfælde af yderligere ændringer, medmindre du besøger denne side.',

	'UserSettingsEmailMe'		=> 'Email mig når ...',

	'UserSettingsExtended'		=> 'Udvidet',
	'UserSettingsOther'			=> 'Andre indstillinger',
	'UserSpace'					=> 'Bruger plads',
	'ChooseTheme'				=> 'Vælg tema',

	'CreatePage'				=> 'Opret denne side',
	'CreateNewPage'				=> 'Opret en ny side',
	'CreateNewPageText'			=> 'Opret',
	'CreateNewPageTip'			=> 'Opret en ny side',

	'CreateRandomPage'			=> 'Opret en tilfældig side:',
	'CreateSubPage'				=> 'Opret en underside i klyngen:',
	'CreatePageParentCluster'	=> 'Opret en side i den overordnede klynge:',
	'CreatePageDenied'			=> 'Du har ikke de nødvendige adgangsrettigheder.',
	'CreatePageDeniedAddress'	=> 'Du har ikke ret til at oprette siden på denne adresse.',
	'PageAlreadyExists'			=> 'Ifølge adressen findes siden %1 allerede.',
	'PageAlreadyExistsEdit'		=> 'Ønsker du %1 det?',
	'PageAlreadyExistsEdit2'	=> 'rediger',
	'PageAlreadyExistsEditDenied'	=> 'Du kan ikke redigere det.',

	'SimilarPagesExists'		=> 'Lignende sider til %1 findes allerede:',
	'SimilarPagesHint'			=> 'Der findes lignende sider til %1:',

	'PageReservedWord'			=> 'Du kan ikke bruge %1 som en del af adressen, da det er et reserveret ord.',
	'UserReservedWord'			=> 'Brugernavne kan ikke indeholde %1 , da det er et reserveret ord.',

	'DontRedirect'				=> 'Tillad ikke automatisk omdirigering ved handling omdirigering.',
	'SendWatchEmail'			=> 'Send notifikationsmail, når nogen (bortset fra dig) ændrer en side, du ser',
	'AllowIntercom'				=> 'Tillad personlige beskeder fra brugere af systemet',
	'AllowMassemail'			=> 'Administratorer kan e-maile mig information',
	'HideLastSession'			=> 'Skjul seneste session',
	'ValidateIP'				=> 'Tying session til IP',
	'AnonymousPub'				=> 'Fortrinsvis publiceret anonymt (for at skjule navnet)',
	'PageMoved'					=> 'Denne side er flyttet. Du kan finde den på',
	'RedirectedFrom'			=> 'Omdirigeret fra %1',
	'RedirectedTo'				=> 'Omdirigeret til',
	'CurrentPassword'			=> 'Nuværende adgangskode',
	'NewPassword'				=> 'Ny adgangskode',
	'YouWantChangePassword'		=> 'Skift adgangskode',
	'ChangePasswordButton'		=> 'Skift adgangskode',
	'PasswordChanged'			=> 'Adgangskode ændret',
	'EmailWelcome'				=> 'Du har registreret dig på ',
	'EmailRegistered'			=> 'Du har registreret dig hos %1.' . "\n" . 'Dit brugernavn: %2' . "\n\n",
	'EmailVerify'				=> 'Hvis du ønsker at modtage meddelelser, skal du bekræfte din e-mailadresse. Klik venligst på eller kopier følgende link til en webbrowser: ' . "\n" . '%1',
	'EmailRegisteredLogin'		=> 'Gå tilbage til Wiki og log ind med dit nye brugernavn og adgangskode.',
	'EmailRegisteredIgnore'		=> 'Hvis du ikke har anmodet om denne registrering, så ignorér denne besked, og intet vil ske.',
	'EmailDoNotReply'			=> 'Svar ikke på denne besked.',
	'EmailReverify'				=> 'Nogen (måske dig) indsendte din e-mail som notifikationsadresse på %1.' . "\n" . 'Dit brugernavn: %2'."\n\n" . 'Hvis du ønsker at modtage notifikationer, skal du godkende din e-mail. Følg linket for at gøre dette.' . "\n" . '%3' . "\n\n",
	'EmailConfirm'				=> 'Bekræft venligst din e-mail',
	'EmailConfirmed'			=> 'E-mail bekræftet.',
	'EmailNotConfirmed'			=> 'E-mail kan ikke bekræftes. Dette kan skyldes en forkert bekræftelseskode, eller e-mail-adressen kan allerede bekræftes. Du kan kontrollere, om e-mailadressen allerede er bekræftet ved at logge ind og se dens status på din %1 side.',
	'EmailNotVerified'			=> 'E-mail ikke bekræftet!',
	'EmailNotVerifiedDesc'		=> 'Du vil ikke modtage notifikation om ændringer eller kommentarer på sete sider, ' .
									'eller beskeder fra andre brugere. Du <strong>vil heller ikke være i stand til at gendanne en glemt adgangskode</strong>, ' .
									'indtil din e-mail-adresse bekræftes ved at følge linket i den e-mail, der sendes til dig. ' .
									'Hvis du inden for dage efter registreringen ikke modtager en e-mail, beder om det igen ved at klikke ',

	'ForgotPasswordHint'		=> 'Indtast din login- og e-mailadresse,' . "\n" . 'så en e-mail med instruktioner vil blive sendt til dig.',
	'ForgotPassword'			=> 'Glemt adgangskode?',
	'UserNotFound'				=> 'Bruger med dette navn eller e-mail adresse blev ikke fundet.',
	'NotConfirmedEmail'			=> 'Din e-mailadresse er ikke bekræftet.<br>Mail kan ikke sendes til en ikke-bekræftet adresse.',
	'EmailForgotSubject'		=> 'Adgangskode fornyelse for ',
	'EmailForgotMessage'		=> 'Nogen (måske dig) har glemt din adgangskode til %1.' . "\n" . 'Dit login: %2'."\n\n" . 'Klik på linket eller kopier det til browserens adresselinje for at ændre din adgangskode.' . "\n" . '%3'."\n\n",
	'CodeWasSent'				=> 'Adgangskodegendannelsesinstruktion blev sendt til dig via e-mail.',
	'WrongCode'					=> 'Forkert kode',
	'ChangePasswordForUser'		=> '%1\'s adgangskode ændring',

	'Watchers'					=> 'Liste over iagttagere for %1',
	'WatchersFor'				=> 'Overvågere til',
	'NoWatchers'				=> 'Der er ingen iagttagere for %1',
	'NotOwnerToViewWatchers'	=> 'Du er ikke ejeren af denne side, og du kan ikke se listen over overvågere for den.',

	// thumbnail
	'TbnError'					=> 'Fejl ved oprettelse af miniature: %1',
	'TbnImageAreaTooBig'		=> 'Fil med dimensioner større end %1',
	'TbnImageMissing'			=> 'Filen synes at mangle: %1',

	// admin_recovery action
	'GenerateRecoveryHash'		=> 'Generer adgangskodehash til din <code>recovery_password</code>',

	// import action
	'ImportTo'					=> 'Importer i klynge:',
	'ImportWhat'				=> 'XML- fil at importere:',
	'ImportButton'				=> 'Importér',
	'ImportSuccess'				=> 'Importeret med succes.',
	'ImportFailed'				=> 'IMPORT mislykkedes.',
	'ImportHint'				=> 'Angiv venligst en klynge, du ønsker at importere til, ingen relativ adressering.',
	'ImportAttention'			=> 'Opmærksomhed: Overskriver de samme sider i klyngen.',
	'ImportNote'				=> 'Importeret side',

	// mywatches action
	'WatchedPages'				=> 'Liste over alle sider du følger for ændringer ',
	'UnwatchedPages'			=> 'Liste over alle sider du ikke ser',
	'NoWatchedPages'			=> 'Du har ingen sete sider.',
	'NoUnwatchedPages'			=> 'Du overvåger for ændringer på alle sider.',
	'ViewWatchedPages'			=> 'Vis sete sider',
	'ViewUnwatchedPages'		=> 'Vis side som ikke ses',
	'NotLoggedInWatches'		=> 'Du er ikke logget ind, derfor kunne vi ikke identificere din liste over ure.',

	// mychangeswatches action
	'MyChangesWatches'			=> 'Liste over alle sider du så der blev redigeret af andre siden din seneste redigering',
	'ResetChangesWatches'		=> 'nulstil listen over ændringer',
	'NoChangesWatches'			=> 'Blandt dine sete sider er ingen ændringer...',

	// whatsnew action
	'NewCommentAdded'			=> 'Tilføjet ny kommentar',
	'NewFileAdded'				=> 'Tilføjet ny fil',
	'NewPageCreated'			=> 'Oprettede en ny side',
	'NewRevisionAdded'			=> 'Ændret side',
	'Cluster'					=> 'klynge',
	'PageDeleted'				=> 'Side slettet',
	'CommentDeleted'			=> 'Kommentar slettet',
	'FileDeleted'				=> 'Fil slettet',

	// users action
	'UsersSearch'				=> 'Find Brugere',
	'UsersOpenProfile'			=> 'Vis Profil',
	'UsersNoMatching'			=> 'Matchende brugere ikke fundet. Prøv et mindre strengt søgekriterium.',
	'UsersName'					=> 'Navn',
	'UsersPages'				=> 'Sider',
	'UsersChanges'				=> 'Ændringer',
	'UsersSubscription'			=> 'Abonnement',
	'UsersWatches'				=> 'Ure',
	'UsersComments'				=> 'Kommentarer',
	'UsersUploads'				=> 'Uploads',
	'UploadQuota'				=> 'Brugt plads',
	'UploadQuotaTip'			=> 'Upload Rumkvote',
	'UsersLogins'				=> 'Logins',
	'UsersRevisions'			=> 'Revisioner',
	'UsersSignup'				=> 'Tilmelding',
	'UsersLastSession'			=> 'Seneste session',
	'UsersNotFound'				=> 'Bruger %2 blev ikke fundet. Klik på <a href="%1">her</a>for at gå til hovedlisten.',
	'UsersProfile'				=> 'Profil',
	'UsersContact'				=> 'Kontakt',
	'UsersList'					=> 'Se hele listen over brugere',
	'UsersNA'					=> '[ikke angivet]',
	'UsersNA2'					=> '[No]',
	'UsersSignupDate'			=> 'Tilmeldings dato',
	'UsersGroupMembership'		=> 'Gruppe medlemskab',
	'UsersPersonalInfo'			=> 'Personlig info',
	'UsersOwnedPages'			=> 'Ejede sider:',
	'UsersCommentsPosted'		=> 'Kommentarer indsendt:',
	'UsersFilesUploaded'		=> 'Filer uploadet:',
	'UsersRevisionsMade'		=> 'Revisioner foretaget:',
	'UsersDocsSortName'			=> '[Sorter efter navn]',
	'UsersDocsSortCreation'		=> '[Sorter efter oprettelsesdato]',
	'UsersChangesSortAsc'		=> '[Sorter stigende]',
	'UsersChangesSortDesc'		=> '[Sorter faldende]',
	'UsersSessionNA'			=> '[ikke registreret]',
	'UsersSessionHidden'		=> '[hidden]',
	'IntercomSubject'			=> 'Emne:',
	'IntercomMessage'			=> 'Besked:',
	'IntercomCopy'				=> 'Send mig en kopi',
	'IntercomSubjectN'			=> '[start et nyt emne]',
	'IntercomDisabled'			=> 'Beklager, du ønsker ikke, eller kan ikke modtage personlige beskeder.',
	'IntercomHint'				=> 'Log venligst ind først og følg linket igen, hvis du ønsker at besvare den personlige besked, du har modtaget.',
	'IntercomDesc'				=> 'Bemærk: Afsendelse af personlige beskeder, der medbringes på e-mailmodtageren uden at afsløre din adresse. Modtageren vil være i stand til at svare dig ved hjælp af en lignende formular på din profilside. ',
	'PMOversized'				=> 'Længden af beskeden overstiger den maksimale tilladte størrelse med %1. Forkort din besked og send igen.',
	'PMFlooded'					=> 'Intervallet mellem afsendelse af personlige beskeder bør ikke være mindre end %1 sekunder.',
	'PMSent'					=> 'Personlig besked blev sendt til brugeren.',
	'PMBody'					=> 'Denne besked er blevet sendt til dig af brugeren %1.',
	'PMBodyCopy'				=> 'Du har sendt følgende besked til brugeren %1.',
	'PMReply'					=> 'For at besvare denne e-mail, klik på følgende link (brug ikke knappen Svar / Svar i mailer):',
	'PMNotLoggedIn'				=> 'Du er ikke registreret i systemet og kan ikke sende personlige beskeder til brugere.',

	// admin_replace action
	'ReplaceText'				=> 'Erstat tekst',
	'TextOriginal'				=> 'Oprindelig tekst:',
	'TextReplacement'			=> 'Erstatnings tekst:',
	'ReplaceTextRegex'			=> 'Brug regulære udtryk',
	'Namespace'					=> 'Namespace:',
	'ReplaceTextCluster'		=> 'Søg og erstat kun i denne klynge:',
	'ReplaceTextEditPages'		=> 'Erstat tekst i sideindhold',
	'ReplaceTextEditComments'	=> 'Erstat tekst i kommentarer',
	'ReplaceTextEditTitles'		=> 'Erstat tekst i sidetitler',
	'ReplaceTextGiveTarget'		=> 'Du skal angive den streng, der skal erstattes.',
	'ReplaceTextNoNamespace'	=> 'Du skal vælge mindst et navneområde.',
	'ReplaceTextNoDifference'	=> 'Der er ingen forskel på erstatningstekst og måltekst.',
	'ReplaceTextNoOption'		=> 'Du skal vælge mindst en af erstatningsmulighederne.',
	'ReplaceTextPagesEdit'		=> 'Erstat %1 med %2 i teksten på følgende %3 sider:',
	'ReplaceTextTitlesEdit'		=> 'Erstat %1 med %2 i titlerne på følgende %3 sider:',
	'ReplaceTextReplace'		=> 'Erstat',
	'ReplaceTextSuccess'		=> '%1 er blevet erstattet med %2 på %3 sider.',
	'ReplaceTextNoMatch'		=> 'Der blev ikke fundet sider der indeholder strengen %1.',
	'ReplaceTextNoTitleMatch'	=> 'Ingen sider blev fundet hvilken titel der indeholder %1.',
	'ReplaceTextEditFailed'		=> 'Erstatning af tekst mislykkedes',
	'ReplaceTextTitleTooBig'	=> 'Oprindelig eller erstatningstekst er for stor til titel.',
	'ReplaceTextReturn'			=> 'Tilbage til formularen',
	'ReplaceTextWarning'		=> 'Advarsel: Der er %1 sider, der allerede indeholder erstatningsstrengen, %2. Hvis du laver denne erstatning, vil du ikke være i stand til at adskille dine erstatninger fra disse strenge.',
	'ReplaceTextBlankWarning'	=> 'Advarsel: Da erstatningsstrengen er tom, vil denne handling ikke være reversibel.',
	'ReplaceTextEditSummary'	=> 'Tekstudskiftning: %1 → %2',
	'InvertSelection'			=> 'Invertér valg',

	// Properties
	'PropertiesFor'				=> 'Side egenskaber for %1',
	'MetaTag'					=> 'Mærke',
	'MetaTitle'					=> 'Titel',
	'MetaKeywords'				=> 'Nøgleord',
	'MetaDescription'			=> 'Varebeskrivelse',
	'On'						=> 'Til',
	'Off'						=> 'Fra',
	'Registered'				=> 'Registreret',
	'MetaComments'				=> 'Vis kommentarer',
	'MetaFiles'					=> 'Vis filpanel',
	'MetaToc'					=> 'Vis indholdsfortegnelsen',
	'MetaIndex'					=> 'Vis klynge sektionspanel',
	'MetaIndexMode'				=> 'Vis Niveau Tilstand',
	'MetaIndexFull'				=> 'Træ',
	'MetaIndexUpper'			=> 'Øvre',
	'MetaIndexLower'			=> 'Lavere',
	'MetaHtml'					=> 'HTML understøttelse af side',
	'MetaSafeHtml'				=> 'Filtrering af usikker HTML',
	'MetaTypografica'			=> 'Typografisk Korrekturlæser',
	'MetaNoIndex'				=> 'Blokér søgemaskiner',
	'SettingsID'				=> 'Side ID',
	'SettingsSize'				=> 'Størrelse',
	'SettingsSizeTip'			=> 'kilde / kompileret',
	'SettingsCreated'			=> 'Oprettet',
	'SettingsCurrent'			=> 'Ændret',
	'SettingsTotalRevs'			=> 'Revisioner',
	'SettingsTotalComs'			=> 'Kommentarer',
	'SettingsWatchers'			=> 'Overvågere',
	'SettingsHits'				=> 'Visninger',
	'SettingsText'				=> 'Indstillinger',
	'SettingsEdit'				=> 'Rediger',
	'SettingsRevisions'			=> 'Revisioner',
	'SettingsClone'				=> 'Klon',
	'SettingsRename'			=> 'Omdøb',
	'MassRename'				=> 'for hele klyngen',
	'SettingsRemove'			=> 'Fjern',
	'SettingsPurge'				=> 'Purge',
	'SettingsModerate'			=> 'Moderat',
	'SettingsPermissions'		=> 'Rettigheder',
	'AclForEntireCluster'		=> 'for hele klyngen',
	'SettingsAttachments'		=> 'Vedhæftninger',
	'SettingsUpload'			=> 'Upload',
	'SettingsCategories'		=> 'Kategorier',
	'SettingsLanguages'			=> 'Sprog',
	'SettingsReferrers'			=> 'Henvisere',
	'SettingsWatch'				=> 'Se',
	'SettingsLatex'				=> 'Latex- version',
	'SettingsXML'				=> 'Eksporter til XML',
	'NeedToChangeLang'			=> 'Ikke understøttet side sprog %1 skal ændres.',
	'SetLang'					=> 'Sprog for denne side',
	'SetMenuLabel'				=> 'Menu etiket',
	'SetShowMenuLabel'			=> 'Vis i navigation',

	// upload
	'UploadFiles'				=> 'Upload filer',
	'UploadFor'					=> 'Fil upload:',
	'UploadButton'				=> 'Upload',
	'UploadGlobalText'			=> 'for offentlig adgang',
	'UploadGlobal'				=> 'global',
	'UploadLocalText'			=> 'kun for brugere der har tilladelse til at se nuværende side',
	'UploadAsName'				=> 'Navn:',
	'UploadOverwrite'			=> 'Overskriv eksisterende filer',
	'FileDesc'					=> 'Beskrivelse:',
	'UploadForbidden'			=> 'Du har ikke tilladelse til at uploade filer her.',
	'UploadOverwriteDenied'		=> 'Kun filejeren eller administratoren kan overskrive %1 -filen.',
	'UploadNoFile'				=> 'Der var ingen fil i form, af en eller anden grund.',
	'UploadMaxSizeReached'		=> 'Filstørrelse er over tilladt grænse!',
	'UploadDirNotWritable'		=> 'Filmappen er ikke skrivbar!',
	'UploadNotAPicture'			=> 'Billedoverførsler er kun tilladt. Hvad forsøger du at uploade?',
	'UploadEmptyExtension'		=> 'Filnavnet og endelsen kan ikke være tom.',
	'FilenameTooLong'			=> 'Filnavne må ikke være længere end 240 bytes.',
	'BannedFiletype'			=> '%1 er ikke en tilladt filtype.',
	'PermittedFiletype'			=> 'Tilladte filtyper:',
	'UploadMimeMismatch'		=> 'Filtype %1 matcher ikke den detekterede MIME-type for filen (%2).',
	'UploadBadMime'				=> 'Filer af MIME-typen %1 må ikke uploades.',
	'FileIsDuplicate'			=> 'Upload er en nøjagtig kopi af den aktuelle version.',
	'FileHasDuplicate'			=> 'Denne fil er en kopi af følgende filer:',

	'UploadMaxFileQuota'		=> 'Du har nået din upload grænse. Denne fil kan ikke uploades',
	'UploadDone'				=> 'Upload af fil lykkedes',
	'UploadFileForbidden'		=> 'Adgang til fil forbudt',
	'UploadTitle'				=> 'Filer tilgængelige fra denne side',
	'UploadTitleGlobal'			=> 'Filer tilgængelige fra hvor som helst',

	'UploadFile'				=> 'Upload',
	'UploadMax'					=> 'Ikke mere end ',
	'UploadUsedStorage'			=> 'Opbevaring i brug ',

	// attachments
	'Attachments'				=> 'Vedhæftninger',
	'Attachment'				=> 'Vedhæft',
	'AttachmentsToPage'			=> 'til side',
	'AttachmentsToCluster'		=> 'klynge',
	'AttachmentsByTime'			=> 'efter tid',
	'AttachmentsGlobal'			=> 'global',
	'AttachmentsAll'			=> 'alle',
	'AttachmentsLinked'			=> 'brugt',

	'FileViewProperties'		=> 'Vis',
	'FileViewPropertiesTip'		=> 'Se metadata for denne fil',
	'FileEditProperties'		=> 'Rediger',
	'FileEditPropertiesTip'		=> 'Rediger metadata for denne fil',
	'FileEditedMeta'			=> 'Opdaterede metadata for denne fil',
	'FileEditDenied'			=> 'Du har ikke tilladelse til at redigere denne fil',
	'FileLabel'					=> 'Etiket',
	'FileLabelTip'				=> 'Label denne fil',
	'FileRemove'				=> 'Fjern',
	'FileRemovedFromDB'			=> 'Fil fjernet fra database',
	'FileRemovedFromFS'			=> 'Fil slettet fra fysisk hosting',
	'FileRemovedFromFSError'	=> 'Det synes umuligt at slette filen!',
	'FileRemoveConfirm'			=> 'Vil du fjerne denne fil?',
	'FileRemoveDenied'			=> 'Du har ikke tilladelse til at fjerne denne fil',
	'FileNotFound'				=> 'Fil ikke fundet.',

	'FileSearch'				=> 'Find Fil',
	'UploadBy'					=> 'Uploadet af:',
	'FileAdded'					=> 'Tilføjet:',
	'FileModified'				=> 'Ændret:',
	'FileSize'					=> 'Størrelse:',
	'FileDimension'				=> 'Dimension:',
	'MimeType'					=> 'Mimetype:',
	'FileName'					=> 'Navn:',
	'FileCaption'				=> 'Billedtekst:',
	'FileAuthor'				=> 'Forfatter:',
	'FileSource'				=> 'Kilde:',
	'FileSourceUrl'				=> 'URL:',
	'FileAttachedTo'			=> 'Vedhæftet til:',
	'FileSyntax'				=> 'Syntaks:',
	'FileAbsolutePath'			=> 'absolut sti',
	'FileRelativePath'			=> 'relativ sti',
	'FileUsage'					=> 'Brug af fil:',
	'FileUsageText'				=> 'The following pages link to this file: (Automatic Copy)',
	'NoFileUsage'				=> 'Ingen sider link til denne fil.',

	'FileSortExt'				=> 'udvidelse',
	'FileSortName'				=> 'navn',
	'FileSortSize'				=> 'størrelse',
	'FileSortTime'				=> 'oprettet',

	'SortBy'					=> 'Sorter efter',
	'Ascending'					=> 'stigende',
	'Decending'					=> 'faldende',

	'Files0'					=> 'Vedhæft Filer',
	'Files1'					=> 'Vis filer (1 fil)',
	'FilesN'					=> 'Vis filer (%1 filer)',
	'Files'						=> 'Filer',
	'File'						=> 'Fil',
	'ShowFiles'					=> 'Vis filer / formular',
	'HideFiles'					=> 'Skjul filer / formular',
	'DoShowFiles'				=> 'Vis filer lister som standard',
	'NoAttachments'				=> 'Der er ingen vedhæftede filer at vise.',

	'RegistrationLang'			=> 'Dit sprog',
	'InvalidWikiName'			=> 'Valgt navn er ugyldigt',
	'InvalidUserName'			=> 'Valgte brugernavn er ugyldigt',
	'Bookmarks'					=> 'Bogmærker',
	'ReallyDeleteComment'		=> 'Vil du virkelig slette denne kommentar?<br>Der er ingen fortryd for denne handling!',
	'ReallyDeleteRevision'		=> 'Vil du virkelig slette denne revision?<br>Der er ingen fortryd for denne handling!',

	'RegistrationClosed'		=> 'Registrering er ikke tilgængelig her. Prøv at kontakte webstedsadministrator.',
	'AclAreYouSure'				=> 'Du vil ændre ACL på denne side og alle dens undersider. Fortsæt?',

	'BookmarkDeleteSelected'	=> 'Slet valgte',
	'BookmarkMark'				=> 'Markér',
	'BookmarkNumber'			=> 'Nej.',
	'BookmarkNone'				=> 'Du har ingen bogmærker.',
	'BookmarkTitle'				=> 'Bogmærke titel',
	'BookmarkPage'				=> 'Side',
	'BookmarkSaveChanges'		=> 'Gem ændringer',
	'BookmarksAddPage'			=> 'Angiv et bogmærke for den følgende side',
	'BookmarkAlreadyExists'		=> 'Bogmærket eksisterer allerede.',

	'PoweredBy'					=> 'Drevet af',

	'MassRenaming'				=> 'Omdøb hele klynge',
	'MassNewName'				=> 'Indtast nyt navn for denne klynge',
	'MassNeedRedirect'			=> 'Opret omdirigering til de nye sider på de gamle sider',

	// pagination
	'ToOverview'				=> 'Tilbage til oversigt',
	'Overview'					=> 'Oversigt',
	'ToThePage'					=> 'Til side:',
	'Next'						=> 'Næste',
	'Prev'						=> 'Forrige',
	'NextAcr'					=> 'Næste',
	'PrevAcr'					=> 'Forrige',
	'Back'						=> 'Tilbage',

	// filter
	'Filter'					=> 'Filtrer',
	'OptionalFilters'			=> 'Valgfrie filtre:',
	'Any'						=> 'Alle',

	// My Groups
	'UserGroups'				=> 'Grupper af brugere',
	'MyGroups'					=> 'Gruppe Associationer',
	'Group'						=> 'gruppe',
	'Groups'					=> 'grupper',

	// license action
	'DistributedUnder'			=> 'Materialet distribueres under',
	'AuthorsDisplayHint'		=> 'Listen over forfattere vil blive vist når siden gemmes.',
	'AnonymousUsers'			=> 'Anonyme brugere',
	'License'					=> 'Licens',
	'LicenseArray'				=> [
		'1'		=> 'Attribution-NoDerivater',
		'2'		=> 'Attribution-NonCommercial-ShareAlike',
		'3'		=> 'Attribution-IkkeKommercielle NoDerivater',
		'4'		=> 'Attribution-ShareAlike',
		'5'		=> 'Attribution-IkkeKommerciel',
		'6'		=> 'Tildeling',
		'7'		=> 'CC0 1.0 Universal',
		'8'		=> 'GNU Free Documentation Licens',
		'9'		=> 'Offentligt Domæne / Gratis Brug',
		'10'	=> 'Alle Rettigheder Forbeholdes',
	],
	'LicenseMeta'				=> [
		'1'		=> 'Offentligt domæne',
		'2'		=> 'Nogle rettigheder forbeholdt',
		'3'		=> 'Alle Rettigheder Forbeholdes',
	],

	// Cache
	'ClearCache'				=> 'Ryd cache',
	'CacheCleared'				=> 'Cache ryddet.',
	'ConfigCache'				=> 'Konfigurer cache',
	'FeedCache'					=> 'Feed cache',
	'PageCache'					=> 'Side cache',
	'SQLCache'					=> 'SQL cache',
	'TemplateCache'				=> 'Skabelon cache',
	'ThumbCache'				=> 'Thumbnail cache',

	// Embed
	'EmbedNoURL'				=> 'Angiv venligst en adresse på ressourcen med Parameter URL. (f.eks. {{embed url="https://example.com/embed/video.mp4"}} )',

	// Feed
	'FeedTitle'					=> 'Feed Titel',
	'FeedMulti'					=> 'Multi-Feed',
	'FeedNoURL'					=> 'Angiv venligst et feed med Parameter URL. (f.eks. {{feed url="https://example.com/feed.xml"}} )',
	'FeedError'					=> 'Kunne ikke indlæse eller parse feed',
	'FeedSource'				=> 'Kilde:',
	'FeedXMLTip'				=> '',

	// XML / RSS autodiscovery
	'ChangesXMLTitle'			=> ' - Seneste ændringer',
	'ChangesXML'				=> 'Seneste ændringer i ',
	'CommentsXMLTitle'			=> ' - Seneste kommentarer',
	'CommentsXML'				=> 'Seneste kommentarer til ',
	'NewsXMLTitle'				=> ' - Seneste nyheder',
	'NewsXML'					=> 'Seneste nyheder til ',
	'RevisionXMLTip'			=> 'Klik for at se seneste siderevisioner i XML-format.',
	'CommentsXMLTip'			=> 'Klik for at se de seneste kommentarer i XML-format.',
	'ChangesXMLTip'				=> 'Klik for at se de seneste ændringer i XML-format.',
	'NewsXMLTip'				=> 'Klik for at se de seneste nyheder i XML-format.',
	'RevisionsXML'				=> 'Revisioner af ',
	'ExportClusterXML'			=> 'Eksport af hele klynger af ',
	'AccessDeniedXML'			=> 'Du har ikke adgang til disse oplysninger.',

	'ChangesFeed'				=> 'Ændringer',
	'CommentsFeed'				=> 'Kommentarer',
	'NewsFeed'					=> 'Nyheder',
	'RevisionsFeed'				=> 'Revisioner af ',

	'LastModification'			=> 'Sidste Ændring',

	// Captcha
	'Captcha'					=> 'Skriv venligst det ord, du læste i billedet',
	'CaptchaFailed'				=> 'Du har indtastet captcha ordet forkert. Prøv venligst igen.',
	'CaptchaReload'				=> 'Ny Captcha',
	'CaptchaReloadWarning'		=> 'Beklager, kan ikke genindlæse captcha billedet, du skal genindlæse siden for at gøre det',

	// news
	'News'						=> 'Nyheder',
	'NewsName'					=> 'Titel:',
	'NewsNoName'				=> 'Du har glemt at tilføje nyhedsoverskrift.',
	'NewsNotAvailable'			=> 'Ingen nyheder tilgængelige.',
	'NewsNoClusterDefined'		=> 'Ingen nyhedsklynge defineret.',
	'NewsDiscuss'				=> 'Diskuter denne artikel...',

	// blog
	'BlogNewTopic'				=> 'Opret et nyt indlæg',
	'NoPostAvailable'			=> 'Intet indlæg tilgængeligt endnu.',

	// Review
	'Reviewer'					=> 'Tester',
	'Reviewed'					=> 'revideret',
	'Review'					=> 'gennemgang',
	'ReviewedBy'				=> 'gennemgået af',
	'RemoveReview'				=> 'Fjern gennemgang for denne side',
	'SetReview'					=> 'Gennemgik denne side',
	'SetAsReviewed'				=> 'Angiv side som revideret',
	'SetAsUnreviewed'			=> 'Angiv side som ikke revideret',

	// word filter
	'PotentialSpam'				=> 'Identificeret Potentiel Spam',

	// moderation handler
	'Moderation'				=> 'Moderation',
	'Topics'					=> 'emner',
	'ModerateSection'			=> 'sektion / side ',

	'NotModerator'				=> 'Du har ikke autoritet til at moderere denne side / kapitel',
	'ModerateDeleteTopic'		=> 'Slet emne / side',
	'ModerateDeletePosts'		=> 'Slet kommentarer',
	'ModerateMove'				=> 'Flyt',
	'ModerateSplit'				=> 'Opdel / flyt kommentarer',
	'ModerateMerge'				=> 'Flet',
	'ModerateLock'				=> 'Lås',
	'ModerateUnlock'			=> 'Oplås',
	'ModerateAccept'			=> 'Accepter',
	'ModerateDeleteConfirm'		=> 'Er du sikker på du vil <strong>fjerne</strong> følgende emner?',
	'ModerateRenameConfirm'		=> 'Angiv en ny titel for den valgte side',
	'ModerateRenameExists'		=> 'Side med samme navn findes allerede! Vælg et andet navn.',
	'ModerateRename1Only'		=> 'Bemærk: Kun den første side du valgte vil blive omdøbt!',
	'ModerateMovesConfirm'		=> 'Vælg målpartitionen for at flytte forummet til',
	'ModerateMoveConfirm'		=> 'Vælg forummet eller angiv klyngen for at flytte disse emner. For at flytte en side til roden af webstedet, skriv &quot;/&quot;',
	'ModeratePgMoveConfirm'		=> 'Angiv navnet på klyngen hvor siden skal placeres. For at flytte en side til roden af webstedet, skriv &quot;/&quot;',
	'ModerateMoveExists'		=> 'Handling afbrudt: I denne sektion findes allerede emner med samme navn %1. Hvis du stadig har brug for at overføre ovennævnte emner, bedes du først omdøbe dem.',
	'ModerateMoveNotExists'		=> 'Siden / klynge findes ikke. Kontroller navnet og prøv igen.',
	'ModerateMergeConfirm'		=> 'Vælg et emne, som skal kombinere de resterende',
	'ModerateMerge2Min'			=> 'For at deltage skal du vælge mindst to emner!',
	'ModerateComDelConfirm'		=> 'Er du sikker på du vil <strong>fjerne</strong> %1 %2?',
	'ModerateComment'			=> 'Kommentar',
	'ModerateComments'			=> 'Kommentarer',
	'ModerateSplitNewName'		=> 'Angiv et navn til et emne der kan adskilles, og vælg et adskillelsesskema',
	'ModerateSplitPageName'		=> 'Indtast navnet på siden / emnet, hvor der skal flyttes aftagelige kommentarer, og vælg et separationsskema',
	'ModerateSplitAllAfter'		=> 'Frigør alle kommentarer efter den første valgte (og inklusive)',
	'ModerateSplitSelected'		=> 'Separerede kun valgte kommentarer (i alt %1)',
	'ModerateUserProfile'		=> 'profil',
	'ModerateNoItemChosen'		=> 'Vælg venligst mindst et element via knappen Indstil.',

	'ModerateSection2'			=> 'moderat sektion',
	'ModerateTopicsDeleted'		=> 'Valgte emner blev slettet.',
	'ModerateTopicsRelocated'	=> 'Valgte emner blev relokeret.',
	'ModerateTopicsRenamed'		=> 'Emne omdøbt.',
	'ModerateTopicsMerged'		=> 'Valgte emner blev sammenflettet.',
	'ModerateTopicsBlocked'		=> 'Valgte emner blokeret succesfuldt',
	'ModerateTopicsUnlocked'	=> 'Valgte emner låst op.',
	'ModerateTopicDeleted'		=> 'Emnet er blevet fjernet.',
	'ModeratePageMoved'			=> 'Siden blev flyttet.',
	'ModerateTopicRenamed'		=> 'Emne omdøbt.',
	'ModerateTopicBlocked'		=> 'Emnet blev blokeret',
	'ModerateTopicUnlocked'		=> 'Emnet låst op.',
	'ModerateCommentsDeleted'	=> 'Valgte kommentarer blev slettet.',
	'ModerateCommentsSplit'		=> 'Valgte kommentarer adskilt i et nyt emne.',
	'ModerateCommentsSplitFailed'	=> 'Bemærk: Af en eller anden grund mislykkedes det at adskille de valgte kommentarer til et nyt emne.<br>Normalt skulle dette ikke ske, så kontakt venligst webstedets administrator.<br>Som en sikkerhedsforanstaltning er problemet blevet bevaret i sin oprindelige form.',
	'ModerateCommentsMoved'		=> 'Valgte kommentarer migreret til den givne side.',

	// forum
	'ForumSubforums'			=> 'Forum',
	'ForumTopic'				=> 'Emne',
	'ForumTopics'				=> 'Emner',
	'ForumPosts'				=> 'Indlæg',
	'ForumReplies'				=> 'Svar',
	'ForumAuthor'				=> 'Forfatter',
	'ForumViews'				=> 'Visninger',
	'ForumCreated'				=> 'Oprettet',
	'ForumComments'				=> 'Kommentarer',
	'ForumLastComment'			=> 'Seneste kommentar',
	'ForumNoComments'			=> 'Ingen kommentarer',
	'ForumNoTopics'				=> 'Der er ingen emner eller indlæg i dette forum.',
	'ForumNewTopic'				=> 'Start en ny diskussion',
	'ForumTopicName'			=> 'Emne navn:',
	'ForumTopicSubmit'			=> 'Indsend emne',
	'ForumNoTopicName'			=> 'Angiv et navn til den nye side.',
	'ForumNewPosts'				=> 'nyt indlæg',
	'ForumLocked'				=> 'sektion låst',
	'ForumUpdated'				=> 'opdateret',
	'ForumNoClusterDefined'		=> 'Ingen forumklynge defineret.',
	'ForumOutsideCluster'		=> 'Sørg for, at %1 handlingen er placeret inde i forumklyngen.',

	// password complexity
	'PwdCplxShort'				=> 'Adgangskoden er for kort.',
	'PwdCplxEquals'				=> 'Adgangskoden indeholder brugernavn.',
	'PwdCplxWeak'				=> 'Adgangskoden opfylder ikke kravene til kompleksitet.',
	'PwdCplxDesc1'				=> 'Krav til adgangskoden: ',
	'PwdCplxDesc2'				=> 'adgangskode bør ikke være mindre end %1 tegn',
	'PwdCplxDesc3'				=> 'må ikke indeholde dit brugernavn',
	'PwdCplxDesc4'				=> 'bør bestå af ',
	'PwdCplxDesc41'				=> 'bogstaver og tal',
	'PwdCplxDesc42'				=> 'store og små bogstaver og tal',
	'PwdCplxDesc43'				=> 'store og små bogstaver, cifre og ikke-alfanumeriske tegn',
	'PwdCplxDesc5'				=> 'Du kan bruge alle bogstaver, tal og specialtegn undtagen mellemrum.',

	'PasswordTooShort'			=> 'Adgangskode for kort.',
	'PasswordTooCommon'			=> 'Denne adgangskode er for almindelig.',
	'PasswordSameAsUsername'	=> 'Din adgangskode er den samme som dit brugernavn.',
	'PasswordSameAsEmail'		=> 'Din adgangskode er den samme som din e-mail.',

	'Timezone'					=> 'Timezone',

	'LanguageArray'	=> [
		'bg' => 'Bulgarsk',
		'da' => 'Dansk',
		'de' => 'Tysk',
		'el' => 'Græsk',
		'en' => 'Engelsk',
		'es' => 'Spansk',
		'et' => 'Estisk',
		'fa' => 'Persisk',
		'fr' => 'Fransk',
		'hi' => 'Hindi',
		'hu' => 'Ungarsk',
		'it' => 'Italiensk',
		'ja' => 'Japansk',
		'ko' => 'Koreansk',
		'nl' => 'Hollandsk',
		'pl' => 'Polsk',
		'pt' => 'Portugisisk',
		'ru' => 'Russisk',
		'ta' => 'Tamil',
		'zh' => 'Kinesisk',
		'zh-tw' => 'Kinesisk',
	],

	'AccountStatus'				=> 'Konto status',
	'AccountStatusArray' => [
		'0' => 'aktiv',
		'1' => 'afventer',
		'2' => 'blokeret',
		'3' => 'inaktiv',
	],

	'JustNow'		=> 'lige nu',
	'MinuteAgo'		=> 'et minut siden',
	'MinutesAgo'	=> '%1 minutter siden',
	'HourAgo'		=> 'en time siden',
	'HoursAgo'		=> '%1 timer siden',
	'DayAgo'		=> 'I går',
	'DaysAgo'		=> '%1 dage siden',
	'WeekAgo'		=> 'for en uge siden',
	'WeeksAgo'		=> '%1 uger siden',
	'MonthAgo'		=> 'for en måned siden',
	'MonthsAgo'		=> '%1 måneder siden',
	'YearAgo'		=> 'et år siden',
	'YearsAgo'		=> '%1 år siden',

	'InAMoment'		=> 'om et øjeblik',
	'InAMinute'		=> 'om et minut',
	'InMinutes'		=> 'om %1 minutter',
	'InAnHour'		=> 'om en time',
	'InHours'		=> 'om %1 timer',
	'Tomorrow'		=> 'i morgen',
	'InDays'		=> 'om %1 dage',
	'InAWeek'		=> 'om en uge',
	'InWeeks'		=> 'om %1 uger',
	'InAMonth'		=> 'om en måned',
	'InMonths'		=> 'om %1 måneder',
	'InAYear'		=> 'om et år',
	'InYears'		=> 'om %1 år',

	// norm multiples
	'ByteDecimalShort'			=> ['B', 'kB', 'MB', 'GB', 'TB', 'PB', 'EB', 'ZB', 'YB'],
	'ByteDecimalLong'			=> ['Byte', 'Kilobyte', 'Megabyte', 'Gigabyte', 'Terabyte', 'Petabyte', 'Exabyte', 'Zettabyte', 'Yottabyte'],
	'ByteBinaryShort'			=> ['B', 'KiB', 'MiB', 'GiB', 'TiB', 'PiB', 'Eib', 'ZiB', 'YiB'],
	'ByteBinaryLong'			=> ['Byte', 'Kibibyte', 'Mebibyte', 'Gibibyte', 'Tebibyte', 'Pebibyte', 'Exbibyte', 'Zebibyte', 'Yobibyte'],
	'PixelDecimalShort'			=> ['px', 'KP', 'MP', 'GP', 'TP', 'PP', 'EP', 'ZP', 'YP'],
	'PixelDecimalLong'			=> ['pixel', 'Kpx', 'MPX', 'Gpx', 'Tpx', 'Ppx', 'Epx', 'Zpx', 'Ypx'],

	// loading error
	'UnknownAction'				=> 'Ukendt handling',
	'UnknownMethod'				=> 'Ukendt metode',
	'FormatterNotFound'			=> 'Formatter %1 ikke fundet',

	// log
	'LogAdminLoginSuccess'		=> 'Logget ind på administrationspanelet med succes',
	'LogAdminLogout'			=> 'Logud af administrationspanelet',
	'LogAdminLoginFailed'		=> '!!Undladelse af at godkende adgang til administrationspanel!!',
	'LogAdminLoginLocked'		=> 'Låst login til administrationspanelet',
	'LogUserCookieForged'		=> '!!**Et forsøg på at logge ind på en smedet cookie med login ##%1##**!!',
	'LogInvalidFormToken'		=> 'Potentiel CSRF-angreb i gang opdaget: %1',
	'LogRemovedPage'			=> '!!Fjernet side ##%1## (bruger %2)!!',
	'LogRemovedCluster'			=> '!!Fjernet **klynge** ##%1## (bruger %2)!!',
	'LogRemovedRevision'		=> '!!Fjernet revision ##%3## side [[/%1]] (bruger %2)!!',
	'LogRemovedComment'			=> '!!Fjernet kommentar fra %3 på side [[/%1]] (bruger %2)!!',
	'LogRemovedFile'			=> '!!Fjernet fil ##%2## fra side [[/%1]]!!',
	'LogRemovedAllComments'		=> '!!Fjernede alle kommentarer til siden [[/%1]]!!',
	'LogRemovedAllRevisions'	=> '!!Fjernet alle revisioner af siden [[/%1]]!!',
	'LogRemovedAllFiles'		=> '!!Fjernede alle filer, knyttet til [[/%1]]!!',
	'LogTopicLocked'			=> 'Forum emne er låst [[/%1]]',
	'LogTopicUnlocked'			=> 'Oplåst forumemne [[/%1]]',
	'LogAclUpdated'				=> 'Opdateret ACL side [[/%1]]',
	'LogOwnershipChanged'		=> 'Ejerskab af siden [[/%1]] overført til brugeren ##%2##',
	'LogUserLoginFailed'		=> '!!Mislykkede forsøg på at logge ind med ##~%1##!!',
	'LogClonedPage'				=> 'Side ##%1## klonet til [[/%2]]',
	'LogRenamedPage'			=> 'Side ##%1## omdøbt til [[/%2]]',
	'LogRenamedPage2'			=> '. Den gamle side sat som linket til den nye',
	'LogSplittedPage'			=> 'Kommentarer til siden [[/%1]] opdelt på side [[/%2]]',
	'LogMergedPages'			=> 'Sider %1 fusioneret til side [[/%2]]',
	'LogUserPasswordReminded'	=> 'Bruger ##%1## bad om adgangskodegendannelsesprocessen til at adressere ##%2##',
	'LogUserPasswordRecovered'	=> 'Bruger ##%1## gendannede den glemte adgangskode',
	'LogUserPasswordChanged'	=> 'Bruger ##%1## opdateret (ændret) adgangskoden',
	'LogUserPasswordMismatch'	=> '!!Bruger ##%1## kunne ikke ændre adgangskoden: nuværende adgangskodefejl!!',
	'LogUserIPSwitched'			=> 'Uautoriseret IP-adresseændring for brugeren %1 fra %2 til %3',
	'LogPageImported'			=> 'Importeret side [[/%1]]',
	'LogSaveNoRights'			=> 'Ingen passende rettigheder til at gemme siden [[/%1]]',
	'LogPageCreated'			=> 'Oprettet ny side [[/%1]]',
	'LogPagePropertiesUpdated'	=> 'Opdateret sideegenskaber [[/%1]]',
	'LogPageOwnershipClaimed'	=> 'Brugeren fik ejerskab af siden [[/%1]]',
	'LogFileUploadedLocal'		=> 'Ny fil ##%2## uploadet til siden [[/%1]] (størrelse %3)',
	'LogFileUploadedGlobal'		=> 'Ny fil ##%2## uploadet til den globale mappe (størrelse %3)',
	'LogPMSent'					=> 'Personlig besked ##%1## -> ##%2## afsendt',
	'LogUserSimilarName'		=> 'Der var forsøg på at registrere sig under samme brugernavn: ##%1##',
	'LogUserEmailNotAllowed'	=> 'E-mail ##%1## ikke i tilladte domæner liste',
	'LogRegisterTiming'			=> 'Registrering mislykkedes, formulartidsgrænse er ##%1## sekunder (var ##%2##)',
	'LogUserRegistered'			=> 'Registrerede en ny bruger ##%1## (##%2##)',
	'LogUserEmailActivated'		=> 'Aktiverede e-mail ##%1## bruger ##%2##',
	'LogCommentPosted'			=> 'Tilføjet [[/%1 nye kommentarer]] til side [[/%2]]',
	'LogUserLoginOK'			=> 'Bruger ##%1## logget ind i systemet',
	'LogUserLoggedOut'			=> 'Bruger ##%1## loggede systemet ud',
	'LogUserSessionContinued'	=> 'Bruger ##%1## fortsatte den suspenderede session',
	'LogUserSettingsUpdate'		=> 'Bruger ##%1## opdaterede personlige indstillinger',
	'LogPageEdited'				=> 'Redigeret side [[/%1]]',
	'LogCommentEdited'			=> 'Redigeret kommentar [[/%1]]',
	'LogUpdatedFileMeta'		=> 'Opdateret filmetadata for ##%2## fra side [[/%1]]',
	'LogUpdatedFileCategories'	=> 'Opdateret fil kategorier for ##%2## fra side [[/%1]]',

	'LogXmlSitemapGenerated'	=> 'XML Sitemap genereret',
	'LogReferrersPurged'		=> 'Vedligehold: henvisere renset',
	'LogRevisionsPurged'		=> 'Vedligeholdelse: forældede sider revisioner renset',
	'LogDeletedPagesPurged'		=> 'Vedligeholdelse: slettede sider renset',
	'LogSystemLogPurged'		=> 'Vedligeholdelse: system log renset',
	'LogCachedPagesPurged'		=> 'Vedligeholdelse: cachede sider renset',
	'LogSqlCachePurged'			=> 'Vedligehold: cachede ql resultater renset',
	'LogExpiredTokensPurged'	=> 'Vedligeholdelse: udløbet cookie_tokens renset',
	'LogErrorSplitComments'		=> 'Fejl ved adskillelse af kommentarer fra emnet [[/%1]] et nyt emne ##%2##: siden blev ikke oprettet',
	'LogCategoriesUpdated'		=> 'Opdateret sidekategorier [[/%1]]',
	'LogCategoryCreated'		=> 'Oprettede en ny kategori //%1//',
	'LogCategoryRenamed'		=> 'Kategori ##%1## omdøbt til ##%2##',
	'LogCategoryDebundled'		=> 'Kategori ##%1## debundled',
	'LogCategoryGrouped'		=> 'Kategori ##%1## grupperet med ordet ##%2##',
	'LogCategoryRemoved'		=> 'Kategori ##%1## fjernet fra databasen',
	'LogThumbnailGeneration'	=> 'Miniaturegenerering %1 sek.',

	'ErrorMinPHPVersion'		=> 'PHP versionen skal være større end <strong>' . PHP_MIN_VERSION . '</strong>,' .
									' din server ser ud til at køre <strong>' . PHP_VERSION . '</strong>.' .
									'  Du bør opgradere til en nyere PHP-version for at WackoWiki kan fungere korrekt.',

];
