<?php

if (!defined('IN_WACKO'))
{
	exit;
}

$wacko_translation = [

	// language
	'lang_scheme'	=> [
		'name'		=> 'Anglais',
		'code'		=> 'fr',
		'dir'		=> 'ltr',
		'locale'	=> 'fr_FR.UTF-8',
	],

	// common
	'AddButton'					=> 'Ajouter',
	'ArchiveButton'				=> 'Archive',
	'CancelButton'				=> 'Abandonner',
	'ContinueButton'			=> 'Continuer',
	'ConvertButton'				=> 'Convertir',
	'CreateButton'				=> 'Créer',
	'DeleteButton'				=> 'Supprimez',
	'RemoveButton'				=> 'Retirer',
	'RenameButton'				=> 'Renommer',
	'ResetButton'				=> 'Reset',
	'RestoreButton'				=> 'Restaurer',
	'SaveButton'				=> 'Enregistrer',
	'SearchButton'				=> 'Chercher',
	'SendButton'				=> 'Envoyer',
	'SetButton'					=> 'Régler',
	'SubmitButton'				=> 'Soumettre',
	'UpdateButton'				=> 'Mise à jour',

	'FormInvalid'				=> 'Le formulaire soumis n\'était pas valide. Essayez de soumettre à nouveau.',
	'UnitPixel'					=> 'px',
	'Number'					=> 'Numéros',

	// logged in panel
	'AccountText'				=> 'Compte client',
	'AccountTip'				=> 'Paramètres du compte',
	'AdminText'					=> 'Administrateur',
	'AdminTip'					=> 'Panneau Administratif',
	'LogoutLink'				=> 'Déconnexion',
	'LogoutButton'				=> 'Déconnexion',
	'LogoutAreYouSure'			=> 'Voulez-vous vraiment vous déconnecter ?',

	// registration panel
	'RegistrationWelcome'		=> 'Inscription d\'un nouvel utilisateur:',
	'RegistrationButton'		=> 'Enregistrez-moi',
	'UserNameOwned'				=> 'Ce nom d\'utilisateur est déjà enregistré. Veuillez en choisir un autre.',
	'SiteRegistered'			=> 'Vous vous êtes inscrit avec succès sur le site %1.',
	'RegistrationEmailInfo'		=> 'Une adresse e-mail valide. Tous les e-mails du système seront envoyés à cette adresse. L\'adresse e-mail n\'est pas rendue publique et ne sera utilisée que si vous souhaitez recevoir un nouveau mot de passe ou que vous souhaitez recevoir certaines nouvelles ou notifications par courriel.',
	'EmailConfirmHint'			=> 'Please confirm your E-mail address by clicking on the link in the instructions sent to you. <br>If you do not verify your email address, you will not be able to retrieve a possible lost password. <br>Furthermore you will not be notified of recent page changes and comments.',
	'EmailConfirmRequired'		=> 'Sans une adresse e-mail confirmée, vous ne serez pas autorisé à vous connecter.',
	'NameTooShort'				=> 'The Username is too short, a minimum of %2 characters is required.',
	'NameTooLong'				=> 'Le nom d\'utilisateur est trop long, un maximum de %2 caractères est autorisé.',
	'NameAlphanumOnly'			=> 'Le nom d\'utilisateur doit contenir entre %1 et %2 caractères et n\'utiliser que des caractères alphanumériques. Les caractères majuscules sont OK.',
	'NameCamelCaseOnly'			=> 'Le nom d\'utilisateur doit être compris entre %1 et %2 caractères et le format WikiName est formaté.',
	'NewUserAccount'			=> 'nouveau compte utilisateur',

	'NewAccountSubject'			=> 'Enregistrement du compte',
	'NewAccountAdminCreated'	=> 'L\'utilisateur %1 a créé un compte pour vous avec le nom d\'utilisateur "%2". Afin de terminer votre inscription, visitez l\'URL suivante (assurez-vous qu\'elle est entrée comme une seule ligne) et définissez votre propre mot de passe d\'accès :',
	'NewAccountUsername'		=> 'Nom d\'utilisateur:',
	'AccountLanguage'			=> 'Langue :',
	'NewAccountEmail'			=> 'Email:',
	'NewAccountIP'				=> 'Adresse IP distante :',
	'NewAccountSignupInfo'		=> 'Le compte suivant a été créé :',

	'UserWaitingApproval'		=> 'Un courriel a été envoyé à l\'administrateur du site. L\'administrateur examinera les informations qui ont été soumises et approuvera ou refusera votre demande.',
	'UserRequiresApproval'		=> 'Pour approuver ou refuser l\'accès de cet utilisateur à %1 , allez dans le panneau d\'administration.',
	'UserApprovalInfo'			=> 'Après votre inscription, votre demande sera envoyée à l\'administrateur du site pour approbation. Vous recevrez ensuite un e-mail avec des instructions supplémentaires.',
	'UserApprovalHint'			=> 'L\'activation réussie de votre compte sera annoncée dans un e-mail spécifique. D\'ici là, une connexion n\'est pas possible.',

	'UserApprovalPending'		=> 'Votre compte est toujours en attente d\'approbation.',
	'UserApprovalDenied'		=> 'Votre compte a été refusé d\'accéder à ce site.',

	'RegistrationApproved'		=> 'Inscription approuvée',
	'RegistrationDenied'		=> 'Inscription refusée',
	'PendingApproval'			=> 'En attente d\'approbation',

	'UserApprovedInfo'			=> 'Vous avez été autorisé à accéder à %1.',
	'UserDeniedInfo'			=> 'L\'accès à %1 vous a été refusé.',

	'RegistrationThreshold'		=> 'Le temps de remplir le formulaire ne doit pas être inférieur à %1 secondes.',
	'Language'					=> 'Langue',

	// login panel
	'LoginWelcome'				=> 'Se connecter',
	'CreateAccount'				=> 'Créer un nouveau compte',
	'RegistrationLink'			=> 'Inscription',
	'LoginName'					=> 'Nom d\'utilisateur',
	'Password'					=> 'Mot de passe',
	'LoginButton'				=> 'Se connecter',
	'LoginLink'					=> 'Se connecter',
	'PersistentCookie'			=> 'Rester connecté',
	'Session'					=> 'Séance',
	'SessionTip'				=> 'paramètres de la session en cours',
	'SessionDuration'			=> 'Durée de la session',
	'SessionDurationSession'	=> 'session du navigateur',
	'SessionDurationDay'		=> '1 jour',
	'SessionDurationWeek'		=> '1 semaine',
	'SessionDurationMonth'		=> '1 mois',
	'LoggedInAs'				=> 'Vous êtes connecté en tant que',

	'ClearCookies'				=> 'Supprimer tous les cookies',
	'BindSessionIp'				=> 'Lier la session à l\'adresse IP',
	'BindSessionIpOn'			=> 'activé (IP %1 actuel)',
	'TrafficProtection'			=> 'Protection du trafic',
	'SessionEnds'				=> 'La session en cours se termine',
	'LastVisit'					=> 'La dernière visite a été enregistrée',

	'LoginIncorrect'			=> 'Le nom d\'utilisateur ou le mot de passe que vous avez entré est invalide.',
	'WelcomeBack'				=> 'Bienvenue, %1',
	'LoginAttemptsExceeded'		=> 'You exceeded the maximum allowed number of login attempts.<br>In addition to your username and password you now also have to solve the CAPTCHA below.',

	// session notice
	'IPAddressChanged'			=> 'L\'adresse IP a été changée en %1 (était %2)',

	'SessionReplay'				=> 'Session terminée en raison d\'une rediffusion.',
	'SessionObsolete'			=> 'La session est obsolète.',
	'SessionExpired'			=> 'La session a expiré.',
	'SessionTimeout'			=> 'Session terminée en raison du délai d\'expiration.',
	'SessionInactivity'			=> 'Session terminée en raison de l\'inactivité.',
	'SessionUaChange'			=> 'Session terminée en raison d\'un changement d\'agent utilisateur.',
	'SessionTLSChange'			=> 'Session terminée en raison d\'un changement de TLS.',
	'SessionIPChange'			=> 'Session terminée en raison d\'un changement d\'adresse IP.',

	// other
	'Guest'						=> 'Invité',
	'Everybody'					=> 'Tout le monde',
	'Help'						=> 'Aide',
	'TopicSearchText'			=> 'Rechercher uniquement dans les titres',
	'WordprocessorVersion'		=> 'Version du traitement de texte',

	// notifications
	'EmailHello'				=> 'Bonjour ',
	'EmailModerator'			=> 'Modérateur',
	'WatchedPageChanged'		=> 'Page modifiée ',
	'SomeoneChangedThisPage'	=> ' a changé une page que vous regardez : ',
	'NewPageCreatedSubj'		=> 'Une nouvelle page',
	'NewPageCreatedBody'		=> 'L\'utilisateur %1 a créé une nouvelle page : ',
	'FileUploadedSubj'			=> 'Un nouveau fichier',
	'FileUploadedBody'			=> 'L\'utilisateur %1 a téléchargé un nouveau fichier : ',
	'FileReplacedBody'			=> 'L\'utilisateur %1 a remplacé le fichier : ',

	'ActionDenied'				=> 'L\'action est refusée ici.',
	'TocTitle'					=> 'Contenus ',
	'OuterLink2'				=> 'Lien sortant',
	'FileLink'					=> '',
	'PDFLink'					=> 'Document PDF',
	'RDFLink'					=> 'Document RDF',
	'EmailLink'					=> 'Écrire un e-mail (lancement du client de messagerie)',
	'JabberLink'				=> 'Discuter via XMPP (lancement du client Jabber)',
	'PermaLink'					=> 'Permalien',
	'PermaLinkTip'				=> 'Lien permanent vers cette révision de la page',
	'PermaLink0Tip'				=> 'Lien permanent vers cette page',

	'ShowTip'					=> 'Retour en mode vue',
	'ShowText'					=> 'Voir',
	'WikieditAutocomplete'		=> 'Compléter les wikilinks par Ctrl+Espace',
	'WikiEditInactiveJs'		=> 'Afin de pouvoir utiliser WikiEdit, veuillez activer JavaScript dans votre navigateur.',
	'NumerateLinks'				=> 'Numériser les liens dans la vue imprimée',
	'Comment'					=> 'Commenter',
	'Comments0'					=> 'Ajouter votre commentaire',
	'Comments1'					=> 'Lire le commentaire (1 commentaire)',
	'CommentsN'					=> 'Lire les commentaires ( commentaires%1)',
	'Comments'					=> 'Commentaires',
	'CommentHint'				=> '<a href="%1">Connectez-vous</a> ou <a href="%2">créez un compte</a> pour poster un commentaire.',
	'CommentEdited'				=> 'édité',
	'Links'						=> 'Liens',
	'Version'					=> 'Version',

	// details formatter
	'ShowHideDetails'			=> 'Détails du produit',

	'PrivacyPolicy'				=> 'Politique de confidentialité',
	'TermsOfUse'				=> 'Conditions d\'utilisation',
	'AcceptTermsOfUse'			=> 'J\'ai lu, compris et j\'accepte les conditions d\'utilisation du site.',

	'ShowComments'				=> 'Afficher les commentaires / formulaire',
	'HideComments'				=> 'Masquer les commentaires / formulaire',
	'AddComment'				=> 'Joindre un commentaire à cette page :',
	'AddCommentTitle'			=> 'Titre du commentaire :',
	'CommentTitleRe'			=> 'Re :',
	'AddCommentButton'			=> 'Joindre un commentaire',
	'HereLink'					=> 'ici',
	'PageHandlerMoreTip'		=> 'plus',

	'ThemeCorrupt'				=> 'Le thème est corrompu',
	'InvalidNamespace'			=> 'Espace de noms invalide.',
	'DoesNotExists'				=> 'Cette page n\'existe pas.',
	'PromptCreate'				=> 'Peut-être voulez-vous <strong><a href="%1">créer</a></strong>?',
	'RevisionHint'				=> 'Ceci est une ancienne révision de <a href="%1">%2</a> de %3 édité par %4.',
	'ReadAccessDenied'			=> 'Vous n\'êtes pas autorisé à lire cette page.',
	'ReadAccessDeniedHintGuest'	=> 'Pour lire cette page, vous devez vous connecter.',
	'PageDeletedInfo'			=> 'Cette page a été supprimée.',
	'RevisionDeletedInfo'		=> 'Cette révision a été supprimée.',
	'CommentDeletedInfo'		=> 'Ce commentaire a été supprimé.',

	'LastEditedBy'				=> 'Dernière modification par',
	'YouAreOwner'				=> 'Vous êtes le propriétaire de cette page.',
	'Owner'						=> 'Propriétaire :',
	'Nobody'					=> 'Personne',
	'TakeOwnership'				=> 'Prendre la propriété',
	'FilesTip'					=> 'Gérer les fichiers attachés',
	'FilesText'					=> 'Fichiers joints',
	'DeleteTip'					=> 'Supprimer la page, ses fichiers et ses commentaires',
	'DeleteCommentTip'			=> 'Supprimer le commentaire',
	'DeleteText'				=> 'Supprimez',
	'AclText'					=> 'Permissions',
	'AclTip'					=> 'Droits d\'édition',

	'PropertiesText'			=> 'Propriétés',
	'PropertiesTip'				=> 'Modifier les propriétés de la page',
	'EditTip'					=> 'Modifier cette page.',
	'EditText'					=> 'Editer',
	'EditSection'				=> 'Modifier la section %1',
	'EditSectionHint'			=> 'Section %1 de %2',
	'SectionHeadline'			=> 'Section',
	'EditCommentTip'			=> 'Modifier le commentaire',
	'EditComment'				=> 'Modifier ce commentaire',
	'ReplyComment'				=> 'Répondre',
	'ReplyCommentTip'			=> 'Répondre à ce commentaire',
	'RevisionTip'				=> 'Voir les révisions de la page',
	'RevisionText'				=> 'Révisions',
	'ReferrersTip'				=> 'Voir une liste d\'URL se référant à cette page',
	'ReferrersText'				=> 'Référents',
	'ModerateTip'				=> 'Modération des sujets et des messages du forum',
	'ModerateText'				=> 'Modérée',
	'SearchText'				=> 'Recherche: ',

	'AclUpdated'				=> 'Listes de contrôle d\'accès mises à jour',
	'AclGaveOwnership'			=> ' et a donné la propriété à %1.',
	'AclNoNewOwner'				=> 'La propriété de la page n\'est pas transférée, car l\'utilisateur %1 n\'a pas été trouvé.',
	'NewPageOwnership'			=> 'Propriété de la page transférée',
	'YouAreNewOwner'			=> 'l\'ancien propriétaire %1 a transféré la propriété ' . "\n" . 'de la page suivante pour vous',
	'PageOwnershipInfo'			=> '',
	'AclRead'					=> 'Lecture :',
	'AclWrite'					=> 'Écriture:',
	'AclComment'				=> 'Commentaires :',
	'AclCreate'					=> 'Créer:',
	'AclUpload'					=> 'Téléversement:',
	'AclFor'					=> 'Listes de contrôle d\'accès pour %1',
	'SetOwner'					=> 'Définir le propriétaire :',
	'OwnerDontChange'			=> 'Ne pas changer',
	'AclAccessDenied'			=> 'Vous n\'êtes pas le propriétaire de cette page.',
	'AclSyntaxError'			=> 'Erreur de syntaxe de la liste de contrôle d\'accès',
	'AclHelp'					=> '<code>*</code> - tout le monde est autorisé<br>' .
									'<code>$</code> - seulement les utilisateurs enregistrés<br>' .
									'<code>!</code> - a preceding exclamation mark denies the respective right<br>' .
									'<code>[UserName]</code> - noms des utilisateurs autorisés<br>' .
									'<code>[GroupName]</code> - noms des groupes d\'utilisateurs (alias)<br>' .
									'<code>(une liste vide)</code> - seul le propriétaire de la page a accès',

	'AccessMode'				=> 'Visibilité',
	'AccessDenied'				=> 'refusée',
	'AccessPublic'				=> 'public',
	'AccessRegistered'			=> 'Inscrit',
	'AccessPrivate'				=> 'privé',
	'AccessCustom'				=> 'personnalisable',

	// purge handler
	'PurgePage'					=> 'Purge page',
	'NotOwnerAndCantPurge'		=> 'Vous n\'êtes pas le propriétaire de la page et vous ne pouvez pas la purger.',
	'ReallyPurge'				=> 'ATTENTION : La purge de la page est irréversible !',
	'SelectPurgeOptions'		=> 'Sélectionnez les options de purge nécessaires :',
	'PurgeComments'				=> 'Purger tous les commentaires de la page',
	'CommentsPurged'			=> 'Tous les commentaires ont été supprimés.',
	'PurgeFiles'				=> 'Supprimer tous les fichiers joints',
	'FilesPurged'				=> 'Tous les fichiers joints ont été supprimés.',
	'PurgeRevisions'			=> 'Purger toutes les révisions de la page',
	'RevisionsPurged'			=> 'Les révisions ont été purgées.',
	'PurgeButton'				=> 'Purge',

	// categories handler
	'Categories'				=> 'Catégories',
	'CategoriesAssign'			=> 'assigner',
	'CategoriesEdit'			=> 'éditer',
	'Category'					=> 'Catégorie',
	'CategoriesFor'				=> 'Catégories pour',
	'CategoriesTip'				=> 'Modifier les catégories',
	'CategoriesText'			=> 'Catégories',
	'CategoriesUpdated'			=> 'Catégories mises à jour',
	'CategoriesAlreadyExists'	=> 'La catégorie %1 existe déjà.',
	'CategoriesAdded'			=> 'Catégorie %1 ajoutée avec succès.',
	'CategoriesRenamed'			=> 'Catégorie renommée avec succès.',
	'CategoriesUngrouped'		=> 'Catégorie déboursée avec succès.',
	'CategoriesGrouped'			=> 'La catégorie est entrée dans le nouveau groupe.',
	'NoMultilevelGrouping'		=> 'Les catégories de regroupement à plusieurs niveaux ne sont pas possibles.',
	'CategoriesDeleted'			=> 'La catégorie a été supprimée de la base de données et de toutes les pages.',
	'CategoriesAdd'				=> 'Ajouter une nouvelle catégorie',
	'CategoryDescription'		=> 'Libellé',
	'CategoriesAddGrouped'		=> 'Groupé avec la catégorie',
	'CategoriesAddGroupedNo'	=> 'Aucun groupe.',
	'CategoriesRename'			=> 'Renommer la catégorie %1 en',
	'CategoriesRenameInfo'		=> '* Note: Le changement affectera toutes les pages qui sont assignées à cette catégorie.',
	'CategoriesGroup'			=> 'Grouper les catégories %1 avec',
	'CategoriesGroupInfo'		=> '* Sélectionnez [aucun groupe] pour débunder la catégorie.',
	'CategoriesNoGroup'			=> '[aucun groupe]',
	'CategoriesDelete'			=> 'Êtes-vous sûr de vouloir supprimer la catégorie %1?',
	'CategoriesDeleteInfo'		=> '* Note: Le changement affectera toutes les pages qui sont assignées à cette catégorie. Si le mot a une sous-catégorie, ils ne seront pas supprimés, mais seulement déboursés.',
	'CategoriesStoreInfo'		=> 'Pour assigner des catégories à une page, sélectionnez les cases à cocher.',
	'CategoriesStoreButton'		=> 'Enregistrer les catégories',
	'CategoriesGroupButton'		=> 'Groupes',
	'CategoriesEditInfo'		=> 'Pour modifier la liste des catégories, sélectionnez le bouton radio.',
	'NoCategoriesForThisLang'	=> 'Les catégories pour cette langue ne sont pas spécifiées.',
	'PagesCategory'				=> 'Catégorie de pages',
	'CategoryNotExists'			=> 'La catégorie n\'existe pas.',
	'CategoryEmpty'				=> 'Catégorie vide.',
	'NoCategorySelected'		=> 'Aucune catégorie sélectionnée.',
	'NoCategoriesAssigned'		=> 'Aucune catégorie assignée pour cette langue.',
	'TagCloud'					=> 'Nuage de balises',
	'PagesTaggedWith'			=> '%1 pages taggées avec %2',
	'CategoriesOfCluster'		=> 'du cluster',
	'TaggedWithTip'				=> 'afficher les pages taggées %1',

	// source handler
	'SourceText'				=> 'Source',
	'SourceTip'					=> 'Voir la source du wiki',
	'SourceCopyToClipboard'		=> 'copier dans le presse-papiers',
	'SourceFor'					=> 'Voir la source pour %1',

	// Groups action
	'GroupsSearch'				=> 'Trouver des groupes',
	'GroupsNoMatching'			=> 'Groupes correspondants non trouvés. Essayez un critère de recherche moins strict.',
	'GroupsOpenProfile'			=> 'Voir le profil',
	'GroupsName'				=> 'Groupes',
	'GroupsMembers'				=> 'Membres',
	'GroupsDescription'			=> 'Libellé',
	'GroupsCreated'				=> 'Créé',
	'GroupsNotFound'			=> 'Groupe %2 introuvable. Cliquez sur <a href="%1">ici</a>pour accéder à la liste principale.',
	'GroupsProfile'				=> 'Profil',
	'GroupsList'				=> 'Voir la liste complète des groupes',
	'GroupSpace'				=> 'Espace de groupe',

	'MetaUpdated'				=> 'Méta données mises à jour',

	'PreviewButton'				=> 'Aperçu',
	'Preview'					=> 'Aperçu',
	'Chars'						=> 'caractères',
	'PageBody'					=> 'Corps de la page',
	'EditNote'					=> 'Modifier le résumé',
	'EditNoteMissing'			=> 'Modifier le résumé manquant',
	'EditMinor'					=> 'Modification mineure',
	'MinorEditHide'				=> 'Masquer l\'édition mineure',
	'MinorEditShow'				=> 'Afficher les modifications mineures',
	'PostAnonymously'			=> 'Publier anonymement sans donner votre nom',
	'NotifyMe'					=> 'M\'avertir des nouveaux commentaires et modifications de la page',
	'OverwriteAlert'			=> 'ALERTE DE SURWRITE : Cette page a été modifiée par quelqu\'un d\'autre pendant que vous l\'édiez.<br>Veuillez copier vos modifications et modifier à nouveau cette page.',
	'TextDbOversize'			=> 'Warning: Your text exceeds the length limit by %1 characters. Please shorten your text to an acceptable number of characters. Tip: You may place the remaining text on a separate page.',
	'EditingRevisionWarning'	=> 'You are editing an old revision of this page. If you publish it, any changes made since then will be removed. <br>You may wish to edit the current revision instead.',
	'WriteAccessDenied'			=> 'Vous n\'avez pas d\'accès en écriture à cette page.',
	'EmptyPage'					=> 'Le corps de la page était vide - pas sauvegardé !',
	'EmptyComment'				=> 'Le corps du commentaire est vide - pas sauvegardé!',
	'CommentAccessDenied'		=> 'Désolé, vous n\'êtes pas autorisé à poster des commentaires sur cette page.',
	'CommentFlooded'			=> 'L\'intervalle entre la publication des messages ne doit pas être inférieur à %1 secondes.',
	'CommentAdded'				=> 'Commentaire ajouté.',
	'YouAreNowTheOwner'			=> 'Vous êtes maintenant le propriétaire de cette page.',
	'PageSaved'					=> 'La version %1 de la page est enregistrée.',
	'CommentSaved'				=> 'Commentaire enregistré.',

	'RevisionsFor'				=> 'Révisions pour %1',
	'DefaultDiffMode'			=> 'Mode de diff par défaut',
	'DiffMode'		=> [
		'0'		=> 'Diff complet',
		'1'		=> 'Diff simple',
		'2'		=> 'Source',
		'3'		=> 'Côté à côte',
		'4'		=> 'En ligne',
		'5'		=> 'Fusionné',
		'6'		=> 'Unifié',
		'7'		=> 'Contexte',
	],

	'PreviousEdit'				=> 'Édition précédente',
	'NextEdit'					=> 'Édition suivante',

	'Diff'						=> 'Différence',
	'PreviousVersion'			=> 'Révision précédente',
	'LatestVersion'				=> 'Dernière révision',
	'NextVersion'				=> 'Révision suivante',

	'ShowDifferencesButton'		=> 'Afficher les différences',
	'CancelReturnButton'		=> 'Annuler et revenir à la page',
	'Comparison'				=> 'Différence entre les révisions pour %1',
	'RevisionAsOf'				=> 'Révision %1 à partir du',
	'SimpleDiffAdditions'		=> 'Ajouts :',
	'SimpleDiffDeletions'		=> 'Suppressions:',
	'NoDifferences'				=> 'Aucune différence.',
	'ReEditOldRevision'			=> 'Ré-éditer cette ancienne révision',

	'ExternalPages'				=> 'Pages externes avec un lien vers %1 (%2) (<a href="%3">voir la liste des domaines</a> ) :',
	'ExternalPagesGlobal'		=> 'Sites liés à ce WackoWiki (%2) (<a href="%1">voir la liste des domaines</a> ) :',
	'Last24Hours'				=> 'dernières 24 heures',
	'LastDays'					=> 'derniers %1 jours',
	'DomainsSitesPages'			=> 'Domaines/pages de sites reliant à  %1 (%2) (<a href="%3">voir la liste des différentes URLs</a> ) :',
	'DomainsSitesPagesGlobal'	=> 'Domains/sites linking to this WackoWiki (<a href="%1">see list of different URLs</a>):',
	'ViewReferrersPage'			=> 'à la page',
	'ViewReferrersPerPage'		=> 'par page',
	'ViewReferrersByTime'		=> 'par temps',
	'ViewReferrersGlobal'		=> 'global',
	'NoneReferrers'				=> 'Aucun',
	'NotOwnerCantDelete'		=> 'Vous n\'êtes pas propriétaire de cette page et ne pouvez pas la supprimer',

	// remove
	'RemovePage'				=> 'Supprimer la page',
	'RemoveRevision'			=> 'Supprimer la révision',
	'RemoveComment'				=> 'Supprimer le commentaire',
	'RemoveCluster'				=> 'Supprimer toutes les pages du cluster',
	'RemoveDontKeep'			=> 'Ne pas enregistrer une copie d\'une page et des commentaires supprimés',
	'RemoveDontKeepRevision'	=> 'Ne pas enregistrer une copie de la révision supprimée',
	'RemoveDontKeepComment'		=> 'Ne pas enregistrer une copie du commentaire supprimé',
	'RemoveDontKeepFile'		=> 'Ne pas enregistrer une copie du fichier supprimé',
	'ReferrersRemoved'			=> 'Référents supprimés.',
	'LinksRemoved'				=> 'Liens supprimés.',
	'CategoriesRemoved'			=> 'Catégories de pages supprimées.',
	'AclsRemoved'				=> 'Acls de page supprimés.',
	'BookmarksRemoved'			=> 'Signets supprimés.',
	'WatchesRemoved'			=> 'Montres supprimées.',
	'CommentsRemoved'			=> 'Commentaires de la page supprimés.',
	'FilesRemoved'				=> 'Les fichiers de la page ont été supprimés.',
	'PageRemoved'				=> 'Page supprimée.',
	'PageCachePurged'			=> 'Cache purgé.',
	'ClusterRemoved'			=> 'Toutes les pages du cluster ont été supprimées.',
	'RevisionRemoved'			=> 'La révision %1 a été supprimée.',
	'RevisionsRemoved'			=> 'Révisions supprimées.',
	'ActionHaveNoUndo'			=> 'Cette action ne peut être annulée.',

	// restore
	'PageRestored'				=> 'Page restaurée.',
	'RevisionRestored'			=> 'Révision restaurée.',
	'LocalFilesRestored'		=> 'Fichiers locaux restaurés.',

	'PrintVersion'				=> 'Version imprimée',
	'PrintText'					=> 'Imprimer',
	'LinkedPages'				=> 'Pages liées :',
	'NoLinkedPages'				=> 'Il n\'y a pas de pages liées',
	'ReferringPages'			=> 'Pages référant :',
	'NoReferringPages'			=> 'Il n\'y a aucune page de référence',
	'Footnotes'					=> 'Notes de bas de page :',
	'Footnote'					=> 'Note de bas de page',
	'MostPopularPages'			=> 'Pages les plus populaires',
	'MostCommentedPages'		=> 'Pages les plus commentées',
	'NoAccessToSourcePage'		=> 'Vous n\'êtes pas autorisé à lire la page source de l\'action.',
	'SourcePageDoesntExist'		=> 'La page source de l\'action n\'existe pas encore',
	'NotLoggedInThusEdited'		=> 'Vous n\'êtes pas connecté, nous n\'avons donc pas pu identifier les pages que vous avez modifiées.',
	'DidntEditAnyPage'			=> 'Vous n\'avez pas encore édité de page.',
	'NoPagesFound'				=> 'Aucune page trouvée.',
	'MyChangesTitle1'			=> 'Voici la liste des pages que vous avez modifiées, classées par date de votre dernière modification',
	'MyChangesTitle2'			=> 'Voici la liste des pages que vous avez modifiées, ainsi que l\'heure de votre dernière modification',
	'OrderABC'					=> 'alphabétiquement',
	'OrderCreation'				=> 'par création',
	'OrderChange'				=> 'par changement',
	'ListOwnedPages'			=> 'Ceci est la liste des pages que vous possédez (ordonnées par ordre alphabétique)',
	'ListOwnedPages2'			=> 'Voici la liste des pages que vous possédez (classées par date)',
	'ListOwnedPages3'			=> 'Ceci est la liste des pages que vous possédez (classées par changement)',
	'NotLoggedInThusOwned'		=> 'Vous n\'êtes pas connecté, nous n\'avons pas pu récupérer vos pages.',
	'NoOrphaned'				=> 'Pas de pages orphelines. Bien.',
	'NoRecentComments'			=> 'Aucun commentaire récent.',
	'LatestCommentBy'			=> 'dernier commentaire de',
	'NoRecentlyCommented'		=> 'Aucune page récemment commentée.',
	'NoDeletedPages'			=> 'Aucune page supprimée trouvée.',
	'NoDeletedRevisions'		=> 'Aucune révision supprimée trouvée.',
	'NoDeletedFiles'			=> 'Aucun fichier supprimé trouvé.',
	'CommentsDisabled'			=> 'Les commentaires ne sont pas disponibles.',

	'SearchResults'				=> 'Résultats de recherche pour ',
	'NotFound'					=> 'non trouvé',
	'NoResultsFor'				=> 'Aucun résultat pour ',
	'SearchFor'					=> 'Recherche pour:',
	'TopicSearchResults'		=> 'Résultats de la recherche de sujets pour ',
	'NotFoundInTopics'			=> 'non trouvé dans les sujets',
	'FilterLangNotAvailable'	=> 'La langue sélectionnée n\'est pas disponible !',

	'PostedBy'					=> 'posté par',
	'ThisIsCommentOn'			=> 'Ceci est un commentaire sur',
	'At'						=> 'à',
	'To'						=> 'à',
	'By'						=> 'par',
	'From'						=> 'de',
	'For'						=> 'pour',
	'ReturnToCommented'			=> 'Retour à la page commentée',
	'AbandonedComment'			=> 'La page à laquelle ce commentaire appartient n\'existe plus !',

	'PagesLinkingTo'			=> 'Pages liées à',
	'NoPageLinkingTo'			=> 'Aucune page n\'est liée à',
	'NoWantedPages'				=> 'Pas de pages souhaitées. Bien.',
	'RemoveWatch'				=> 'Supprimer la surveillance de cette page',
	'SetWatch'					=> 'Surveiller cette page',
	'WatchText'					=> 'Regarder',
	'UnwatchText'				=> 'Ne pas suivre',
	'UserSettingsStored'		=> 'Paramètres utilisateur enregistrés.',
	'LoggedOut'					=> 'Vous êtes maintenant déconnecté.',
	'LoggedOutAuto'				=> 'Pour des raisons de sécurité, votre session est terminée. Veuillez vous reconnecter.',

	// user settings
	'EmailConfirmResent'		=> 'Le code de confirmation de l\'e-mail a été renvoyé à votre adresse.',
	'EmailConfirmNotSent'		=> 'Impossible d\'envoyer le code de confirmation : l\'e-mail n\'est pas spécifié !',
	'Hello'						=> 'Bonjour',
	'UserName'					=> 'Nom d\'utilisateur',
	'EmailAddress'				=> 'Adresse e-mail',
	'RealName'					=> 'Nom réel',
	'MenuItemsShown'			=> 'Éléments du menu affichés',
	'RecordsPerPage'			=> 'Enregistrements par page',
	'DoShowComments'			=> 'Afficher les commentaires par défaut',
	'DoubleclickEditing'		=> 'Doubleclick Édition',
	'UpdateSettingsButton'		=> 'Mettre à jour les paramètres',

	'AccountDisabled'			=> 'Votre compte peut être désactivé ou bloqué.',
	'WrongPassword'				=> 'Mot de passe incorrect !',
	'ConfirmPassword'			=> 'Confirmer le mot de passe',
	'Email'						=> 'Adresse e-mail',
	'MustBeWikiName'			=> 'Le nom d\'utilisateur doit être au format <a href="https://wackowiki.org/doc/Doc/English/WikiName" target="_blank">WikiName</a>!',
	'SpecifyEmail'				=> 'Vous devez spécifier une adresse e-mail.',
	'NotAEmail'					=> 'Cela ne ressemble pas à une adresse e-mail valide.',
	'EmailTaken'				=> 'L\'adresse e-mail saisie est déjà utilisée.',
	'EmailDomainNotAllowed'		=> 'L\'adresse e-mail %1 saisie n\'est pas dans la liste des domaines autorisés.',
	'PasswordsDidntMatch'		=> 'Les mots de passe ne correspondent pas.',
	'SpacesArentAllowed'		=> 'Les espaces ne sont pas autorisés dans les mots de passe.',
	'ListMyPages'				=> 'Lister vos pages',
	'ListMyChanges'				=> 'Lister vos modifications',
	'ListMyWatches'				=> 'Liste des pages regardées',
	'ListMyChangesWatches'		=> 'Changements entre les pages regardées',
	'SeeListOfPages'			=> 'Voir une liste des pages que vous possédez (MyPages) et des pages que vous avez éditées (MyChanges).',
	'AddBookmark'				=> 'Ajouter la page actuelle aux favoris',
	'RemoveBookmark'			=> 'Retirer des favoris',

	'YourLanguage'				=> 'Sélectionner la langue',
	'ShowSpaces'				=> 'Afficher les espaces dans WikiNames',
	'WrongPage4Redirect'		=> 'Impossible de rediriger en raison d\'un mauvais paramètre de redirection',
	'RedirectsToItself'			=> 'La page se redirige vers elle-même.',
	'ReallyDeletePage'			=> 'Voulez-vous vraiment SUPPRIMER cette page ?<br>Il n\'y a pas d\'annulation pour cette action !<br><br>ATTENTION : La suppression de cette page supprimera toutes les versions, commentaires, pièces jointes, ACLs et référents.',
	'CommentForWatchedPage'		=> 'Nouveau commentaire pour la page ',
	'SomeoneCommented'			=> ' a commenté cette page que vous regardez : ',
	'AlertReferringPages'		=> 'Cette page est référencée par ces pages',

	'AccountDelete'				=> 'Supprimer le compte',
	'AccountDeleteConfirm'		=> 'Êtes-vous sûr de vouloir supprimer le compte ?',
	'AccountDeleted'			=> 'Compte supprimé avec succès',
	'AccountDeleteHeader'		=> 'Supprimer le compte %1',
	'AccountDeleteInfo'			=> 'Des données que vous avez créées (par exemple, e-mail, préférences, pièces jointes, entrées wiki) seront supprimées autant que possible. Notez toutefois que les données telles que les pièces jointes et les entrées wiki ne peuvent pas être supprimées sans entraver le travail des autres utilisateurs. Ces données sont donc réaffectées à un compte appelé %1. Comme les données de chaque compte supprimé sont réaffectées à ce compte, il ne sera pas possible de distinguer les données que vous avez créées des données d\'un autre compte supprimé.',
	'AccountDeleteWarning'		=> 'La suppression du compte utilisateur est une action irréversible.',
	'AccountDeleteHint'			=> 'Votre compte sera supprimé du système. Par conséquent, vous ne pourrez plus vous connecter avec vos identifiants actuels. Si vous choisissez de redevenir un utilisateur de cette application, vous pouvez le faire en utilisant les moyens accordés par cette application.',
	'AccountDeleteVerify'		=> 'Entrez votre identifiant %1 pour vérifier la suppression. Une fois soumis, il vous sera demandé de confirmer votre mot de passe.',

	'MarkRead'					=> 'Marquer tout comme lu',
	'CurrentTime'				=> 'Il est actuellement',
	'Created'					=> 'créé',
	'Modified'					=> 'modifié',

	'EditIcon'					=> 'éditer',
	'TreeClusterTitle'			=> 'Arbre de la grappe %1',
	'TreeSiteTitle'				=> 'Arborescence du site',
	'TreeEmpty'					=> '%1 n\'a pas de sous-pages',
	'TreeEmptyLevels'			=> '%1 n\'a pas de sous-pages pour des niveaux de profondeur donnés. Augmentez la valeur pour la profondeur.',
	'TreeTooBig'				=> 'trop de sous-pages',

	// clone handler
	'ClonePage'					=> 'Cloner la page',
	'CloneText'					=> 'Cloner',
	'CloneName'					=> 'Entrez un nouveau nom pour un clone de cette page',
	'CloneButton'				=> 'Cloner',
	'PageCloned'				=> 'Page %1 clonée.',
	'ClonedFrom'				=> 'Cloné de %1.',
	'MassClone'					=> 'Cloner toute la grappe',
	'MassCloning'				=> 'Clonage du cluster.',
	'CloneCannotRead'			=> 'Page %1 illisible.',
	'CloneCannotCreate'			=> 'Page incrémentale %1.',

	'SortComment'				=> 'Trier les commentaires par',
	'SortCommentAsc'			=> 'Plus récent en bas',
	'SortCommentDesc'			=> 'Les plus récents au premier plan',

	'RenamePage'				=> 'Renommer la page',
	'RenameText'				=> 'Renommer',
	'RenameTip'					=> 'Renommer la page',
	'NewName'					=> 'Entrez un nouveau nom pour cette page',
	'AlreadyExists'				=> 'La page %1 existe déjà.',
	'AlreadyNamed'				=> 'Cette page est déjà nommée %1.',
	'PageRenamed'				=> 'Page renommée.',
	'NewNameOfPage'				=> 'Nouveau nom de cette page : ',
	'NotOwnerCantRename'		=> 'Vous n\'êtes pas propriétaire de cette page et ne pouvez donc pas la renommer',
	'NeedRedirect'				=> 'Créer une redirection vers la nouvelle page sur l\'ancienne page',
	'RedirectCreated'			=> 'Dans la page %1 créé une redirection vers la nouvelle page',

	'UserSettings'				=> 'Paramètres de l\'utilisateur',
	'UserSettingsGeneral'		=> 'Généraux',
	'UserSettingsNotifications'	=> 'Notifications',

	'NotifyMinorEdit'			=> 'Notifier également les modifications mineures',
	'NotifyPageEdit'			=> 'Editer',
	'NotifyComment'				=> 'Commenter',
	'NotifyOff'					=> 'Désactivé',
	'NotifyAlways'				=> 'Toujours',
	'NotifyPending'				=> 'En attente',
	'NotifyDigest'				=> 'Résumé',
	'NotifyPendingPageTip'		=> 'Une seule notification est envoyée pour le changement de première page d\'une page que vous regardez.',
	'NotifyPendingCommentTip'	=> 'Une seule notification est envoyée pour le premier commentaire à une page que vous regardez.',
	'NotifyPendingTip'			=> 'La notification est automatiquement réactivée lorsque vous visitez la version actuelle de la page.',

	'FurtherPending'			=> 'Il n\'y aura aucune autre notification en cas de modifications ultérieures à moins que vous ne visitez cette page.',

	'UserSettingsEmailMe'		=> 'Envoyez-moi un e-mail quand ...',

	'UserSettingsExtended'		=> 'Étendu',
	'UserSettingsOther'			=> 'Autres paramètres',
	'UserSpace'					=> 'Espace utilisateur',
	'ChooseTheme'				=> 'Choisir un thème',

	'CreatePage'				=> 'Créer cette page',
	'CreateNewPage'				=> 'Créer une nouvelle page',
	'CreateNewPageText'			=> 'Créer',
	'CreateNewPageTip'			=> 'Créer une nouvelle page',

	'CreateRandomPage'			=> 'Créer une page au hasard:',
	'CreateSubPage'				=> 'Créer une sous-page dans le cluster :',
	'CreatePageParentCluster'	=> 'Créer une page dans le cluster parent :',
	'CreatePageDenied'			=> 'Vous n\'avez pas les droits d\'accès nécessaires.',
	'CreatePageDeniedAddress'	=> 'Vous n\'avez pas le droit de créer la page à cette adresse.',
	'PageAlreadyExists'			=> 'Selon l\'adresse indiquée, la page %1 existe déjà.',
	'PageAlreadyExistsEdit'		=> 'Voulez-vous %1?',
	'PageAlreadyExistsEdit2'	=> 'éditer',
	'PageAlreadyExistsEditDenied'	=> 'Vous ne pouvez pas l\'éditer.',

	'SimilarPagesExists'		=> 'Des pages similaires à %1 existent déjà:',
	'SimilarPagesHint'			=> 'Il existe des pages similaires à %1:',

	'PageReservedWord'			=> 'Vous ne pouvez pas utiliser %1 comme partie de l\'adresse car c\'est un mot réservé.',
	'UserReservedWord'			=> 'Les noms d\'utilisateurs ne peuvent pas contenir %1 car c\'est un mot réservé.',

	'DontRedirect'				=> 'Ne pas autoriser la redirection automatique par redirection d\'action.',
	'SendWatchEmail'			=> 'Envoyer un e-mail de notification lorsque quelqu\'un (sauf vous) modifie la page que vous regardez',
	'AllowIntercom'				=> 'Autoriser les messages personnels des utilisateurs du système',
	'AllowMassemail'			=> 'Les administrateurs peuvent m\'envoyer des informations par e-mail',
	'HideLastSession'			=> 'Cacher la dernière session',
	'ValidateIP'				=> 'Session liée à l\'IP',
	'AnonymousPub'				=> 'De préférence, publié de manière anonyme (pour cacher le nom)',
	'PageMoved'					=> 'Cette page a été déplacée. Vous pouvez la trouver sur',
	'RedirectedFrom'			=> 'Redirigé depuis %1',
	'RedirectedTo'				=> 'Redirigé vers',
	'CurrentPassword'			=> 'Mot de passe actuel',
	'NewPassword'				=> 'Nouveau mot de passe',
	'YouWantChangePassword'		=> 'Changer le mot de passe',
	'ChangePasswordButton'		=> 'Changer le mot de passe',
	'PasswordChanged'			=> 'Mot de passe modifié',
	'EmailWelcome'				=> 'Vous vous êtes inscrit à ',
	'EmailRegistered'			=> 'Vous vous êtes inscrit avec succès à %1.' . "\n" . 'Votre nom d\'utilisateur : %2' . "\n\n",
	'EmailVerify'				=> 'Si vous souhaitez recevoir des notifications, vous devez vérifier votre adresse e-mail. Veuillez cliquer sur ou copier le lien suivant dans un navigateur web : ' . "\n" . '%1',
	'EmailRegisteredLogin'		=> 'Veuillez retourner au Wiki et vous connecter avec votre nouveau nom d\'utilisateur et votre nouveau mot de passe.',
	'EmailRegisteredIgnore'		=> 'Si vous n\'avez pas demandé cette inscription, ignorez ce message et rien ne se passera.',
	'EmailDoNotReply'			=> 'Ne répondez pas à ce message.',
	'EmailReverify'				=> 'Quelqu\'un (peut-être vous) a envoyé votre e-mail comme adresse de notification à %1.' . "\n" . 'Votre nom d\'utilisateur : %2'."\n\n" . 'Si vous souhaitez recevoir des notifications, vous devez approuver votre e-mail. Veuillez suivre le lien pour le faire.' . "\n" . '%3' . "\n\n",
	'EmailConfirm'				=> 'Veuillez vérifier votre adresse e-mail',
	'EmailConfirmed'			=> 'Courriel confirmé avec succès.',
	'EmailNotConfirmed'			=> 'L\'e-mail ne peut pas être confirmé. Cela peut être dû à un code de confirmation incorrect ou l\'adresse e-mail peut déjà être confirmée. Vous pouvez vérifier si l\'adresse e-mail est déjà confirmée en vous connectant et en visualisant son statut sur votre page %1.',
	'EmailNotVerified'			=> 'Courriel non vérifié!',
	'EmailNotVerifiedDesc'		=> 'Vous ne recevrez pas de notification de modifications ou de commentaires de pages regardées, ' .
									'ou les messages d\'autres utilisateurs. De plus, vous <strong>ne pourrez pas récupérer un mot de passe oublié</strong>, ' .
									'jusqu\'à ce que votre adresse e-mail soit confirmée en suivant le lien dans l\'e-mail qui vous a été envoyé. ' .
									'Si, dans les jours suivant votre inscription, vous ne recevez pas de courriel, demandez-le à nouveau en cliquant sur ',

	'ForgotPasswordHint'		=> 'Entrez votre login et votre adresse e-mail' . "\n" . 'alors un email contenant les instructions vous sera envoyé.',
	'ForgotPassword'			=> 'Mot de passe oublié ?',
	'UserNotFound'				=> 'L\'utilisateur avec ce nom ou cette adresse e-mail n\'a pas été trouvé.',
	'NotConfirmedEmail'			=> 'Your email address is not confirmed.<br>Mail can\'t be send to a non-confirmed address.',
	'EmailForgotSubject'		=> 'Renouvellement du mot de passe pour ',
	'EmailForgotMessage'		=> 'Quelqu\'un (peut-être vous) a oublié votre mot de passe pour %1.' . "\n" . 'Votre identifiant : %2'."\n\n" . 'Cliquez sur le lien ou copiez-le sur la ligne d\'adresse du navigateur pour changer votre mot de passe.' . "\n" . '%3'."\n\n",
	'CodeWasSent'				=> 'Les instructions de récupération de mot de passe vous ont été envoyées par courriel.',
	'WrongCode'					=> 'Mauvais code',
	'ChangePasswordForUser'		=> 'Changement de mot de passe de l\'%1',

	'Watchers'					=> 'Liste des observateurs pour %1',
	'WatchersFor'				=> 'Observateurs pour',
	'NoWatchers'				=> 'Il n\'y a aucun observateur pour %1',
	'NotOwnerToViewWatchers'	=> 'Vous n\'êtes pas le propriétaire de cette page et vous ne pouvez pas voir la liste des observateurs pour elle.',

	// thumbnail
	'TbnError'					=> 'Erreur lors de la création de la miniature : %1',
	'TbnImageAreaTooBig'		=> 'Fichier avec des dimensions supérieures à %1',
	'TbnImageMissing'			=> 'Le fichier semble manquant: %1',

	// admin_recovery action
	'GenerateRecoveryHash'		=> 'Générer le hachage du mot de passe pour votre <code>recovery_password</code>',

	// import action
	'ImportTo'					=> 'Importer dans le cluster :',
	'ImportWhat'				=> 'Fichier XML à importer :',
	'ImportButton'				=> 'Importation',
	'ImportSuccess'				=> 'Importé avec succès.',
	'ImportFailed'				=> 'Échec de l\'importation.',
	'ImportHint'				=> 'Veuillez fournir un cluster vers lequel vous voulez importer, pas d\'adresse relative.',
	'ImportAttention'			=> 'Attention : Écrase les mêmes pages du cluster.',
	'ImportNote'				=> 'Page importée',

	// mywatches action
	'WatchedPages'				=> 'Liste de toutes les pages que vous suivez pour les modifications ',
	'UnwatchedPages'			=> 'Liste de toutes les pages que vous ne suivez pas',
	'NoWatchedPages'			=> 'Vous n\'avez aucune page regardée.',
	'NoUnwatchedPages'			=> 'Vous surveillez les changements dans toutes les pages.',
	'ViewWatchedPages'			=> 'Afficher les pages vues',
	'ViewUnwatchedPages'		=> 'Afficher la page non vue',
	'NotLoggedInWatches'		=> 'Vous n\'êtes pas connecté, nous n\'avons donc pas pu identifier votre liste de montres.',

	// mychangeswatches action
	'MyChangesWatches'			=> 'Liste de toutes les pages que vous avez regardées qui ont été modifiées par d\'autres depuis votre dernière édition',
	'ResetChangesWatches'		=> 'réinitialiser la liste des modifications',
	'NoChangesWatches'			=> 'Parmi vos pages regardées ne sont pas modifiées...',

	// whatsnew action
	'NewCommentAdded'			=> 'Nouveau commentaire ajouté',
	'NewFileAdded'				=> 'Nouveau fichier ajouté',
	'NewPageCreated'			=> 'Nouvelle page créée',
	'NewRevisionAdded'			=> 'Page modifiée',
	'Cluster'					=> 'grappe',
	'PageDeleted'				=> 'Page supprimée',
	'CommentDeleted'			=> 'Commentaire supprimé',
	'FileDeleted'				=> 'Fichier supprimé',

	// users action
	'UsersSearch'				=> 'Trouver des utilisateurs',
	'UsersOpenProfile'			=> 'Voir le profil',
	'UsersNoMatching'			=> 'Utilisateurs correspondants non trouvés. Essayez un critère de recherche moins strict.',
	'UsersName'					=> 'Nom',
	'UsersPages'				=> 'Pages',
	'UsersChanges'				=> 'Changements',
	'UsersSubscription'			=> 'Abonnement',
	'UsersWatches'				=> 'Montres',
	'UsersComments'				=> 'Commentaires',
	'UsersUploads'				=> 'Téléversements',
	'UploadQuota'				=> 'Espace utilisé',
	'UploadQuotaTip'			=> 'Quota d\'espace de téléchargement',
	'UsersLogins'				=> 'Connexions',
	'UsersRevisions'			=> 'Révisions',
	'UsersSignup'				=> 'Inscription',
	'UsersLastSession'			=> 'Dernière session',
	'UsersNotFound'				=> 'Utilisateur %2 introuvable. Cliquez sur <a href="%1">ici</a>pour accéder à la liste principale.',
	'UsersProfile'				=> 'Profil',
	'UsersContact'				=> 'Contacter',
	'UsersList'					=> 'Voir la liste complète des utilisateurs',
	'UsersNA'					=> '[non défini]',
	'UsersNA2'					=> '[No]',
	'UsersSignupDate'			=> 'Date d\'inscription',
	'UsersGroupMembership'		=> 'Adhésion au groupe',
	'UsersPersonalInfo'			=> 'Infos personnelles',
	'UsersOwnedPages'			=> 'Pages possédées :',
	'UsersCommentsPosted'		=> 'Commentaires postés :',
	'UsersFilesUploaded'		=> 'Fichiers téléchargés :',
	'UsersRevisionsMade'		=> 'Révisions faites :',
	'UsersDocsSortName'			=> '[Trier par nom]',
	'UsersDocsSortCreation'		=> '[Trier par date de création]',
	'UsersChangesSortAsc'		=> '[Tri ascendant]',
	'UsersChangesSortDesc'		=> '[Tri décroissant]',
	'UsersSessionNA'			=> '[non enregistré]',
	'UsersSessionHidden'		=> '[hidden]',
	'IntercomSubject'			=> 'Objet:',
	'IntercomMessage'			=> 'Message :',
	'IntercomCopy'				=> 'Envoyez-moi une copie',
	'IntercomSubjectN'			=> '[démarrer un nouveau sujet]',
	'IntercomDisabled'			=> 'Désolé, vous ne voulez pas ou ne pouvez pas recevoir de messages personnels.',
	'IntercomHint'				=> 'Veuillez d\'abord vous connecter et suivre le lien à nouveau, si vous voulez répondre au message personnel que vous avez reçu.',
	'IntercomDesc'				=> 'Remarque : Envoi de messages personnels sur le destinataire sans divulguer votre adresse. Le destinataire pourra vous répondre en utilisant un formulaire similaire sur votre page de profil. ',
	'PMOversized'				=> 'La longueur du message dépasse la taille maximale autorisée par %1. Veuillez raccourcir votre message et soumettre à nouveau.',
	'PMFlooded'					=> 'L\'intervalle entre l\'envoi de messages personnels ne doit pas être inférieur à %1 secondes.',
	'PMSent'					=> 'Le message personnel a été envoyé à l\'utilisateur avec succès.',
	'PMBody'					=> 'Ce message vous a été envoyé par l\'utilisateur %1.',
	'PMBodyCopy'				=> 'Vous avez envoyé le message suivant à l\'utilisateur %1.',
	'PMReply'					=> 'Pour répondre à cet e-mail, cliquez sur le lien suivant (n\'utilisez pas le bouton Répondre / Répondre dans le courrier) :',
	'PMNotLoggedIn'				=> 'Vous n\'êtes pas enregistré dans le système et ne pouvez pas envoyer de messages personnels aux utilisateurs.',

	// admin_replace action
	'ReplaceText'				=> 'Remplacer le texte',
	'TextOriginal'				=> 'Texte original :',
	'TextReplacement'			=> 'Texte de remplacement :',
	'ReplaceTextRegex'			=> 'Utiliser des expressions régulières',
	'Namespace'					=> 'Espace de nommage :',
	'ReplaceTextCluster'		=> 'Rechercher et remplacer uniquement dans cette grappe :',
	'ReplaceTextEditPages'		=> 'Remplacer le texte dans le contenu de la page',
	'ReplaceTextEditComments'	=> 'Remplacer le texte dans les commentaires',
	'ReplaceTextEditTitles'		=> 'Remplacer le texte dans les titres de la page',
	'ReplaceTextGiveTarget'		=> 'Vous devez spécifier la chaîne à remplacer.',
	'ReplaceTextNoNamespace'	=> 'Vous devez sélectionner au moins un espace de noms.',
	'ReplaceTextNoDifference'	=> 'Il n\'y a pas de différence entre remplacer le texte et le texte cible.',
	'ReplaceTextNoOption'		=> 'Vous devez sélectionner au moins une des options de remplacement.',
	'ReplaceTextPagesEdit'		=> 'Remplacer %1 par %2 dans le texte des pages %3 suivantes :',
	'ReplaceTextTitlesEdit'		=> 'Remplacer %1 par %2 dans les titres des pages %3 suivantes :',
	'ReplaceTextReplace'		=> 'Remplacer',
	'ReplaceTextSuccess'		=> '%1 a été remplacé par %2 dans les pages %3.',
	'ReplaceTextNoMatch'		=> 'Aucune page ne contient la chaîne %1.',
	'ReplaceTextNoTitleMatch'	=> 'Aucune page qui contient le titre %1 n\'a été trouvée.',
	'ReplaceTextEditFailed'		=> 'Échec du remplacement du texte',
	'ReplaceTextTitleTooBig'	=> 'Le texte original ou le texte de remplacement est trop grand pour le titre.',
	'ReplaceTextReturn'			=> 'Retour au formulaire',
	'ReplaceTextWarning'		=> 'Attention : Il y a des pages %1 qui contiennent déjà la chaîne de remplacement, %2. Si vous faites ce remplacement, vous ne serez pas en mesure de séparer vos remplacements de ces chaînes.',
	'ReplaceTextBlankWarning'	=> 'Attention : Comme la chaîne de remplacement est vide, cette opération ne sera pas réversible.',
	'ReplaceTextEditSummary'	=> 'Remplacement du texte : %1 → %2',
	'InvertSelection'			=> 'Inverser la sélection',

	// Properties
	'PropertiesFor'				=> 'Propriétés de la page pour %1',
	'MetaTag'					=> 'Étiquette',
	'MetaTitle'					=> 'Titre de la page',
	'MetaKeywords'				=> 'Mots clés',
	'MetaDescription'			=> 'Libellé',
	'On'						=> 'Activé',
	'Off'						=> 'Désactivé',
	'Registered'				=> 'Enregistré',
	'MetaComments'				=> 'Afficher les commentaires',
	'MetaFiles'					=> 'Afficher le panneau des fichiers',
	'MetaToc'					=> 'Afficher la table des matières',
	'MetaIndex'					=> 'Afficher le panneau de section du cluster',
	'MetaIndexMode'				=> 'Afficher le mode de niveau',
	'MetaIndexFull'				=> 'Arborescence',
	'MetaIndexUpper'			=> 'Supérieur',
	'MetaIndexLower'			=> 'Inférieur',
	'MetaHtml'					=> 'Support HTML pour la page',
	'MetaSafeHtml'				=> 'Filtrage du HTML dangereux',
	'MetaTypografica'			=> 'Relecteur de texte',
	'MetaNoIndex'				=> 'Bloquer les moteurs de recherche',
	'SettingsID'				=> 'ID de la page',
	'SettingsSize'				=> 'Taille',
	'SettingsSizeTip'			=> 'source / compilé',
	'SettingsCreated'			=> 'Créé',
	'SettingsCurrent'			=> 'Modifié',
	'SettingsTotalRevs'			=> 'Révisions',
	'SettingsTotalComs'			=> 'Commentaires',
	'SettingsWatchers'			=> 'Observateurs',
	'SettingsHits'				=> 'Vues',
	'SettingsText'				=> 'Réglages',
	'SettingsEdit'				=> 'Editer',
	'SettingsRevisions'			=> 'Révisions',
	'SettingsClone'				=> 'Cloner',
	'SettingsRename'			=> 'Renommer',
	'MassRename'				=> 'pour l\'ensemble du cluster',
	'SettingsRemove'			=> 'Retirer',
	'SettingsPurge'				=> 'Purge',
	'SettingsModerate'			=> 'Modérée',
	'SettingsPermissions'		=> 'Permissions',
	'AclForEntireCluster'		=> 'pour l\'ensemble du cluster',
	'SettingsAttachments'		=> 'Fichiers joints',
	'SettingsUpload'			=> 'Charger',
	'SettingsCategories'		=> 'Catégories',
	'SettingsLanguages'			=> 'Langues',
	'SettingsReferrers'			=> 'Référents',
	'SettingsWatch'				=> 'Regarder',
	'SettingsLatex'				=> 'Version LaTeX',
	'SettingsXML'				=> 'Exporter vers XML',
	'NeedToChangeLang'			=> 'La langue de la page %1 non prise en charge doit être modifiée.',
	'SetLang'					=> 'Langue de cette page',
	'SetMenuLabel'				=> 'Étiquette de menu',
	'SetShowMenuLabel'			=> 'Afficher dans la navigation',

	// upload
	'UploadFiles'				=> 'Charger des fichiers',
	'UploadFor'					=> 'Envoi de fichiers:',
	'UploadButton'				=> 'Charger',
	'UploadGlobalText'			=> 'pour un accès public',
	'UploadGlobal'				=> 'global',
	'UploadLocalText'			=> 'uniquement pour les utilisateurs autorisés à voir la page courante',
	'UploadAsName'				=> 'Nom:',
	'UploadOverwrite'			=> 'Écraser les fichiers existants',
	'FileDesc'					=> 'Description :',
	'UploadForbidden'			=> 'Vous n\'êtes pas autorisé à télécharger des fichiers ici.',
	'UploadOverwriteDenied'		=> 'Seul le propriétaire ou l\'administrateur du fichier peut écraser le fichier %1.',
	'UploadNoFile'				=> 'Il n\'y avait pas de fichier dans le formulaire, pour une raison quelconque.',
	'UploadMaxSizeReached'		=> 'La taille du fichier est supérieure à la limite autorisée !',
	'UploadDirNotWritable'		=> 'Le répertoire de fichiers n\'est pas accessible en écriture !',
	'UploadNotAPicture'			=> 'Les téléchargements de photos sont uniquement autorisés. Qu\'est-ce que vous essayez de télécharger ?',
	'UploadEmptyExtension'		=> 'Le nom du fichier et l\'extension ne peuvent pas être vides.',
	'FilenameTooLong'			=> 'Les noms de fichiers ne peuvent pas être plus longs que 240 octets.',
	'BannedFiletype'			=> '%1 n\'est pas un type de fichier autorisé.',
	'PermittedFiletype'			=> 'Types de fichiers autorisés :',
	'UploadMimeMismatch'		=> 'L\'extension de fichier %1 ne correspond pas au type MIME détecté du fichier (%2).',
	'UploadBadMime'				=> 'Les fichiers de type MIME %1 ne sont pas autorisés à être téléchargés.',
	'FileIsDuplicate'			=> 'Le téléchargement est un doublon exact de la version actuelle.',
	'FileHasDuplicate'			=> 'Ce fichier est un doublon des fichiers suivants :',

	'UploadMaxFileQuota'		=> 'Vous avez atteint votre limite de téléchargement. Ce fichier ne peut pas être téléchargé',
	'UploadDone'				=> 'Téléchargement du fichier réussi',
	'UploadFileForbidden'		=> 'Accès au fichier interdit',
	'UploadTitle'				=> 'Fichiers accessibles depuis cette page',
	'UploadTitleGlobal'			=> 'Fichiers accessibles depuis n\'importe où',

	'UploadFile'				=> 'Charger',
	'UploadMax'					=> 'Pas plus de ',
	'UploadUsedStorage'			=> 'Stockage en cours d\'utilisation ',

	// attachments
	'Attachments'				=> 'Fichiers joints',
	'Attachment'				=> 'Pièce jointe',
	'AttachmentsToPage'			=> 'à la page',
	'AttachmentsToCluster'		=> 'grappe',
	'AttachmentsByTime'			=> 'par temps',
	'AttachmentsGlobal'			=> 'global',
	'AttachmentsAll'			=> 'Tous',
	'AttachmentsLinked'			=> 'utilisé',

	'FileViewProperties'		=> 'Voir',
	'FileViewPropertiesTip'		=> 'Voir les métadonnées de ce fichier',
	'FileEditProperties'		=> 'Editer',
	'FileEditPropertiesTip'		=> 'Modifier les métadonnées de ce fichier',
	'FileEditedMeta'			=> 'Métadonnées de ce fichier mises à jour',
	'FileEditDenied'			=> 'Vous n\'êtes pas autorisé à modifier ce fichier',
	'FileLabel'					=> 'Étiquette',
	'FileLabelTip'				=> 'Étiqueter ce fichier',
	'FileRemove'				=> 'Retirer',
	'FileRemovedFromDB'			=> 'Fichier supprimé de la base de données',
	'FileRemovedFromFS'			=> 'Fichier effacé de l\'hébergement physique',
	'FileRemovedFromFSError'	=> 'Il semble impossible d\'effacer le fichier !',
	'FileRemoveConfirm'			=> 'Êtes-vous sûr de vouloir supprimer ce fichier ?',
	'FileRemoveDenied'			=> 'Vous n\'êtes pas autorisé à supprimer ce fichier',
	'FileNotFound'				=> 'Fichier introuvable.',

	'FileSearch'				=> 'Rechercher un fichier',
	'UploadBy'					=> 'Envoyé par:',
	'FileAdded'					=> 'Ajouté:',
	'FileModified'				=> 'Modifié :',
	'FileSize'					=> 'Taille:',
	'FileDimension'				=> 'Dimensions:',
	'MimeType'					=> 'Mimetype:',
	'FileName'					=> 'Nom:',
	'FileCaption'				=> 'Légende :',
	'FileAuthor'				=> 'Auteur:',
	'FileSource'				=> 'Source :',
	'FileSourceUrl'				=> 'URL :',
	'FileAttachedTo'			=> 'Attaché à:',
	'FileSyntax'				=> 'Syntaxe :',
	'FileAbsolutePath'			=> 'chemin absolu',
	'FileRelativePath'			=> 'chemin relatif',
	'FileUsage'					=> 'Utilisation du fichier :',
	'FileUsageText'				=> 'Les pages suivantes ont un lien vers ce fichier :',
	'NoFileUsage'				=> 'Aucun lien de page vers ce fichier.',

	'FileSortExt'				=> 'extension',
	'FileSortName'				=> 'Nom',
	'FileSortSize'				=> 'taille',
	'FileSortTime'				=> 'créé',

	'SortBy'					=> 'Trier par',
	'Ascending'					=> 'ascendant',
	'Decending'					=> 'décevant',

	'Files0'					=> 'Joindre des fichiers',
	'Files1'					=> 'Afficher les fichiers (1 fichier)',
	'FilesN'					=> 'Afficher les fichiers (%1 fichiers)',
	'Files'						=> 'Fichiers',
	'File'						=> 'Fichier',
	'ShowFiles'					=> 'Afficher les fichiers / formulaire',
	'HideFiles'					=> 'Cacher les fichiers / formulaire',
	'DoShowFiles'				=> 'Afficher les listes de fichiers par défaut',
	'NoAttachments'				=> 'Il n\'y a aucun fichier joint à afficher.',

	'RegistrationLang'			=> 'Votre langue',
	'InvalidWikiName'			=> 'Le nom choisi n\'est pas valide',
	'InvalidUserName'			=> 'Le nom d\'utilisateur choisi n\'est pas valide',
	'Bookmarks'					=> 'Signets',
	'ReallyDeleteComment'		=> 'Voulez-vous vraiment SUPPRIMER ce commentaire ?<br>Il n\'y a pas d\'annulation pour cette action !',
	'ReallyDeleteRevision'		=> 'Voulez-vous vraiment SUPPRIMER cette révision ?<br>Il n\'y a pas d\'annulation pour cette action !',

	'RegistrationClosed'		=> 'L\'inscription n\'est pas disponible ici. Essayez de contacter l\'administrateur du site.',
	'AclAreYouSure'				=> 'Vous allez changer les ACLs de cette page et de toutes ses sous-pages. Continuer ?',

	'BookmarkDeleteSelected'	=> 'Supprimer la sélection',
	'BookmarkMark'				=> 'Marquer',
	'BookmarkNumber'			=> 'Non.',
	'BookmarkNone'				=> 'Vous n\'avez pas de signets.',
	'BookmarkTitle'				=> 'Titre du favori',
	'BookmarkPage'				=> 'Page',
	'BookmarkSaveChanges'		=> 'Enregistrer les modifications',
	'BookmarksAddPage'			=> 'Définir un signet pour la page suivante',
	'BookmarkAlreadyExists'		=> 'Ce favori existe déjà.',

	'PoweredBy'					=> 'Propulsé par',

	'MassRenaming'				=> 'Renommer l\'ensemble du cluster',
	'MassNewName'				=> 'Entrez un nouveau nom pour ce cluster',
	'MassNeedRedirect'			=> 'Créer une redirection vers les nouvelles pages sur les anciennes pages',

	// pagination
	'ToOverview'				=> 'Retour à la vue d\'ensemble',
	'Overview'					=> 'Aperçu',
	'ToThePage'					=> 'Vers la page :',
	'Next'						=> 'Suivant',
	'Prev'						=> 'Précédent',
	'NextAcr'					=> 'Suivant',
	'PrevAcr'					=> 'Précédent',
	'Back'						=> 'Précédent',

	// filter
	'Filter'					=> 'Filtre',
	'OptionalFilters'			=> 'Filtres optionnels :',
	'Any'						=> 'N\'importe quel',

	// My Groups
	'UserGroups'				=> 'Groupes d\'utilisateurs',
	'MyGroups'					=> 'Associations de groupe',
	'Group'						=> 'Groupe',
	'Groups'					=> 'Groupes',

	// license action
	'DistributedUnder'			=> 'Le matériel est distribué sous',
	'AuthorsDisplayHint'		=> 'La liste des auteurs sera affichée lors de l\'enregistrement de la page.',
	'AnonymousUsers'			=> 'Utilisateurs anonymes',
	'License'					=> 'Licence',
	'LicenseArray'				=> [
		'1'		=> 'Attribution-Pas de Modification',
		'2'		=> 'Attribution-Pas d\'Utilisation Commerciale-Partage à l\'identique',
		'3'		=> 'Attribution-Pas d\'Utilisation Commerciale-Pas de Modification',
		'4'		=> 'Attribution-Partage à l\'identique',
		'5'		=> 'Attribution-Non Commercial',
		'6'		=> 'Attribution',
		'7'		=> 'CC0 1.0 Universal',
		'8'		=> 'Licence de documentation libre GNU',
		'9'		=> 'Domaine public / Utilisation gratuite',
		'10'	=> 'Tous droits réservés',
	],
	'LicenseMeta'				=> [
		'1'		=> 'Domaine public',
		'2'		=> 'Certains droits réservés',
		'3'		=> 'Tous droits réservés',
	],

	// Cache
	'ClearCache'				=> 'Vider le cache',
	'CacheCleared'				=> 'Cache effacé.',
	'ConfigCache'				=> 'Cache de configuration',
	'FeedCache'					=> 'Cache du flux',
	'PageCache'					=> 'Cache de page',
	'SQLCache'					=> 'Cache SQL',
	'TemplateCache'				=> 'Cache du modèle',
	'ThumbCache'				=> 'Thumbnail cache',

	// Embed
	'EmbedNoURL'				=> 'Veuillez spécifier une adresse de la ressource avec l\'URL du paramètre. (par exemple {{embed url="https://example.com/embed/video.mp4"}} )',

	// Feed
	'FeedTitle'					=> 'Titre du flux',
	'FeedMulti'					=> 'Multi-flux',
	'FeedNoURL'					=> 'Veuillez spécifier un flux avec l\'URL du paramètre. (par exemple {{feed url="https://example.com/feed.xml"}} )',
	'FeedError'					=> 'Impossible de charger ou d\'analyser le flux',
	'FeedSource'				=> 'Source :',
	'FeedXMLTip'				=> '',

	// XML / RSS autodiscovery
	'ChangesXMLTitle'			=> ' - Changements récents',
	'ChangesXML'				=> 'Modifications récentes de la ',
	'CommentsXMLTitle'			=> ' - Commentaires récents',
	'CommentsXML'				=> 'Commentaires récents sur le ',
	'NewsXMLTitle'				=> ' - Actualités récentes',
	'NewsXML'					=> 'Nouvelles récentes de la ',
	'RevisionXMLTip'			=> 'Cliquez pour voir les révisions récentes de la page au format XML.',
	'CommentsXMLTip'			=> 'Cliquez pour voir les commentaires récents au format XML.',
	'ChangesXMLTip'				=> 'Cliquez pour voir les changements récents au format XML.',
	'NewsXMLTip'				=> 'Cliquez pour voir les dernières actualités au format XML.',
	'RevisionsXML'				=> 'Révisions de ',
	'ExportClusterXML'			=> 'Exportation de l\'ensemble du cluster de ',
	'AccessDeniedXML'			=> 'Vous n\'êtes pas autorisé à accéder à ces informations.',

	'ChangesFeed'				=> 'Changements',
	'CommentsFeed'				=> 'Commentaires',
	'NewsFeed'					=> 'Actualités',
	'RevisionsFeed'				=> 'Révisions de ',

	'LastModification'			=> 'Dernière modification',

	// Captcha
	'Captcha'					=> 'Veuillez taper le mot que vous avez lu dans l\'image',
	'CaptchaFailed'				=> 'Vous avez entré le mot captcha incorrectement. Veuillez réessayer.',
	'CaptchaReload'				=> 'Nouveau Captcha',
	'CaptchaReloadWarning'		=> 'Désolé, impossible de recharger l\'image captcha, vous devrez recharger la page pour faire cela',

	// news
	'News'						=> 'Actualités',
	'NewsName'					=> 'Titre:',
	'NewsNoName'				=> 'Vous avez oublié d\'ajouter les titres des nouvelles.',
	'NewsNotAvailable'			=> 'Aucune Actualité disponible.',
	'NewsNoClusterDefined'		=> 'Aucun cluster d\'actualités défini.',
	'NewsDiscuss'				=> 'Discuter de cet article...',

	// blog
	'BlogNewTopic'				=> 'Créer un nouveau message',
	'NoPostAvailable'			=> 'Aucun message disponible pour le moment.',

	// Review
	'Reviewer'					=> 'Evaluateur',
	'Reviewed'					=> 'revu',
	'Review'					=> 'Revoir',
	'ReviewedBy'				=> 'révisé par',
	'RemoveReview'				=> 'Supprimer la revue pour cette page',
	'SetReview'					=> 'Revu cette page',
	'SetAsReviewed'				=> 'Définir la page comme revue',
	'SetAsUnreviewed'			=> 'Définir la page comme non révisée',

	// word filter
	'PotentialSpam'				=> 'Spam potentiel identifié',

	// moderation handler
	'Moderation'				=> 'Modération',
	'Topics'					=> 'Sujets',
	'ModerateSection'			=> 'section / page ',

	'NotModerator'				=> 'Vous n\'avez pas l\'autorisation de modérer cette page / chapitre',
	'ModerateDeleteTopic'		=> 'Supprimer le sujet / la page',
	'ModerateDeletePosts'		=> 'Supprimer les commentaires',
	'ModerateMove'				=> 'Déplacer',
	'ModerateSplit'				=> 'Diviser / Déplacer les commentaires',
	'ModerateMerge'				=> 'Fusionner',
	'ModerateLock'				=> 'Verrouiller',
	'ModerateUnlock'			=> 'Déverrouiller',
	'ModerateAccept'			=> 'Accepter',
	'ModerateDeleteConfirm'		=> 'Êtes-vous sûr de vouloir <strong>supprimer</strong> les sujets suivants ?',
	'ModerateRenameConfirm'		=> 'Entrez un nouveau titre pour la page sélectionnée',
	'ModerateRenameExists'		=> 'Une page avec le même nom existe déjà ! Choisissez un nom différent.',
	'ModerateRename1Only'		=> 'Note: seule la première page que vous avez sélectionnée sera renommée!',
	'ModerateMovesConfirm'		=> 'Sélectionnez la partition cible vers laquelle déplacer le forum',
	'ModerateMoveConfirm'		=> 'Sélectionnez le forum ou spécifiez le cluster pour déplacer ces sujets. Pour déplacer une page à la racine du site, tapez &quot;/&quot;',
	'ModeratePgMoveConfirm'		=> 'Spécifie le nom du cluster dans lequel placer la page. Pour déplacer une page à la racine du site, tapez &quot;/&quot;',
	'ModerateMoveExists'		=> 'Opération annulée : Dans cette section existe déjà des sujets du même nom %1. Si vous avez encore besoin de transférer les sujets mentionnés ci-dessus, veuillez les renommer d\'abord.',
	'ModerateMoveNotExists'		=> 'La page / cluster n\'existe pas. Veuillez vérifier le nom et réessayer.',
	'ModerateMergeConfirm'		=> 'Choisissez un sujet, qui devrait combiner le reste',
	'ModerateMerge2Min'			=> 'Pour vous inscrire, vous devez sélectionner au moins deux sujets !',
	'ModerateComDelConfirm'		=> 'Êtes-vous sûr de vouloir <strong>supprimer</strong> %1 %2?',
	'ModerateComment'			=> 'Commenter',
	'ModerateComments'			=> 'Commentaires',
	'ModerateSplitNewName'		=> 'Spécifiez un nom pour un sujet séparable et sélectionnez un schéma de séparation',
	'ModerateSplitPageName'		=> 'Entrez le nom de la page / sujet, où déplacer les commentaires détachables, et sélectionnez un schéma de séparation',
	'ModerateSplitAllAfter'		=> 'Détacher tous les commentaires après la première sélection (et incluse)',
	'ModerateSplitSelected'		=> 'Seulement les commentaires sélectionnés séparés (total %1)',
	'ModerateUserProfile'		=> 'profil',
	'ModerateNoItemChosen'		=> 'Veuillez sélectionner au moins un élément via le bouton \'Définir\'.',

	'ModerateSection2'			=> 'section modérée',
	'ModerateTopicsDeleted'		=> 'Thèmes sélectionnés supprimés avec succès.',
	'ModerateTopicsRelocated'	=> 'Sujets sélectionnés déplacés avec succès.',
	'ModerateTopicsRenamed'		=> 'Sujet renommé avec succès.',
	'ModerateTopicsMerged'		=> 'Sujets sélectionnés fusionnés avec succès.',
	'ModerateTopicsBlocked'		=> 'Thèmes sélectionnés bloqués avec succès',
	'ModerateTopicsUnlocked'	=> 'Sujets sélectionnés déverrouillés avec succès.',
	'ModerateTopicDeleted'		=> 'Le sujet a été supprimé avec succès.',
	'ModeratePageMoved'			=> 'Page déplacée avec succès.',
	'ModerateTopicRenamed'		=> 'Sujet renommé avec succès.',
	'ModerateTopicBlocked'		=> 'Sujet bloqué avec succès',
	'ModerateTopicUnlocked'		=> 'Sujet déverrouillé avec succès.',
	'ModerateCommentsDeleted'	=> 'Les commentaires sélectionnés ont été supprimés avec succès.',
	'ModerateCommentsSplit'		=> 'Les commentaires sélectionnés ont été séparés avec succès dans une nouvelle discussion.',
	'ModerateCommentsSplitFailed'	=> 'Remarque : Pour une raison quelconque, la séparation des commentaires sélectionnés avec un nouveau sujet a échoué.<br>Habituellement, cela ne devrait pas se produire, donc veuillez en informer l\'administrateur du site.<br>Par précaution, la question a été préservée sous sa forme originale.',
	'ModerateCommentsMoved'		=> 'Les commentaires sélectionnés ont été migrés avec succès vers la page donnée.',

	// forum
	'ForumSubforums'			=> 'Forums',
	'ForumTopic'				=> 'Sujet',
	'ForumTopics'				=> 'Sujets',
	'ForumPosts'				=> 'Publications',
	'ForumReplies'				=> 'Réponses',
	'ForumAuthor'				=> 'Auteur',
	'ForumViews'				=> 'Vues',
	'ForumCreated'				=> 'Créé',
	'ForumComments'				=> 'Commentaires',
	'ForumLastComment'			=> 'Dernier commentaire',
	'ForumNoComments'			=> 'Aucun commentaire',
	'ForumNoTopics'				=> 'Il n\'y a aucun sujet ou message dans ce forum.',
	'ForumNewTopic'				=> 'Commencer une nouvelle discussion',
	'ForumTopicName'			=> 'Nom du sujet:',
	'ForumTopicSubmit'			=> 'Soumettre le sujet',
	'ForumNoTopicName'			=> 'Spécifiez un nom pour la nouvelle page.',
	'ForumNewPosts'				=> 'nouvelle publication',
	'ForumLocked'				=> 'section verrouillée',
	'ForumUpdated'				=> 'Mis à jour',
	'ForumNoClusterDefined'		=> 'Aucune instance de forum définie.',
	'ForumOutsideCluster'		=> 'Assurez-vous que l\'action %1 se trouve dans la grappe de forums.',

	// password complexity
	'PwdCplxShort'				=> 'Le mot de passe est trop court.',
	'PwdCplxEquals'				=> 'Le mot de passe contient le nom d\'utilisateur.',
	'PwdCplxWeak'				=> 'Le mot de passe ne répond pas aux exigences de complexité.',
	'PwdCplxDesc1'				=> 'Exigences pour le mot de passe : ',
	'PwdCplxDesc2'				=> 'le mot de passe ne doit pas être inférieur à %1 caractères',
	'PwdCplxDesc3'				=> 'ne doit pas contenir votre nom d\'utilisateur',
	'PwdCplxDesc4'				=> 'devrait consister de ',
	'PwdCplxDesc41'				=> 'lettres et chiffres',
	'PwdCplxDesc42'				=> 'lettres majuscules et minuscules et chiffres',
	'PwdCplxDesc43'				=> 'lettres majuscules et minuscules, chiffres et caractères non alphanumériques',
	'PwdCplxDesc5'				=> 'Vous pouvez utiliser toutes les lettres, chiffres et caractères spéciaux sauf les espaces.',

	'PasswordTooShort'			=> 'Mot de passe trop court.',
	'PasswordTooCommon'			=> 'Ce mot de passe est trop fréquent.',
	'PasswordSameAsUsername'	=> 'Votre mot de passe est le même que votre nom d\'utilisateur.',
	'PasswordSameAsEmail'		=> 'Votre mot de passe est identique à votre adresse e-mail.',

	'Timezone'					=> 'Timezone',

	'LanguageArray'	=> [
		'bg' => 'Bulgare',
		'da' => 'Danois',
		'de' => 'Allemand',
		'el' => 'Grecque',
		'en' => 'Anglais',
		'es' => 'Espagnol',
		'et' => 'estonien',
		'fa' => 'Perse',
		'fr' => 'Français',
		'hi' => 'Hindi',
		'hu' => 'Hongrois',
		'it' => 'Italien',
		'ja' => 'Japonais',
		'ko' => 'Coréen',
		'nl' => 'Néerlandais',
		'pl' => 'Polonais',
		'pt' => 'Portugais',
		'ru' => 'Russe',
		'ta' => 'Tamil',
		'zh' => 'Chinois',
		'zh-tw' => 'Chinois',
	],

	'AccountStatus'				=> 'État du compte',
	'AccountStatusArray' => [
		'0' => 'Actif',
		'1' => 'en attente',
		'2' => 'bloqués',
		'3' => 'inactif',
	],

	'JustNow'		=> 'à l\'instant',
	'MinuteAgo'		=> 'il y a une minute',
	'MinutesAgo'	=> '%1 minutes ago',
	'HourAgo'		=> 'il y a une heure',
	'HoursAgo'		=> '%1 hours ago',
	'DayAgo'		=> 'Hier',
	'DaysAgo'		=> '%1 days ago',
	'WeekAgo'		=> 'il y a une semaine',
	'WeeksAgo'		=> '%1 weeks ago',
	'MonthAgo'		=> 'il y a un mois',
	'MonthsAgo'		=> '%1 months ago',
	'YearAgo'		=> 'il y a un an',
	'YearsAgo'		=> '%1 ans',

	'InAMoment'		=> 'dans un moment',
	'InAMinute'		=> 'dans une minute',
	'InMinutes'		=> 'dans %1 minutes',
	'InAnHour'		=> 'dans une heure',
	'InHours'		=> 'dans %1 heures',
	'Tomorrow'		=> 'demain',
	'InDays'		=> 'dans %1 jours',
	'InAWeek'		=> 'dans une semaine',
	'InWeeks'		=> 'dans %1 semaines',
	'InAMonth'		=> 'dans un mois',
	'InMonths'		=> 'dans %1 mois',
	'InAYear'		=> 'dans une année',
	'InYears'		=> 'dans %1 ans',

	// norm multiples
	'ByteDecimalShort'			=> ['Os', 'Ko', 'MO', 'GR', 'TB', 'PO', 'EB', 'ZB', 'YO'],
	'ByteDecimalLong'			=> ['Octets', 'Kilobyte', 'Megabyte', 'Gigabyte', 'Terabyte', 'Petabyte', 'Exabyte', 'Zettabyte', 'Yottabyte'],
	'ByteBinaryShort'			=> ['Os', 'KiB', 'Mio', 'GiB', 'TiB', 'PiB', 'EiB', 'ZiB', 'YiB'],
	'ByteBinaryLong'			=> ['Octets', 'Kibibyte', 'Mebibyte', 'Gibibyte', 'Tebibyte', 'Pebibyte', 'Exbibyte', 'Zebibyte', 'Yobibyte'],
	'PixelDecimalShort'			=> ['px', 'KP', 'MM', 'GR', 'PT', 'PP', 'EP', 'ZP', 'YP'],
	'PixelDecimalLong'			=> ['Pixel', 'Kpx', 'Mpx', 'Gpx', 'Tpx', 'Ppx', 'Epx', 'Zpx', 'Ypx'],

	// loading error
	'UnknownAction'				=> 'Action inconnue',
	'UnknownMethod'				=> 'Méthode inconnue',
	'FormatterNotFound'			=> 'Formatter %1 introuvable',

	// log
	'LogAdminLoginSuccess'		=> 'Connexion réussie dans le panneau d\'administration',
	'LogAdminLogout'			=> 'Déconnexion du panneau d\'administration',
	'LogAdminLoginFailed'		=> '!!Échec d\'autorisation d\'accès au panneau d\'administration!!',
	'LogAdminLoginLocked'		=> 'Connexion au panneau d\'administration verrouillée',
	'LogUserCookieForged'		=> '!!**Tentative de connexion sur un cookie forgé avec connexion ##%1##**!!',
	'LogInvalidFormToken'		=> 'Attaque potentielle CSRF en cours détectée : %1',
	'LogRemovedPage'			=> '!!Page supprimée ##%1## (utilisateur %2)!!',
	'LogRemovedCluster'			=> '!!Enlevé **cluster** ##%1## (utilisateur %2)!!',
	'LogRemovedRevision'		=> '!!Retrait de la révision ##%3## de la page [[/%1]] (utilisateur %2)!!',
	'LogRemovedComment'			=> '!!Commentaire retiré de %3 sur la page [[/%1]] (utilisateur %2)!!',
	'LogRemovedFile'			=> '!!Fichier supprimé ##%2## de la page [[/%1]]!!',
	'LogRemovedAllComments'		=> '!!Tous les commentaires de la page [[/%1]]!!',
	'LogRemovedAllRevisions'	=> '!!Toutes les révisions de la page [[/%1]]!!',
	'LogRemovedAllFiles'		=> '!!Tous les fichiers attachés à [[/%1]]!!',
	'LogTopicLocked'			=> 'Le sujet du forum est verrouillé [[/%1]]',
	'LogTopicUnlocked'			=> 'Sujet du forum [[/%1] ] déverrouillé',
	'LogAclUpdated'				=> 'Page ACL mise à jour [[/%1]]',
	'LogOwnershipChanged'		=> 'Propriété de la page [[/%1]] transférée à l\'utilisateur ##%2##',
	'LogUserLoginFailed'		=> '!!Tentatives de connexion infructueuses avec ##~%1##!!',
	'LogClonedPage'				=> 'Page ##%1## cloné vers [[/%2]]',
	'LogRenamedPage'			=> 'Page ##%1## renommé en [[/%2]]',
	'LogRenamedPage2'			=> '. L\'ancienne page définie comme lien vers la nouvelle',
	'LogSplittedPage'			=> 'Commentaires sur la page [[/%1]] divisé en page [[/%2]]',
	'LogMergedPages'			=> 'Pages %1 fusionnées à la page [[/%2]]',
	'LogUserPasswordReminded'	=> 'L\'utilisateur ##%1## a demandé que le processus de récupération du mot de passe soit adressé ##%2##',
	'LogUserPasswordRecovered'	=> 'L\'utilisateur ##%1## a récupéré avec succès le mot de passe oublié',
	'LogUserPasswordChanged'	=> 'Utilisateur ##%1## ## mis à jour avec succès le mot de passe',
	'LogUserPasswordMismatch'	=> '!!User ##%1## n\'a pas réussi à changer le mot de passe : le mot de passe actuel n\'est pas identique!!',
	'LogUserIPSwitched'			=> 'Changement d\'adresse IP non autorisé de l\'utilisateur %1 de %2 à %3',
	'LogPageImported'			=> 'Page importée [[/%1]]',
	'LogSaveNoRights'			=> 'Aucun droit approprié pour enregistrer la page [[/%1]]',
	'LogPageCreated'			=> 'Nouvelle page créée [[/%1]]',
	'LogPagePropertiesUpdated'	=> 'Propriétés de la page [[/%1] ] mises à jour',
	'LogPageOwnershipClaimed'	=> 'L\'utilisateur a été propriétaire de la page [[/%1]]',
	'LogFileUploadedLocal'		=> 'Nouveau fichier ##%2## téléchargé sur la page [[/%1]] (taille %3)',
	'LogFileUploadedGlobal'		=> 'Nouveau fichier ##%2## téléchargé dans le dossier global (taille %3)',
	'LogPMSent'					=> 'Message personnel ##%1## -> ##%2## envoyé avec succès',
	'LogUserSimilarName'		=> 'Il y a eu des tentatives d\'inscription sous le même nom d\'utilisateur : ##%1##',
	'LogUserEmailNotAllowed'	=> 'Email ##%1## non dans la liste des domaines autorisés',
	'LogRegisterTiming'			=> 'L\'inscription a échoué, le seuil de temps du formulaire est ##%1## secondes (était ##%2##)',
	'LogUserRegistered'			=> 'Nouvel utilisateur enregistré avec succès ##%1## (##%2##)',
	'LogUserEmailActivated'		=> 'E-mail activé avec succès ##%1## de l\'utilisateur ##%2##',
	'LogCommentPosted'			=> 'Ajout de [[/%1 nouveau(x) commentaire(s) à la page [[/%2]]',
	'LogUserLoginOK'			=> 'Utilisateur ##%1## connecté avec succès dans le système',
	'LogUserLoggedOut'			=> 'Utilisateur ##%1## déconnecté avec succès du système',
	'LogUserSessionContinued'	=> 'Utilisateur ##%1## a poursuivi la session suspendue',
	'LogUserSettingsUpdate'		=> 'Utilisateur ##%1## Mise à jour des paramètres personnels',
	'LogPageEdited'				=> 'Page éditée [[/%1]]',
	'LogCommentEdited'			=> 'Commentaire modifié [[/%1]]',
	'LogUpdatedFileMeta'		=> 'Métadonnées du fichier mises à jour pour ##%2## depuis la page [[/%1]]',
	'LogUpdatedFileCategories'	=> 'Catégories de fichiers mises à jour pour ##%2## depuis la page [[/%1]]',

	'LogXmlSitemapGenerated'	=> 'Plan du site XML généré',
	'LogReferrersPurged'		=> 'Maintenance : référents purgés',
	'LogRevisionsPurged'		=> 'Maintenance : révisions des pages obsolètes purgées',
	'LogDeletedPagesPurged'		=> 'Maintenance : pages supprimées',
	'LogSystemLogPurged'		=> 'Maintenance : journal système effacé',
	'LogCachedPagesPurged'		=> 'Maintenance : pages mises en cache purgées',
	'LogSqlCachePurged'			=> 'Maintenance : résultats du cache sql purgés',
	'LogExpiredTokensPurged'	=> 'Maintenance : cookies expirés purgés',
	'LogErrorSplitComments'		=> 'Erreur lors de la séparation des commentaires du sujet [[/%1]] un nouveau sujet ##%2##: la page n\'a pas été créée',
	'LogCategoriesUpdated'		=> 'Catégories de page mises à jour [[/%1]]',
	'LogCategoryCreated'		=> 'Création d\'une nouvelle catégorie //%1//',
	'LogCategoryRenamed'		=> 'Catégorie ##%1## renommée en ##%2##',
	'LogCategoryDebundled'		=> 'Catégorie ##%1## debundled',
	'LogCategoryGrouped'		=> 'Catégorie ##%1## regroupés avec le mot ##%2##',
	'LogCategoryRemoved'		=> 'Catégorie ##%1## supprimée de la base de données',
	'LogThumbnailGeneration'	=> 'Génération de la miniature %1 sec.',

	'ErrorMinPHPVersion'		=> 'La version de PHP doit être supérieure à <strong>' . PHP_MIN_VERSION . '</strong>,' .
									' votre serveur semble exécuter <strong>' . PHP_VERSION . '</strong>.' .
									'  Vous devriez mettre à jour PHP vers une version plus récente pour que WackoWiki fonctionne correctement.',

];
