<?php

if (!defined('IN_WACKO'))
{
	exit;
}

$wacko_translation = [

	// language
	'lang_scheme'	=> [
		'name'		=> 'Russian',
		'code'		=> 'ru',
		'dir'		=> 'ltr',
		'locale'	=> 'ru_US.UTF-8',
	],

	// common
	'AddButton'					=> 'Добавить',
	'ArchiveButton'				=> 'Архивировать',
	'CancelButton'				=> 'Отмена',
	'ContinueButton'			=> 'Продолжить',
	'ConvertButton'				=> 'Конвертировать',
	'CreateButton'				=> 'Создать',
	'DeleteButton'				=> 'Удалить',
	'RemoveButton'				=> 'Удалить',
	'RenameButton'				=> 'Переименовать',
	'ResetButton'				=> 'Reset',
	'RestoreButton'				=> 'Восстановить',
	'SaveButton'				=> 'Сохранить',
	'SearchButton'				=> 'Искать',
	'SendButton'				=> 'Отправить',
	'SetButton'					=> 'Задать',
	'SubmitButton'				=> 'Отправить',
	'UpdateButton'				=> 'Обновить',

	'FormInvalid'				=> 'Отправленная форма неверна. Попробуйте еще раз.',
	'UnitPixel'					=> 'px',
	'Number'					=> 'Номер',

	// logged in panel
	'AccountText'				=> 'Аккаунт',
	'AccountTip'				=> 'Настройки учётной записи',
	'AdminText'					=> 'Админ',
	'AdminTip'					=> 'Административная панель',
	'LogoutLink'				=> 'Выйти',
	'LogoutButton'				=> 'Выйти',
	'LogoutAreYouSure'			=> 'Вы действительно хотите выйти?',

	// registration panel
	'RegistrationWelcome'		=> 'Регистрация нового пользователя:',
	'RegistrationButton'		=> 'Зарегистрировать меня',
	'UserNameOwned'				=> 'Это имя пользователя уже зарегистрировано. Пожалуйста, выберите другое.',
	'SiteRegistered'			=> 'Вы успешно зарегистрировались на сайте %1.',
	'RegistrationEmailInfo'		=> 'Действующий адрес электронной почты. Все письма системы будут отправлены на этот адрес. Адрес электронной почты не является публичным и будет использован только в том случае, если вы хотите получить новый пароль или хотите получать новости или уведомления по электронной почте.',
	'EmailConfirmHint'			=> 'Пожалуйста, подтвердите свой адрес электронной почты, нажав на ссылку в инструкциях, отправленных вам. <br>Если вы не подтвердите свой адрес электронной почты, вы не сможете получить возможный утерянный пароль. <br>Кроме того, вы не будете уведомлены о последних изменениях страниц и комментариях.',
	'EmailConfirmRequired'		=> 'Без подтвержденного адреса электронной почты вы не сможете войти в систему.',
	'NameTooShort'				=> 'Имя пользователя слишком короткое, должно быть не менее %2 символов.',
	'NameTooLong'				=> 'Имя пользователя слишком длинное, допускается максимум %2 символов.',
	'NameAlphanumOnly'			=> 'Имя пользователя должно быть между %1 и %2 символами и содержать только буквенно-цифровые символы. В верхнем регистре OK.',
	'NameCamelCaseOnly'			=> 'Имя пользователя должно быть между %1 и %2 символами и форматом WikiName.',
	'NewUserAccount'			=> 'новый аккаунт пользователя',

	'NewAccountSubject'			=> 'Регистрация аккаунта',
	'NewAccountAdminCreated'	=> 'Пользователь %1 создал учетную запись для вас с именем пользователя "%2". Чтобы завершить регистрацию, перейдите по следующей ссылке (убедитесь, что она введена в виде одной строки) и установите свой собственный пароль доступа:',
	'NewAccountUsername'		=> 'Имя пользователя:',
	'AccountLanguage'			=> 'Язык:',
	'NewAccountEmail'			=> 'Email:',
	'NewAccountIP'				=> 'Удаленный IP адрес:',
	'NewAccountSignupInfo'		=> 'Следующая учетная запись была создана:',

	'UserWaitingApproval'		=> 'Администратору сайта было отправлено сообщение по электронной почте. Администратор проверит отправленную информацию и одобрит или отклонит ваш запрос.',
	'UserRequiresApproval'		=> 'Чтобы утвердить или отказать этому пользователю в доступе к %1 перейдите на панель администратора.',
	'UserApprovalInfo'			=> 'После регистрации ваш запрос будет отправлен администратору сайта на утверждение. Затем вы получите письмо с дальнейшими инструкциями.',
	'UserApprovalHint'			=> 'Успешная активация вашей учетной записи будет объявлена на конкретном e-mail. До этого вход невозможен.',

	'UserApprovalPending'		=> 'Ваша учетная запись все еще ожидает подтверждения.',
	'UserApprovalDenied'		=> 'Вашему аккаунту было отказано в доступе к этому сайту.',

	'RegistrationApproved'		=> 'Регистрация утверждена',
	'RegistrationDenied'		=> 'Регистрация запрещена',
	'PendingApproval'			=> 'Ожидает утверждения',

	'UserApprovedInfo'			=> 'You have been approved to access %1.',
	'UserDeniedInfo'			=> 'Вам было отказано в доступе к %1.',

	'RegistrationThreshold'		=> 'Время заполнения формы должно быть не меньше %1 секунд.',
	'Language'					=> 'Язык',

	// login panel
	'LoginWelcome'				=> 'Логин',
	'CreateAccount'				=> 'Создать новый аккаунт',
	'RegistrationLink'			=> 'Регистрация',
	'LoginName'					=> 'Имя пользователя',
	'Password'					=> 'Пароль',
	'LoginButton'				=> 'Логин',
	'LoginLink'					=> 'Логин',
	'PersistentCookie'			=> 'Оставаться в системе',
	'Session'					=> 'Сессия',
	'SessionTip'				=> 'параметры текущей сессии',
	'SessionDuration'			=> 'Длительность сессии',
	'SessionDurationSession'	=> 'сессия браузера',
	'SessionDurationDay'		=> '1 день',
	'SessionDurationWeek'		=> '1 неделя',
	'SessionDurationMonth'		=> '1 месяц',
	'LoggedInAs'				=> 'Вы вошли как',

	'ClearCookies'				=> 'Удалить все cookies',
	'BindSessionIp'				=> 'Привязать сессию к IP-адресу',
	'BindSessionIpOn'			=> 'включён (текущий IP %1)',
	'TrafficProtection'			=> 'Защита трафика',
	'SessionEnds'				=> 'Текущая сессия заканчивается',
	'LastVisit'					=> 'Последний визит был записан',

	'LoginIncorrect'			=> 'Введенное имя пользователя или пароль неверно.',
	'WelcomeBack'				=> 'С возвращением, %1',
	'LoginAttemptsExceeded'		=> 'Вы превысили максимально допустимое количество попыток входа.<br>В дополнение к вашему логину и паролю вам теперь нужно решить капча ниже.',

	// session notice
	'IPAddressChanged'			=> 'IP адрес изменен на %1 (было %2)',

	'SessionReplay'				=> 'Сессия прекращена из-за повтора.',
	'SessionObsolete'			=> 'Сессия устарела.',
	'SessionExpired'			=> 'Сессия истекла.',
	'SessionTimeout'			=> 'Сессия закрыта по истечении таймаута.',
	'SessionInactivity'			=> 'Сеанс прерван из-за неактивности.',
	'SessionUaChange'			=> 'Сессия прервана из-за изменения пользовательского агента.',
	'SessionTLSChange'			=> 'Сеанс прерван из-за изменения TLS.',
	'SessionIPChange'			=> 'Сеанс прерван из-за изменения IP.',

	// other
	'Guest'						=> 'Гость',
	'Everybody'					=> 'Все',
	'Help'						=> 'Справка',
	'TopicSearchText'			=> 'Искать только в заголовках',
	'WordprocessorVersion'		=> 'Версия текстового процессора',

	// notifications
	'EmailHello'				=> 'Привет ',
	'EmailModerator'			=> 'Модератор',
	'WatchedPageChanged'		=> 'Страница изменена ',
	'SomeoneChangedThisPage'	=> ' изменена страница, которую вы отслеживаете: ',
	'NewPageCreatedSubj'		=> 'Новая страница',
	'NewPageCreatedBody'		=> 'Пользователь %1 создал новую страницу: ',
	'FileUploadedSubj'			=> 'Новый файл',
	'FileUploadedBody'			=> 'Пользователь %1 загрузил новый файл: ',
	'FileReplacedBody'			=> 'Пользователь %1 заменил файл: ',

	'ActionDenied'				=> 'Действие отклонено.',
	'TocTitle'					=> 'Содержание ',
	'OuterLink2'				=> 'Исходящая ссылка',
	'FileLink'					=> '',
	'PDFLink'					=> 'Документ PDF',
	'RDFLink'					=> 'Документ RDF',
	'EmailLink'					=> 'Написать письмо (запуск почтового клиента)',
	'JabberLink'				=> 'Чат через XMPP (запуск Jabber клиента)',
	'PermaLink'					=> 'Постоянная ссылка',
	'PermaLinkTip'				=> 'Постоянная ссылка на эту версию страницы',
	'PermaLink0Tip'				=> 'Постоянная ссылка на эту страницу',

	'ShowTip'					=> 'Вернуться в режиме просмотра',
	'ShowText'					=> 'Вид',
	'WikieditAutocomplete'		=> 'Завершить wikilinks с помощью Ctrl+Space',
	'WikiEditInactiveJs'		=> 'Чтобы иметь возможность использовать WikiEdit, пожалуйста, включите JavaScript в вашем браузере.',
	'NumerateLinks'				=> 'Нумеровать ссылки в режиме печати',
	'Comment'					=> 'Комментарий',
	'Comments0'					=> 'Добавить комментарий',
	'Comments1'					=> 'Прочитать комментарий (1 комментарий)',
	'CommentsN'					=> 'Прочитать комментарии (%1 комментариев)',
	'Comments'					=> 'Комментарии',
	'CommentHint'				=> '<a href="%1">Log in</a> or <a href="%2">create an account</a> to post a comment.',
	'CommentEdited'				=> 'отредактировано',
	'Links'						=> 'Ссылки',
	'Version'					=> 'Версии',

	// details formatter
	'ShowHideDetails'			=> 'Детали',

	'PrivacyPolicy'				=> 'Политика конфиденциальности',
	'TermsOfUse'				=> 'Условия использования',
	'AcceptTermsOfUse'			=> 'Я прочитал, понял и согласен с Условиями обслуживания сайта.',

	'ShowComments'				=> 'Показать комментарии / формы',
	'HideComments'				=> 'Скрыть комментарии / формы',
	'AddComment'				=> 'Прикрепить комментарий к этой странице:',
	'AddCommentTitle'			=> 'Заголовок комментария:',
	'CommentTitleRe'			=> 'Re:',
	'AddCommentButton'			=> 'Прикрепить комментарий',
	'HereLink'					=> 'здесь',
	'PageHandlerMoreTip'		=> 'больше',

	'ThemeCorrupt'				=> 'Тема повреждена',
	'InvalidNamespace'			=> 'Неверное имя пространства имен.',
	'DoesNotExists'				=> 'Эта страница не существует.',
	'PromptCreate'				=> 'Может быть, вы хотите <strong><a href="%1">создать</a></strong>?',
	'RevisionHint'				=> 'Это старая версия <a href="%1">%2</a> от %3 отредактирована %4.',
	'ReadAccessDenied'			=> 'Вам не разрешено читать эту страницу.',
	'ReadAccessDeniedHintGuest'	=> 'Чтобы прочитать эту страницу, войдите в систему.',
	'PageDeletedInfo'			=> 'Эта страница была удалена.',
	'RevisionDeletedInfo'		=> 'Эта версия была удалена.',
	'CommentDeletedInfo'		=> 'Этот комментарий был удален.',

	'LastEditedBy'				=> 'Последнее редактирование',
	'YouAreOwner'				=> 'Вы являетесь владельцем этой страницы.',
	'Owner'						=> 'владелец:',
	'Nobody'					=> 'Никто',
	'TakeOwnership'				=> 'Взять в собственность',
	'FilesTip'					=> 'Управление вложенными файлами',
	'FilesText'					=> 'Вложения',
	'DeleteTip'					=> 'Удалить страницу, ее файлы и комментарии',
	'DeleteCommentTip'			=> 'Удалить комментарий',
	'DeleteText'				=> 'Удалить',
	'AclText'					=> 'Права доступа',
	'AclTip'					=> 'Изменить права доступа',

	'PropertiesText'			=> 'Свойства',
	'PropertiesTip'				=> 'Изменить свойства страницы',
	'EditTip'					=> 'Редактировать эту страницу.',
	'EditText'					=> 'Редактирование',
	'EditSection'				=> 'Редактировать раздел %1',
	'EditSectionHint'			=> 'Раздел %1 из %2',
	'SectionHeadline'			=> '1 С-4, 1 С-3, 1 ПС, 1 НС, 1 ДООН',
	'EditCommentTip'			=> 'Редактировать комментарий',
	'EditComment'				=> 'Редактировать этот комментарий',
	'ReplyComment'				=> 'Ответ',
	'ReplyCommentTip'			=> 'Ответить на комментарий',
	'RevisionTip'				=> 'Просмотр версий страницы',
	'RevisionText'				=> 'Версии',
	'ReferrersTip'				=> 'Просмотреть список URL, ссылающихся на эту страницу',
	'ReferrersText'				=> 'Рефералы',
	'ModerateTip'				=> 'Модерирование тем и сообщений на форуме',
	'ModerateText'				=> 'Модерировать',
	'SearchText'				=> 'Поиск: ',

	'AclUpdated'				=> 'Списки контроля доступа обновлены',
	'AclGaveOwnership'			=> ' и передал право владения %1.',
	'AclNoNewOwner'				=> 'Владелец страницы не передается, так как пользователь %1 не найден.',
	'NewPageOwnership'			=> 'Владелец переданной страницы',
	'YouAreNewOwner'			=> 'бывший владелец %1 передал право собственности ' . "\n" . 'из следующих страниц к вам',
	'PageOwnershipInfo'			=> '',
	'AclRead'					=> 'Читать:',
	'AclWrite'					=> 'Запись записи:',
	'AclComment'				=> 'Комментарии:',
	'AclCreate'					=> 'Создать:',
	'AclUpload'					=> 'Загрузить:',
	'AclFor'					=> 'Списки контроля доступа для %1',
	'SetOwner'					=> 'Установить владельца:',
	'OwnerDontChange'			=> 'Не изменять',
	'AclAccessDenied'			=> 'Вы не являетесь владельцем этой страницы.',
	'AclSyntaxError'			=> 'Ошибка синтаксиса списка контроля доступа',
	'AclHelp'					=> '<code>*</code> - всем разрешено<br>' .
									'<code>$</code> - only registered users<br>' .
									'<code>!</code> - предшествующий восклицательный знак отрицает соответствующие права<br>' .
									'<code>[UserName]</code> - имена допустимых пользователей<br>' .
									'<code>[GroupName]</code> - имена разрешенных групп пользователей (алиасов)<br>' .
									'<code>(an empty list)</code> - only the page owner has access',

	'AccessMode'				=> 'Видимость',
	'AccessDenied'				=> 'отказано',
	'AccessPublic'				=> 'публичный',
	'AccessRegistered'			=> 'зарегистрирован',
	'AccessPrivate'				=> 'приватный',
	'AccessCustom'				=> 'пользовательский',

	// purge handler
	'PurgePage'					=> 'Purge page',
	'NotOwnerAndCantPurge'		=> 'Вы не являетесь владельцем страницы и не можете ее очистить.',
	'ReallyPurge'				=> 'ВНИМАНИЕ: Очистка страницы необратимо!',
	'SelectPurgeOptions'		=> 'Выберите необходимые параметры очистки:',
	'PurgeComments'				=> 'Удалить все комментарии страницы',
	'CommentsPurged'			=> 'Все комментарии были удалены.',
	'PurgeFiles'				=> 'Удалить все прикрепленные файлы',
	'FilesPurged'				=> 'Все прикрепленные файлы были удалены.',
	'PurgeRevisions'			=> 'Очистить все версии страницы',
	'RevisionsPurged'			=> 'Были опущены изменения.',
	'PurgeButton'				=> 'Purge',

	// categories handler
	'Categories'				=> 'Категории',
	'CategoriesAssign'			=> 'назначить',
	'CategoriesEdit'			=> 'редактировать',
	'Category'					=> 'Категория',
	'CategoriesFor'				=> 'Категории для',
	'CategoriesTip'				=> 'Редактировать категории',
	'CategoriesText'			=> 'Категории',
	'CategoriesUpdated'			=> 'Категории обновлены',
	'CategoriesAlreadyExists'	=> 'Категория %1 уже существует.',
	'CategoriesAdded'			=> 'Категория %1 успешно добавлена.',
	'CategoriesRenamed'			=> 'Категория успешно переименована.',
	'CategoriesUngrouped'		=> 'Категория успешно заполнена.',
	'CategoriesGrouped'			=> 'Категория, введенная в новую группу.',
	'NoMultilevelGrouping'		=> 'Группировка многоуровневых категорий невозможна.',
	'CategoriesDeleted'			=> 'Категория была удалена из базы данных и всех страниц.',
	'CategoriesAdd'				=> 'Добавить новую категорию',
	'CategoryDescription'		=> 'Описание',
	'CategoriesAddGrouped'		=> 'Сгруппировано с категорией',
	'CategoriesAddGroupedNo'	=> 'Нет группы.',
	'CategoriesRename'			=> 'Переименовать категорию %1 в',
	'CategoriesRenameInfo'		=> '* Примечание: изменение повлияет на все страницы, которые привязаны к этой категории.',
	'CategoriesGroup'			=> 'Категории групп %1 с',
	'CategoriesGroupInfo'		=> '* Выберите [нет группы] для заполнения категории.',
	'CategoriesNoGroup'			=> '[нет группы]',
	'CategoriesDelete'			=> 'Вы уверены, что хотите удалить категорию %1?',
	'CategoriesDeleteInfo'		=> '* Примечание: изменение повлияет на все страницы, которые привязаны к этой категории. Если слово имеет подкатегорию, то оно не будет удалено, а будет только удалено.',
	'CategoriesStoreInfo'		=> 'Чтобы назначить категории на страницу, выберите флажки.',
	'CategoriesStoreButton'		=> 'Сохранить категории',
	'CategoriesGroupButton'		=> 'Группа',
	'CategoriesEditInfo'		=> 'Для редактирования списка категорий выберите кнопку радио.',
	'NoCategoriesForThisLang'	=> 'Категории для этого языка не указаны.',
	'PagesCategory'				=> 'Категория страниц',
	'CategoryNotExists'			=> 'Категория не существует.',
	'CategoryEmpty'				=> 'Категория пуста.',
	'NoCategorySelected'		=> 'Не выбрана категория.',
	'NoCategoriesAssigned'		=> 'Нет назначенных категорий для этого языка.',
	'TagCloud'					=> 'Облако тегов',
	'PagesTaggedWith'			=> '%1 страниц с тегом %2',
	'CategoriesOfCluster'		=> 'кластера',
	'TaggedWithTip'				=> 'показать страницы с тегом %1',

	// source handler
	'SourceText'				=> 'Источник',
	'SourceTip'					=> 'Просмотр исходного кода вики',
	'SourceCopyToClipboard'		=> 'скопировать в буфер обмена',
	'SourceFor'					=> 'Просмотр исходного кода для %1',

	// Groups action
	'GroupsSearch'				=> 'Найти группы',
	'GroupsNoMatching'			=> 'Подходящие группы не найдены. Попробуйте менее строгие критерии поиска.',
	'GroupsOpenProfile'			=> 'Просмотр профиля',
	'GroupsName'				=> 'Группа',
	'GroupsMembers'				=> 'Члены Комитета',
	'GroupsDescription'			=> 'Описание',
	'GroupsCreated'				=> 'Создано',
	'GroupsNotFound'			=> 'Группа %2 не найдена. Нажмите <a href="%1">здесь</a>, чтобы перейти в основной список.',
	'GroupsProfile'				=> 'Профиль',
	'GroupsList'				=> 'Просмотреть весь список групп',
	'GroupSpace'				=> 'Область в группе',

	'MetaUpdated'				=> 'Мета-данные обновлены',

	'PreviewButton'				=> 'Предпросмотр',
	'Preview'					=> 'Предпросмотр',
	'Chars'						=> 'символов',
	'PageBody'					=> 'Тело страницы',
	'EditNote'					=> 'Изменить резюме',
	'EditNoteMissing'			=> 'Редактирование сводки отсутствует',
	'EditMinor'					=> 'Небольшое изменение',
	'MinorEditHide'				=> 'Скрыть незначительные изменения',
	'MinorEditShow'				=> 'Показать незначительные изменения',
	'PostAnonymously'			=> 'Опубликовать анонимно без указания вашего имени',
	'NotifyMe'					=> 'Уведомлять меня о новых комментариях и изменениях страницы',
	'OverwriteAlert'			=> 'OVERWRITE ALERT: This page was modified by someone else while you were editing it.<br>Please copy your changes and re-edit this page.',
	'TextDbOversize'			=> 'Предупреждение: Ваш текст превышает ограничение длины на %1 символов. Пожалуйста, сократите текст до допустимого количества символов. Совет: оставшийся текст может быть помещен на отдельной странице.',
	'EditingRevisionWarning'	=> 'Вы редактируете старую версию этой страницы. Если опубликовать ее, все изменения, сделанные с тех пор, будут удалены. <br>Вы можете вместо этого изменить текущую версию.',
	'WriteAccessDenied'			=> 'У вас нет прав на запись на эту страницу.',
	'EmptyPage'					=> 'Тело страницы пусто - не сохранено!',
	'EmptyComment'				=> 'Тело комментария пустое - не сохранено!',
	'CommentAccessDenied'		=> 'Извините, вы не можете оставлять комментарии на этой странице.',
	'CommentFlooded'			=> 'Интервал между публикацией сообщений должен быть не меньше %1 секунд.',
	'CommentAdded'				=> 'Комментарий добавлен.',
	'YouAreNowTheOwner'			=> 'Теперь вы являетесь владельцем этой страницы.',
	'PageSaved'					=> 'Версия страницы %1 сохранена.',
	'CommentSaved'				=> 'Комментарий сохранен.',

	'RevisionsFor'				=> 'Версии для %1',
	'DefaultDiffMode'			=> 'Режим Diff по умолчанию',
	'DiffMode'		=> [
		'0'		=> 'Полная разница',
		'1'		=> 'Простой дифф',
		'2'		=> 'Источник',
		'3'		=> 'Рядом',
		'4'		=> 'Встроенный',
		'5'		=> 'Объединенные',
		'6'		=> 'Единый',
		'7'		=> 'Контекст',
	],

	'PreviousEdit'				=> 'Предыдущая правка',
	'NextEdit'					=> 'Следующее изменение',

	'Diff'						=> 'Разница',
	'PreviousVersion'			=> 'Предыдущая версия',
	'LatestVersion'				=> 'Последняя версия',
	'NextVersion'				=> 'Следующая версия',

	'ShowDifferencesButton'		=> 'Показать различия',
	'CancelReturnButton'		=> 'Отменить и вернуться к странице',
	'Comparison'				=> 'Разница между версиями для %1',
	'RevisionAsOf'				=> 'Версия %1 по состоянию на',
	'SimpleDiffAdditions'		=> 'Добавления:',
	'SimpleDiffDeletions'		=> 'Удаления:',
	'NoDifferences'				=> 'Нет различий.',
	'ReEditOldRevision'			=> 'Повторно отредактировать старую версию',

	'ExternalPages'				=> 'Внешние страницы, связанные с %1 (%2) (<a href="%3">см. список доменов</a>):',
	'ExternalPagesGlobal'		=> 'Сайты, связанные с этой WackoWiki (%2) (<a href="%1">смотрите список доменов</a>):',
	'Last24Hours'				=> 'последние 24 часа',
	'LastDays'					=> 'последние %1 дней',
	'DomainsSitesPages'			=> 'Домены/страницы, связанные с  %1 (%2) (<a href="%3">см. список различных URL-адресов</a>):',
	'DomainsSitesPagesGlobal'	=> 'Домены/сайты, связанные с этой WackoWiki (<a href="%1">см. список различных URL-адресов</a>):',
	'ViewReferrersPage'			=> 'на страницу',
	'ViewReferrersPerPage'		=> 'на страницу',
	'ViewReferrersByTime'		=> 'по времени',
	'ViewReferrersGlobal'		=> 'глобальный',
	'NoneReferrers'				=> 'Нет',
	'NotOwnerCantDelete'		=> 'Вы не являетесь владельцем этой страницы и не можете удалить ее',

	// remove
	'RemovePage'				=> 'Удалить страницу',
	'RemoveRevision'			=> 'Удалить версию',
	'RemoveComment'				=> 'Удалить комментарий',
	'RemoveCluster'				=> 'Удалить все страницы кластера',
	'RemoveDontKeep'			=> 'Не сохранять копию удаленной страницы и комментариев',
	'RemoveDontKeepRevision'	=> 'Не сохранять копию удаленной ревизии',
	'RemoveDontKeepComment'		=> 'Не сохранять копию удаленного комментария',
	'RemoveDontKeepFile'		=> 'Не сохранять копию удаленного файла',
	'ReferrersRemoved'			=> 'Рефералы удалены.',
	'LinksRemoved'				=> 'Ссылки удалены.',
	'CategoriesRemoved'			=> 'Категории страниц удалены.',
	'AclsRemoved'				=> 'Эклы страниц удалены.',
	'BookmarksRemoved'			=> 'Закладки удалены.',
	'WatchesRemoved'			=> 'Наблюдатели удалены.',
	'CommentsRemoved'			=> 'Комментарии от страницы удалены.',
	'FilesRemoved'				=> 'Удалены файлы со страницы.',
	'PageRemoved'				=> 'Страница удалена.',
	'PageCachePurged'			=> 'Кэш очищен.',
	'ClusterRemoved'			=> 'Все страницы кластера удалены.',
	'RevisionRemoved'			=> 'Ревизия %1 удалена.',
	'RevisionsRemoved'			=> 'Изменения удалены.',
	'ActionHaveNoUndo'			=> 'Это действие нельзя отменить.',

	// restore
	'PageRestored'				=> 'Страница восстановлена.',
	'RevisionRestored'			=> 'Проверка восстановлена.',
	'LocalFilesRestored'		=> 'Локальные файлы восстановлены.',

	'PrintVersion'				=> 'Версия для печати',
	'PrintText'					=> 'Печать',
	'LinkedPages'				=> 'Связанные страницы:',
	'NoLinkedPages'				=> 'Нет связанных страниц',
	'ReferringPages'			=> 'Ссылающиеся страницы:',
	'NoReferringPages'			=> 'Нет ссылочных страниц',
	'Footnotes'					=> 'Примечания:',
	'Footnote'					=> 'Примечание',
	'MostPopularPages'			=> 'Самые популярные страницы',
	'MostCommentedPages'		=> 'Часто прокомментированные страницы',
	'NoAccessToSourcePage'		=> 'Вам не разрешено читать страницу исходных действий.',
	'SourcePageDoesntExist'		=> 'Исходная страница действия еще не существует',
	'NotLoggedInThusEdited'		=> 'Вы не вошли в систему, поэтому мы не смогли идентифицировать отредактированные вами страницы.',
	'DidntEditAnyPage'			=> 'Вы еще не редактировали ни одной страницы.',
	'NoPagesFound'				=> 'Страницы не найдены.',
	'MyChangesTitle1'			=> 'Это список страниц, которые вы отредактировали, упорядоченных к моменту последнего изменения',
	'MyChangesTitle2'			=> 'Это список страниц, которые вы отредактировали, а также время последнего изменения',
	'OrderABC'					=> 'в алфавитном порядке',
	'OrderCreation'				=> 'по созданию',
	'OrderChange'				=> 'по изменению',
	'ListOwnedPages'			=> 'Это список страниц, которые вы владеете (упорядочены по алфавиту)',
	'ListOwnedPages2'			=> 'Это список страниц, которые вы владеете (упорядочены по дате)',
	'ListOwnedPages3'			=> 'Это список страниц, которые вы владеете (упорядочены по изменениям)',
	'NotLoggedInThusOwned'		=> 'Вы не вошли в систему, поэтому мы не смогли получить ваши страницы.',
	'NoOrphaned'				=> 'Нет осиротевших страниц. Хорошо.',
	'NoRecentComments'			=> 'Нет последних комментариев.',
	'LatestCommentBy'			=> 'последний комментарий',
	'NoRecentlyCommented'		=> 'Нет недавно прокомментированной страницы.',
	'NoDeletedPages'			=> 'Удаленные страницы не найдены.',
	'NoDeletedRevisions'		=> 'Удаленных версий не найдено.',
	'NoDeletedFiles'			=> 'Удаленные файлы не найдены.',
	'CommentsDisabled'			=> 'Комментарии недоступны.',

	'SearchResults'				=> 'Результаты поиска для ',
	'NotFound'					=> 'не найден',
	'NoResultsFor'				=> 'Нет результатов для ',
	'SearchFor'					=> 'Искать:',
	'TopicSearchResults'		=> 'Результаты поиска тем для ',
	'NotFoundInTopics'			=> 'в темах не найдено',
	'FilterLangNotAvailable'	=> 'Выбранный язык недоступен!',

	'PostedBy'					=> 'опубликовано',
	'ThisIsCommentOn'			=> 'Это комментарий к',
	'At'						=> 'в',
	'To'						=> 'до',
	'By'						=> 'от',
	'From'						=> 'от',
	'For'						=> 'для',
	'ReturnToCommented'			=> 'Вернуться на прокомментированную страницу',
	'AbandonedComment'			=> 'Страница, к которой принадлежит этот комментарий больше не существует!',

	'PagesLinkingTo'			=> 'Страницы, связанные с',
	'NoPageLinkingTo'			=> 'Нет ссылок на страницу',
	'NoWantedPages'				=> 'Нет нужных страниц. Хорошо.',
	'RemoveWatch'				=> 'Удалить наблюдения для этой страницы',
	'SetWatch'					=> 'Смотреть эту страницу',
	'WatchText'					=> 'Смотреть',
	'UnwatchText'				=> 'Не следовать',
	'UserSettingsStored'		=> 'Настройки пользователя сохранены.',
	'LoggedOut'					=> 'Вы вышли из системы.',
	'LoggedOutAuto'				=> 'В целях безопасности ваша сессия закончилась. Пожалуйста, войдите снова.',

	// user settings
	'EmailConfirmResent'		=> 'Код подтверждения электронной почты повторно отправлен на ваш адрес.',
	'EmailConfirmNotSent'		=> 'Не удалось отправить код подтверждения: не указан адрес электронной почты!',
	'Hello'						=> 'Привет',
	'UserName'					=> 'Имя пользователя',
	'EmailAddress'				=> 'Email адрес',
	'RealName'					=> 'Настоящее имя',
	'MenuItemsShown'			=> 'Элементы меню показаны',
	'RecordsPerPage'			=> 'Записи на странице',
	'DoShowComments'			=> 'Показывать комментарии по умолчанию',
	'DoubleclickEditing'		=> 'Редактирование двойным щелчком',
	'UpdateSettingsButton'		=> 'Настройки обновления',

	'AccountDisabled'			=> 'Ваша учетная запись может быть отключена или заблокирована.',
	'WrongPassword'				=> 'Неверный пароль!',
	'ConfirmPassword'			=> 'Подтвердите пароль',
	'Email'						=> 'Email адрес',
	'MustBeWikiName'			=> 'Имя пользователя должно быть <a href="https://wackowiki.org/doc/Doc/English/WikiName" target="_blank">в формате WikiName</a>!',
	'SpecifyEmail'				=> 'Вы должны указать адрес электронной почты.',
	'NotAEmail'					=> 'Это не похоже на действительный адрес электронной почты.',
	'EmailTaken'				=> 'Введенный адрес электронной почты уже используется.',
	'EmailDomainNotAllowed'		=> 'Введённый адрес электронной почты %1 не находится в списке разрешенных доменов.',
	'PasswordsDidntMatch'		=> 'Пароли не совпадают.',
	'SpacesArentAllowed'		=> 'Пробелы в паролях запрещены.',
	'ListMyPages'				=> 'Список ваших страниц',
	'ListMyChanges'				=> 'Список ваших изменений',
	'ListMyWatches'				=> 'Список просмотренных страниц',
	'ListMyChangesWatches'		=> 'Изменения в просмотренных страницах',
	'SeeListOfPages'			=> 'Смотрите список ваших собственных страниц (MyPages) и отредактированных страниц (MyChanges).',
	'AddBookmark'				=> 'Добавить текущую страницу в закладки',
	'RemoveBookmark'			=> 'Удалить из закладок',

	'YourLanguage'				=> 'Выберите язык',
	'ShowSpaces'				=> 'Показывать пробелы в WikiNames',
	'WrongPage4Redirect'		=> 'Невозможно перенаправить из-за неправильного параметра редиректа',
	'RedirectsToItself'			=> 'Страница перенаправляется на себя.',
	'ReallyDeletePage'			=> 'Do you really want to DELETE this page?<br>There is no undo for this action!<br><br>WARNING: Deleting this page will delete all page versions, comments, attachments, ACLs and referrers.',
	'CommentForWatchedPage'		=> 'Новый комментарий к странице ',
	'SomeoneCommented'			=> ' прокомментировал эту страницу, которую вы отслеживаете: ',
	'AlertReferringPages'		=> 'На эту страницу ссылаются эти страницы',

	'AccountDelete'				=> 'Удалить аккаунт',
	'AccountDeleteConfirm'		=> 'Вы уверены, что хотите удалить учетную запись?',
	'AccountDeleted'			=> 'Учетная запись успешно удалена',
	'AccountDeleteHeader'		=> 'Удалить учетную запись %1',
	'AccountDeleteInfo'			=> 'Из данных, которые вы создали (например, email, настройки, вложения, записи вики), как можно больше будут удалены. Однако обратите внимание, что данные вложения и записи вики не могут быть удалены, не препятствуя работе других пользователей. Такие данные переназначены на аккаунт под названием %1. Так как данные каждого удаленного аккаунта переназначены на этот счет, невозможно отличить данные, которые вы создали от данных другого удаленного аккаунта.',
	'AccountDeleteWarning'		=> 'Удаление учетной записи пользователя является необратимым действием.',
	'AccountDeleteHint'			=> 'Ваша учетная запись будет удалена из системы. Таким образом вы больше не сможете войти в систему с текущими учетными данными. Если вы решите стать пользователем этого приложения, вы можете сделать это, используя средства, предоставленные этим приложением.',
	'AccountDeleteVerify'		=> 'Введите ваш логин %1 для проверки удаления. После отправки вам будет предложено подтвердить ваш пароль.',

	'MarkRead'					=> 'Отметить все как прочитанные',
	'CurrentTime'				=> 'В настоящее время',
	'Created'					=> 'создано',
	'Modified'					=> 'изменено',

	'EditIcon'					=> 'редактировать',
	'TreeClusterTitle'			=> 'Дерево кластера %1',
	'TreeSiteTitle'				=> 'Дерево сайта',
	'TreeEmpty'					=> 'У %1 нет подстраниц',
	'TreeEmptyLevels'			=> '%1 не имеет подстраниц для данного уровня глубины. Увеличьте значение для глубины.',
	'TreeTooBig'				=> 'слишком много подстраниц',

	// clone handler
	'ClonePage'					=> 'Скопировать страницу',
	'CloneText'					=> 'Клон',
	'CloneName'					=> 'Введите новое имя для клонирования этой страницы',
	'CloneButton'				=> 'Клон',
	'PageCloned'				=> 'Страница %1 скопирована.',
	'ClonedFrom'				=> 'Клонировано из %1.',
	'MassClone'					=> 'Клонировать весь кластер',
	'MassCloning'				=> 'Клонирующий кластер.',
	'CloneCannotRead'			=> 'Нечитаемая страница %1.',
	'CloneCannotCreate'			=> 'Страница без создания %1.',

	'SortComment'				=> 'Сортировать комментарии по',
	'SortCommentAsc'			=> 'Последние снизу',
	'SortCommentDesc'			=> 'Последние сверху',

	'RenamePage'				=> 'Переименовать страницу',
	'RenameText'				=> 'Переименовать',
	'RenameTip'					=> 'Переименовать страницу',
	'NewName'					=> 'Введите новое название для этой страницы',
	'AlreadyExists'				=> 'Страница %1 уже существует.',
	'AlreadyNamed'				=> 'Эта страница уже с именем %1.',
	'PageRenamed'				=> 'Страница переименована.',
	'NewNameOfPage'				=> 'Новое имя страницы: ',
	'NotOwnerCantRename'		=> 'Вы не являетесь владельцем этой страницы и не можете переименовать ее',
	'NeedRedirect'				=> 'Создать перенаправление на новую страницу на старой странице',
	'RedirectCreated'			=> 'На странице %1 создан редирект на новый',

	'UserSettings'				=> 'Настройки пользователя',
	'UserSettingsGeneral'		=> 'Общие положения',
	'UserSettingsNotifications'	=> 'Уведомления',

	'NotifyMinorEdit'			=> 'Уведомить также о незначительных изменениях',
	'NotifyPageEdit'			=> 'Редактирование',
	'NotifyComment'				=> 'Комментарий',
	'NotifyOff'					=> 'Выкл',
	'NotifyAlways'				=> 'Всегда',
	'NotifyPending'				=> 'В ожидании',
	'NotifyDigest'				=> 'Дайджест',
	'NotifyPendingPageTip'		=> 'При первом изменении страницы вы получаете только одно уведомление.',
	'NotifyPendingCommentTip'	=> 'Только одно уведомление отправляется для первого комментария на страницу, которую вы отслеживаете.',
	'NotifyPendingTip'			=> 'Уведомление автоматически включается при посещении текущей версии страницы.',

	'FurtherPending'			=> 'Никаких других уведомлений в случае дальнейших изменений не будет, если вы не посетите эту страницу.',

	'UserSettingsEmailMe'		=> 'Отправлять мне, когда ...',

	'UserSettingsExtended'		=> 'Расширенный',
	'UserSettingsOther'			=> 'Другие настройки',
	'UserSpace'					=> 'Область пользователя',
	'ChooseTheme'				=> 'Выберите тему',

	'CreatePage'				=> 'Создать страницу',
	'CreateNewPage'				=> 'Создать новую страницу',
	'CreateNewPageText'			=> 'Создать',
	'CreateNewPageTip'			=> 'Создать новую страницу',

	'CreateRandomPage'			=> 'Создать случайную страницу:',
	'CreateSubPage'				=> 'Создать подстраницу в кластере:',
	'CreatePageParentCluster'	=> 'Создать страницу в родительском кластере:',
	'CreatePageDenied'			=> 'У вас нет необходимых прав доступа.',
	'CreatePageDeniedAddress'	=> 'У вас недостаточно прав для создания страницы на этот адрес.',
	'PageAlreadyExists'			=> 'В соответствии с указанным адресом страница %1 уже существует.',
	'PageAlreadyExistsEdit'		=> 'Вы хотите %1?',
	'PageAlreadyExistsEdit2'	=> 'редактировать',
	'PageAlreadyExistsEditDenied'	=> 'Вы не можете редактировать его.',

	'SimilarPagesExists'		=> 'Похожие страницы с %1 уже существуют:',
	'SimilarPagesHint'			=> 'Существуют похожие страницы для %1:',

	'PageReservedWord'			=> 'Вы не можете использовать %1 как часть адреса как зарезервированное слово.',
	'UserReservedWord'			=> 'Имена пользователей не могут содержать %1 , так как это зарезервированное слово.',

	'DontRedirect'				=> 'Не допускать автоматическое перенаправление действием Redirect.',
	'SendWatchEmail'			=> 'Отправить уведомление по электронной почте, когда кто-то (за исключением вас) меняет любую страницу, которую вы просматриваете',
	'AllowIntercom'				=> 'Разрешить личные сообщения от пользователей системы',
	'AllowMassemail'			=> 'Администраторы могут отправлять мне информацию по электронной почте',
	'HideLastSession'			=> 'Скрыть последнюю сессию',
	'ValidateIP'				=> 'Привязка сессии к IP',
	'AnonymousPub'				=> 'Предпочтительно, анонимно опубликовано (чтобы скрыть имя)',
	'PageMoved'					=> 'Эта страница перемещена. Вы можете найти ее в',
	'RedirectedFrom'			=> 'Перенаправлено с %1',
	'RedirectedTo'				=> 'Перенаправлено на',
	'CurrentPassword'			=> 'Текущий пароль',
	'NewPassword'				=> 'Новый пароль',
	'YouWantChangePassword'		=> 'Изменить пароль',
	'ChangePasswordButton'		=> 'Изменить пароль',
	'PasswordChanged'			=> 'Пароль изменен',
	'EmailWelcome'				=> 'Вы зарегистрировались в ',
	'EmailRegistered'			=> 'Вы успешно зарегистрировались на %1.' . "\n" . 'Ваше имя пользователя: %2' . "\n\n",
	'EmailVerify'				=> 'Если вы хотите получать уведомления, вы должны подтвердить ваш адрес электронной почты. Пожалуйста, нажмите на ссылку ниже или скопируйте её в браузер: ' . "\n" . '%1',
	'EmailRegisteredLogin'		=> 'Пожалуйста, вернитесь в Wiki и войдите в систему с новым именем пользователя и паролем.',
	'EmailRegisteredIgnore'		=> 'Если вы не запрашивали регистрацию, проигнорируйте это сообщение и ничего не произойдет.',
	'EmailDoNotReply'			=> 'Не отвечать на это сообщение.',
	'EmailReverify'				=> 'Кто-то (возможно, вы) отправил ваш email как адрес для уведомления на %1.' . "\n" . 'Ваше имя пользователя: %2'."\n\n" . 'Если вы хотите получать уведомления, вы должны подтвердить ваш email. Пожалуйста, перейдите по ссылке, чтобы сделать это.' . "\n" . '%3' . "\n\n",
	'EmailConfirm'				=> 'Пожалуйста, подтвердите ваш адрес электронной почты',
	'EmailConfirmed'			=> 'Email успешно подтвержден.',
	'EmailNotConfirmed'			=> 'Адрес электронной почты не может быть подтвержден. Это может быть вызвано неправильным кодом подтверждения, или адрес электронной почты может быть уже подтвержден. Вы можете проверить, подтвержден ли адрес электронной почты, войдя в систему и просмотрев его статус на странице %1.',
	'EmailNotVerified'			=> 'Email не подтвержден!',
	'EmailNotVerifiedDesc'		=> 'Вы не будете получать уведомления об изменениях или комментариях к просмотренным страницам, ' .
									'or messages from other users. Also, you <strong>will not be able to recover a forgotten password</strong>, ' .
									'до тех пор, пока ваш адрес электронной почты не будет подтвержден, перейдя по ссылке в письме, отправленном вам. ' .
									'Если в течение нескольких дней после регистрации вы не получите письмо, попросите его еще раз, нажав ',

	'ForgotPasswordHint'		=> 'Введите свой логин и адрес электронной почты' . "\n" . 'Вы получите письмо с инструкциями по электронной почте.',
	'ForgotPassword'			=> 'Забыли пароль?',
	'UserNotFound'				=> 'Пользователь с таким именем или адресом электронной почты не найден.',
	'NotConfirmedEmail'			=> 'Your email address is not confirmed.<br>Mail can\'t be send to a non-confirmed address.',
	'EmailForgotSubject'		=> 'Восстановление пароля для ',
	'EmailForgotMessage'		=> 'Кто-то (возможно, вы) забыл ваш пароль для %1.' . "\n" . 'Ваш логин: %2'."\n\n" . 'Нажмите на ссылку или скопируйте ее в адресную строку браузера для изменения пароля.' . "\n" . '%3'."\n\n",
	'CodeWasSent'				=> 'Инструкция по восстановлению пароля была отправлена вам по электронной почте.',
	'WrongCode'					=> 'Неверный код',
	'ChangePasswordForUser'		=> 'Смена пароля %1',

	'Watchers'					=> 'Список наблюдателей для %1',
	'WatchersFor'				=> 'Наблюдатели для',
	'NoWatchers'				=> 'Нет наблюдателей для %1',
	'NotOwnerToViewWatchers'	=> 'Вы не являетесь владельцем этой страницы, и вы не можете видеть список наблюдателей за ней.',

	// thumbnail
	'TbnError'					=> 'Ошибка создания эскиза: %1',
	'TbnImageAreaTooBig'		=> 'Файл с размерами больше %1',
	'TbnImageMissing'			=> 'Файл отсутствует: %1',

	// admin_recovery action
	'GenerateRecoveryHash'		=> 'Generate the password hash for your <code>recovery_password</code>',

	// import action
	'ImportTo'					=> 'Импорт из кластера:',
	'ImportWhat'				=> 'XML-файл для импорта:',
	'ImportButton'				=> 'Импорт',
	'ImportSuccess'				=> 'Успешно импортировано.',
	'ImportFailed'				=> 'Ошибка IMPORT.',
	'ImportHint'				=> 'Пожалуйста, укажите кластер, который вы хотите импортировать, без относительного адреса.',
	'ImportAttention'			=> 'Внимание: Перезаписывает те же страницы в кластере.',
	'ImportNote'				=> 'Импортированная страница',

	// mywatches action
	'WatchedPages'				=> 'Список всех страниц, на которые вы следите за изменениями ',
	'UnwatchedPages'			=> 'Список всех страниц, которые вы не смотрите',
	'NoWatchedPages'			=> 'У вас нет просмотренных страниц.',
	'NoUnwatchedPages'			=> 'Вы наблюдаете за изменениями на всех страницах.',
	'ViewWatchedPages'			=> 'Показать просмотренные страницы',
	'ViewUnwatchedPages'		=> 'Показать непросмотренную страницу',
	'NotLoggedInWatches'		=> 'Вы не вошли в систему, поэтому мы не смогли идентифицировать ваш список просмотров.',

	// mychangeswatches action
	'MyChangesWatches'			=> 'Список всех просмотренных вами страниц, которые были отредактированы другими с момента вашего последнего редактирования',
	'ResetChangesWatches'		=> 'сбросить список изменений',
	'NoChangesWatches'			=> 'Среди просмотренных страниц нет изменений...',

	// whatsnew action
	'NewCommentAdded'			=> 'Добавлен новый комментарий',
	'NewFileAdded'				=> 'Добавлен новый файл',
	'NewPageCreated'			=> 'Создана страница',
	'NewRevisionAdded'			=> 'Страница изменена',
	'Cluster'					=> 'кластер',
	'PageDeleted'				=> 'Страница удалена',
	'CommentDeleted'			=> 'Комментарий удален',
	'FileDeleted'				=> 'Файл удален',

	// users action
	'UsersSearch'				=> 'Найти пользователей',
	'UsersOpenProfile'			=> 'Просмотр профиля',
	'UsersNoMatching'			=> 'Подходящие пользователи не найдены. Попробуйте менее строгие критерии поиска.',
	'UsersName'					=> 'Наименование',
	'UsersPages'				=> 'Страницы',
	'UsersChanges'				=> 'Изменения',
	'UsersSubscription'			=> 'Подписка',
	'UsersWatches'				=> 'Часы',
	'UsersComments'				=> 'Комментарии',
	'UsersUploads'				=> 'Выгрузки',
	'UploadQuota'				=> 'Использовано',
	'UploadQuotaTip'			=> 'Квота загрузки',
	'UsersLogins'				=> 'Логины',
	'UsersRevisions'			=> 'Версии',
	'UsersSignup'				=> 'Регистрация',
	'UsersLastSession'			=> 'Последняя сессия',
	'UsersNotFound'				=> 'Пользователь %2 не найден. Нажмите <a href="%1">здесь</a>, чтобы перейти в основной список.',
	'UsersProfile'				=> 'Профиль',
	'UsersContact'				=> 'Контакт',
	'UsersList'					=> 'Просмотреть весь список пользователей',
	'UsersNA'					=> '[не установлен]',
	'UsersNA2'					=> '[No]',
	'UsersSignupDate'			=> 'Дата регистрации',
	'UsersGroupMembership'		=> 'Участие в группах',
	'UsersPersonalInfo'			=> 'Личная информация',
	'UsersOwnedPages'			=> 'Имеющиеся страницы:',
	'UsersCommentsPosted'		=> 'Комментарии размещены:',
	'UsersFilesUploaded'		=> 'Файлы загружены:',
	'UsersRevisionsMade'		=> 'Сделано изменений:',
	'UsersDocsSortName'			=> '[Сортировать по названию]',
	'UsersDocsSortCreation'		=> '[Сортировать по дате создания]',
	'UsersChangesSortAsc'		=> '[Сортировка по возрастанию]',
	'UsersChangesSortDesc'		=> '[Сортировка по убыванию]',
	'UsersSessionNA'			=> '[не записано]',
	'UsersSessionHidden'		=> '[hidden]',
	'IntercomSubject'			=> 'Тема:',
	'IntercomMessage'			=> 'Сообщение:',
	'IntercomCopy'				=> 'Отправить мне копию',
	'IntercomSubjectN'			=> '[начать новую тему]',
	'IntercomDisabled'			=> 'Извините, вы не хотите или не можете получать личные сообщения.',
	'IntercomHint'				=> 'Пожалуйста, войдите сначала и перейдите по ссылке снова, если вы хотите ответить на полученное личное сообщение.',
	'IntercomDesc'				=> 'Примечание: Отправка личных сообщений, сделанных на email получателя, не раскрывая свой адрес. Получатель сможет ответить на вас, используя аналогичную форму на странице вашего профиля. ',
	'PMOversized'				=> 'Длина сообщения превышает максимально допустимый размер на %1. Пожалуйста, сократите ваше сообщение и отправьте снова.',
	'PMFlooded'					=> 'Интервал между отправкой личных сообщений должен быть не меньше, чем %1 секунд.',
	'PMSent'					=> 'Сообщение успешно отправлено пользователю.',
	'PMBody'					=> 'Это сообщение было отправлено вам пользователем %1.',
	'PMBodyCopy'				=> 'You sent the following message to the user %1.',
	'PMReply'					=> 'Чтобы ответить на это письмо, нажмите на следующую ссылку (не используйте кнопку Ответить / Ответить в почтовом ящике):',
	'PMNotLoggedIn'				=> 'Вы не зарегистрированы в системе и не можете отправлять личные сообщения пользователям.',

	// admin_replace action
	'ReplaceText'				=> 'Заменить текст',
	'TextOriginal'				=> 'Исходный текст:',
	'TextReplacement'			=> 'Текст замены:',
	'ReplaceTextRegex'			=> 'Использовать регулярные выражения',
	'Namespace'					=> 'Пространство имен:',
	'ReplaceTextCluster'		=> 'Поиск и замена только внутри этого кластера:',
	'ReplaceTextEditPages'		=> 'Заменить текст в содержимом страницы',
	'ReplaceTextEditComments'	=> 'Заменить текст в комментариях',
	'ReplaceTextEditTitles'		=> 'Заменить текст в заголовках страниц',
	'ReplaceTextGiveTarget'		=> 'Вы должны указать строку для замены.',
	'ReplaceTextNoNamespace'	=> 'Вы должны выбрать хотя бы одно пространство имён.',
	'ReplaceTextNoDifference'	=> 'Нет различий между текстом замены и целевым текстом.',
	'ReplaceTextNoOption'		=> 'Вы должны выбрать хотя бы один из вариантов замены.',
	'ReplaceTextPagesEdit'		=> 'Заменить %1 на %2 в тексте следующих страниц %3:',
	'ReplaceTextTitlesEdit'		=> 'Заменить %1 на %2 в заголовках следующих %3 страниц:',
	'ReplaceTextReplace'		=> 'Заменить',
	'ReplaceTextSuccess'		=> '%1 был заменен на %2 на страницах %3.',
	'ReplaceTextNoMatch'		=> 'Страницы не найдены, содержащие строку %1.',
	'ReplaceTextNoTitleMatch'	=> 'Страницы не найдены в заголовке %1.',
	'ReplaceTextEditFailed'		=> 'Не удалось заменить текст',
	'ReplaceTextTitleTooBig'	=> 'Оригинальный или замененный текст слишком большой для заголовка.',
	'ReplaceTextReturn'			=> 'Вернуться к форме',
	'ReplaceTextWarning'		=> 'Предупреждение: Есть %1 страницы, которые уже содержат строку замены, %2. Если вы выполните замену, вы не сможете отделить замену от этих строк.',
	'ReplaceTextBlankWarning'	=> 'Предупреждение: Так как строка замены пустая, эта операция не будет обратима.',
	'ReplaceTextEditSummary'	=> 'Замена текста: %1 → %2',
	'InvertSelection'			=> 'Инвертировать выделение',

	// Properties
	'PropertiesFor'				=> 'Свойства страницы для %1',
	'MetaTag'					=> 'Тег',
	'MetaTitle'					=> 'Заголовок',
	'MetaKeywords'				=> 'Ключевые слова',
	'MetaDescription'			=> 'Описание',
	'On'						=> 'На',
	'Off'						=> 'Выкл',
	'Registered'				=> 'Зарегистрирован',
	'MetaComments'				=> 'Показать комментарии',
	'MetaFiles'					=> 'Показать панель файлов',
	'MetaToc'					=> 'Показать содержание',
	'MetaIndex'					=> 'Показывать панель кластера',
	'MetaIndexMode'				=> 'Показать режим уровня',
	'MetaIndexFull'				=> 'Дерево',
	'MetaIndexUpper'			=> 'Верхний',
	'MetaIndexLower'			=> 'Опустить',
	'MetaHtml'					=> 'Поддержка HTML страницы',
	'MetaSafeHtml'				=> 'Фильтрация небезопасных HTML',
	'MetaTypografica'			=> 'Типографический Корректор',
	'MetaNoIndex'				=> 'Блокировать поисковые системы',
	'SettingsID'				=> 'ID страницы',
	'SettingsSize'				=> 'Размер',
	'SettingsSizeTip'			=> 'исходник / скомпилирован',
	'SettingsCreated'			=> 'Создано',
	'SettingsCurrent'			=> 'Изменено',
	'SettingsTotalRevs'			=> 'Версии',
	'SettingsTotalComs'			=> 'Комментарии',
	'SettingsWatchers'			=> 'Наблюдатели',
	'SettingsHits'				=> 'Просмотров',
	'SettingsText'				=> 'Настройки',
	'SettingsEdit'				=> 'Редактирование',
	'SettingsRevisions'			=> 'Версии',
	'SettingsClone'				=> 'Клон',
	'SettingsRename'			=> 'Переименовать',
	'MassRename'				=> 'для всего кластера',
	'SettingsRemove'			=> 'Удалить',
	'SettingsPurge'				=> 'Purge',
	'SettingsModerate'			=> 'Модерировать',
	'SettingsPermissions'		=> 'Права доступа',
	'AclForEntireCluster'		=> 'для всего кластера',
	'SettingsAttachments'		=> 'Вложения',
	'SettingsUpload'			=> 'Выгрузить',
	'SettingsCategories'		=> 'Категории',
	'SettingsLanguages'			=> 'Языки',
	'SettingsReferrers'			=> 'Рефералы',
	'SettingsWatch'				=> 'Смотреть',
	'SettingsLatex'				=> 'Версия LaTeX',
	'SettingsXML'				=> 'Экспорт в XML',
	'NeedToChangeLang'			=> 'Неподдерживаемый язык страницы %1 должен быть изменен.',
	'SetLang'					=> 'Язык этой страницы',
	'SetMenuLabel'				=> 'Метка меню',
	'SetShowMenuLabel'			=> 'Показать в навигации',

	// upload
	'UploadFiles'				=> 'Загрузить файлы',
	'UploadFor'					=> 'Загрузка файла:',
	'UploadButton'				=> 'Выгрузить',
	'UploadGlobalText'			=> 'для публичного доступа',
	'UploadGlobal'				=> 'глобальный',
	'UploadLocalText'			=> 'только для пользователей, которым разрешено просматривать текущую страницу',
	'UploadAsName'				=> 'Имя:',
	'UploadOverwrite'			=> 'Перезаписать существующие файлы',
	'FileDesc'					=> 'Пояснение:',
	'UploadForbidden'			=> 'Вы не можете загружать файлы здесь.',
	'UploadOverwriteDenied'		=> 'Только владелец файла или администратор может перезаписать файл %1.',
	'UploadNoFile'				=> 'По некоторым причинам файл не найден.',
	'UploadMaxSizeReached'		=> 'Размер файла превышает допустимый лимит!',
	'UploadDirNotWritable'		=> 'Каталог файлов не доступен для записи!',
	'UploadNotAPicture'			=> 'Фотографии разрешены только для загрузки. Что вы пытаетесь загрузить?',
	'UploadEmptyExtension'		=> 'Имя файла и расширение не могут быть пустыми.',
	'FilenameTooLong'			=> 'Имя файла не может быть длиннее 240 байт.',
	'BannedFiletype'			=> '%1 не является разрешенным типом файла.',
	'PermittedFiletype'			=> 'Разрешенные типы файлов:',
	'UploadMimeMismatch'		=> 'Расширение файла %1 не соответствует обнаруженному MIME типу файла (%2).',
	'UploadBadMime'				=> 'Файлы MIME типа %1 не могут быть загружены.',
	'FileIsDuplicate'			=> 'Выгрузка точного дублирования текущей версии.',
	'FileHasDuplicate'			=> 'Этот файл является копией следующих файлов:',

	'UploadMaxFileQuota'		=> 'Вы достигли лимита загрузок. Этот файл не может быть загружен',
	'UploadDone'				=> 'Файл успешно загружен',
	'UploadFileForbidden'		=> 'Доступ к файлам запрещен',
	'UploadTitle'				=> 'Файлы, доступные с этой страницы',
	'UploadTitleGlobal'			=> 'Файлы доступны из любого места',

	'UploadFile'				=> 'Выгрузить',
	'UploadMax'					=> 'Не более чем ',
	'UploadUsedStorage'			=> 'Используется хранилище ',

	// attachments
	'Attachments'				=> 'Вложения',
	'Attachment'				=> 'Вложение',
	'AttachmentsToPage'			=> 'на страницу',
	'AttachmentsToCluster'		=> 'кластер',
	'AttachmentsByTime'			=> 'по времени',
	'AttachmentsGlobal'			=> 'глобальный',
	'AttachmentsAll'			=> 'все',
	'AttachmentsLinked'			=> 'использовано',

	'FileViewProperties'		=> 'Вид',
	'FileViewPropertiesTip'		=> 'Просмотр метаданных этого файла',
	'FileEditProperties'		=> 'Редактирование',
	'FileEditPropertiesTip'		=> 'Редактировать метаданные этого файла',
	'FileEditedMeta'			=> 'Обновлены метаданные этого файла',
	'FileEditDenied'			=> 'Вы не можете редактировать этот файл',
	'FileLabel'					=> 'Метка',
	'FileLabelTip'				=> 'Отметить этот файл',
	'FileRemove'				=> 'Удалить',
	'FileRemovedFromDB'			=> 'Файл удален из базы данных',
	'FileRemovedFromFS'			=> 'Файл удален из физического хостинга',
	'FileRemovedFromFSError'	=> 'Невозможно стереть файл!',
	'FileRemoveConfirm'			=> 'Вы уверены, что хотите удалить этот файл?',
	'FileRemoveDenied'			=> 'Вы не можете удалить этот файл',
	'FileNotFound'				=> 'Файл не найден.',

	'FileSearch'				=> 'Найти файл',
	'UploadBy'					=> 'Загружено:',
	'FileAdded'					=> 'Добавлено:',
	'FileModified'				=> 'Изменено:',
	'FileSize'					=> 'Размер:',
	'FileDimension'				=> 'Размер:',
	'MimeType'					=> 'Миметип:',
	'FileName'					=> 'Имя:',
	'FileCaption'				=> 'Заголовок:',
	'FileAuthor'				=> 'Автор:',
	'FileSource'				=> 'Источник:',
	'FileSourceUrl'				=> 'URL:',
	'FileAttachedTo'			=> 'Прикреплено:',
	'FileSyntax'				=> 'Синтаксис:',
	'FileAbsolutePath'			=> 'абсолютный путь',
	'FileRelativePath'			=> 'относительный путь',
	'FileUsage'					=> 'Использование файла:',
	'FileUsageText'				=> 'На следующие страницы ссылки на этот файл:',
	'NoFileUsage'				=> 'Нет ссылок на этот файл.',

	'FileSortExt'				=> 'расширение',
	'FileSortName'				=> 'имя',
	'FileSortSize'				=> 'размер',
	'FileSortTime'				=> 'создано',

	'SortBy'					=> 'Сортировать по',
	'Ascending'					=> 'по возрастанию',
	'Decending'					=> 'удаление',

	'Files0'					=> 'Прикрепить файлы',
	'Files1'					=> 'Показать файлы (1 файл)',
	'FilesN'					=> 'Показать файлы (%1 файлов)',
	'Files'						=> 'Файлы',
	'File'						=> 'Файл',
	'ShowFiles'					=> 'Отобразить файлы / формы',
	'HideFiles'					=> 'Скрыть файлы / формы',
	'DoShowFiles'				=> 'Показывать списки файлов по умолчанию',
	'NoAttachments'				=> 'Нет прикрепленных файлов для отображения.',

	'RegistrationLang'			=> 'Ваш язык',
	'InvalidWikiName'			=> 'Выбранное имя является недопустимым',
	'InvalidUserName'			=> 'Неверное имя пользователя',
	'Bookmarks'					=> 'Закладки',
	'ReallyDeleteComment'		=> 'Do you really want to DELETE this comment?<br>There is no undo for this action!',
	'ReallyDeleteRevision'		=> 'Do you really want to DELETE this revision?<br>There is no undo for this action!',

	'RegistrationClosed'		=> 'Регистрация недоступна. Попробуйте связаться с администратором сайта.',
	'AclAreYouSure'				=> 'Вы собираетесь изменить ACL этой страницы и все ее подстраницы. Продолжить?',

	'BookmarkDeleteSelected'	=> 'Удалить выбранные',
	'BookmarkMark'				=> 'Отметить',
	'BookmarkNumber'			=> 'Нет.',
	'BookmarkNone'				=> 'У вас нет закладок.',
	'BookmarkTitle'				=> 'Заголовок закладки',
	'BookmarkPage'				=> 'Страница',
	'BookmarkSaveChanges'		=> 'Сохранить изменения',
	'BookmarksAddPage'			=> 'Установить закладку для следующей страницы',
	'BookmarkAlreadyExists'		=> 'Закладка уже существует.',

	'PoweredBy'					=> 'При поддержке',

	'MassRenaming'				=> 'Переименовать весь кластер',
	'MassNewName'				=> 'Введите новое имя для этого кластера',
	'MassNeedRedirect'			=> 'Создать перенаправление на новые страницы на старых страницах',

	// pagination
	'ToOverview'				=> 'Вернуться к обзору',
	'Overview'					=> 'Общий обзор',
	'ToThePage'					=> 'К странице:',
	'Next'						=> 'Следующий',
	'Prev'						=> 'Предыдущий',
	'NextAcr'					=> 'Следующий',
	'PrevAcr'					=> 'Предыдущий',
	'Back'						=> 'Назад',

	// filter
	'Filter'					=> 'Фильтр',
	'OptionalFilters'			=> 'Необязательные фильтры:',
	'Any'						=> 'Любая',

	// My Groups
	'UserGroups'				=> 'Группы пользователей',
	'MyGroups'					=> 'Ассоциации групп',
	'Group'						=> 'группа',
	'Groups'					=> 'группы',

	// license action
	'DistributedUnder'			=> 'Материал распространяется под',
	'AuthorsDisplayHint'		=> 'Список авторов будет отображаться при сохранении страницы.',
	'AnonymousUsers'			=> 'Анонимные пользователи',
	'License'					=> 'Лицензия',
	'LicenseArray'				=> [
		'1'		=> 'Атрибуция - Без производных атрибутов',
		'2'		=> 'Атрибуция — Некоммерческая акция',
		'3'		=> 'Атрибуция - Некоммерческие-производные',
		'4'		=> 'Характеристики',
		'5'		=> 'Атрибуция - Некоммерческое',
		'6'		=> 'Характеристики',
		'7'		=> 'CC0 1.0 Universal',
		'8'		=> 'Лицензия GNU Free Documentation License',
		'9'		=> 'Публичный домен / Бесплатное использование',
		'10'	=> 'Все права защищены',
	],
	'LicenseMeta'				=> [
		'1'		=> 'Публичный домен',
		'2'		=> 'Некоторые права защищены',
		'3'		=> 'Все права защищены',
	],

	// Cache
	'ClearCache'				=> 'Очистить кэш',
	'CacheCleared'				=> 'Кэш очищен.',
	'ConfigCache'				=> 'Кэш конфигурации',
	'FeedCache'					=> 'Кэш ленты',
	'PageCache'					=> 'Кэш страницы',
	'SQLCache'					=> 'Кэш SQL',
	'TemplateCache'				=> 'Кэш шаблона',
	'ThumbCache'				=> 'Thumbnail cache',

	// Embed
	'EmbedNoURL'				=> 'Пожалуйста, укажите адрес ресурса с URL-адресом параметра (например {{embed url="https://example.com/embed/video.mp4"}} )',

	// Feed
	'FeedTitle'					=> 'Заголовок ленты',
	'FeedMulti'					=> 'Мульти-канал',
	'FeedNoURL'					=> 'Пожалуйста, укажите Ленту с URL параметра (например {{feed url="https://example.com/feed.xml"}} )',
	'FeedError'					=> 'Не удалось загрузить или проанализировать канал',
	'FeedSource'				=> 'Источник:',
	'FeedXMLTip'				=> '',

	// XML / RSS autodiscovery
	'ChangesXMLTitle'			=> ' - Последние изменения',
	'ChangesXML'				=> 'Последние изменения ',
	'CommentsXMLTitle'			=> ' - Последние комментарии',
	'CommentsXML'				=> 'Последние комментарии к ',
	'NewsXMLTitle'				=> ' - Последние новости',
	'NewsXML'					=> 'Последние новости ',
	'RevisionXMLTip'			=> 'Нажмите для просмотра последних версий страниц в формате XML.',
	'CommentsXMLTip'			=> 'Нажмите для просмотра последних комментариев в формате XML.',
	'ChangesXMLTip'				=> 'Нажмите для просмотра последних изменений в формате XML.',
	'NewsXMLTip'				=> 'Нажмите, чтобы просмотреть последние новости в формате XML.',
	'RevisionsXML'				=> 'Пересмотр ',
	'ExportClusterXML'			=> 'Экспорт всего кластера ',
	'AccessDeniedXML'			=> 'У вас нет доступа к этой информации.',

	'ChangesFeed'				=> 'Изменения',
	'CommentsFeed'				=> 'Комментарии',
	'NewsFeed'					=> 'Новости',
	'RevisionsFeed'				=> 'Пересмотр ',

	'LastModification'			=> 'Последнее изменение',

	// Captcha
	'Captcha'					=> 'Пожалуйста, введите слово, которое вы читаете на изображении',
	'CaptchaFailed'				=> 'Вы ввели кодовое слово неправильно. Пожалуйста, попробуйте еще раз.',
	'CaptchaReload'				=> 'Новая капча',
	'CaptchaReloadWarning'		=> 'К сожалению, не удается перезагрузить captcha изображение, вам придется обновить страницу для этого',

	// news
	'News'						=> 'Новости',
	'NewsName'					=> 'Название:',
	'NewsNoName'				=> 'Вы забыли добавить заголовок новости.',
	'NewsNotAvailable'			=> 'Нет доступных новостей.',
	'NewsNoClusterDefined'		=> 'Кластер новостей не определен.',
	'NewsDiscuss'				=> 'Обсудить эту статью...',

	// blog
	'BlogNewTopic'				=> 'Создать новую запись',
	'NoPostAvailable'			=> 'Пост пока не доступен.',

	// Review
	'Reviewer'					=> 'Рецензент',
	'Reviewed'					=> 'проверено',
	'Review'					=> 'рецензия',
	'ReviewedBy'				=> 'оценил',
	'RemoveReview'				=> 'Удалить отзыв для этой страницы',
	'SetReview'					=> 'Просмотрел эту страницу',
	'SetAsReviewed'				=> 'Установить страницу как проверенную',
	'SetAsUnreviewed'			=> 'Сделать страницу непроверенной',

	// word filter
	'PotentialSpam'				=> 'Выявленный потенциальный спам',

	// moderation handler
	'Moderation'				=> 'Модерирование',
	'Topics'					=> 'темы',
	'ModerateSection'			=> 'раздел / страница ',

	'NotModerator'				=> 'У вас нет полномочий модерировать эту страницу / главу',
	'ModerateDeleteTopic'		=> 'Удалить тему / страницу',
	'ModerateDeletePosts'		=> 'Удалить комментарии',
	'ModerateMove'				=> 'Переместить',
	'ModerateSplit'				=> 'Разделить / Перенести комментарии',
	'ModerateMerge'				=> 'Объединить',
	'ModerateLock'				=> 'Заблокировать',
	'ModerateUnlock'			=> 'Разблокировать',
	'ModerateAccept'			=> 'Принять',
	'ModerateDeleteConfirm'		=> 'Are you sure you want to <strong>remove</strong> the following topics?',
	'ModerateRenameConfirm'		=> 'Введите новое название для выбранной страницы',
	'ModerateRenameExists'		=> 'Страница с таким именем уже существует! Выберите другое имя.',
	'ModerateRename1Only'		=> 'Примечание: только первая страница, которую вы выбрали, будет переименована!',
	'ModerateMovesConfirm'		=> 'Выберите целевой раздел для перемещения форума',
	'ModerateMoveConfirm'		=> 'Выберите форум или укажите кластер, чтобы переместить эти темы. Чтобы переместить страницу в корень сайта, введите &quot;/&quot;',
	'ModeratePgMoveConfirm'		=> 'Укажите имя кластера для размещения страницы. Чтобы переместить страницу в корень сайта, введите &quot;/&quot;',
	'ModerateMoveExists'		=> 'Операция прервана: в этом разделе уже существуют темы с таким же именем %1. Если вам все равно нужно перенести вышеуказанные темы, то переименуйте их первым.',
	'ModerateMoveNotExists'		=> 'Страница / кластер не существует. Пожалуйста, проверьте имя и повторите попытку.',
	'ModerateMergeConfirm'		=> 'Выберите тему, которая должна объединить оставшиеся',
	'ModerateMerge2Min'			=> 'Чтобы присоединиться к вам необходимо выбрать по крайней мере две темы!',
	'ModerateComDelConfirm'		=> 'Are you sure you want to <strong>remove</strong> %1 %2?',
	'ModerateComment'			=> 'Комментарий',
	'ModerateComments'			=> 'Комментарии',
	'ModerateSplitNewName'		=> 'Укажите имя для разделенной темы и выберите схему разделения',
	'ModerateSplitPageName'		=> 'Введите название страницы / темы, где перемещаться съемные комментарии, и выберите схему разделения',
	'ModerateSplitAllAfter'		=> 'Отсоединить все комментарии после первого выбранного (и включая)',
	'ModerateSplitSelected'		=> 'Разделенные только выбранные комментарии (всего %1)',
	'ModerateUserProfile'		=> 'профиль',
	'ModerateNoItemChosen'		=> 'Пожалуйста, выберите хотя бы один элемент с помощью кнопки Set.',

	'ModerateSection2'			=> 'модерировать секцию',
	'ModerateTopicsDeleted'		=> 'Выбранные темы успешно удалены.',
	'ModerateTopicsRelocated'	=> 'Выбранные темы успешно перемещены.',
	'ModerateTopicsRenamed'		=> 'Тема успешно переименована.',
	'ModerateTopicsMerged'		=> 'Выбранные темы успешно объединены.',
	'ModerateTopicsBlocked'		=> 'Выбранные темы успешно заблокированы',
	'ModerateTopicsUnlocked'	=> 'Выбранные темы успешно разблокированы.',
	'ModerateTopicDeleted'		=> 'Тема успешно удалена.',
	'ModeratePageMoved'			=> 'Страница успешно перемещена.',
	'ModerateTopicRenamed'		=> 'Тема успешно переименована.',
	'ModerateTopicBlocked'		=> 'Тема успешно заблокирована',
	'ModerateTopicUnlocked'		=> 'Тема успешно разблокирована.',
	'ModerateCommentsDeleted'	=> 'Выбранные комментарии успешно удалены.',
	'ModerateCommentsSplit'		=> 'Выбранные комментарии успешно разделены в новой теме.',
	'ModerateCommentsSplitFailed'	=> 'Note: For some reason separating the selected comments to a new topic failed.<br>Usually this should not happen, so please notify the site administrator.<br>As a precaution, the issue has been preserved in its original form.',
	'ModerateCommentsMoved'		=> 'Выбранные комментарии успешно перенесены на заданную страницу.',

	// forum
	'ForumSubforums'			=> 'Форум',
	'ForumTopic'				=> 'Тема',
	'ForumTopics'				=> 'Темы',
	'ForumPosts'				=> 'Должности',
	'ForumReplies'				=> 'Ответы',
	'ForumAuthor'				=> 'Автор',
	'ForumViews'				=> 'Просмотров',
	'ForumCreated'				=> 'Создано',
	'ForumComments'				=> 'Комментарии',
	'ForumLastComment'			=> 'Последний комментарий',
	'ForumNoComments'			=> 'Нет комментариев',
	'ForumNoTopics'				=> 'В этом форуме нет тем или сообщений.',
	'ForumNewTopic'				=> 'Начать новое обсуждение',
	'ForumTopicName'			=> 'Название темы:',
	'ForumTopicSubmit'			=> 'Отправить тему',
	'ForumNoTopicName'			=> 'Укажите имя для новой страницы.',
	'ForumNewPosts'				=> 'новый пост',
	'ForumLocked'				=> 'раздел заблокирован',
	'ForumUpdated'				=> 'обновлено',
	'ForumNoClusterDefined'		=> 'Кластер форума не определен.',
	'ForumOutsideCluster'		=> 'Ensure that the %1 action is located inside the forum cluster.',

	// password complexity
	'PwdCplxShort'				=> 'Пароль слишком короткий.',
	'PwdCplxEquals'				=> 'Пароль содержит имя пользователя.',
	'PwdCplxWeak'				=> 'Пароль не соответствует требованиям сложности.',
	'PwdCplxDesc1'				=> 'Требования к паролю: ',
	'PwdCplxDesc2'				=> 'пароль не должен быть меньше %1 символов',
	'PwdCplxDesc3'				=> 'не должен содержать ваше имя пользователя',
	'PwdCplxDesc4'				=> 'должен состоять из ',
	'PwdCplxDesc41'				=> 'буквы и цифры',
	'PwdCplxDesc42'				=> 'заглавные и строчные буквы и цифры',
	'PwdCplxDesc43'				=> 'заглавные и строчные буквы, цифры и небуквенно-цифровые символы',
	'PwdCplxDesc5'				=> 'Можно использовать любые буквы, цифры и специальные символы, кроме пробелов.',

	'PasswordTooShort'			=> 'Пароль слишком короткий.',
	'PasswordTooCommon'			=> 'Этот пароль слишком распространен.',
	'PasswordSameAsUsername'	=> 'Ваш пароль совпадает с вашим именем пользователя.',
	'PasswordSameAsEmail'		=> 'Ваш пароль совпадает с вашим email.',

	'Timezone'					=> 'Timezone',

	'LanguageArray'	=> [
		'bg' => 'Болгарский',
		'da' => 'Датский',
		'de' => 'Немецкий',
		'el' => 'Греческий',
		'en' => 'Russian',
		'es' => 'Испанский',
		'et' => 'Эстонский',
		'fa' => 'Персидский',
		'fr' => 'Французский',
		'hi' => 'Хинди',
		'hu' => 'Венгерский',
		'it' => 'Итальянский',
		'ja' => 'Японский',
		'ko' => 'Корейский',
		'nl' => 'Голландский',
		'pl' => 'Польский',
		'pt' => 'Португальский',
		'ru' => 'Русский',
		'ta' => 'Tamil',
		'zh' => 'Китайский',
		'zh-tw' => 'Китайский',
	],

	'AccountStatus'				=> 'Статус аккаунта',
	'AccountStatusArray' => [
		'0' => 'активный',
		'1' => 'ожидается',
		'2' => 'заблокировано',
		'3' => 'неактивный',
	],

	'JustNow'		=> 'только что',
	'MinuteAgo'		=> 'минуту назад',
	'MinutesAgo'	=> '%1 minutes ago',
	'HourAgo'		=> 'час назад',
	'HoursAgo'		=> '%1 hours ago',
	'DayAgo'		=> 'вчера',
	'DaysAgo'		=> '%1 days ago',
	'WeekAgo'		=> 'неделю назад',
	'WeeksAgo'		=> '%1 weeks ago',
	'MonthAgo'		=> 'месяц назад',
	'MonthsAgo'		=> '%1 months ago',
	'YearAgo'		=> 'год назад',
	'YearsAgo'		=> '%1 years ago',

	'InAMoment'		=> 'в момент',
	'InAMinute'		=> 'через минуту',
	'InMinutes'		=> 'через %1 минут',
	'InAnHour'		=> 'через час',
	'InHours'		=> 'через %1 часов',
	'Tomorrow'		=> 'завтра',
	'InDays'		=> 'через %1 дней',
	'InAWeek'		=> 'через неделю',
	'InWeeks'		=> 'в %1 недель',
	'InAMonth'		=> 'через месяц',
	'InMonths'		=> 'в %1 месяцев',
	'InAYear'		=> 'через год',
	'InYears'		=> 'в %1 лет',

	// norm multiples
	'ByteDecimalShort'			=> ['В', 'кБ', 'МБ', 'Гб', 'ТБ', 'ПБ', 'ЕБ', 'ZB', 'YB'],
	'ByteDecimalLong'			=> ['Байт', 'Kilobyte', 'Megabyte', 'Gigabyte', 'Terabyte', 'Petabyte', 'Exabyte', 'Zettabyte', 'Yottabyte'],
	'ByteBinaryShort'			=> ['В', 'KiB', 'МиБ', 'GiB', 'TiB', 'PiB', 'EiB', 'ZiB', 'YiB'],
	'ByteBinaryLong'			=> ['Байт', 'Kibibyte', 'Mebibyte', 'Gibibyte', 'Tebibyte', 'Pebibyte', 'Exbibyte', 'Zebibyte', 'Yobibyte'],
	'PixelDecimalShort'			=> ['px', 'KP', 'Мана', 'GP', 'TP', 'PP', 'EP', 'ZP', 'YP'],
	'PixelDecimalLong'			=> ['пиксель', 'Kpx', 'Mpx', 'Gpx', 'Tpx', 'Ppx', 'Эпкс', 'Zpx', 'Ypx'],

	// loading error
	'UnknownAction'				=> 'Неизвестное действие',
	'UnknownMethod'				=> 'Неизвестный метод',
	'FormatterNotFound'			=> 'Formatter %1 не найден',

	// log
	'LogAdminLoginSuccess'		=> 'Успешный вход в панель управления',
	'LogAdminLogout'			=> 'Выйти из административной панели',
	'LogAdminLoginFailed'		=> '!!Несанкционированный доступ к административной панели!!',
	'LogAdminLoginLocked'		=> 'Вход в административную панель заблокирован',
	'LogUserCookieForged'		=> '!!**Попытка войти в систему на кованом cookie с логином ##%1##**!!',
	'LogInvalidFormToken'		=> 'Обнаружена потенциальная CSRF атака: %1',
	'LogRemovedPage'			=> '!!Удалена страница ##%1## (пользователь %2)!!',
	'LogRemovedCluster'			=> '!!Удален **кластер** ##%1## (пользователь %2)!!',
	'LogRemovedRevision'		=> '!!Удалена версия ##%3## страницы [[/%1]] (пользователь %2)!!',
	'LogRemovedComment'			=> '!!Удален комментарий от %3 на странице [[/%1]] (пользователь %2)!!',
	'LogRemovedFile'			=> '!!Удален файл ##%2## со страницы [[/%1]]!!',
	'LogRemovedAllComments'		=> '!!Удалены все комментарии на странице [[/%1]]!!',
	'LogRemovedAllRevisions'	=> '!!Удалены все ревизии страницы [[/%1]]!!',
	'LogRemovedAllFiles'		=> '!!Удалены все файлы, прикрепленные к [[/%1]]!!',
	'LogTopicLocked'			=> 'Тема форума заблокирована [[/%1]]',
	'LogTopicUnlocked'			=> 'Разблокирована тема форума [[/%1]]',
	'LogAclUpdated'				=> 'Страница ACL обновлена [[/%1]]',
	'LogOwnershipChanged'		=> 'Владелец страницы [[/%1]] передан пользователю ##%2##',
	'LogUserLoginFailed'		=> '!!Неудачные попытки входа с ##~%1##!!',
	'LogClonedPage'				=> 'Страница ##%1## клонирована до [[/%2]',
	'LogRenamedPage'			=> 'Страница ##%1## переименована на [[/%2]',
	'LogRenamedPage2'			=> '. Старая страница установлена как ссылка на новую',
	'LogSplittedPage'			=> 'Комментарии на странице [[/%1]] разделить на страницу [[/%2]',
	'LogMergedPages'			=> 'Страницы %1 объединены со страницей [[/%2]]',
	'LogUserPasswordReminded'	=> 'Пользователь ##%1## запросил процедуру восстановления пароля на адрес ##%2##',
	'LogUserPasswordRecovered'	=> 'Пользователь ##%1## успешно восстановил забытый пароль',
	'LogUserPasswordChanged'	=> 'Пользователь ##%1## успешно обновлен (изменен) пароль',
	'LogUserPasswordMismatch'	=> '!!Пользователь ##%1## не удалось изменить пароль: текущий пароль не совпадает!!',
	'LogUserIPSwitched'			=> 'Неавторизованный IP-адрес сменил пользователя %1 с %2 на %3',
	'LogPageImported'			=> 'Импортированная страница [[/%1]]',
	'LogSaveNoRights'			=> 'Нет прав для сохранения страницы [[/%1]]',
	'LogPageCreated'			=> 'Создана новая страница [[/%1]]',
	'LogPagePropertiesUpdated'	=> 'Свойства страницы обновлены [[/%1]]',
	'LogPageOwnershipClaimed'	=> 'Пользователь получил право собственности на страницу [[/%1]]',
	'LogFileUploadedLocal'		=> 'Новый файл ##%2## загружен на страницу [[/%1]] (размер %3)',
	'LogFileUploadedGlobal'		=> 'Новый файл ##%2## загружен в глобальную папку (размер %3)',
	'LogPMSent'					=> 'Личное сообщение ##%1## -> ##%2## успешно отправлено',
	'LogUserSimilarName'		=> 'Были попытки зарегистрироваться под тем же именем пользователя: ##%1##',
	'LogUserEmailNotAllowed'	=> 'Email ##%1## не в списке разрешенных доменов',
	'LogRegisterTiming'			=> 'Регистрация не удалась, порог времени формы ##%1## секунд (был ##%2##)',
	'LogUserRegistered'			=> 'Успешно зарегистрирован новый пользователь ##%1## (##%2##)',
	'LogUserEmailActivated'		=> 'Успешно активирована почта ##%1## пользователя ##%2##',
	'LogCommentPosted'			=> 'Добавлено [[/%1 новый комментарий(ы)]] на страницу [[/%2]]',
	'LogUserLoginOK'			=> 'Пользователь ##%1## успешно вошел в систему',
	'LogUserLoggedOut'			=> 'Пользователь ##%1## успешно вышел из системы',
	'LogUserSessionContinued'	=> 'Пользователь ##%1## продолжил приостановленный сеанс',
	'LogUserSettingsUpdate'		=> 'Пользователь ##%1## обновил персональные настройки',
	'LogPageEdited'				=> 'Страница изменена [[/%1]]',
	'LogCommentEdited'			=> 'Отредактирован комментарий [[/%1]]',
	'LogUpdatedFileMeta'		=> 'Обновлены метаданные файла для ##%2## из страницы [[/%1]]',
	'LogUpdatedFileCategories'	=> 'Обновлены категории файлов для ##%2## со страницы [[/%1]]',

	'LogXmlSitemapGenerated'	=> 'Карта сайта создана',
	'LogReferrersPurged'		=> 'Техническое обслуживание: удаленные рефералы',
	'LogRevisionsPurged'		=> 'Техническое обслуживание: устаревшие версии страниц очищены',
	'LogDeletedPagesPurged'		=> 'Техническое обслуживание: удаленные страницы очищены',
	'LogSystemLogPurged'		=> 'Техническое обслуживание: системный журнал очищен',
	'LogCachedPagesPurged'		=> 'Техническое обслуживание: кэшированные страницы очищены',
	'LogSqlCachePurged'			=> 'Техническое обслуживание: очищенные кэшированные результаты sql',
	'LogExpiredTokensPurged'	=> 'Техническое обслуживание: устаревшие cookie_tokens очищены',
	'LogErrorSplitComments'		=> 'Ошибка при разделении комментариев от темы [[/%1]] новая тема ##%2##: страница не была создана',
	'LogCategoriesUpdated'		=> 'Обновлены категории страниц [[/%1]]',
	'LogCategoryCreated'		=> 'Создана новая категория //%1//',
	'LogCategoryRenamed'		=> 'Категория ##%1## переименована на ##%2##',
	'LogCategoryDebundled'		=> 'Категория ##%1## удалена',
	'LogCategoryGrouped'		=> 'Категория ##%1## сгруппирована по слову ##%2##',
	'LogCategoryRemoved'		=> 'Категория ##%1## удалена из базы данных',
	'LogThumbnailGeneration'	=> 'Эскиз генерации %1 сек.',

	'ErrorMinPHPVersion'		=> 'Версия PHP должна быть больше <strong>' . PHP_MIN_VERSION . '</strong>,' .
									' ваш сервер запущен <strong>' . PHP_VERSION . '</strong>.' .
									'  Для корректной работы WackoWiki необходимо обновить PHP до более свежей версии.',

];
